### ISSUE TITLE
SQL function availability depends on runtime context

### ISSUE THREAD

**Issue by bratseth** [questdb/questdb#1168]
**Describe the bug**

I'm trying to evaluate this statement:

`alter table metrics drop partition where at < dateadd('d', -4, now());`

It works as expected when running it locally (regardless of OS), but when it runs on our production servers it fails with

```
io.questdb.griffin.SqlException: [70] unknown function name: now()
at io.questdb.griffin.SqlException.position(SqlException.java:60)
at io.questdb.griffin.FunctionParser.invalidFunction(FunctionParser.java:295)
at io.questdb.griffin.FunctionParser.createFunction(FunctionParser.java:465)
at io.questdb.griffin.FunctionParser.visit(FunctionParser.java:277)
at io.questdb.griffin.PostOrderTreeTraversalAlgo.traverse(PostOrderTreeTraversalAlgo.java:82)
at io.questdb.griffin.FunctionParser.parseFunction(FunctionParser.java:230)
at io.questdb.griffin.SqlCompiler.alterTableDropOrAttachPartition(SqlCompiler.java:1094)
at io.questdb.griffin.SqlCompiler.alterTable(SqlCompiler.java:769)
```

The only relevant difference between these runtime environments is that on the production servers QuestDB is loaded as part of an OSGi bundle. This means that it will have a special classloader and will not find its classes using the system classloader. 

Is QuestDb loading functions through some classloader introspection or assumptions about the system classloader? If so I can probably provide a fix for you if you point me in the right direction.

If not, can you think of any other reason for this?

**Comment by bluestreak01** [comment]
hey Jon,

We load functions using `java.util.ServiceLoader`. Call literally looks like:

```java
ServiceLoader.load(FunctionFactory.class)
```

We found that on Java11 functions are loaded from `module-info.java`, but on Java8 from `META-INF/services/`. OSGi might offer something else entirely.
