### ISSUE TITLE
Java 15 issue

### ISSUE THREAD

**Issue by paulwoods222** [questdb/questdb#1193]
I'm just starting out with QuestDB, so I'm not even sure if Java 15 is supported.
I'm embedding version 6.0.3

When I try to create a DefaultCairoConfiguration I get the stack trace

Caused by: java.lang.ExceptionInInitializerError: null
	at io.questdb.std.Unsafe.getFieldOffset(Unsafe.java:162)
	at io.questdb.std.Unsafe$1Probe.probe(Unsafe.java:98)
	at io.questdb.std.Unsafe.getOrdinaryObjectPointersCompressionStatus(Unsafe.java:112)
	at io.questdb.std.Unsafe.AccessibleObject_override_fieldOffset(Unsafe.java:79)
	at io.questdb.std.Unsafe.<clinit>(Unsafe.java:58)
	at io.questdb.std.Numbers.<clinit>(Numbers.java:41)
	at io.questdb.std.AbstractCharSequenceHashSet.<init>(AbstractCharSequenceHashSet.java:45)
	at io.questdb.std.CharSequenceObjHashMap.<init>(CharSequenceObjHashMap.java:45)
	at io.questdb.std.CharSequenceObjHashMap.<init>(CharSequenceObjHashMap.java:40)
	at io.questdb.std.CharSequenceObjHashMap.<init>(CharSequenceObjHashMap.java:36)
	at io.questdb.log.LogFactory.<init>(LogFactory.java:51)
	at io.questdb.log.LogFactory.<init>(LogFactory.java:62)
	at io.questdb.log.LogFactory.<clinit>(LogFactory.java:40)
	at io.questdb.cutlass.text.types.InputFormatConfiguration.<clinit>(InputFormatConfiguration.java:46)
	at io.questdb.cutlass.text.DefaultTextConfiguration.<init>(DefaultTextConfiguration.java:45)
	at io.questdb.cutlass.text.DefaultTextConfiguration.<init>(DefaultTextConfiguration.java:41)
	at io.questdb.cairo.DefaultCairoConfiguration.<init>(DefaultCairoConfiguration.java:46)

Caused by: java.lang.NoSuchFieldException: intField
	at java.base/java.lang.Class.getDeclaredField(Class.java:2569)
	at io.questdb.std.Unsafe.getFieldOffset(Unsafe.java:160)

This is the code I'm using, dbFolder is the path to a folder which exists, this is on windows 
configuration = new DefaultCairoConfiguration(dbFolder);

**Comment by bluestreak01** [comment]
we don't support Java 15 for now, only Java 11

**Comment by paulwoods222** [comment]
I thought that might be the case - thanks for your quick reply Vlad

**Comment by bsmth** [comment]
Thanks for raising the issue @paulwoods222, I think I can close it for the moment.
