### ISSUE TITLE
Crash on accessing 'localhost'

### ISSUE THREAD

**Issue by djKooks** [questdb/questdb#149]
**Describe the bug**
Crash log occurs when accessing 'localhost' from browser after running database.

**To Reproduce**
1. `./gradlew build`
2. `java -cp core/target/core-4.2.1-SNAPSHOT.jar io.questdb.ServerMain -d <local_dir>`
3. Access localhost:9000 on browser
4. See error log below.

**Screenshots**
```
2020-04-12T10:46:45.337302Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@3ad9bce6, ex=
java.lang.NullPointerException
	at io.questdb.std.time.DateFormatAsm/1303361261.format(Unknown Source)
	at io.questdb.std.time.DateFormatUtils.formatHTTP(DateFormatUtils.java:109)
	at io.questdb.cutlass.http.HttpResponseSink$HttpResponseHeaderImpl.status(HttpResponseSink.java:436)
	at io.questdb.cutlass.http.processors.StaticContentProcessor.sendVanilla(StaticContentProcessor.java:243)
	at io.questdb.cutlass.http.processors.StaticContentProcessor.send(StaticContentProcessor.java:165)
	at io.questdb.cutlass.http.processors.StaticContentProcessor.onRequestComplete(StaticContentProcessor.java:89)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:361)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:145)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:84)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:147)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:88)
	at io.questdb.mp.Worker.run(Worker.java:107)
]
2020-04-12T10:46:49.974357Z I http-server disconnected [ip=127.0.0.1, fd=28]
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by bluestreak01** [comment]
This is to do with country/language combination on your system.  We are fixing this, but in the mean time workaround is to set these system properties:

```
-Duser.country=US -Duser.language=en
```

**Comment by bluestreak01** [comment]
fix is now on master

**Comment by djKooks** [comment]
@bluestreak01 works fine now! Thanks 👍
