### ISSUE TITLE
Flaky TableReaderTest

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#1511]
### Describe the bug

`TableReaderTest` fails infrequently with the following failure messages:
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.questdb.cairo.TableReaderTest.lambda$testConcurrentReloadMultiplePartitions$43(TableReaderTest.java:1620)
```
https://dev.azure.com/questdb/questdb/_build/results?buildId=3198&view=ms.vss-test-web.build-test-results-tab&runId=11956&resultId=100511

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by ideoma** [comment]
Most likely to be fixed in #1557
