### ISSUE TITLE
Flaky WriterPoolTest.testGetAndCloseRace test

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#1513]
### Describe the bug

`WriterPoolTest` fails infrequently (3 runs out of ~300):
```
2021-11-03T13:27:00.338825Z E i.q.TestListener ***** Test Failed *****io.questdb.cairo.pool.WriterPoolTest.testGetAndCloseRace : 
java.lang.AssertionError: expected:<2> but was:<8>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:389)
	at io.questdb.cairo.pool.WriterPoolTest.assertWithPool(WriterPoolTest.java:764)
	at io.questdb.cairo.pool.WriterPoolTest.assertWithPool(WriterPoolTest.java:772)
	at io.questdb.cairo.pool.WriterPoolTest.testGetAndCloseRace(WriterPoolTest.java:264)
```
https://dev.azure.com/questdb/questdb/_build/results?buildId=3257&view=logs&j=e0a155a9-5858-51f3-7a0d-fdfd007d5c7f&t=bdb03b31-3467-53ab-ff1a-f5b57273bbae&l=62862

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
fixed

**Comment by bluestreak01** [comment]
still there

**Comment by puzpuzpuz** [comment]
Observed once again in https://dev.azure.com/questdb/questdb/_build/results?buildId=4386&view=logs&j=3fa4b4be-6db3-54fa-4432-6a83730bebb7&t=bb90c814-cfaa-5557-8498-4851227a92fe (mac build)

**Comment by bluestreak01** [comment]
the remaining flapping test is different to this one. The flapping one is `ReaderPoolTest.testGetAndCloseRace`

**Comment by puzpuzpuz** [comment]
My bad. Didn't notice that it was a different class.
