### ISSUE TITLE
Flaky PerformanceTest.testCairoPartitionedReaderReloadSpeed test

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#1543]
### Describe the bug

Occurred in CI runs on Linux:
```
java.lang.AssertionError: Total reload should be around 300 ms
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at io.questdb.PerformanceTest.testCairoPartitionedReaderReloadSpeed(PerformanceTest.java:54)
```
https://dev.azure.com/questdb/questdb/_build/results?buildId=3369&view=logs&s=b1ea3234-5a2e-5e99-b54b-09a630ee02b3&j=e0a155a9-5858-51f3-7a0d-fdfd007d5c7f

We may need to reconsider the assertion threshold.

### Environment

```markdown
- **QuestDB version**: latest 6.1.1-SNAPSHOT
- **OS**:
- **Browser**:
```

**Comment by puzpuzpuz** [comment]
It's been a while since we saw this failure and I couldn't reproduce it locally even with `stress-ng` consuming all cores, so I'm closing it.
