### ISSUE TITLE
Flaky RetryIODispatcherTest.testInsertsIsPerformedWhenWriterLockedAndDisconnectedLoop test

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#1559]
### Describe the bug

Occurred on linux-arm64:
```
2021-11-11T06:08:39.5836216Z 2021-11-11T06:08:39.581228Z I i.q.c.h.p.JsonQueryProcessorState [21] exec [q='select count() from balances_x']
2021-11-11T06:08:39.5837431Z 2021-11-11T06:08:39.581235Z I i.q.c.h.p.QueryCache hit [thread=questdb-worker-360, sql=select count() from balances_x]
2021-11-11T06:08:39.5838695Z 2021-11-11T06:08:39.581240Z I i.q.c.h.p.JsonQueryProcessorState [21] execute-cached [skip: 0, stop: 9223372036854775807]
2021-11-11T06:08:39.5840118Z 2021-11-11T06:08:39.581327Z I i.q.c.h.p.JsonQueryProcessorState [21] timings [compiler: 0, count: 0, execute: 103285, q=`select count() from balances_x`]
2021-11-11T06:08:39.5841545Z 2021-11-11T06:08:39.581344Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=21, lastRequestBytesSent=308, nCompletedRequests=31, totalBytesSent=4620]
2021-11-11T06:08:39.5843075Z 2021-11-11T06:08:39.581355Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-360, sql=select count() from balances_x]
2021-11-11T06:08:39.5920381Z 2021-11-11T06:08:39.590762Z I IODispatcher scheduling disconnect [fd=21, reason=12]
2021-11-11T06:08:39.5921662Z 2021-11-11T06:08:39.590768Z I IODispatcher disconnected [ip=255.255.255.255, fd=21, src=queue]
2021-11-11T06:08:39.6434444Z 2021-11-11T06:08:39.641478Z I IODispatcher connected [ip=127.0.0.1, fd=21]
2021-11-11T06:08:39.6435800Z 2021-11-11T06:08:39.641549Z I i.q.c.h.p.JsonQueryProcessorState [21] exec [q='select count() from balances_x']
2021-11-11T06:08:39.6437024Z 2021-11-11T06:08:39.641557Z I i.q.c.h.p.QueryCache hit [thread=questdb-worker-359, sql=select count() from balances_x]
2021-11-11T06:08:39.6438328Z 2021-11-11T06:08:39.641561Z I i.q.c.h.p.JsonQueryProcessorState [21] execute-cached [skip: 0, stop: 9223372036854775807]
2021-11-11T06:08:39.6439765Z 2021-11-11T06:08:39.641654Z I i.q.c.h.p.JsonQueryProcessorState [21] timings [compiler: 0, count: 0, execute: 108241, q=`select count() from balances_x`]
2021-11-11T06:08:39.6441203Z 2021-11-11T06:08:39.641670Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=21, lastRequestBytesSent=308, nCompletedRequests=28, totalBytesSent=4004]
2021-11-11T06:08:39.6442446Z 2021-11-11T06:08:39.641681Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-359, sql=select count() from balances_x]
2021-11-11T06:08:39.6515766Z 2021-11-11T06:08:39.651086Z I IODispatcher scheduling disconnect [fd=21, reason=12]
2021-11-11T06:08:39.6517203Z 2021-11-11T06:08:39.651093Z I IODispatcher disconnected [ip=255.255.255.255, fd=21, src=queue]
2021-11-11T06:08:39.7027657Z 2021-11-11T06:08:39.701386Z I IODispatcher connected [ip=127.0.0.1, fd=21]
2021-11-11T06:08:39.7028991Z 2021-11-11T06:08:39.701455Z I i.q.c.h.p.JsonQueryProcessorState [21] exec [q='select count() from balances_x']
2021-11-11T06:08:39.7030352Z 2021-11-11T06:08:39.701462Z I i.q.c.h.p.QueryCache hit [thread=questdb-worker-361, sql=select count() from balances_x]
2021-11-11T06:08:39.7031708Z 2021-11-11T06:08:39.701467Z I i.q.c.h.p.JsonQueryProcessorState [21] execute-cached [skip: 0, stop: 9223372036854775807]
2021-11-11T06:08:39.7033396Z 2021-11-11T06:08:39.701549Z I i.q.c.h.p.JsonQueryProcessorState [21] timings [compiler: 0, count: 0, execute: 97763, q=`select count() from balances_x`]
2021-11-11T06:08:39.7034808Z 2021-11-11T06:08:39.701565Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=21, lastRequestBytesSent=308, nCompletedRequests=54, totalBytesSent=8008]
2021-11-11T06:08:39.7036068Z 2021-11-11T06:08:39.701576Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-361, sql=select count() from balances_x]
2021-11-11T06:08:39.7168483Z 2021-11-11T06:08:39.711390Z I IODispatcher scheduling disconnect [fd=21, reason=12]
2021-11-11T06:08:39.7170232Z 2021-11-11T06:08:39.711396Z I IODispatcher disconnected [ip=255.255.255.255, fd=21, src=queue]
2021-11-11T06:08:39.7171253Z 2021-11-11T06:08:39.711543Z I i.q.c.h.HttpServer closed
2021-11-11T06:08:39.7172163Z 2021-11-11T06:08:39.711553Z I i.q.c.h.p.QueryCache closed
2021-11-11T06:08:39.7173136Z 2021-11-11T06:08:39.711554Z I i.q.c.h.HttpQueryTestBuilder cleaned [worker=3]
2021-11-11T06:08:39.7174056Z 2021-11-11T06:08:39.712121Z I i.q.c.h.HttpServer closed
2021-11-11T06:08:39.7174891Z 2021-11-11T06:08:39.712127Z I i.q.c.h.p.QueryCache closed
2021-11-11T06:08:39.7175798Z 2021-11-11T06:08:39.712128Z I i.q.c.h.HttpQueryTestBuilder cleaned [worker=2]
2021-11-11T06:08:39.7176692Z 2021-11-11T06:08:39.712219Z I i.q.c.h.HttpServer closed
2021-11-11T06:08:39.7177548Z 2021-11-11T06:08:39.712233Z I i.q.c.h.p.QueryCache closed
2021-11-11T06:08:39.7178553Z 2021-11-11T06:08:39.712234Z I i.q.c.h.HttpQueryTestBuilder cleaned [worker=0]
2021-11-11T06:08:39.7179480Z 2021-11-11T06:08:39.712383Z I i.q.c.h.HttpServer closed
2021-11-11T06:08:39.7180330Z 2021-11-11T06:08:39.712390Z I i.q.c.h.p.QueryCache closed
2021-11-11T06:08:39.7181240Z 2021-11-11T06:08:39.712392Z I i.q.c.h.HttpQueryTestBuilder cleaned [worker=1]
2021-11-11T06:08:39.7182294Z 2021-11-11T06:08:39.712443Z I IODispatcher closed
2021-11-11T06:08:39.7183141Z 2021-11-11T06:08:39.712895Z I i.q.c.TableWriter closed 'balances_x'
2021-11-11T06:08:39.7184135Z 2021-11-11T06:08:39.712899Z I i.q.c.p.WriterPool closed [table=`balances_x`, reason=POOL_CLOSED, by=1]
2021-11-11T06:08:39.7185088Z 2021-11-11T06:08:39.712912Z I i.q.c.p.WriterPool closed
2021-11-11T06:08:39.7186078Z 2021-11-11T06:08:39.712980Z I i.q.c.p.ReaderPool closed 'balances_x' [at=0:0, reason=POOL_CLOSED]
2021-11-11T06:08:39.7187206Z 2021-11-11T06:08:39.713045Z I i.q.c.p.ReaderPool closed 'balances_x' [at=0:1, reason=POOL_CLOSED]
2021-11-11T06:08:39.7188179Z 2021-11-11T06:08:39.713050Z I i.q.c.p.ReaderPool closed
2021-11-11T06:08:39.7232841Z 2021-11-11T06:08:39.720213Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.http.RetryIODispatcherTest.testInsertsIsPerformedWhenWriterLockedAndDisconnectedLoop : 
2021-11-11T06:08:39.7234155Z org.junit.ComparisonFailure: expected:<...LONG"}],"dataset":[[[4]]],"count":1}
2021-11-11T06:08:39.7234861Z 00
2021-11-11T06:08:39.7235523Z ...> but was:<...LONG"}],"dataset":[[[3]]],"count":1}
2021-11-11T06:08:39.7236158Z 00
2021-11-11T06:08:39.7236654Z ...>
2021-11-11T06:08:39.7237287Z 	at org.junit.Assert.assertEquals(Assert.java:117)
2021-11-11T06:08:39.7238044Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:308)
2021-11-11T06:08:39.7247839Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeExplicit(SendAndReceiveRequestBuilder.java:194)
2021-11-11T06:08:39.7249021Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeWithSocket(SendAndReceiveRequestBuilder.java:352)
2021-11-11T06:08:39.7249996Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.execute(SendAndReceiveRequestBuilder.java:106)
2021-11-11T06:08:39.7251033Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeWithStandardHeaders(SendAndReceiveRequestBuilder.java:309)
2021-11-11T06:08:39.7252145Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.lambda$assertInsertsIsPerformedWhenWriterLockedAndDisconnected$12(RetryIODispatcherTest.java:671)
2021-11-11T06:08:39.7253199Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.lambda$run$0(HttpQueryTestBuilder.java:201)
2021-11-11T06:08:39.7254280Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:405)
2021-11-11T06:08:39.7255087Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:67)
2021-11-11T06:08:39.7255919Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:60)
2021-11-11T06:08:39.7256869Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.assertInsertsIsPerformedWhenWriterLockedAndDisconnected(RetryIODispatcherTest.java:619)
2021-11-11T06:08:39.7258031Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.testInsertsIsPerformedWhenWriterLockedAndDisconnectedLoop(RetryIODispatcherTest.java:200)
2021-11-11T06:08:39.7258946Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-11-11T06:08:39.7259729Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-11-11T06:08:39.7260627Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-11-11T06:08:39.7261461Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2021-11-11T06:08:39.7262236Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2021-11-11T06:08:39.7263134Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2021-11-11T06:08:39.7263961Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2021-11-11T06:08:39.7264831Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2021-11-11T06:08:39.7265641Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2021-11-11T06:08:39.7266454Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-11-11T06:08:39.7267875Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2021-11-11T06:08:39.7268947Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2021-11-11T06:08:39.7269826Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2021-11-11T06:08:39.7270716Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2021-11-11T06:08:39.7271519Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2021-11-11T06:08:39.7272291Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2021-11-11T06:08:39.7298534Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2021-11-11T06:08:39.7299681Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2021-11-11T06:08:39.7300894Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2021-11-11T06:08:39.7301769Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-11-11T06:08:39.7302513Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2021-11-11T06:08:39.7303746Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
2021-11-11T06:08:39.7304656Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
2021-11-11T06:08:39.7369686Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
2021-11-11T06:08:39.7370699Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
2021-11-11T06:08:39.7371757Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
2021-11-11T06:08:39.7372680Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
2021-11-11T06:08:39.7374332Z 2021-11-11T06:08:39.720390Z I i.q.TestListener <<<< io.questdb.cutlass.http.RetryIODispatcherTest.testInsertsIsPerformedWhenWriterLockedAndDisconnectedLoop
```
https://dev.azure.com/questdb/questdb/_build/results?buildId=3420&view=logs&j=3f6d6c51-98d1-5660-18ca-359ba67071a1&t=81c0c352-b32a-5bdd-ab3e-d1f8bef5232f&s=69ac5850-00d1-5647-dde2-5c4259a813d3

### Environment

```markdown
- **QuestDB version**: latest 6.1.2-SNAPSHOT
- **OS**:
- **Browser**:
```

**Comment by puzpuzpuz** [comment]
Got this one recently in https://dev.azure.com/questdb/questdb/_build/results?buildId=4205&view=logs&j=bd06cbe1-a964-5048-ec4d-b96ff4693915&t=ad06c901-2e90-5184-2bb4-5f8df27de5c6

**Comment by bluestreak01** [comment]
This issue re-occurred in the above PR. Not fixed

**Comment by puzpuzpuz** [comment]
Reopening as this test is still flaky. Failed recently on linux-jdk8:
```
2022-01-19T20:45:34.9263565Z 2022-01-19T20:45:34.857881Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.http.RetryIODispatcherTest.testInsertsIsPerformedWhenWriterLockedAndDisconnectedLoop : 
2022-01-19T20:45:34.9264793Z org.junit.ComparisonFailure: expected:<...LONG"}],"dataset":[[[4]]],"count":1}
2022-01-19T20:45:34.9265298Z 00
2022-01-19T20:45:34.9265752Z ...> but was:<...LONG"}],"dataset":[[[3]]],"count":1}
2022-01-19T20:45:34.9266213Z 00
2022-01-19T20:45:34.9266549Z ...>
2022-01-19T20:45:34.9266993Z 	at org.junit.Assert.assertEquals(Assert.java:117)
2022-01-19T20:45:34.9267595Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:322)
2022-01-19T20:45:34.9268308Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeExplicit(SendAndReceiveRequestBuilder.java:193)
2022-01-19T20:45:34.9269147Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeWithSocket(SendAndReceiveRequestBuilder.java:355)
2022-01-19T20:45:34.9269954Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.execute(SendAndReceiveRequestBuilder.java:105)
2022-01-19T20:45:34.9270788Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeWithStandardHeaders(SendAndReceiveRequestBuilder.java:307)
2022-01-19T20:45:34.9271719Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.lambda$assertInsertsIsPerformedWhenWriterLockedAndDisconnected$12(RetryIODispatcherTest.java:680)
2022-01-19T20:45:34.9272581Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.lambda$run$0(HttpQueryTestBuilder.java:229)
2022-01-19T20:45:34.9273279Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:419)
2022-01-19T20:45:34.9273953Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:73)
2022-01-19T20:45:34.9274785Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:66)
2022-01-19T20:45:34.9275594Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.assertInsertsIsPerformedWhenWriterLockedAndDisconnected(RetryIODispatcherTest.java:624)
2022-01-19T20:45:34.9276538Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.testInsertsIsPerformedWhenWriterLockedAndDisconnectedLoop(RetryIODispatcherTest.java:200)
```

https://dev.azure.com/questdb/questdb/_build/results?buildId=4987&view=logs&j=a323ea9a-30c8-527d-e9f6-8da037f30fba&t=1d01f561-fbea-58f9-43ff-6d3a2de64d37

**Comment by puzpuzpuz** [comment]
Failed on ARM64 build yesterday:
```
2022-01-31T14:35:18.9071355Z org.junit.ComparisonFailure: expected:<...LONG"}],"dataset":[[[4]]],"count":1}
2022-01-31T14:35:18.9072115Z 00
2022-01-31T14:35:18.9072806Z ...> but was:<...LONG"}],"dataset":[[[3]]],"count":1}
2022-01-31T14:35:18.9073498Z 00
2022-01-31T14:35:18.9074042Z ...>
2022-01-31T14:35:18.9074708Z 	at org.junit.Assert.assertEquals(Assert.java:117)
2022-01-31T14:35:18.9075538Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:310)
2022-01-31T14:35:18.9076511Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeExplicit(SendAndReceiveRequestBuilder.java:193)
2022-01-31T14:35:18.9077615Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeWithSocket(SendAndReceiveRequestBuilder.java:355)
2022-01-31T14:35:18.9078696Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.execute(SendAndReceiveRequestBuilder.java:105)
2022-01-31T14:35:18.9079806Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeWithStandardHeaders(SendAndReceiveRequestBuilder.java:307)
2022-01-31T14:35:18.9081031Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.lambda$assertInsertsIsPerformedWhenWriterLockedAndDisconnected$12(RetryIODispatcherTest.java:705)
2022-01-31T14:35:18.9082185Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.lambda$run$0(HttpQueryTestBuilder.java:242)
2022-01-31T14:35:18.9083140Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:407)
2022-01-31T14:35:18.9084062Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:81)
2022-01-31T14:35:18.9085017Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:74)
2022-01-31T14:35:18.9086108Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.assertInsertsIsPerformedWhenWriterLockedAndDisconnected(RetryIODispatcherTest.java:627)
2022-01-31T14:35:18.9087317Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.testInsertsIsPerformedWhenWriterLockedAndDisconnectedLoop(RetryIODispatcherTest.java:201)
...
```

**Comment by puzpuzpuz** [comment]
Closing this one as it's been a while since the last occurrence and I failed to reproduce it locally.
