### ISSUE TITLE
NPE on `LATEST BY` SQL query

### ISSUE THREAD

**Issue by zhmaeff** [questdb/questdb#1578]
### Describe the bug

```
021-11-16T15:14:40.367857Z E i.q.c.h.p.JsonQueryProcessorState [49] Uh-oh. Error!
java.lang.NullPointerException
	at io.questdb.griffin.engine.table.AbstractDeferredTreeSetRecordCursorFactory.getCursorInstance(AbstractDeferredTreeSetRecordCursorFactory.java:93)
	at io.questdb.griffin.engine.table.LatestByValuesIndexedFilteredRecordCursorFactory.getCursorInstance(LatestByValuesIndexedFilteredRecordCursorFactory.java:83)
	at io.questdb.griffin.engine.table.LatestByValuesIndexedFilteredRecordCursorFactory.getCursorInstance(LatestByValuesIndexedFilteredRecordCursorFactory.java:39)
	at io.questdb.griffin.engine.table.AbstractDataFrameRecordCursorFactory.getCursor(AbstractDataFrameRecordCursorFactory.java:47)
	at io.questdb.griffin.engine.table.AbstractDeferredTreeSetRecordCursorFactory.getCursor(AbstractDeferredTreeSetRecordCursorFactory.java:39)
	at io.questdb.griffin.engine.groupby.GroupByRecordCursorFactory.getCursor(GroupByRecordCursorFactory.java:89)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.of(JsonQueryProcessorState.java:583)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect(JsonQueryProcessor.java:376)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeCachedSelect(JsonQueryProcessor.java:323)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:134)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:183)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:564)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:242)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:89)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:93)
	at io.questdb.mp.Worker.run(Worker.java:111)

2021-11-16T15:14:40.368140Z I i.q.c.h.HttpConnectionContext kicked out [fd=49]
2021-11-16T15:14:40.368162Z I http-server scheduling disconnect [fd=49, reason=5]
2021-11-16T15:14:40.368185Z I http-server disconnected [ip=127.0.0.1, fd=49, src=queue]
2021-11-16T15:14:40.368258Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-4, sql=SELECT metric, sum(value) FROM test_latest_by LATEST BY mc_member, metric WHERE mc_member IN('1', '2') AND metric IN('memory.usedHeap', 'memory.committedHeap')]
```

### To reproduce

Run these SQL queries 1 by 1:
```
CREATE TABLE IF NOT EXISTS 'test_latest_by' (time TIMESTAMP, metric SYMBOL CAPACITY 1024 index, value LONG, unit SYMBOL, mc_member SYMBOL index) TIMESTAMP(time) PARTITION BY DAY;

INSERT INTO test_latest_by VALUES(now(), 'memory.committedHeap', 200, 'bytes', '1');
INSERT INTO test_latest_by VALUES(now(), 'memory.usedHeap', 100, 'bytes', '1');
INSERT INTO test_latest_by VALUES(now(), 'memory.maxHeap', 300, 'bytes', '1');

INSERT INTO test_latest_by VALUES(now(), 'memory.committedHeap', 200, 'bytes', '3');
INSERT INTO test_latest_by VALUES(now(), 'memory.usedHeap', 100, 'bytes', '3');
INSERT INTO test_latest_by VALUES(now(), 'memory.maxHeap', 300, 'bytes', '3');

INSERT INTO test_latest_by VALUES(now(), 'memory.committedHeap', 200, 'bytes', '2');
INSERT INTO test_latest_by VALUES(now(), 'memory.usedHeap', 100, 'bytes', '2');
INSERT INTO test_latest_by VALUES(now(), 'memory.maxHeap', 300, 'bytes', '2');

SELECT metric, sum(value) FROM test_latest_by LATEST BY mc_member, metric WHERE mc_member IN('1', '2') AND metric IN('memory.usedHeap', 'memory.committedHeap');
```

### Expected Behavior

No NPE and some results like this returned:
-  memory.usedHeap=200
-  memory.committedHeap=400

### Environment

```markdown
- **QuestDB version**: 6.1.1-jdk8
- **OS**: Mac OS Monterey 12.0.1
- **Browser**: Safari
```

### Additional context

`SELECT metric, sum(value) FROM test_latest_by LATEST BY mc_member WHERE mc_member IN('1', '2') AND metric IN('memory.usedHeap', 'memory.committedHeap')` this query throws the following exception

```
2021-11-16T15:35:55.761063Z E i.q.c.h.p.JsonQueryProcessorState [49] internal error [q=`SELECT metric, sum(value) FROM test_latest_by LATEST BY mc_member WHERE mc_member IN('1', '2') AND metric IN('memory.usedHeap', 'memory.committedHeap')`, ex=
io.questdb.cairo.CairoException: [0] Not indexed: value
]
```

**Comment by puzpuzpuz** [comment]
That looks a lot like a bug: no NPE should be observed on query execution. Thanks for creating the issue!
