### ISSUE TITLE
Cannot lock table that is unlocking

### ISSUE THREAD

**Issue by benclark0** [questdb/questdb#1636]
### Describe the bug

While running QuestDB using Helm/kubernetes, I tried to delete the questdb pod so that k8s would restart it. The container presented an exit code 143 and the pod failed to terminate. Unfortunately these logs are lost to the sands of time. The pod was then stuck in a terminating state. I made sure the container wasn't running and force removed the pod. My questdb pod is now stuck in a crashloopbackoff state. The exceptions look like this:

```
2021-12-01T17:58:39.583568Z I server-main open database [id=2162653649977053017.8811455998645619569]
2021-12-01T17:58:39.583630Z I server-main platform [bit=64]
2021-12-01T17:58:39.583679Z I server-main OS: linux-amd64 [SSE4.1,7]
2021-12-01T17:58:39.590686Z I i.q.g.FunctionFactoryCache loading functions [test=false]
2021-12-01T17:58:39.783301Z I i.q.c.EngineMigration table structures are up to date
2021-12-01T17:58:39.895035Z E i.q.c.TableUtils cannot lock '/root/.questdb/db/telemetry.lock' [errno=11, fd=7]
2021-12-01T17:58:39.895164Z E i.q.c.p.WriterPool could not lock [table=`telemetry`, thread=1]
Exception in thread "main" io.questdb.griffin.SqlException: [27] cannot acquire table lock [lockedReason=unlocking]
	at io.questdb@6.0.4/io.questdb.griffin.SqlException.position(SqlException.java:60)
	at io.questdb@6.0.4/io.questdb.griffin.SqlException.$(SqlException.java:40)
	at io.questdb@6.0.4/io.questdb.griffin.SqlCompiler.createTable(SqlCompiler.java:1595)
	at io.questdb@6.0.4/io.questdb.griffin.SqlCompiler.executeWithRetries(SqlCompiler.java:1687)
	at io.questdb@6.0.4/io.questdb.griffin.SqlCompiler.createTableWithRetries(SqlCompiler.java:1651)
	at io.questdb@6.0.4/io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1362)
	at io.questdb@6.0.4/io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:688)
	at io.questdb@6.0.4/io.questdb.TelemetryJob.<init>(TelemetryJob.java:80)
	at io.questdb@6.0.4/io.questdb.ServerMain.<init>(ServerMain.java:164)
	at io.questdb@6.0.4/io.questdb.ServerMain.main(ServerMain.java:271)
```

Hoping anyone has an idea for how I can recover from this because right now I'm stuck.

### To reproduce

1. Delete a questdb pod and have the container exit in an error state
2. Note that the pod is stuck in a terminating state but the container is no longer running.
3. Foolishly force delete the questdb pod
4. Allow the pod to come back up. It will be in a CrashLoopBackoff state

### Expected Behavior

QuestDB could recover from a table stuck in an unlocking state

### Environment

```markdown
- **QuestDB version**:6.04
- **OS**: Red Hat Enterprise Linux release 8.4 (Ootpa)
- **Browser**: N/A (Using Helm Chart install of QuestDB in Kubernetes)
```

**Comment by bluestreak01** [comment]
please remove `telemetry*` directories are try to restart

**Comment by bluestreak01** [comment]
also upgrade to 6.1.2 please

**Comment by benclark0** [comment]
removing the telemetry directories got me past that point!  I then went to follow your instructions @bluestreak01 to upgrade to 6.1.2 and the upgrade of my table from v421 to v422 is hanging consistently. The conversion from 419 to 421 did seem to work though. The docker logs aren't very helpful:
`2021-12-01T21:55:02.252723Z I i.q.g.FunctionFactoryCache loading functions [test=false]
2021-12-01T21:55:02.481742Z I i.q.c.m.EngineMigration upgrading database [version=424]
2021-12-01T21:55:02.487351Z I i.q.c.m.EngineMigration upgrading [path=/root/.questdb/db/whelk_duration/_meta,fromVersion=421,toVersion=424]
2021-12-01T21:55:02.487817Z I i.q.c.m.EngineMigration backing up [file=/root/.questdb/db/whelk_duration/_meta,to=/root/.questdb/db/whelk_duration/_meta.v421]
2021-12-01T21:55:02.492067Z I i.q.c.m.EngineMigration upgrading table [path=/root/.questdb/db/whelk_duration,toVersion=422]`

from that directory, I see these things:
`🐳  my-questdb-0 whelk_duration # ls
_meta  _meta.prev  _meta.v419  _meta.v421  _todo_  _txn  _txn_scoreboard  default`

I can't seem to find more helpful logging on it. I am using an NFS PV but it doesn't seem to be a problem with the volume. I looked around but can't find any other issues/help where people have been stuck here.  The schema includes string, float, timestamp, and int.

**Comment by bluestreak01** [comment]
NFS is not supported!

**Comment by bsmth** [comment]
Hi @benclark0 - could you try again [with a supported filesystem](https://questdb.io/docs/operations/backup/#limitations).

> QuestDB officially supports EXT4 or XTS or any filesystem that supports [mmap](https://man7.org/linux/man-pages/man2/mmap.2.html).

Let us know if that resolves the issue for you!

**Comment by bluestreak01** [comment]
I'm assuming that NFS has hang the system. We had better success with GFS, although this is not an officially supported file system either.
