### ISSUE TITLE
Hash join assertion error

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1684]
### Describe the bug

Memory bound assertion error generated for a hash join on string field, here is relevant piece of log

```
2021-12-10T08:50:45.842027Z I i.q.c.p.PGConnectionContext parse [fd=17, q=SELECT        result.TABLE_CAT,        result.TABLE_SCHEM,        result.TABLE_NAME,        result.COLUMN_NAME,        result.KEY_SEQ,        result.PK_NAME FROM      (SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM,   ct.relname AS TABLE_NAME, a.attname AS COLUMN_NAME,   (information_schema._pg_expandarray(i.indkey)).n AS KEY_SEQ, ci.relname AS PK_NAME,   information_schema._pg_expandarray(i.indkey) AS KEYS, a.attnum AS A_ATTNUM FROM pg_catalog.pg_class ct   JOIN pg_catalog.pg_attribute a ON (ct.oid = a.attrelid)   JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid)   JOIN pg_catalog.pg_index i ON ( a.attrelid = i.indrelid)   JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid) WHERE true  AND ct.relname = E'processed_swap_txs' AND i.indisprimary  ) result where  result.A_ATTNUM = (result.KEYS).x  ORDER BY result.table_name, result.pk_name, result.key_seq]^M
2021-12-10T08:50:45.846389Z I i.q.g.SqlCompiler plan [q=`select-choose TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, KEY_SEQ, PK_NAME from (select-virtual [NULL TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, _pg_expandarray . n KEY_SEQ, PK_NAME] NULL TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, _pg_expandarray . n KEY_SEQ, PK_NAME, _pg_expandarray KEYS, A_ATTNUM from (select-choose [n.nspname TABLE_SCHEM, ct.relname TABLE_NAME, a.attname COLUMN_NAME, _pg_expandarray, ci.relname PK_NAME] n.nspname TABLE_SCHEM, ct.relname TABLE_NAME, a.attname COLUMN_NAME, _pg_expandarray, ci.relname PK_NAME, _pg_expandarray KEYS, a.attnum A_ATTNUM from (select [relname, oid, relnamespace] from pg_catalog.pg_class() ct join select [attname, attrelid, attnum] from pg_catalog.pg_attribute() a on a.attrelid = ct.oid join select [nspname, oid] from pg_catalog.pg_namespace() n on n.oid = ct.relnamespace join (select [indrelid, indisprimary, indexrelid] from pg_catalog.pg_index() i where indisprimary) i on i.indrelid = a.attrelid join select [relname, oid] from pg_catalog.pg_class() ci on ci.oid = i.indexrelid cross join select-cursor [information_schema._pg_expandarray(i.indkey) _pg_expandarray] information_schema._pg_expandarray(i.indkey) _pg_expandarray from (information_schema._pg_expandarray(i.indkey)) _xQdbA0 post-join-where a.attnum = _pg_expandarray . x where relname = E'processed_swap_txs' const-where true) ct) ct) result order by TABLE_NAME, PK_NAME, KEY_SEQ`, fd=17]^M
2021-12-10T08:50:45.915674Z E server-main unhandled error [job=io.questdb.cutlass.pgwire.PGWireServer$1@cd1d761, ex=^M
java.lang.AssertionError^M
        at io.questdb.cairo.vm.MemoryCARWImpl.checkAndExtend(MemoryCARWImpl.java:155)^M
        at io.questdb.cairo.vm.MemoryCARWImpl.appendAddressFor(MemoryCARWImpl.java:110)^M
        at io.questdb.cairo.vm.api.MemoryCARW.putStr(MemoryCARW.java:216)^M
        at io.questdb.cairo.vm.api.MemoryCARW.putStr(MemoryCARW.java:209)^M
        at io.questdb.cairo.RecordChain.putStr(RecordChain.java:231)^M
        at io.questdb.cairo.sink/0x000000010025a440.copy(Unknown Source)^M
        at io.questdb.cairo.RecordChain.put(RecordChain.java:156)^M
        at io.questdb.griffin.engine.join.HashOuterJoinRecordCursorFactory.buildMap(HashOuterJoinRecordCursorFactory.java:85)^M
        at io.questdb.griffin.engine.join.HashJoinRecordCursorFactory.buildMapOfSlaveRecords(HashJoinRecordCursorFactory.java:99)^M
        at io.questdb.griffin.engine.join.HashJoinRecordCursorFactory.getCursor(HashJoinRecordCursorFactory.java:84)^M
        at io.questdb.griffin.engine.join.HashJoinRecordCursorFactory.getCursor(HashJoinRecordCursorFactory.java:89)^M
        at io.questdb.griffin.engine.join.HashJoinRecordCursorFactory.getCursor(HashJoinRecordCursorFactory.java:89)^M
        at io.questdb.griffin.engine.join.HashJoinRecordCursorFactory.getCursor(HashJoinRecordCursorFactory.java:89)^M
        at io.questdb.griffin.engine.join.CrossJoinRecordCursorFactory.getCursor(CrossJoinRecordCursorFactory.java:61)^M
        at io.questdb.griffin.engine.table.FilteredRecordCursorFactory.getCursor(FilteredRecordCursorFactory.java:55)^M
        at io.questdb.griffin.engine.table.SelectedRecordCursorFactory.getCursor(SelectedRecordCursorFactory.java:58)^M
        at io.questdb.griffin.engine.table.VirtualRecordCursorFactory.getCursor(VirtualRecordCursorFactory.java:73)^M
        at io.questdb.griffin.engine.orderby.SortedRecordCursorFactory.getCursor(SortedRecordCursorFactory.java:73)^M
        at io.questdb.cutlass.pgwire.PGConnectionContext.setupFactoryAndCursor(PGConnectionContext.java:2219)^M
        at io.questdb.cutlass.pgwire.PGConnectionContext.processExecute(PGConnectionContext.java:1836)^M
        at io.questdb.cutlass.pgwire.PGConnectionContext.processExec(PGConnectionContext.java:1829)^M
        at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1411)^M
        at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:371)^M
        at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:69)^M
        at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:76)^M
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)^M
        at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:91)^M
        at io.questdb.mp.Worker.run(Worker.java:112)^M
```

### Environment

```markdown
- **QuestDB version**: 6.0.9
- **OS**:
- **Browser**:
```

**Comment by laksh1270** [comment]
Can you assign this to me
