### ISSUE TITLE
Flaky RetryIODispatcherTest.testImportProcessedWhenClientDisconnectedLoop

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#1700]
### Describe the bug

Occurred on linux-jdk8:
```
2021-12-16T12:37:29.0386639Z 2021-12-16T12:37:29.017259Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.http.RetryIODispatcherTest.testImportProcessedWhenClientDisconnectedLoop : 
2021-12-16T12:37:29.0387340Z org.junit.ComparisonFailure: expected:<...LONG"}],"dataset":[[[72]]],"count":1}
2021-12-16T12:37:29.0387713Z 00
2021-12-16T12:37:29.0388036Z ...> but was:<...LONG"}],"dataset":[[[48]]],"count":1}
2021-12-16T12:37:29.0388361Z 00
2021-12-16T12:37:29.0388596Z ...>
2021-12-16T12:37:29.0388896Z 	at org.junit.Assert.assertEquals(Assert.java:117)
2021-12-16T12:37:29.0389329Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:318)
2021-12-16T12:37:29.0389872Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeExplicit(SendAndReceiveRequestBuilder.java:193)
2021-12-16T12:37:29.0390487Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeWithSocket(SendAndReceiveRequestBuilder.java:351)
2021-12-16T12:37:29.0391090Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.execute(SendAndReceiveRequestBuilder.java:105)
2021-12-16T12:37:29.0391714Z 	at io.questdb.cutlass.http.SendAndReceiveRequestBuilder.executeWithStandardHeaders(SendAndReceiveRequestBuilder.java:308)
2021-12-16T12:37:29.0392338Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.assertNRowsInserted(RetryIODispatcherTest.java:404)
2021-12-16T12:37:29.0392978Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.lambda$assertImportProcessedWhenClientDisconnected$4(RetryIODispatcherTest.java:389)
2021-12-16T12:37:29.0393609Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.lambda$run$0(HttpQueryTestBuilder.java:229)
2021-12-16T12:37:29.0394108Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:415)
2021-12-16T12:37:29.0394604Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:73)
2021-12-16T12:37:29.0395121Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:66)
2021-12-16T12:37:29.0395713Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.assertImportProcessedWhenClientDisconnected(RetryIODispatcherTest.java:344)
2021-12-16T12:37:29.0396381Z 	at io.questdb.cutlass.http.RetryIODispatcherTest.testImportProcessedWhenClientDisconnectedLoop(RetryIODispatcherTest.java:144)
2021-12-16T12:37:29.0396918Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-16T12:37:29.0397370Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-16T12:37:29.0397899Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-16T12:37:29.0398543Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2021-12-16T12:37:29.0399000Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2021-12-16T12:37:29.0399534Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2021-12-16T12:37:29.0400060Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2021-12-16T12:37:29.0400588Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2021-12-16T12:37:29.0401095Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2021-12-16T12:37:29.0401660Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-12-16T12:37:29.0402158Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2021-12-16T12:37:29.0402651Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2021-12-16T12:37:29.0403156Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2021-12-16T12:37:29.0403665Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2021-12-16T12:37:29.0404152Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2021-12-16T12:37:29.0404606Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2021-12-16T12:37:29.0405067Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2021-12-16T12:37:29.0405529Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2021-12-16T12:37:29.0405989Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2021-12-16T12:37:29.0406453Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-12-16T12:37:29.0406903Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2021-12-16T12:37:29.0407366Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
2021-12-16T12:37:29.0407904Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
2021-12-16T12:37:29.0408437Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
2021-12-16T12:37:29.0408987Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
2021-12-16T12:37:29.0409556Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
2021-12-16T12:37:29.0410080Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
2021-12-16T12:37:29.0410905Z 2021-12-16T12:37:29.017446Z I i.q.TestListener <<<< io.questdb.cutlass.http.RetryIODispatcherTest.testImportProcessedWhenClientDisconnectedLoop
```

https://dev.azure.com/questdb/questdb/_build/results?buildId=4213&view=logs&j=a323ea9a-30c8-527d-e9f6-8da037f30fba&t=1d01f561-fbea-58f9-43ff-6d3a2de64d37

### Environment

```markdown
- **QuestDB version**: latest 6.1.4-SNAPSHOT
- **OS**:
- **Browser**:
```

**Comment by nwoolmer** [comment]
[testImportProcessedWhenClientDisconnectedLoop.txt](https://github.com/user-attachments/files/20887733/testImportProcessedWhenClientDisconnectedLoop.txt)

Re-ocurred on this PR: https://github.com/questdb/questdb/pull/5761
