### ISSUE TITLE
cannot open shared object file: No such file or directory (Possible cause: architecture word width mismatch)

### ISSUE THREAD

**Issue by Gszekt** [questdb/questdb#1715]
### Describe the bug

When I trying to run QuestDB on mips64 , it sharts with the stack trace below.

Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libquestdb10629085137526084360.so: /tmp/libquestdb10629085137526084360.so: cannot open shared object file: No such file or directory (Possible cause: architecture word width mismatch)
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
at java.base/java.lang.Runtime.load0(Runtime.java:768)
at java.base/java.lang.System.load(System.java:1837)
at io.questdb@6.1.2/io.questdb.std.Os.loadLib(Os.java:174)
at io.questdb@6.1.2/io.questdb.std.Os.(Os.java:192)
at io.questdb@6.1.2/io.questdb.ServerMain.(ServerMain.java:74)
at io.questdb@6.1.2/io.questdb.ServerMain.main(ServerMain.java:253)

Then I tried to build QuestDB from source code, there is another error:

[  1%] Building CXX object CMakeFiles/questdb-avx2.dir/src/main/c/share/vec_agg.cpp.o
c++: error: unrecognized command line option ‘-m64’
c++: error: unrecognized command line option ‘-mavx2’
c++: error: unrecognized command line option ‘-mfma’; did you mean ‘-mdmx’?
gmake[2]: *** [CMakeFiles/questdb-avx2.dir/build.make:76: CMakeFiles/questdb-avx2.dir/src/main/c/share/vec_agg.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:175: CMakeFiles/questdb-avx2.dir/all] Error 2
gmake: *** [Makefile:101: all] Error 2

### Environment

```markdown
- **QuestDB version**:6.1.2
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
`mips64` is not a supported platform for now. `vec_agg.cpp` relies on x86 SIMD instruction set and wont compile. There is a replacement implementation that we use for ARM64 that should be compiled instead. Perhaps its a matter of refactoring cmake file

**Comment by Gszekt** [comment]
> `mips64` is not a supported platform for now. `vec_agg.cpp` relies on x86 SIMD instruction set and wont compile. There is a replacement implementation that we use for ARM64 that should be compiled instead. Perhaps its a matter of refactoring cmake file

OK , thanks !

**Comment by Gszekt** [comment]
> `mips64` is not a supported platform for now. `vec_agg.cpp` relies on x86 SIMD instruction set and wont compile. There is a replacement implementation that we use for ARM64 that should be compiled instead. Perhaps its a matter of refactoring cmake file

Will mips64 be supported in the future?

**Comment by bluestreak01** [comment]
which device do you use to compile on mips64?

**Comment by Gszekt** [comment]
> which device do you use to compile on mips64?

Loongson-3A R4
