### ISSUE TITLE
Unable to import exported data from QuestDB

### ISSUE THREAD

**Issue by arturro96** [questdb/questdb#1716]
### Describe the bug

I'm storing a JSON in one column of type string:
`{"filed1":1, "filed2":1, "filed3":"admin", "filed4":1}`

After exporting I receive:
`"{\"filed1"\":1, \"filed2\":1, \"filed3\":\"admin\", \"filed4\":1}"`

And then, when I want to import exported csv file, I've got an error:

	2021-12-20T10:37:06.969591Z I i.q.c.t.TextLoader configured [table=`new_table`, overwrite=true, durable=false, atomicity=2, partitionBy=MONTH, timestamp=timestamp]
	2021-12-20T10:37:06.989465Z I i.q.c.t.TextDelimiterScanner scan result [table=`new_table`, delimiter=',', priority=10, mean=3.0, stddev=0.0]
	2021-12-20T10:37:07.001425Z E i.q.c.t.TextLexer extra fields [table=new_table, fieldIndex=4, fieldMax=3]
	1 -> 2021-01-01T00:00:01.000000Z,1609455601000,1.0,{\ ...
	2021-12-20T10:37:07.003583Z E i.q.c.t.TextLexer extra fields [table=new_table, fieldIndex=5, fieldMax=3]
	1 -> 2021-01-01T00:00:01.000000Z,1609455601000,1.0,{\ ...
	2021-12-20T10:37:07.004042Z E i.q.c.t.TextLexer extra fields [table=new_table, fieldIndex=6, fieldMax=3]
	1 -> 2021-01-01T00:00:01.000000Z,1609455601000,1.0,{\ ...
	2021-12-20T10:37:07.004881Z E i.q.c.t.TextLexer extra fields [table=new_table, fieldIndex=4, fieldMax=3]
	2 -> 2021-01-01T00:00:02.000000Z,1609455602000,1.0,{\ ...
	2021-12-20T10:37:07.004894Z E i.q.c.t.TextLexer extra fields [table=new_table, fieldIndex=5, fieldMax=3]
	2 -> 2021-01-01T00:00:02.000000Z,1609455602000,1.0,{\ ...
	2021-12-20T10:37:07.004903Z E i.q.c.t.TextLexer extra fields [table=new_table, fieldIndex=6, fieldMax=3]
	2 -> 2021-01-01T00:00:02.000000Z,1609455602000,1.0,{\ ...
	2021-12-20T10:37:07.009065Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@4c8724a2, ex=
	java.lang.AssertionError
	at io.questdb.std.ObjList.getQuick(ObjList.java:143)
	at io.questdb.cutlass.text.TextLexer.shift(TextLexer.java:390)
	at io.questdb.cutlass.text.TextLexer.rollLine(TextLexer.java:379)
	at io.questdb.cutlass.text.TextLexer.parse(TextLexer.java:358)
	at io.questdb.cutlass.text.TextLexer.parse(TextLexer.java:133)
	at io.questdb.cutlass.text.TextLexer.analyseStructure(TextLexer.java:84)
	at io.questdb.cutlass.text.TextLoader.parseStructure(TextLoader.java:237)
	at io.questdb.cutlass.text.TextLoader.parse(TextLoader.java:191)
	at io.questdb.cutlass.http.processors.TextImportProcessor.onChunk(TextImportProcessor.java:93)
	at io.questdb.cutlass.http.HttpMultipartContentParser.onChunkWithRetryHandle(HttpMultipartContentParser.java:234)
	at io.questdb.cutlass.http.HttpMultipartContentParser.parse(HttpMultipartContentParser.java:188)
	at io.questdb.cutlass.http.HttpConnectionContext.parseMultipartResult(HttpConnectionContext.java:630)
	at io.questdb.cutlass.http.HttpConnectionContext.continueConsumeMultipart(HttpConnectionContext.java:357)
	at io.questdb.cutlass.http.HttpConnectionContext.consumeMultipart(HttpConnectionContext.java:341)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:548)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:242)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:89)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:93)
	at io.questdb.mp.Worker.run(Worker.java:111)

So it seems that it fails on backslashes generated during export.

### Environment

```markdown
- **QuestDB version**: 6.1.2
- **OS**: macOS
```

**Comment by bsmth** [comment]
Thanks for reporting this @arturro96, we'll take a look 👀

**Comment by bluestreak01** [comment]
I can reproduce the problem, thank you

**Comment by bluestreak01** [comment]
it appears that QuestDB CSV parser does not support escaped quotes, e.g. `\"`. This is non-trivial change, so please bear with us

**Comment by CutieDeng** [comment]
Can I have a try? But I am confusing about some points that: 
- The format of the input/output file is `.csv` or `.json `? 
- It seems exist a typo with an extra `"` char in the above content: "{\"filed1"\":1, \"filed2\":1, \"filed3\":\"admin\", \"filed4\":1}", exactly after the 'field1' word. 
- I fails to import a json file in questDB, maybe I do not understand the exact format of it. 😭

**Comment by ZachsCoffee** [comment]
@bluestreak01 Can I start working on this one?
