### ISSUE TITLE
NullPointerException using PostgreSQL/JDBC PreparedStatement on table with 'symbol index'

### ISSUE THREAD

**Issue by mcbridematt** [questdb/questdb#1740]
### Describe the bug

When using PreparedStatements with JDBC on a table with `symbol index`, this NullPointerException can occur:
```
2021-12-28T22:19:50.056029Z I i.q.g.SqlCompiler plan [q=`select-choose ticker, sample_time, value from (select [ticker, sample_time, value] from symboltest timestamp (sample_time) where ticker = $1)`, fd=1944]
2021-12-28T22:19:50.056840Z E server-main unhandled error [job=io.questdb.cutlass.pgwire.PGWireServer$1@2bedbff1, ex=
java.lang.NullPointerException
        at io.questdb.griffin.FunctionParser.getBindVariableService(FunctionParser.java:873)
        at io.questdb.griffin.FunctionParser.createIndexParameter(FunctionParser.java:158)
        at io.questdb.griffin.FunctionParser.parseIndexedParameter(FunctionParser.java:887)
        at io.questdb.griffin.FunctionParser.createBindVariable(FunctionParser.java:142)
        at io.questdb.griffin.SqlCodeGenerator.generateTableQuery(SqlCodeGenerator.java:2663)
        at io.questdb.griffin.SqlCodeGenerator.generateNoSelect(SqlCodeGenerator.java:1182)
        at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:1646)
        at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:1300)
        at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:1289)
        at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:2373)
        at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:1859)
        at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:1631)
        at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:1300)
        at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:1289)
        at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:679)
        at io.questdb.griffin.SqlCompiler.generate(SqlCompiler.java:1984)
        at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1638)
        at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:913)
        at io.questdb.cutlass.pgwire.PGConnectionContext.compileQuery(PGConnectionContext.java:1042)
        at io.questdb.cutlass.pgwire.PGConnectionContext.parseQueryText(PGConnectionContext.java:1435)
        at io.questdb.cutlass.pgwire.PGConnectionContext.processParse(PGConnectionContext.java:1934)
        at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1384)
        at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:371)
        at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:68)
        at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:72)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)
        at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:87)
        at io.questdb.mp.Worker.run(Worker.java:111)
]

```

### To reproduce

The issue seems to occur consistently on a 'fresh' (restarted) server instance.

With a table like:
```
CREATE TABLE symboltest (
    ticker symbol index,
    sample_time timestamp,
    value int
) timestamp (sample_time);
INSERT INTO symboltest VALUES ('ABC',NOW(),rnd_int());
```

Then
```
SELECT * FROM symboltest WHERE ticker=?
setString(1,'ABC')
```

If the table is only created without an index on symbol (`CREATE TABLE symboltest ( ticker symbol, ..`) the NPE does not occur.

If a non-prepared statement is executed before hand over JDBC (`SELECT * FROM symboltest WHERE ticker='ABC'`) then sometimes the PreparedStatement does return successfully.

### Expected Behavior

No NullPointerException on the server side, Prepared statement returns successfully.

### Environment

```markdown
- **QuestDB version**: 6.1.3
- **OS**: Windows 10, Zulu JDK 11
- **PostgreSQL driver**: Up to and including 42.3.1
```

### Additional context

Minimal test client:
```
public class TestJDBCSymbol {    
    public static void printResultSet(ResultSet rs) throws SQLException {
        while (rs.next()) {
            String symbol = rs.getString("ticker");
            LocalDateTime timestamp = rs.getObject("sample_time", LocalDateTime.class);
            int value = rs.getInt("value");
            System.out.format("Symbol: %s Timestamp: %s value: %d\n", symbol, timestamp, value);
        }
    }

    public static void main(String[] args) throws SQLException {
        Properties properties = new Properties();
        properties.setProperty("user", "admin");
        properties.setProperty("password", "quest");
        properties.setProperty("sslmode", "disable");

        final Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:8812/qdb", properties);
        System.out.println("Connected");

        System.out.println("Non prepared statement: ");
        Statement stmt = connection.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM symboltest where ticker='ABC'");
        printResultSet(rs);
        
        System.out.println("PreparedStatement:");
        // PreparedStatement version
        PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM symboltest where ticker=?");
        preparedStatement.setString(1, "ABC");
        ResultSet preparedRs = preparedStatement.executeQuery();
        printResultSet(preparedRs);

        System.out.flush();
        connection.close();
    }
}
```

**Comment by bluestreak01** [comment]
thank you for detailed issue Mathew 👍  I'm investigating...
