### ISSUE TITLE
Flaky ReaderPoolTest.testGetAndCloseRace test

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1745]
### Describe the bug

Flapping test:

```
2021-12-28T09:44:59.4359640Z 2021-12-28T09:44:58.884459Z I i.q.c.AbstractCairoTest Tearing down test ReaderPoolTest#testGetAndCloseRace
2021-12-28T09:44:59.4362640Z 2021-12-28T09:44:58.902433Z E i.q.TestListener ***** Test Failed *****io.questdb.cairo.pool.ReaderPoolTest.testGetAndCloseRace : 
2021-12-28T09:44:59.4364750Z java.lang.AssertionError: [15,12,16,17,18] expected:<3> but was:<6>
2021-12-28T09:44:59.4366400Z    at org.junit.Assert.fail(Assert.java:89)
2021-12-28T09:44:59.4367700Z    at org.junit.Assert.failNotEquals(Assert.java:835)
2021-12-28T09:44:59.4369500Z    at org.junit.Assert.assertEquals(Assert.java:647)
2021-12-28T09:44:59.4374600Z    at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:418)
2021-12-28T09:44:59.4376290Z    at io.questdb.cairo.pool.ReaderPoolTest.assertWithPool(ReaderPoolTest.java:877)
2021-12-28T09:44:59.4378090Z    at io.questdb.cairo.pool.ReaderPoolTest.assertWithPool(ReaderPoolTest.java:873)
2021-12-28T09:44:59.4380670Z    at io.questdb.cairo.pool.ReaderPoolTest.testGetAndCloseRace(ReaderPoolTest.java:382)
2021-12-28T09:44:59.4384810Z    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-28T09:44:59.4386240Z    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-28T09:44:59.4387810Z    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-28T09:44:59.4393480Z    at java.lang.reflect.Method.invoke(Method.java:566)
2021-12-28T09:44:59.4395510Z    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
```

Observed in https://dev.azure.com/questdb/questdb/_build/results?buildId=4386&view=logs&j=3fa4b4be-6db3-54fa-4432-6a83730bebb7&t=bb90c814-cfaa-5557-8498-4851227a92fe

Please do not confuse with https://github.com/questdb/questdb/issues/1513, which is fixed

### To reproduce

Run this test to failure

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
Still flaky

**Comment by puzpuzpuz** [comment]
Failed to reproduce this one locally and with 3 CI runs on #1804. Let's see how frequently it shows up on CI.

**Comment by bluestreak01** [comment]
Duplicate of https://github.com/questdb/questdb/issues/1813
