### ISSUE TITLE
NullPointerException in AbstractTypeContainer.copyTypesFrom using prepared statements on table with symbol index

### ISSUE THREAD

**Issue by mcbridematt** [questdb/questdb#1752]
### Describe the bug

This is a follow on to #1740. I built a 6.1.4-SNAPSHOT Docker container to see if the fix worked.

If I use prepared statements to set where clauses for the other columns (not the symbol column) I get this NPE:
```
2022-01-02T21:17:05.386966Z I i.q.c.p.PGConnectionContext parse [fd=66, q=SELECT * FROM symboltest where ticker=$1 and sample_time=$2]
2022-01-02T21:17:05.389839Z I i.q.g.SqlCompiler plan [q=`select-choose ticker, sample_time, value from (select [ticker, sample_time, value] from symboltest timestamp (sample_time) where ticker = $1 and sample_time = $2)`, fd=66]
2022-01-02T21:17:05.399248Z E server-main unhandled error [job=io.questdb.cutlass.pgwire.PGWireServer$1@4b672daa, ex=
java.lang.NullPointerException: Cannot invoke "io.questdb.cairo.sql.Function.getType()" because the return value of "io.questdb.cairo.sql.BindVariableService.getFunction(int)" is null
   at io.questdb.cutlass.pgwire.AbstractTypeContainer.copyTypesFrom(AbstractTypeContainer.java:60)
   at io.questdb.cutlass.pgwire.TypesAndSelect.of(TypesAndSelect.java:51)
   at io.questdb.cutlass.pgwire.PGConnectionContext.compileQuery(PGConnectionContext.java:1053)
   at io.questdb.cutlass.pgwire.PGConnectionContext.parseQueryText(PGConnectionContext.java:1453)
   at io.questdb.cutlass.pgwire.PGConnectionContext.processParse(PGConnectionContext.java:1952)
   at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1395)
   at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:372)
   at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:65)
   at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:74)
   at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)
   at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:89)
   at io.questdb.mp.Worker.run(Worker.java:111)
]
```
This happens for both a timestamp and integer column:
```
INSERT INTO symboltest VALUES ('ABC','2022-01-01 00:00:00',100);

/* Works (bound on symbol column only, same as 1740) */
PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM symboltest where ticker=?");
preparedStatement.setString(1, "ABC");
ResultSet preparedRs = preparedStatement.executeQuery();

/* Works (no bound variables) */
Statement stmt = connection.createStatement();
ResultSet rs = stmt.executeQuery("SELECT * FROM symboltest where ticker='ABC' and value=100");

/* Fails (bound on int column) */
PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM symboltest where ticker=? and value=?");
preparedStatement.setString(1, "ABC");
preparedStatement.setInt(2, 100);
ResultSet preparedRs = preparedStatement.executeQuery(); // server side NPE

/* Fails (bound on timestamp column) */
PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM symboltest where ticker=? and sample_time=?");
preparedStatement.setString(1, "ABC");
preparedStatement.setString(2, "2022-01-01 00:00:00");
ResultSet preparedRs = preparedStatement.executeQuery(); // server side NPE

```

On a table with no index on symbol, all of the above works.

### To reproduce

Using this table:
```
CREATE TABLE symboltest (
    ticker symbol index,
    sample_time timestamp,
    value int
) timestamp (sample_time);
INSERT INTO symboltest VALUES ('ABC','2022-01-01 00:00:00',100);
```
Attempt to set values for `sample_time` or `value` in a prepared statement using a PostgreSQL/JDBC connection.

### Expected Behavior

For the queries to return as expected (they all execute successfully in the web console)

### Environment

```markdown
- **QuestDB version**:6.1.4-SNAPSHOT (as of commit 2fcf366fe8cc29da8a08ad4f4cea36d563703c7b)
- **OS**: Linux (Docker container, arm64)
```

**Comment by bluestreak01** [comment]
I can reproduce, thanks 👍

**Comment by bluestreak01** [comment]
The root cause is that indexed symbol lookup implementations do not support bind variables. Additionally `WhereClauseParser` is not able to "define" bind variable type yet for PG wire.

The issue is quite involved, we will fix this asap

**Comment by puzpuzpuz** [comment]
@mcbridematt this issue should be closed by #1825 and shipped in 6.2. Please reopen if you're able to find new edge cases.
