### ISSUE TITLE
Flaky IODispatcherTest.testImportEmptyData

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1771]
### Describe the bug

```
2022-01-07T20:54:23.1600827Z 2022-01-07T20:54:23.132086Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.http.IODispatcherTest.testImportEmptyData : 
2022-01-07T20:54:23.1603256Z java.lang.AssertionError: [17,19,80,18,21,22,46] expected:<8> but was:<7>
2022-01-07T20:54:23.1604582Z    at org.junit.Assert.fail(Assert.java:89)
2022-01-07T20:54:23.1605787Z    at org.junit.Assert.failNotEquals(Assert.java:835)
2022-01-07T20:54:23.1607030Z    at org.junit.Assert.assertEquals(Assert.java:647)
2022-01-07T20:54:23.1608273Z    at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:418)
2022-01-07T20:54:23.1609729Z    at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:73)
2022-01-07T20:54:23.1611085Z    at io.questdb.cutlass.http.IODispatcherTest.testImport(IODispatcherTest.java:683)
2022-01-07T20:54:23.1612436Z    at io.questdb.cutlass.http.IODispatcherTest.testImport(IODispatcherTest.java:660)
2022-01-07T20:54:23.1613870Z    at io.questdb.cutlass.http.IODispatcherTest.testImportEmptyData(IODispatcherTest.java:964)
2022-01-07T20:54:23.1615215Z    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-01-07T20:54:23.1616531Z    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-01-07T20:54:23.1617983Z    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-01-07T20:54:23.1619316Z    at java.lang.reflect.Method.invoke(Method.java:566)
2022-01-07T20:54:23.1620627Z    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-01-07T20:54:23.1622001Z    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-01-07T20:54:23.1623367Z    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-01-07T20:54:23.1624730Z    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-01-07T20:54:23.1629603Z    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-01-07T20:54:23.1632238Z    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2022-01-07T20:54:23.1633663Z    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-01-07T20:54:23.1635012Z    at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2022-01-07T20:54:23.1636336Z    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2022-01-07T20:54:23.1637653Z    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2022-01-07T20:54:23.1639020Z    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2022-01-07T20:54:23.1640334Z    at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2022-01-07T20:54:23.1641501Z    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2022-01-07T20:54:23.1642646Z    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2022-01-07T20:54:23.1643794Z    at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2022-01-07T20:54:23.1644936Z    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2022-01-07T20:54:23.1646075Z    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-01-07T20:54:23.1647422Z    at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2022-01-07T20:54:23.1648615Z    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
2022-01-07T20:54:23.1649850Z    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
2022-01-07T20:54:23.1651165Z    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
2022-01-07T20:54:23.1652406Z    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
2022-01-07T20:54:23.1654829Z    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
2022-01-07T20:54:23.1657980Z    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

### Environment

```markdown
- **QuestDB version**:6.1.4-SNAPSHOT
- **OS**: Linux JDK11
- **Browser**:
```

**Comment by bluestreak01** [comment]
feel free to reopen if there evidence this test still flaps
