### ISSUE TITLE
An error occured  if there is no record in the subquery

### ISSUE THREAD

**Issue by yiwojiu** [questdb/questdb#1786]
### Describe the bug

i query a sql in the web console, if the sub query has 'sample by'  and has no record, the query will reported error in the server log as follow:
```
2022-01-14T09:22:45.645552Z I i.q.c.p.PGConnectionContext parse [fd=55, q=SET application_name = 'PostgreSQL JDBC Driver']
2022-01-14T09:23:03.716523Z I i.q.c.p.PGConnectionContext parse [fd=55, q=select v as value,tagName,to_timezone(t,'Asia/Shanghai') as ts from 
(select last(value) as v,tagName,timestamp as t from xush 
where objectName='/aaaa/channsdel/sd' and timestamp >=cast(1642146102400000 as TIMESTAMP) and timestamp <= cast(1642146302400000 as TIMESTAMP) 
and tagName in('tag2')  sample by 1s fill(NULL) ALIGN TO CALENDAR TIME ZONE 'Asia/Shanghai' WITH OFFSET '00:00' order by tagName,t desc)]
2022-01-14T09:23:03.717984Z I i.q.g.SqlCompiler plan [q=`select-virtual value, tagName, to_timezone(t,'Asia/Shanghai') ts from (select-choose [v value, tagName, t] v value, tagName, t from (select-group-by [last(value) v, tagName, t] last(value) v, tagName, t from (select-choose [value, tagName, timestamp t] value, tagName, timestamp t from (select [value, tagName, timestamp, objectName] from xush timestamp (timestamp) where objectName = '/aaaa/channsdel/sd' and timestamp >= cast(1642146102400000,TIMESTAMP) and timestamp <= cast(1642146302400000,TIMESTAMP) and tagName in 'tag2')) sample by 1s fill(NULL) align to calendar time zone 'Asia/Shanghai' with offset '00:00' order by tagName, t desc))`, fd=55]
2022-01-14T09:23:03.756374Z E server-main unhandled error [job=io.questdb.cutlass.pgwire.PGWireServer$1@1205972e, ex=
java.lang.AssertionError
	at io.questdb.griffin.engine.functions.columns.SymbolColumn.init(SymbolColumn.java:60)
	at io.questdb.cairo.sql.Function.init(Function.java:45)
	at io.questdb.griffin.engine.table.VirtualRecordCursorFactory.getCursor(VirtualRecordCursorFactory.java:74)
	at io.questdb.cutlass.pgwire.PGConnectionContext.setupFactoryAndCursor(PGConnectionContext.java:2218)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processExecute(PGConnectionContext.java:1851)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processExec(PGConnectionContext.java:1844)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1426)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:365)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:68)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:72)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:87)
	at io.questdb.mp.Worker.run(Worker.java:111)
]
```

### To reproduce

run this sql :
```sql
select v as value,tagName,to_timezone(t,'Asia/Shanghai') as ts from 
(select last(value) as v,tagName,timestamp as t from xush 
where objectName='/aaaa/channsdel/sd' and timestamp >=cast(1642146102400000 as TIMESTAMP) and timestamp <= cast(1642146302400000 as TIMESTAMP) 
and tagName in('tag2')  sample by 1s fill(NULL) ALIGN TO CALENDAR TIME ZONE 'Asia/Shanghai' WITH OFFSET '00:00' order by tagName,t desc);
```

### Expected Behavior

The query returns normally resultSet with 0 record

### Environment

```markdown
- **QuestDB version**:6.1.2
- **OS**:centos 7.5
- **Browser**:Microsoft Edge 97.0.1072.55
```

**Comment by eugenels** [comment]
Hi @yiwojiu, thanks for raising the issue! Just to clarify, do you use the web console to reproduce this error? Because I can see a stack trace of the PGWire protocol in the log. Do you have some active PGWire connections in the background?

**Comment by yiwojiu** [comment]
> Hi @yiwojiu, thanks for raising the issue! Just to clarify, do you use the web console to reproduce this error? Because I can see a stack trace of the PGWire protocol in the log. Do you have some active PGWire connections in the background?

yes,There is a service connecting to questdb in the background use PGWire.Both query in  web console and query in the service used PGWire can  reproduce this same error.
