### ISSUE TITLE
Flapping test NetTest.testNoLinger

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1841]
### Describe the bug

Mac OSX, ci server

```
2022-01-28T13:44:44.718092Z E i.q.TestListener ***** Test Failed *****io.questdb.network.NetTest.testNoLinger : 
java.lang.AssertionError: expected:<0> but was:<-1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.questdb.network.NetTest.bindAcceptConnectClose(NetTest.java:138)
	at io.questdb.network.NetTest.testNoLinger(NetTest.java:51)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
this is fixed

**Comment by jerrinot** [comment]
another failure, ale on Mac OSX:
```
TestListener >>>> io.questdb.test.network.NetTest.testNoLinger
2023-08-02T07:34:57.0059340Z 2023-08-02T07:34:56.970413Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.network.NetTest.testNoLinger duration_ms=22624 : 
2023-08-02T07:34:57.0134150Z java.lang.AssertionError: expected:<0> but was:<-1>
2023-08-02T07:34:57.0162530Z 	at org.junit.Assert.fail(Assert.java:89)
2023-08-02T07:34:57.0164320Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2023-08-02T07:34:57.0166430Z 	at org.junit.Assert.assertEquals(Assert.java:647)
2023-08-02T07:34:57.0167750Z 	at org.junit.Assert.assertEquals(Assert.java:633)
2023-08-02T07:34:57.0169350Z 	at io.questdb.test.network.NetTest.bindAcceptConnectClose(NetTest.java:388)
2023-08-02T07:34:57.0170700Z 	at io.questdb.test.network.NetTest.testNoLinger(NetTest.java:173)
2023-08-02T07:34:57.0172090Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-08-02T07:34:57.0174360Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-08-02T07:34:57.0176130Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-08-02T07:34:57.0177640Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2023-08-02T07:34:57.0179490Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-08-02T07:34:57.0180720Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-08-02T07:34:57.0181920Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-08-02T07:34:57.0183100Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-08-02T07:34:57.0184280Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-08-02T07:34:57.0185500Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2023-08-02T07:34:57.0186710Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2023-08-02T07:34:57.0187870Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2023-08-02T07:34:57.0189050Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2023-08-02T07:34:57.0190230Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-08-02T07:34:57.0191380Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-08-02T07:34:57.0192540Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-08-02T07:34:57.0193690Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-08-02T07:34:57.0194840Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-08-02T07:34:57.0196790Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-08-02T07:34:57.0197950Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-08-02T07:34:57.0199620Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
2023-08-02T07:34:57.0201750Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
2023-08-02T07:34:57.0206020Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
2023-08-02T07:34:57.0220220Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
2023-08-02T07:34:57.0230400Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
2023-08-02T07:34:57.0231710Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
2023-08-02T07:34:57.0233220Z 2023-08-02T07:34:56.970615Z I i.q.t.TestListener <<<< io.questdb.test.network.NetTest.testNoLinger duration_ms=22624
2023-08-02T07:34:57.0234630Z 2023-08-02T07:34:56.970695Z I i.q.t.TestListener >>>> io.questdb.test.network.NetTest.testSendAndRecvBuffer
2023-08-02T07:34:57.0236030Z 2023-08-02T07:34:56.976932Z I i.q.t.TestListener <<<< io.questdb.test.network.NetTest.testSendAndRecvBuffer duration_ms=6
2023-08-02T07:34:57.0238590Z 2023-08-02T07:34:56.977037Z I i.q.t.TestListener >>>> io.questdb.test.network.NetTest.testSocketShutdown
2023-08-02T07:34:57.4926130Z Tests run: 13, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 24.192 sec <<< FAILURE! - in io.questdb.test.network.NetTest
2023-08-02T07:34:57.5028010Z testNoLinger(io.questdb.test.network.NetTest)  Time elapsed: 22.628 sec  <<< FAILURE!
2023-08-02T07:34:57.5070830Z java.lang.AssertionError: expected:<0> but was:<-1>
2023-08-02T07:34:57.5085960Z 	at org.junit.Assert.fail(Assert.java:89)
2023-08-02T07:34:57.5096700Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2023-08-02T07:34:57.5098050Z 	at org.junit.Assert.assertEquals(Assert.java:647)
2023-08-02T07:34:57.5099280Z 	at org.junit.Assert.assertEquals(Assert.java:633)
2023-08-02T07:34:57.5101350Z 	at io.questdb.test.network.NetTest.bindAcceptConnectClose(NetTest.java:388)
2023-08-02T07:34:57.5102270Z 	at io.questdb.test.network.NetTest.testNoLinger(NetTest.java:173)
2023-08-02T07:34:57.5102570Z 
```
