### ISSUE TITLE
Flaky LineTcpReceiverFuzzTest.testAddColumns

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#1873]
Occurred on windows-other:
```
2022-02-11T07:10:00.0401867Z 2022-02-11T07:10:00.014698Z I i.q.c.AbstractCairoTest Tearing down test LineTcpReceiverFuzzTest#testAddColumns
2022-02-11T07:10:00.0533302Z Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 565.067 sec <<< FAILURE! - in io.questdb.cutlass.line.tcp.LineTcpReceiverFuzzTest
2022-02-11T07:10:00.0534895Z testLoad(io.questdb.cutlass.line.tcp.LineTcpReceiverFuzzTest)  Time elapsed: 121.234 sec  <<< FAILURE!
2022-02-11T07:10:00.0535994Z java.lang.AssertionError: Timed out on waiting for the data to be ingested
2022-02-11T07:10:00.0536839Z 	at org.junit.Assert.fail(Assert.java:89)
2022-02-11T07:10:00.0537746Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.assertTable(AbstractLineTcpReceiverFuzzTest.java:160)
2022-02-11T07:10:00.0538820Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.lambda$runTest$3(AbstractLineTcpReceiverFuzzTest.java:415)
2022-02-11T07:10:00.0540115Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$0(AbstractLineTcpReceiverTest.java:186)
2022-02-11T07:10:00.0541133Z 	at io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$1(AbstractCairoTest.java:231)
2022-02-11T07:10:00.0542043Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:407)
2022-02-11T07:10:00.0542910Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:228)
2022-02-11T07:10:00.0543852Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:223)
2022-02-11T07:10:00.0544816Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:176)
2022-02-11T07:10:00.0545848Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:379)
2022-02-11T07:10:00.0552890Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:354)
2022-02-11T07:10:00.0558555Z 	at io.questdb.cutlass.line.tcp.LineTcpReceiverFuzzTest.testLoad(LineTcpReceiverFuzzTest.java:90)
2022-02-11T07:10:00.0570214Z 
```

https://dev.azure.com/questdb/questdb/_build/results?buildId=5516&view=logs&j=2a8db746-6336-53bd-306b-3f5b3836e6eb&t=856b52a7-8d37-5a6e-f64c-b8e55c77b9fc

**Comment by glasstiger** [comment]
Issue has been addressed in this [change](https://github.com/questdb/questdb/pull/1856/files#diff-6fa61de875e6097d125d8f5c156d4f0568339df30d8fc4e60666e0bde4c89e42).

The test was too slow on Windows, QuestDB was in constant O3.
The change is that we ingest less data if the OS is Windows.
