### ISSUE TITLE
Invalid column error using table_name.column in query

### ISSUE THREAD

**Issue by jfcalvo** [questdb/questdb#2015]
### Describe the bug

I get an unexpected `invalid column: table_a.cache_key` error executing the following query:

```sql
SELECT DAY(table_b.ts) AS day, COUNT_DISTINCT(table_a.cache_key)
FROM table_a
JOIN table_b ON table_b.response_id = table_a.request_id
GROUP by day;
```

`cache_key` column only exists on `table_a`.

It only works if instead of using `table_a.cache_key` we changed it to `cache_key` inside the `COUNT_DISTINCT`:

```sql
SELECT DAY(table_b.ts) AS day, COUNT_DISTINCT(cache_key)
FROM table_a
JOIN table_b ON table_b.response_id = table_a.request_id
GROUP by day;
```

With this change the query works as expected.

I have been discussing this issue with @bziobrowski on Slack and he indicated that this is most likely a bug.

### To reproduce

Execute the first query on QuestDB web client.

### Expected Behavior

The query should work specifying the complete name of the column using the table name with `table_a.cache_key`.

### Environment

```markdown
- **QuestDB version**: 6.1.3
- **OS**: the OS used by docker image for version 6.1.3
```

**Comment by CutieDeng** [comment]
I'm sorry because I cannot make your situation recurrent. 

That's my attempt to reach it but fail. 
<img width="1393" alt="Screen Shot 2022-04-21 at 22 21 13" src="https://user-images.githubusercontent.com/74101347/164478871-cb2bbe2e-b77d-4055-a92a-9e6255ebf007.png">

**Comment by marregui** [comment]
Hola @jfcalvo 

Would these tables fit your setup:

```
create table table_a (
    cache_key int,
    request_id int,
    response_id int,
    ts timestamp
) timestamp(ts) partition by day;


create table table_b (
    request_id int,
    response_id int,
    ts timestamp
) timestamp(ts) partition by day;
```

If so, it is confirmed, the first query:

```
SELECT DAY(table_b.ts) AS day, COUNT_DISTINCT(table_a.cache_key)
FROM table_a
JOIN table_b ON table_b.response_id = table_a.request_id
GROUP by day;
```

results in:

```
org.postgresql.util.PSQLException: ERROR: Invalid column: table_a.cache_key
  Position: 47
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
```

es un bicho which lives hidden in the latest version too, we shall have a look.

Thank you for the report.
