### ISSUE TITLE
Assertion error in FunctionParser

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2016]
### Describe the bug

```
    2022-04-07T14:04:14.213079Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-3, sql=
    SELECT cta
    FROM users_cta
    WHERE id = '0x05d851a083a25000000014e24296be'
    LIMIT -1;
    ]
    2022-04-07T14:04:14.213262Z I i.q.g.SqlCompiler plan [q=`select-choose cta from (select [cta, id] from users_cta timestamp (ts) where id = '0x05d851a083a25000000014e24296be') limit -(1)`, fd=8]
    2022-04-07T14:04:14.213350Z E i.q.c.h.p.JsonQueryProcessorState [8] Uh-oh. Error!
    java.lang.AssertionError
    at io.questdb.griffin.FunctionParser.parseFunction(FunctionParser.java:254)
    at io.questdb.griffin.SqlCodeGenerator.compileFilter(SqlCodeGenerator.java:152)
    at io.questdb.griffin.SqlCodeGenerator.generateFilter0(SqlCodeGenerator.java:731)
    at io.questdb.griffin.SqlCodeGenerator.generateFilter(SqlCodeGenerator.java:724)
    at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:1430)
    at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:1419)
    at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:2579)
    at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:1993)
    at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:1765)
    at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:1431)
    at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:1419)
    at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:719)
    at io.questdb.griffin.SqlCompiler.generate(SqlCompiler.java:2236)
    at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1762)
    at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:937)
    at io.questdb.griffin.SqlCompiler.compile0(SqlCompiler.java:922)
    at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:908)
    at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:350)
    at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:162)
    at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:214)
    at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:575)
    at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:253)
    at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:88)
    at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:166)
    at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:92)    
``

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.2.1
- **OS**:
- **Browser**:
```

**Comment by ideoma** [comment]
More log in https://questdb.slab.com/posts/telemetry-error-log-g1kcnaat

**Comment by bziobrowski** [comment]
Already fixed in https://github.com/questdb/questdb/pull/1997 .
