### ISSUE TITLE
Flaky ReaderPoolTest.testLockBusyReader test

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2060]
Happened on arm64
```
2022-04-25T08:28:52.7652307Z 2022-04-25T08:28:52.682177Z I i.q.c.AbstractCairoTest Tearing down test ReaderPoolTest#testLockBusyReader
2022-04-25T08:28:52.7653866Z 2022-04-25T08:28:52.685198Z E i.q.TestListener ***** Test Failed *****io.questdb.cairo.pool.ReaderPoolTest.testLockBusyReader : 
2022-04-25T08:28:52.7654950Z java.lang.AssertionError: expected null, but was:<io.questdb.cairo.pool.ReaderPool$R@190e2c62>
2022-04-25T08:28:52.7655733Z 	at org.junit.Assert.fail(Assert.java:89)
2022-04-25T08:28:52.7656455Z 	at org.junit.Assert.failNotNull(Assert.java:756)
2022-04-25T08:28:52.7657202Z 	at org.junit.Assert.assertNull(Assert.java:738)
2022-04-25T08:28:52.7657951Z 	at org.junit.Assert.assertNull(Assert.java:748)
2022-04-25T08:28:52.7658879Z 	at io.questdb.cairo.pool.ReaderPoolTest$4.testLockBusyReaderRollTheDice(ReaderPoolTest.java:578)
2022-04-25T08:28:52.7659763Z 	at io.questdb.cairo.pool.ReaderPoolTest$4.run(ReaderPoolTest.java:545)
2022-04-25T08:28:52.7663052Z 	at io.questdb.cairo.pool.ReaderPoolTest.lambda$assertWithPool$32(ReaderPoolTest.java:885)
2022-04-25T08:28:52.7665269Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:408)
2022-04-25T08:28:52.7667517Z 	at io.questdb.cairo.pool.ReaderPoolTest.assertWithPool(ReaderPoolTest.java:883)
2022-04-25T08:28:52.7668475Z 	at io.questdb.cairo.pool.ReaderPoolTest.assertWithPool(ReaderPoolTest.java:879)
2022-04-25T08:28:52.7669431Z 	at io.questdb.cairo.pool.ReaderPoolTest.testLockBusyReader(ReaderPoolTest.java:536)
2022-04-25T08:28:52.7670296Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-25T08:28:52.7671171Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-25T08:28:52.7672150Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-25T08:28:52.7673014Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-04-25T08:28:52.7674051Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-04-25T08:28:52.7674983Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-04-25T08:28:52.7675930Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-04-25T08:28:52.7676859Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-04-25T08:28:52.7677781Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-04-25T08:28:52.7681394Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-04-25T08:28:52.7682406Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-04-25T08:28:52.7685429Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
2022-04-25T08:28:52.7686444Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
2022-04-25T08:28:52.7687333Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-04-25T08:28:52.7688048Z 	at java.lang.Thread.run(Thread.java:829)
```

**Comment by puzpuzpuz** [comment]
Managed to reproduce this one on Linux and x86. Looking into it.
