### ISSUE TITLE
Flaky TableWriterTest.testAddColumnConcurrentWithDataUpdates test

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2098]
Occured on linux-cairo:
```
Tests run: 132, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 50.358 sec <<< FAILURE! - in io.questdb.cairo.TableWriterTest
testAddColumnConcurrentWithDataUpdates(io.questdb.cairo.TableWriterTest)  Time elapsed: 0.072 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1001> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.questdb.cairo.TableWriterTest.lambda$testAddColumnConcurrentWithDataUpdates$2(TableWriterTest.java:148)
```

**Comment by bluestreak01** [comment]
@puzpuzpuz what branch is this on ?

**Comment by puzpuzpuz** [comment]
That's `fix_timestamp_index_checks`
