### ISSUE TITLE
recent unsafe memory access operation in compiled Java code

### ISSUE THREAD

**Issue by cumtqiangqiang** [questdb/questdb#2202]
### Describe the bug

java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
at io.questdb.cairo.SymbolMapWriter.lookupPutAndCache(SymbolMapWriter.java:267) ~[questdb-6.4-jdk8.jar:6.4-jdk8]
at io.questdb.cairo.SymbolMapWriter.put(SymbolMapWriter.java:194) ~[questdb-6.4-jdk8.jar:6.4-jdk8]
at io.questdb.cairo.SymbolMapWriter.put(SymbolMapWriter.java:179) ~[questdb-6.4-jdk8.jar:6.4-jdk8]
at io.questdb.cairo.TableWriter$RowImpl.putSym(TableWriter.java:5459) ~[questdb-6.4-jdk8.jar:6.4-jdk8]

When I insert with batch insert(2000 rows each commit)with 3 threads ,after insert about 850000 rows,there is an error ,then exit.

questdb 6.4

### Environment

```markdown
- **QuestDB version**:6.4
- **OS**: OS:Bsduname:Darwin 19.6.0 Darwin Kernel Version 19.6.0:
- **Browser**:chrome
```

**Comment by bluestreak01** [comment]
this is embedded use-case I am assuming ? Could you share the inserting code ?

**Comment by bluestreak01** [comment]
cool, what is table structure ? Reason I ask is that `row.put*` calls do not do any checked as to value vs column types. It is hugely important not to insert wrong value into columns.

**Comment by cumtqiangqiang** [comment]
> cool, what is table structure ? Reason I ask is that `row.put*` calls do not do any checked as to value vs column types. It is hugely important not to insert wrong value into columns.

The table structure type is the same with the value type. If it is different ,I think it will not insert any data,but it insert about 850000 rows. And I changed one of Symbol type to string type, then it can run normal for long time, is there any issue about symbol type ? . I'll keep watching my program running status.

**Comment by bluestreak01** [comment]
which column index is timestamp ?

**Comment by cumtqiangqiang** [comment]
> which column index is timestamp ?

create table if not exists table_test (time timestamp,
host symbol,
cluster symbol,
tesk symbol,
timeMs long,
exchTimeMs long,
order string,
idText string,
ccy string) timestamp(time) PARTITION BY DAY;    It is the sql.

**Comment by bluestreak01** [comment]
when first column is the timestamp you should populate columns starting with 1, e.g. 

```java
final Iterator<Data> batchIt = batches.iterator();
    try (TableWriter writer = engine.getWriter(ctx.getCairoSecurityContext(),
            tableName,
            Thread.currentThread().getName())) {
        while (batchIt.hasNext()) {
            final Data data = batchIt.next();
            TableWriter.Row row = writer.newRow(data.getQuestDbMicros());
           
            row.putSym(1, value1);
            row.putStr(2, value2);
            row.putSym(3, value3);
            row.putLong(4, value4);
            row.append();
           
            
        }
        writer.commit();
    }
```

column types have to match `put*()` calls exactly, e.g. you cannot `r.putStr(x, "abc")` into `SYMBOL` column

**Comment by cumtqiangqiang** [comment]
> 



> 
Yes , I do, I create column index use ++i,
int i = 0;
row.putSym(++i, this.hostName);
row.putSym(++i, this.cluster);
row.putSym(++i, this.tesk);

**Comment by cumtqiangqiang** [comment]
> which column index is timestamp ?

Yes , I do, I create column index use ++i,
int i = 0;
row.putSym(++i, this.hostName);
row.putSym(++i, this.cluster);
row.putSym(++i, this.tesk);

**Comment by bluestreak01** [comment]
oh, I should have read this more intently:
>When I insert with batch insert(2000 rows each commit)with 3 threads ,after insert about 850000 rows,there is an error ,then exit.

Could you elaborate on 3 threads ? These threads insert into the same table or several ?

**Comment by bluestreak01** [comment]
I'm going to link issues together, since they stem from the same use-case:

https://github.com/questdb/questdb/issues/2204
https://github.com/questdb/questdb/issues/2203

**Comment by bluestreak01** [comment]
It would most certainly help of you could share your publishing code unredacted. 6.4 ingests data over 1000s of instances with no problem. It would make sense to try to study writing code first.

Regarding `p1` and `p2` - are these processes ? We do not have any code that would cause writing `processes` communicate with each other. If they die simultaneously, I would look at external causes, such is out of disk space or any other resource server-wide contention.

In any case the symptoms you're describing are very new to me and again, I would start by looking at publishing code.

**Comment by bluestreak01** [comment]
This is the sign of corrupt table. Please, provide publishing code - the issue is there

**Comment by cumtqiangqiang** [comment]
> This is the sign of corrupt table. Please, provide publishing code - the issue is there

you mean you want the code that I how to  insert to questdb right? Thanks.

**Comment by cumtqiangqiang** [comment]
> This is the sign of corrupt table. Please, provide publishing code - the issue is there

you mean you want the code that I how to  insert to questdb right? Thanks.

**Comment by cumtqiangqiang** [comment]
> Also, `TableWriter` instances are not thread-safe. Just in case you're sharing instance across threads

sure ,I will show my code later, Thank you very much for you quick replay. Thanks

**Comment by cumtqiangqiang** [comment]
> yes, please
> 
> Also, `TableWriter` instances are not thread-safe. Just in case you're sharing instance across threads

https://github.com/cumtqiangqiang/QuestDbPro/blob/main/src/main/java/app/sink/QuestdbSink.java

This is the code write to questdb. And for my code,there is consumer thread consume data from kafka ,then write to questdb. so I ran a simulation of my own program in this demo. Thanks.

**Comment by cumtqiangqiang** [comment]
> yes, please
> 
> Also, `TableWriter` instances are not thread-safe. Just in case you're sharing instance across threads

forget to tell you that, access data by webconsole ,This error happens offen.

**Comment by bluestreak01** [comment]
thanks, so these are the fields on the table, please notice types (i'm skipping `time` field 0 here):

```
host symbol,
cluster symbol,
tesk symbol,
timeMs long,
exchTimeMs long,
order string,
idText string,
ccy string
```

this is how your code writes them:

```
row.putSym(++i, this.pBookId); // symbol to symbol - ok
row.putInt(++i, this.count); // int to symbol - bad
row.putStr(++i, this.pOrder); // string to symbol - bad
row.putSym(++i, this.pTag); // symbol to long - bad
row.putDouble(++i, this.margin); // etc - type mismatches everywhere
row.putDouble(++i, this.rate);
row.putSym(++i, this.mode);
```

**Comment by cumtqiangqiang** [comment]
> thanks, so these are the fields on the table, please notice types (i'm skipping `time` field 0 here):
> 
> ```
> host symbol,
> cluster symbol,
> tesk symbol,
> timeMs long,
> exchTimeMs long,
> order string,
> idText string,
> ccy string
> ```
> 
> this is how your code writes them:
> 
> ```
> row.putSym(++i, this.pBookId); // symbol to symbol - ok
> row.putInt(++i, this.count); // int to symbol - bad
> row.putStr(++i, this.pOrder); // string to symbol - bad
> row.putSym(++i, this.pTag); // symbol to long - bad
> row.putDouble(++i, this.margin); // etc - type mismatches everywhere
> row.putDouble(++i, this.rate);
> row.putSym(++i, this.mode);
> ```

Seems you didnot see this new code.And there is sql to create table.I thinks it is match with the field type.Thanks
https://github.com/cumtqiangqiang/QuestDbPro/blob/main/src/main/java/app/sink/QuestdbSink.java
create table if not exists  test_position
(
pTime timestamp, 
pBookId symbol, 
count int,
pOrder string,
pTag symbol,
margin double,
rate double,
mode symbol 
) timestamp(pTime) PARTITION BY DAY;

**Comment by ideoma** [comment]
If you post a trimmed version of your application to open source (or via slack) where we can reproduce the issue we can help to debug. 

Embedded usage is "unsafe" there are too many ways to break the database and it's hard to establish what you're doing wrong by exception message, corrupt table examples and parts of the code.

**Comment by cumtqiangqiang** [comment]
> Seems you didnot see this new code.And there is sql to create table.I thinks it is match with the field type.Thanks
> https://github.com/cumtqiangqiang/QuestDbPro/blob/main/src/main/java/app/sink/QuestdbSink.java
> create table if not exists test_position
> (
> pTime timestamp,
> pBookId symbol,
> count int,
> pOrder string,
> pTag symbol,
> margin double,
> rate double,
> mode symbol
> ) timestamp(pTime) PARTITION BY DAY;

 upload this demo for about many days. this demo can Reproduce the problem.After insert about 40 mins, select by webconsole, the questdb will crash.
https://github.com/cumtqiangqiang/QuestDbPro/blob/main/src/main/java/app/sink/QuestdbSink.java
create table if not exists test_position
(
pTime timestamp,
pBookId symbol,
count int,
pOrder string,
pTag symbol,
margin double,
rate double,
mode symbol
) timestamp(pTime) PARTITION BY DAY;

**Comment by ideoma** [comment]
Can you put together  how to run it? I started `App.main` and got back

```
2022-06-17T13:21:15.655587Z E i.q.c.p.WriterPool could not open [table=`test_position`, thread=17, ex=could not open read-write [file=/usr/local/var/questdb/db/test_position/_todo_], errno=2]
2022-06-17T13:21:15.655902Z I i.q.c.p.WriterPool open [table=`test_position`, thread=17]
2022-06-17T13:21:15.655907Z I i.q.c.TableWriter open 'test_position'
```

**Comment by ideoma** [comment]
If I insert code to create table when engine create I run to the end like 

```
 public QuestdbSink(final String configPath,
                       final int workerCount,
                       final int batch,
                       final String tableName) {
        DefaultCairoConfiguration configuration = new DefaultCairoConfiguration(configPath);
        this.engine = new CairoEngine(configuration);
        this.ctx = new SqlExecutionContextImpl(engine, workerCount);
        this.batch = batch;
        this.tableName = tableName;

        try (TableModel model = new TableModel(configuration, tableName, PartitionBy.HOUR)
                .timestamp("pTime")
                .col("pBookId", ColumnType.SYMBOL)
                .col("count", ColumnType.INT)
                .col("pOrder", ColumnType.STRING)
                .col("pTag", ColumnType.SYMBOL)
                .col("margin", ColumnType.DOUBLE)
                .col("rate", ColumnType.DOUBLE)
                .col("mode", ColumnType.SYMBOL)

        ) {
            TableUtils.createTable(
                    configuration,
                    model.getMem(),
                    model.getPath(),
                    model,
                    1
            );
        }

        if (batch > 1 && batch < 2147483647) {
            this.queue = new LinkedBlockingQueue(batch);
        } else {
            this.queue = new LinkedBlockingQueue();
        }

    }
```

everything runs happily to the end

```
2022-06-17T13:39:24.377006Z I i.q.c.p.WriterPool >> [table=`test_position`, thread=17]
2022-06-17T13:39:24.377174Z I i.q.c.p.WriterPool << [table=`test_position`, thread=17]
>>>>>>>>>>>>>QuestDb close
2022-06-17T13:39:25.423413Z I i.q.c.TableWriter closed 'test_position'
2022-06-17T13:39:25.424490Z I i.q.c.p.WriterPool closed [table=`test_position`, reason=POOL_CLOSED, by=1]
2022-06-17T13:39:25.427798Z I i.q.c.p.WriterPool closed
2022-06-17T13:39:25.428119Z I i.q.c.p.ReaderPool closed

```

**Comment by cumtqiangqiang** [comment]
> If I insert code to create table when engine create I run to the end like
> 
> ```
>  public QuestdbSink(final String configPath,
>                        final int workerCount,
>                        final int batch,
>                        final String tableName) {
>         DefaultCairoConfiguration configuration = new DefaultCairoConfiguration(configPath);
>         this.engine = new CairoEngine(configuration);
>         this.ctx = new SqlExecutionContextImpl(engine, workerCount);
>         this.batch = batch;
>         this.tableName = tableName;
> 
>         try (TableModel model = new TableModel(configuration, tableName, PartitionBy.HOUR)
>                 .timestamp("pTime")
>                 .col("pBookId", ColumnType.SYMBOL)
>                 .col("count", ColumnType.INT)
>                 .col("pOrder", ColumnType.STRING)
>                 .col("pTag", ColumnType.SYMBOL)
>                 .col("margin", ColumnType.DOUBLE)
>                 .col("rate", ColumnType.DOUBLE)
>                 .col("mode", ColumnType.SYMBOL)
> 
>         ) {
>             TableUtils.createTable(
>                     configuration,
>                     model.getMem(),
>                     model.getPath(),
>                     model,
>                     1
>             );
>         }
> 
>         if (batch > 1 && batch < 2147483647) {
>             this.queue = new LinkedBlockingQueue(batch);
>         } else {
>             this.queue = new LinkedBlockingQueue();
>         }
> 
>     }
> ```
> 
> everything runs happily to the end
> 
> ```
> 2022-06-17T13:39:24.377006Z I i.q.c.p.WriterPool >> [table=`test_position`, thread=17]
> 2022-06-17T13:39:24.377174Z I i.q.c.p.WriterPool << [table=`test_position`, thread=17]
> >>>>>>>>>>>>>QuestDb close
> 2022-06-17T13:39:25.423413Z I i.q.c.TableWriter closed 'test_position'
> 2022-06-17T13:39:25.424490Z I i.q.c.p.WriterPool closed [table=`test_position`, reason=POOL_CLOSED, by=1]
> 2022-06-17T13:39:25.427798Z I i.q.c.p.WriterPool closed
> 2022-06-17T13:39:25.428119Z I i.q.c.p.ReaderPool closed
> ```

I create table by webconsole. suppose it has issue ? thanks , I will try it. I can run this demo happily to the end too. the key issue is that after about 40 minutes, I select data by web, the table is crashed.

**Comment by ideoma** [comment]
Perhaps your table definition mismatch between your Web and Embedded API. Try to drop and re-create table

**Comment by cumtqiangqiang** [comment]
> Perhaps your table definition mismatch between your Web and Embedded API. Try to drop and re-create table

droped many times.
