### ISSUE TITLE
Flaky io.questdb.cutlass.http.DispatcherWriterQueueTest.testRestUpdateTimeout

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#2224]
### Describe the bug

Memory leak in the test below. Full log is attached.

```
2022-06-14T13:12:35.5447102Z 2022-06-14T13:12:35.542426Z I i.q.TestListener >>>> io.questdb.cutlass.http.DispatcherWriterQueueTest.testRestUpdateTimeout
2022-06-14T13:12:35.5485938Z 2022-06-14T13:12:35.547815Z I i.q.c.t.t.InputFormatConfiguration loading input format config [resource=/text_loader.json]
2022-06-14T13:12:35.5512105Z 2022-06-14T13:12:35.549829Z I i.q.c.m.EngineMigration upgrading database [version=426]
2022-06-14T13:12:35.5513025Z 2022-06-14T13:12:35.549861Z I i.q.c.m.EngineMigration upgraded tables to 426
2022-06-14T13:12:35.5513866Z 2022-06-14T13:12:35.549970Z A IODispatcher listening on 0.0.0.0:9001 [fd=20 backlog=128]
2022-06-14T13:12:35.5606388Z 2022-06-14T13:12:35.560353Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-06-14T13:12:35.5710007Z 2022-06-14T13:12:35.569446Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-06-14T13:12:35.6829687Z 2022-06-14T13:12:35.635276Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-06-14T13:12:35.6831389Z 2022-06-14T13:12:35.640593Z I i.q.c.h.HttpQueryTestBuilder started
2022-06-14T13:12:35.6832424Z 2022-06-14T13:12:35.644653Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-06-14T13:12:35.6833488Z 2022-06-14T13:12:35.648372Z I i.q.c.h.HttpQueryTestBuilder os scheduled [name=questdb-worker-40]
2022-06-14T13:12:35.6834496Z 2022-06-14T13:12:35.650025Z I i.q.c.CairoEngine locked [table=`x`, thread=1]
2022-06-14T13:12:35.6835416Z 2022-06-14T13:12:35.670371Z I i.q.c.TableWriter open 'x'
2022-06-14T13:12:35.6836453Z 2022-06-14T13:12:35.670803Z I i.q.c.TableWriter switched partition [path='/tmp/junit4976290370693507184/x/default']
2022-06-14T13:12:35.6837474Z 2022-06-14T13:12:35.671425Z I i.q.c.CairoEngine unlocked [table=`x`]
2022-06-14T13:12:35.6838686Z 2022-06-14T13:12:35.671438Z I i.q.c.p.WriterPool >> [table=`x`, thread=1]
2022-06-14T13:12:35.8036534Z 2022-06-14T13:12:35.776658Z I IODispatcher connected [ip=127.0.0.1, fd=32]
2022-06-14T13:12:35.8038403Z 2022-06-14T13:12:35.777034Z I i.q.c.h.p.JsonQueryProcessorState [32] exec [q='update x set x=1 from tables() where s = 'a'']
2022-06-14T13:12:35.8039649Z 2022-06-14T13:12:35.777054Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-40, sql=update x set x=1 from tables() where s = 'a']
2022-06-14T13:12:35.8040706Z 2022-06-14T13:12:35.777357Z I i.q.c.p.ReaderPool open 'x' [at=0:0]
2022-06-14T13:12:35.8041750Z 2022-06-14T13:12:35.783518Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=x, fd=32]
2022-06-14T13:12:35.8043031Z 2022-06-14T13:12:35.797138Z I i.q.c.p.WriterPool busy [table=`x`, owner=1, thread=205, reason=test lock]
2022-06-14T13:12:35.8044610Z 2022-06-14T13:12:35.802072Z I i.q.g.e.o.OperationFutureImpl published ASYNC writer command [name=UPDATE,tableName=x,instance=1]
2022-06-14T13:12:35.8045841Z 2022-06-14T13:12:35.797251Z I i.q.c.TableWriter received async cmd [type=3, tableName=x, tableId=1, correlationId=1, cursor=0]
2022-06-14T13:12:35.8046900Z 2022-06-14T13:12:35.800685Z I i.q.g.UpdateOperator updating [table=x instance=1]
2022-06-14T13:12:35.8047851Z 2022-06-14T13:12:35.800791Z E i.q.g.UpdateOperator could not update
2022-06-14T13:12:35.8048591Z io.questdb.cairo.CairoException: [0] timeout, query aborted [fd=32]
2022-06-14T13:12:35.8049331Z 	at io.questdb.cairo.CairoException.instance(CairoException.java:59)
2022-06-14T13:12:35.8050156Z 	at io.questdb.griffin.engine.ops.UpdateOperation.forceTestTimeout(UpdateOperation.java:103)
2022-06-14T13:12:35.8051006Z 	at io.questdb.griffin.UpdateOperator.executeUpdate(UpdateOperator.java:130)
2022-06-14T13:12:35.8051823Z 	at io.questdb.griffin.engine.ops.UpdateOperation.apply(UpdateOperation.java:64)
2022-06-14T13:12:35.8052672Z 	at io.questdb.cairo.TableWriter.processAsyncWriterCommand(TableWriter.java:4041)
2022-06-14T13:12:35.8053492Z 	at io.questdb.cairo.TableWriter.processCommandQueue(TableWriter.java:964)
2022-06-14T13:12:35.8054313Z 	at io.questdb.cairo.TableWriter.processCommandQueue(TableWriter.java:4080)
2022-06-14T13:12:35.8055102Z 	at io.questdb.cairo.TableWriter.tick(TableWriter.java:1419)
2022-06-14T13:12:35.8055976Z 	at io.questdb.cutlass.http.DispatcherWriterQueueTest.lambda$runUpdateOnBusyTable$21(DispatcherWriterQueueTest.java:711)
2022-06-14T13:12:35.8056943Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.lambda$run$0(HttpQueryTestBuilder.java:221)
2022-06-14T13:12:35.8057811Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:448)
2022-06-14T13:12:35.8059551Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:77)
2022-06-14T13:12:35.8060412Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:73)
2022-06-14T13:12:35.8061278Z 	at io.questdb.cutlass.http.DispatcherWriterQueueTest.runUpdateOnBusyTable(DispatcherWriterQueueTest.java:642)
2022-06-14T13:12:35.8062209Z 	at io.questdb.cutlass.http.DispatcherWriterQueueTest.testRestUpdateTimeout(DispatcherWriterQueueTest.java:242)
2022-06-14T13:12:35.8063004Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-06-14T13:12:35.8063758Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-06-14T13:12:35.8064596Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-14T13:12:35.8065363Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-06-14T13:12:35.8066098Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-06-14T13:12:35.8067001Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-06-14T13:12:35.8067812Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-06-14T13:12:35.8068619Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-06-14T13:12:35.8069578Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2022-06-14T13:12:35.8070318Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-06-14T13:12:35.8071096Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2022-06-14T13:12:35.8071840Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2022-06-14T13:12:35.8072579Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2022-06-14T13:12:35.8073382Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2022-06-14T13:12:35.8074133Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2022-06-14T13:12:35.8074838Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2022-06-14T13:12:35.8075655Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2022-06-14T13:12:35.8076381Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2022-06-14T13:12:35.8077106Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2022-06-14T13:12:35.8077821Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-06-14T13:12:35.8078521Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2022-06-14T13:12:35.8079265Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
2022-06-14T13:12:35.8080153Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
2022-06-14T13:12:35.8080969Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
2022-06-14T13:12:35.8081809Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
2022-06-14T13:12:35.8082688Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
2022-06-14T13:12:35.8083641Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
2022-06-14T13:12:35.8085016Z 2022-06-14T13:12:35.801544Z I i.q.c.TableWriter published async command complete event [type=3,tableName=x,tableId=1,correlationId=1,errorCode=-3,errorMsg=timeout, query aborted [fd=32]]
2022-06-14T13:12:35.8086291Z 2022-06-14T13:12:35.802096Z I i.q.g.e.o.OperationFutureImpl writer command QUERY_STARTED response received [instance=1]
2022-06-14T13:12:35.8088715Z 2022-06-14T13:12:35.802099Z I i.q.g.e.o.OperationFutureImpl writer command response received [instance=1]
2022-06-14T13:12:35.8089810Z 2022-06-14T13:12:35.802177Z I i.q.c.h.p.JsonQueryProcessorState [32] syntax-error [q=`update x set x=1 from tables() where s = 'a'`, at=44, message=`timeout, query aborted [fd=32]`]
2022-06-14T13:12:35.8106552Z 2022-06-14T13:12:35.809329Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=32, lastRequestBytesSent=317, nCompletedRequests=1, totalBytesSent=0]
2022-06-14T13:12:35.8117601Z 2022-06-14T13:12:35.811017Z I i.q.c.p.ReaderPool closed 'x' [at=0:0, reason=POOL_CLOSED]
2022-06-14T13:12:35.8118673Z 2022-06-14T13:12:35.811032Z I i.q.c.p.ReaderPool open 'x' [at=0:0]
2022-06-14T13:12:35.8153981Z 2022-06-14T13:12:35.812464Z I i.q.c.p.WriterPool << [table=`x`, thread=1]
2022-06-14T13:12:35.8154938Z 2022-06-14T13:12:35.812582Z I IODispatcher scheduling disconnect [fd=32, reason=12]
2022-06-14T13:12:35.8155710Z 2022-06-14T13:12:35.812739Z I i.q.c.h.HttpServer closed
2022-06-14T13:12:35.8156416Z 2022-06-14T13:12:35.812745Z I i.q.c.h.p.QueryCache closed
2022-06-14T13:12:35.8157166Z 2022-06-14T13:12:35.812755Z I i.q.c.h.HttpQueryTestBuilder cleaned [worker=0]
2022-06-14T13:12:35.8157966Z 2022-06-14T13:12:35.812791Z I IODispatcher disconnected [ip=127.0.0.1, fd=32, src=queue]
2022-06-14T13:12:35.8158697Z 2022-06-14T13:12:35.813116Z I IODispatcher closed
2022-06-14T13:12:35.8159380Z 2022-06-14T13:12:35.813448Z I i.q.c.TableWriter closed 'x'
2022-06-14T13:12:35.8160168Z 2022-06-14T13:12:35.813453Z I i.q.c.p.WriterPool closed [table=`x`, reason=POOL_CLOSED, by=1]
2022-06-14T13:12:35.8160922Z 2022-06-14T13:12:35.813468Z I i.q.c.p.WriterPool closed
2022-06-14T13:12:35.8161892Z 2022-06-14T13:12:35.813526Z I i.q.c.p.ReaderPool closed 'x' [at=0:0, reason=POOL_CLOSED]
2022-06-14T13:12:35.8162663Z 2022-06-14T13:12:35.813532Z I i.q.c.p.ReaderPool closed
2022-06-14T13:12:35.9731610Z 2022-06-14T13:12:35.843070Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.http.DispatcherWriterQueueTest.testRestUpdateTimeout : 
2022-06-14T13:12:35.9733160Z java.lang.AssertionError: Memory usage by tag: NATIVE_FAST_MAP, difference: 16384 expected:<0> but was:<16384>
2022-06-14T13:12:35.9733944Z 	at org.junit.Assert.fail(Assert.java:89)
2022-06-14T13:12:35.9734611Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2022-06-14T13:12:35.9735291Z 	at org.junit.Assert.assertEquals(Assert.java:647)
2022-06-14T13:12:35.9736010Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:461)
2022-06-14T13:12:35.9737072Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:77)
2022-06-14T13:12:35.9737896Z 	at io.questdb.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:73)
2022-06-14T13:12:35.9738791Z 	at io.questdb.cutlass.http.DispatcherWriterQueueTest.runUpdateOnBusyTable(DispatcherWriterQueueTest.java:642)
2022-06-14T13:12:35.9739736Z 	at io.questdb.cutlass.http.DispatcherWriterQueueTest.testRestUpdateTimeout(DispatcherWriterQueueTest.java:242)
2022-06-14T13:12:35.9740565Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-06-14T13:12:35.9741335Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-06-14T13:12:35.9742209Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-14T13:12:35.9742998Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-06-14T13:12:35.9743756Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-06-14T13:12:35.9744603Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-06-14T13:12:35.9745441Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-06-14T13:12:35.9746273Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-06-14T13:12:35.9747075Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2022-06-14T13:12:35.9747838Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-06-14T13:12:35.9748633Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2022-06-14T13:12:35.9749408Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2022-06-14T13:12:35.9750191Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2022-06-14T13:12:35.9751022Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2022-06-14T13:12:35.9751813Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2022-06-14T13:12:35.9754737Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2022-06-14T13:12:35.9756594Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2022-06-14T13:12:35.9757349Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2022-06-14T13:12:35.9758067Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2022-06-14T13:12:35.9758769Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-06-14T13:12:35.9759500Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2022-06-14T13:12:35.9760225Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
2022-06-14T13:12:35.9761052Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
2022-06-14T13:12:35.9761862Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
2022-06-14T13:12:35.9762698Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
2022-06-14T13:12:35.9763896Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
2022-06-14T13:12:35.9764898Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
2022-06-14T13:12:35.9766258Z 2022-06-14T13:12:35.846218Z I i.q.TestListener <<<< io.questdb.cutlass.http.DispatcherWriterQueueTest.testRestUpdateTimeout
```

[70.zip](https://github.com/questdb/questdb/files/8900432/70.zip)

### Environment

```markdown
- **QuestDB version**: 6.4.2-SNAPSHOT
- **OS**: Linux
- **Browser**:
```

**Comment by ideoma** [comment]
Should be fixed in #2226
