### ISSUE TITLE
Message "unsupported file system" in the log when using supported XFS file system

### ISSUE THREAD

**Issue by salsasepp** [questdb/questdb#2337]
### Describe the bug

When starting QuestDB with the data directory on my XFS file system, the log shows "UNSUPPORTED FILE SYSTEM" and "EXPERIMENTAL", despite the docs saying xfs is supported (see https://questdb.io/docs/operations/capacity-planning/#storage-and-filesystem).

```
2022-07-20T08:53:44.789850Z A server-main QuestDB server 6.4.3. Copyright (C) 2014-2022, all rights reserved.^M
2022-07-20T08:53:44.889796Z I server-main web console is up to date^M
2022-07-20T08:53:44.890318Z A server-main Server config: /home/stefan/.questdb/conf/server.conf^M
2022-07-20T08:53:44.919858Z I i.q.c.t.t.InputFormatConfiguration loading input format config [resource=/text_loader.json]^M
2022-07-20T08:53:44.931846Z A server-main Config changes applied:^M
2022-07-20T08:53:44.931873Z A server-main   http.enabled : true^M
2022-07-20T08:53:44.931894Z A server-main   tcp.enabled  : true^M
2022-07-20T08:53:44.931912Z A server-main   pg.enabled   : true^M
2022-07-20T08:53:44.931925Z A server-main open database [id=1435148172356326765.4686310487359770726]^M
2022-07-20T08:53:44.931961Z A server-main platform [bit=64]^M
2022-07-20T08:53:44.931981Z A server-main OS/Arch: linux/amd64 [AVX2,8]^M
2022-07-20T08:53:44.933800Z A server-main available CPUs: 16^M
2022-07-20T08:53:44.933826Z A server-main db root: /home/stefan/.questdb/db^M
2022-07-20T08:53:44.933847Z A server-main backup root: null^M
2022-07-20T08:53:44.933917Z A server-main db file system magic: 0x58465342 [XFS] EXPERIMENTAL^M
2022-07-20T08:53:44.933965Z A server-main


                        *** SYSTEM IS USING UNSUPPORTED FILE SYSTEM AND COULD BE UNSTABLE ***

^M
2022-07-20T08:53:44.934558Z A server-main SQL JIT compiler mode: on^M
[...]
```

### To reproduce

1. `./questdb.sh start`, with the data directory residing on an XFS file system
2. Inspect beginning of log file

### Expected Behavior

No message about unsupported file system in the log.
Alternatively, message about XFS being a supported file system and "all good".

### Environment

```markdown
- **QuestDB version**: 6.4.3
- **OS**: Linux desktop 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bluestreak01** [comment]
Are you using XFS in production?

**Comment by salsasepp** [comment]
Yes. I have been using postgresql with an XFS data volume for years. Giving questdb a whirl on the same volume to see if there's any benefits for my use case. I can switch to another file system for questdb, but would not if XFS is supported and known to work.

**Comment by bluestreak01** [comment]
thank you!

We need to make sure QuestDB runs on XFS. I just ran regression tests and the following test hang: 


```
022-07-25T20:07:14.709082Z I i.q.c.RecoverVarIndex write complete. Index file length: 6920
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.354 sec - in io.questdb.cairo.RecoverVarIndexTest
Running io.questdb.cairo.TableReaderTest
Thread dump:
'main': TIMED_WAITING
                at java.base@17.0.4/jdk.internal.misc.Unsafe.park(Native Method)
                at java.base@17.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
                at java.base@17.0.4/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:444)
                at java.base@17.0.4/java.util.concurrent.FutureTask.get(FutureTask.java:203)
                at app//org.junit.internal.runners.statements.FailOnTimeout.getResult(FailOnTimeout.java:167)
                at app//org.junit.internal.runners.statements.FailOnTimeout.evaluate(FailOnTimeout.java:128)
                at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
                at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
                at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
                at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
                at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
                at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
                at app//org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
                at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)


'Reference Handler': RUNNABLE
                at java.base@17.0.4/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
                at java.base@17.0.4/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
                at java.base@17.0.4/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)


'Finalizer': WAITING
                at java.base@17.0.4/java.lang.Object.wait(Native Method)
                at java.base@17.0.4/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
                at java.base@17.0.4/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
                at java.base@17.0.4/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)


'Signal Dispatcher': RUNNABLE


'Notification Thread': RUNNABLE


'Common-Cleaner': TIMED_WAITING
                at java.base@17.0.4/java.lang.Object.wait(Native Method)
                at java.base@17.0.4/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
                at java.base@17.0.4/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
                at java.base@17.0.4/java.lang.Thread.run(Thread.java:833)
                at java.base@17.0.4/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)


'questdb-worker-1': TIMED_WAITING
                at java.base@17.0.4/java.lang.Thread.sleep(Native Method)
                at app//io.questdb.std.Os.sleep(Os.java:146)
                at app//io.questdb.mp.Worker.run(Worker.java:142)


'Thread-1': RUNNABLE
                at java.management@17.0.4/sun.management.ThreadImpl.getThreadInfo1(Native Method)
                at java.management@17.0.4/sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:197)
                at app//io.questdb.TestListener.dumpThreadStacks(TestListener.java:46)
                at app//io.questdb.TestListener.lambda$static$0(TestListener.java:66)
                at app//io.questdb.TestListener$$Lambda$55/0x0000000800c220d0.run(Unknown Source)
                at java.base@17.0.4/java.lang.Thread.run(Thread.java:833)


'Attach Listener': RUNNABLE


'questdb-worker-1157': TIMED_WAITING
                at java.base@17.0.4/java.lang.Thread.sleep(Native Method)
                at app//io.questdb.std.Os.sleep(Os.java:146)
                at app//io.questdb.mp.Worker.run(Worker.java:142)


'questdb-worker-1158': TIMED_WAITING
                at java.base@17.0.4/java.lang.Thread.sleep(Native Method)
                at app//io.questdb.std.Os.sleep(Os.java:146)
                at app//io.questdb.mp.Worker.run(Worker.java:142)


'questdb-worker-1180': TIMED_WAITING
                at java.base@17.0.4/java.lang.Thread.sleep(Native Method)
                at app//io.questdb.std.Os.sleep(Os.java:146)
                at app//io.questdb.mp.Worker.run(Worker.java:142)


'questdb-worker-1181': TIMED_WAITING
                at java.base@17.0.4/java.lang.Thread.sleep(Native Method)
                at app//io.questdb.std.Os.sleep(Os.java:146)
                at app//io.questdb.mp.Worker.run(Worker.java:142)


'Time-limited test': WAITING
                at java.base@17.0.4/java.lang.Object.wait(Native Method)
                at java.base@17.0.4/java.lang.Thread.join(Thread.java:1304)
                at java.base@17.0.4/java.lang.Thread.join(Thread.java:1372)
                at app//io.questdb.cairo.TableReaderTest.lambda$testAddColumnPartitionConcurrent$44(TableReaderTest.java:1567)
                at app//io.questdb.cairo.TableReaderTest$$Lambda$3382/0x0000000801abd680.run(Unknown Source)
                at app//io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$1(AbstractCairoTest.java:414)
                at app//io.questdb.cairo.AbstractCairoTest$$Lambda$574/0x00000008010e8000.run(Unknown Source)
                at app//io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:462)
                at app//io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:411)
                at app//io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:406)
                at app//io.questdb.cairo.TableReaderTest.testAddColumnPartitionConcurrent(TableReaderTest.java:1506)
                at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base@17.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base@17.0.4/java.lang.reflect.Method.invoke(Method.java:568)
                at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
                at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
                at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)


'Thread-131531': TIMED_WAITING
                at java.base@17.0.4/jdk.internal.misc.Unsafe.park(Native Method)
                at java.base@17.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
                at app//io.questdb.std.Os.pause(Os.java:125)
                at app//io.questdb.cairo.TableReaderTest.lambda$testAddColumnPartitionConcurrent$43(TableReaderTest.java:1556)
                at app//io.questdb.cairo.TableReaderTest$$Lambda$3384/0x0000000801abdad0.run(Unknown Source)
                at java.base@17.0.4/java.lang.Thread.run(Thread.java:833)


```

We need to get to the bottom of this and have clean test passes before declaring XFS supported.

**Comment by salsasepp** [comment]
Thanks for looking into this! Please feel free to close my issue, the log message seems fine as it is.

If you want to move forward with XFS support, I'm all for it. I'd very much appreciate if the docs could be fixed ("QuestDB officially supports EXT4 or XFS or any filesystem that supports mmap"). Right now I am unsure as to which file system is actually supported. Just about any file system supports mmap(), but maybe there's gotchas galore.
