### ISSUE TITLE
Flaky AlterTableLineTcpReceiverTest.testAlterCommandDropsColumn test

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2350]
### Describe the bug

Occurred on windows-other:
```
37:45.826988Z I i.q.TestListener >>>> io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropsColumn
2022-07-26T06:37:45.8775798Z 2022-07-26T06:37:45.827532Z I i.q.c.AbstractCairoTest Starting test AlterTableLineTcpReceiverTest#testAlterCommandDropsColumn
2022-07-26T06:37:45.8776732Z 2022-07-26T06:37:45.828710Z I i.q.c.l.t.LineTcpReceiver using default context
2022-07-26T06:37:45.8777410Z 2022-07-26T06:37:45.828898Z A IODispatcher listening on 0.0.0.0:9002 [fd=2448 backlog=128]
2022-07-26T06:37:45.8778126Z 2022-07-26T06:37:45.831805Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-07-26T06:37:45.8778847Z 2022-07-26T06:37:45.835424Z I i.q.c.CairoEngine locked [table=`__syscolumn_versions_purge_log`, thread=995]
2022-07-26T06:37:46.3792738Z 2022-07-26T06:37:46.357029Z I i.q.c.p.WriterPool created [table=`__syscolumn_versions_purge_log`, thread=995]
2022-07-26T06:37:46.3793906Z 2022-07-26T06:37:46.357102Z I i.q.c.TableWriter open '__syscolumn_versions_purge_log'
2022-07-26T06:37:46.3795237Z 2022-07-26T06:37:46.360138Z I i.q.c.TableWriter purging non attached partitions [path=C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\__syscolumn_versions_purge_log]
2022-07-26T06:37:46.3796181Z 2022-07-26T06:37:46.360255Z I i.q.c.CairoEngine unlocked [table=`__syscolumn_versions_purge_log`]
2022-07-26T06:37:46.3796870Z 2022-07-26T06:37:46.360284Z I i.q.c.p.WriterPool >> [table=`__syscolumn_versions_purge_log`, thread=995]
2022-07-26T06:37:46.3797693Z 2022-07-26T06:37:46.360638Z I i.q.c.p.ReaderPool open '__syscolumn_versions_purge_log' [at=0:0]
2022-07-26T06:37:46.3799311Z 2022-07-26T06:37:46.361797Z I i.q.g.SqlCompiler plan [q=`select-choose ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed from (select [ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed] from __syscolumn_versions_purge_log timestamp (ts) where ts > dateadd('d',-(7),now()) and completed = null)`, fd=-1]
2022-07-26T06:37:46.3801109Z 2022-07-26T06:37:46.362276Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=__syscolumn_versions_purge_log, fd=-1]
2022-07-26T06:37:46.3801809Z 2022-07-26T06:37:46.363508Z I i.q.c.l.t.AbstractLineTcpReceiverTest started
2022-07-26T06:37:46.3802430Z 2022-07-26T06:37:46.363711Z I i.q.c.l.t.AbstractLineTcpReceiverTest os scheduled [name=questdb-worker-470]
2022-07-26T06:37:46.3803050Z 2022-07-26T06:37:46.364281Z I IODispatcher connected [ip=127.0.0.1, fd=3080]
2022-07-26T06:37:46.3803653Z 2022-07-26T06:37:46.364533Z I i.q.c.l.t.LineTcpMeasurementScheduler creating table [tableName=plug]
2022-07-26T06:37:46.3804261Z 2022-07-26T06:37:46.364803Z I i.q.c.CairoEngine locked [table=`plug`, thread=996]
2022-07-26T06:37:46.7852401Z 2022-07-26T06:37:46.694721Z I i.q.c.p.WriterPool created [table=`plug`, thread=996]
2022-07-26T06:37:46.7853293Z 2022-07-26T06:37:46.694789Z I i.q.c.TableWriter open 'plug'
2022-07-26T06:37:46.7854355Z 2022-07-26T06:37:46.697352Z I i.q.c.TableWriter purging non attached partitions [path=C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug]
2022-07-26T06:37:46.7855097Z 2022-07-26T06:37:46.697606Z I i.q.c.CairoEngine unlocked [table=`plug`]
2022-07-26T06:37:46.7855647Z 2022-07-26T06:37:46.697722Z I i.q.c.p.WriterPool >> [table=`plug`, thread=996]
2022-07-26T06:37:46.7856239Z 2022-07-26T06:37:46.697728Z I i.q.c.l.t.AlterTableLineTcpReceiverTest EV_GET plug
2022-07-26T06:37:46.7856887Z 2022-07-26T06:37:46.697729Z I i.q.c.l.t.AlterTableLineTcpReceiverTest Started waiting for writer ASYNC event
2022-07-26T06:37:46.7857538Z 2022-07-26T06:37:46.700535Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-07-26T06:37:46.7858221Z 2022-07-26T06:37:46.703972Z I i.q.c.p.ReaderPool open 'plug' [at=0:0]
2022-07-26T06:37:46.7858862Z 2022-07-26T06:37:46.704965Z I i.q.c.p.WriterPool busy [table=`plug`, owner=996, thread=996, reason=tcpIlp]
2022-07-26T06:37:46.7859591Z 2022-07-26T06:37:46.705040Z I i.q.g.e.o.OperationFutureImpl published ASYNC writer command [name=ALTER TABLE,tableName=plug,instance=2]
2022-07-26T06:37:46.7860476Z 2022-07-26T06:37:46.705717Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned plug to thread 0
2022-07-26T06:37:46.7861195Z 2022-07-26T06:37:46.705728Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=0, tableName=plug, nNetworkIoWorkers=1]
2022-07-26T06:37:46.7861892Z 2022-07-26T06:37:46.706575Z I IODispatcher scheduling disconnect [fd=3080, reason=0]
2022-07-26T06:37:46.7862544Z 2022-07-26T06:37:46.706607Z I i.q.c.l.t.LineTcpWriterJob assigned table to writer thread [tableName=plug, threadId=0]
2022-07-26T06:37:46.7863353Z 2022-07-26T06:37:46.707843Z I i.q.c.l.t.AlterTableLineTcpReceiverTest Busy waiting for writer ASYNC event io.questdb.griffin.engine.ops.OperationFutureImpl@40331a10
2022-07-26T06:37:47.0143860Z 2022-07-26T06:37:46.985220Z I i.q.c.TableWriter switched partition [path='C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\1970-01-01']
2022-07-26T06:37:47.0147548Z 2022-07-26T06:37:46.986045Z I i.q.c.TableWriter switched to o3 [table=plug]
2022-07-26T06:37:47.0149054Z 2022-07-26T06:37:46.986167Z I IODispatcher disconnected [ip=127.0.0.1, fd=3080, src=queue]
2022-07-26T06:37:47.0150072Z 2022-07-26T06:37:46.986527Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=0, tableName=plug, nNetworkIoWorkers=0]
2022-07-26T06:37:47.0151098Z 2022-07-26T06:37:46.986533Z I i.q.c.l.t.LineTcpMeasurementScheduler active table going idle [tableName=plug]
2022-07-26T06:37:47.0152183Z 2022-07-26T06:37:46.986543Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2022-07-26T06:37:46.705000Z[tableName=plug]
2022-07-26T06:37:47.0153196Z 2022-07-26T06:37:46.986631Z I i.q.c.TableWriter sorting o3 [table=plug]
2022-07-26T06:37:47.0154019Z 2022-07-26T06:37:46.986711Z I i.q.c.TableWriter sorted [table=plug]
2022-07-26T06:37:47.0154933Z 2022-07-26T06:37:46.986978Z I i.q.c.TableWriter received async cmd [type=2, tableName=plug, tableId=2, correlationId=2, cursor=0]
2022-07-26T06:37:47.0156003Z 2022-07-26T06:37:46.987006Z I i.q.c.TableWriter removing column 'label' from C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug
2022-07-26T06:37:47.0157067Z 2022-07-26T06:37:46.987372Z I i.q.g.e.o.OperationFutureImpl writer command QUERY_STARTED response received [instance=2]
2022-07-26T06:37:47.0160329Z 2022-07-26T06:37:46.989732Z I i.q.c.TableWriter removed: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\1970-01-01\label.d
2022-07-26T06:37:47.0161618Z 2022-07-26T06:37:46.989910Z E i.q.c.TableWriter cannot remove: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\label.o [errno=5]
2022-07-26T06:37:47.0162754Z 2022-07-26T06:37:46.989987Z E i.q.c.TableWriter cannot remove: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\label.c [errno=5]
2022-07-26T06:37:47.0163869Z 2022-07-26T06:37:46.990100Z E i.q.c.TableWriter cannot remove: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\label.k [errno=5]
2022-07-26T06:37:47.0164956Z 2022-07-26T06:37:46.990225Z I i.q.c.TableWriter removed: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\label.v
2022-07-26T06:37:47.0166033Z 2022-07-26T06:37:46.990275Z I i.q.c.TableWriter REMOVED column 'label' from C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug
2022-07-26T06:37:47.0167107Z 2022-07-26T06:37:46.990287Z I i.q.c.TableWriter published async command complete event [type=2,tableName=plug,tableId=2,correlationId=2]
2022-07-26T06:37:47.0168146Z 2022-07-26T06:37:46.990291Z I i.q.c.p.WriterPool << [table=`plug`, thread=996]
2022-07-26T06:37:47.0169012Z 2022-07-26T06:37:46.990301Z I i.q.c.l.t.AlterTableLineTcpReceiverTest EV_RETURN plug
2022-07-26T06:37:47.0169932Z 2022-07-26T06:37:46.990385Z I i.q.g.e.o.OperationFutureImpl writer command response received [instance=2]
2022-07-26T06:37:47.0170884Z 2022-07-26T06:37:46.990434Z I i.q.c.l.t.AlterTableLineTcpReceiverTest Stopped waiting for writer ASYNC event
2022-07-26T06:37:47.0172002Z 2022-07-26T06:37:46.990516Z E i.q.c.l.t.AbstractLineTcpReceiverTest Stopping ILP worker pool because of an error
2022-07-26T06:37:47.0172791Z java.lang.AssertionError
2022-07-26T06:37:47.0173467Z 	at org.junit.Assert.fail(Assert.java:87)
2022-07-26T06:37:47.0174209Z 	at org.junit.Assert.assertTrue(Assert.java:42)
2022-07-26T06:37:47.0174956Z 	at org.junit.Assert.assertNotNull(Assert.java:713)
2022-07-26T06:37:47.0175751Z 	at org.junit.Assert.assertNotNull(Assert.java:723)
2022-07-26T06:37:47.0176721Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.lambda$testAlterCommandDropsColumn$6(AlterTableLineTcpReceiverTest.java:302)
2022-07-26T06:37:47.0178032Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$0(AbstractLineTcpReceiverTest.java:223)
2022-07-26T06:37:47.0179076Z 	at io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$1(AbstractCairoTest.java:414)
2022-07-26T06:37:47.0179993Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:462)
2022-07-26T06:37:47.0180892Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:411)
2022-07-26T06:37:47.0181805Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:406)
2022-07-26T06:37:47.0182781Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:213)
2022-07-26T06:37:47.0183812Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:208)
2022-07-26T06:37:47.0184891Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropsColumn(AlterTableLineTcpReceiverTest.java:293)
2022-07-26T06:37:47.0185856Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-26T06:37:47.0186721Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-07-26T06:37:47.0187709Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-26T06:37:47.0188675Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-07-26T06:37:47.0189309Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-07-26T06:37:47.0189985Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-07-26T06:37:47.0190652Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-07-26T06:37:47.0191317Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-07-26T06:37:47.0191963Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-07-26T06:37:47.0192605Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-07-26T06:37:47.0193208Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-07-26T06:37:47.0193856Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2022-07-26T06:37:47.0194843Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2022-07-26T06:37:47.0195626Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-07-26T06:37:47.0196137Z 	at java.lang.Thread.run(Thread.java:829)
2022-07-26T06:37:47.0196691Z 2022-07-26T06:37:46.990839Z I i.q.c.l.t.LineTcpWriterJob line protocol writer closing [threadId=0]
2022-07-26T06:37:47.0197691Z 2022-07-26T06:37:46.991052Z I i.q.c.l.t.LineTcpReceiver closed
2022-07-26T06:37:47.0198616Z 2022-07-26T06:37:46.991058Z I i.q.c.l.t.AbstractLineTcpReceiverTest cleaned [worker=0]
2022-07-26T06:37:47.0199338Z 2022-07-26T06:37:46.991077Z I i.q.c.p.WriterPool << [table=`__syscolumn_versions_purge_log`, thread=995]
2022-07-26T06:37:47.0200196Z 2022-07-26T06:37:46.991223Z I i.q.c.l.t.TableUpdateDetails closing table parsers [tableName=plug]
2022-07-26T06:37:47.0200853Z 2022-07-26T06:37:46.991234Z I i.q.c.l.t.TableUpdateDetails closing table writer [tableName=plug]
2022-07-26T06:37:47.0201597Z 2022-07-26T06:37:46.991236Z I i.q.c.l.t.TableUpdateDetails closing table parsers [tableName=plug]
2022-07-26T06:37:47.0202135Z 2022-07-26T06:37:46.991272Z I IODispatcher closed
2022-07-26T06:37:47.0202711Z 2022-07-26T06:37:46.991276Z E i.q.c.l.t.AbstractLineTcpReceiverTest Stopping ILP receiver because of an error
2022-07-26T06:37:47.0203218Z java.lang.AssertionError
2022-07-26T06:37:47.0203621Z 	at org.junit.Assert.fail(Assert.java:87)
2022-07-26T06:37:47.0204076Z 	at org.junit.Assert.assertTrue(Assert.java:42)
2022-07-26T06:37:47.0204556Z 	at org.junit.Assert.assertNotNull(Assert.java:713)
2022-07-26T06:37:47.0205112Z 	at org.junit.Assert.assertNotNull(Assert.java:723)
2022-07-26T06:37:47.0205933Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.lambda$testAlterCommandDropsColumn$6(AlterTableLineTcpReceiverTest.java:302)
2022-07-26T06:37:47.0206950Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$0(AbstractLineTcpReceiverTest.java:223)
2022-07-26T06:37:47.0208078Z 	at io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$1(AbstractCairoTest.java:414)
2022-07-26T06:37:47.0208934Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:462)
2022-07-26T06:37:47.0209589Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:411)
2022-07-26T06:37:47.0210231Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:406)
2022-07-26T06:37:47.0210928Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:213)
2022-07-26T06:37:47.0211680Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:208)
2022-07-26T06:37:47.0212484Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropsColumn(AlterTableLineTcpReceiverTest.java:293)
2022-07-26T06:37:47.0213164Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-26T06:37:47.0213751Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-07-26T06:37:47.0214444Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-26T06:37:47.0215041Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-07-26T06:37:47.0215621Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-07-26T06:37:47.0216274Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-07-26T06:37:47.0216918Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-07-26T06:37:47.0217562Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-07-26T06:37:47.0218343Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-07-26T06:37:47.0219164Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-07-26T06:37:47.0219795Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-07-26T06:37:47.0220428Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2022-07-26T06:37:47.0221146Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2022-07-26T06:37:47.0221766Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-07-26T06:37:47.0222251Z 	at java.lang.Thread.run(Thread.java:829)
2022-07-26T06:37:47.0222893Z 2022-07-26T06:37:46.991575Z I i.q.c.p.ReaderPool closed '__syscolumn_versions_purge_log' [at=0:0, reason=POOL_CLOSED]
2022-07-26T06:37:47.0223597Z 2022-07-26T06:37:46.991928Z I i.q.c.p.ReaderPool closed 'plug' [at=0:0, reason=POOL_CLOSED]
2022-07-26T06:37:47.0224223Z 2022-07-26T06:37:46.992980Z I i.q.c.TableWriter closed '__syscolumn_versions_purge_log'
2022-07-26T06:37:47.0224900Z 2022-07-26T06:37:46.992986Z I i.q.c.p.WriterPool closed [table=`__syscolumn_versions_purge_log`, reason=POOL_CLOSED, by=995]
2022-07-26T06:37:47.0225621Z 2022-07-26T06:37:46.994235Z I i.q.c.TableWriter closed 'plug'
2022-07-26T06:37:47.0226871Z 2022-07-26T06:37:46.994240Z I i.q.c.p.WriterPool closed [table=`plug`, reason=POOL_CLOSED, by=995]
2022-07-26T06:37:47.0227764Z 2022-07-26T06:37:46.994393Z I i.q.c.AbstractCairoTest Tearing down test AlterTableLineTcpReceiverTest#testAlterCommandDropsColumn
2022-07-26T06:37:47.0228980Z 2022-07-26T06:37:47.004291Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropsColumn : 
2022-07-26T06:37:47.0229698Z java.lang.AssertionError
2022-07-26T06:37:47.0230357Z 	at org.junit.Assert.fail(Assert.java:87)
2022-07-26T06:37:47.0230909Z 	at org.junit.Assert.assertTrue(Assert.java:42)
2022-07-26T06:37:47.0231497Z 	at org.junit.Assert.assertNotNull(Assert.java:713)
2022-07-26T06:37:47.0232088Z 	at org.junit.Assert.assertNotNull(Assert.java:723)
2022-07-26T06:37:47.0232890Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.lambda$testAlterCommandDropsColumn$6(AlterTableLineTcpReceiverTest.java:302)
2022-07-26T06:37:47.0233848Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$0(AbstractLineTcpReceiverTest.java:223)
2022-07-26T06:37:47.0234697Z 	at io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$1(AbstractCairoTest.java:414)
2022-07-26T06:37:47.0235445Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:462)
2022-07-26T06:37:47.0236146Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:411)
2022-07-26T06:37:47.0236889Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:406)
2022-07-26T06:37:47.0237691Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:213)
2022-07-26T06:37:47.0238592Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:208)
2022-07-26T06:37:47.0239499Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropsColumn(AlterTableLineTcpReceiverTest.java:293)
2022-07-26T06:37:47.0240291Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-26T06:37:47.0240993Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-07-26T06:37:47.0241974Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-26T06:37:47.0242703Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-07-26T06:37:47.0243300Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-07-26T06:37:47.0243971Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-07-26T06:37:47.0244625Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-07-26T06:37:47.0245269Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-07-26T06:37:47.0245911Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-07-26T06:37:47.0246543Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-07-26T06:37:47.0247113Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-07-26T06:37:47.0247753Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2022-07-26T06:37:47.0248564Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2022-07-26T06:37:47.0249196Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-07-26T06:37:47.0249693Z 	at java.lang.Thread.run(Thread.java:829)
2022-07-26T06:37:47.0250311Z 2022-07-26T06:37:47.004392Z I i.q.TestListener <<<< io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropsColumn
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by jerrinot** [comment]
I can reproduce *a* failure when I decrease time out here: https://github.com/questdb/questdb/blob/aaa30eab284eaa53de1b3e6d32dcf5e464337df8/core/src/test/java/io/questdb/cutlass/line/tcp/AlterTableLineTcpReceiverTest.java#L491
With sufficiently short timeout `alterOperationFuture.await()` returns before it has a chance to throw `SqlException`. 

But this looks to be a different failure mode than @puzpuzpuz captured in the logs above. As in his logs the column is actually dropped: `2022-07-26T06:37:47.0166033Z 2022-07-26T06:37:46.990275Z I i.q.c.TableWriter REMOVED column 'label' from C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug` while the reproducer attempt with a short timeout only ignores `SqlException`, but a column is NOT dropped. 

Some more data:
The captured logs show almost 300ms hiccup/JVM pause. There is almost 300ms between these two log lines and nothing is happening in between:
```
2022-07-26T06:37:46.7863353Z 2022-07-26T06:37:46.707843Z I i.q.c.l.t.AlterTableLineTcpReceiverTest Busy waiting for writer ASYNC event io.questdb.griffin.engine.ops.OperationFutureImpl@40331a10
2022-07-26T06:37:47.0143860Z 2022-07-26T06:37:46.985220Z I i.q.c.TableWriter switched partition [path='C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\1970-01-01']
```

There is also this:
`2022-07-26T06:37:47.0152183Z 2022-07-26T06:37:46.986543Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2022-07-26T06:37:46.705000Z[tableName=plug]` and only then there is a log about removing a column

Hypothesis: The test is running with a very aggressive idle writer timeout. The 300ms hiccup triggers the idle timeout. So when the `ALTER TABLE DROP COLUMN` SQL is running the writer is already returned -> the command suceeds -> the test does not expect that -> failure.

Side note:
The logs shows also this:
```
2022-07-26T06:37:47.0160329Z 2022-07-26T06:37:46.989732Z I i.q.c.TableWriter removed: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\1970-01-01\label.d
2022-07-26T06:37:47.0161618Z 2022-07-26T06:37:46.989910Z E i.q.c.TableWriter cannot remove: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\label.o [errno=5]
2022-07-26T06:37:47.0162754Z 2022-07-26T06:37:46.989987Z E i.q.c.TableWriter cannot remove: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\label.c [errno=5]
2022-07-26T06:37:47.0163869Z 2022-07-26T06:37:46.990100Z E i.q.c.TableWriter cannot remove: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\label.k [errno=5]
2022-07-26T06:37:47.0164956Z 2022-07-26T06:37:46.990225Z I i.q.c.TableWriter removed: C:\Users\VSSADM~1\AppData\Local\Temp\junit1963146532504505749\dbRoot\plug\label.v
```
errno 5 on Windows means "Access is denied.". That's suspicious!

**Comment by jerrinot** [comment]
ok, this is what's going on:
1. The UPDATE command is published
2. ILP rows are written
3. JVM/OS hiccup. 300ms. see the previous message. 
4. `LineTcpWriterJob` is triggered
5. [LineTcpWriterJob.drainQueue()](https://github.com/questdb/questdb/blob/1bc8866146d585d0cadf807c2af394257a684189/core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java#L91) [returns the TableWriter](https://github.com/questdb/questdb/blob/1bc8866146d585d0cadf807c2af394257a684189/core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java#L186) to the pool
6. [LineTcpWriterJob.drainQueue()](https://github.com/questdb/questdb/blob/1bc8866146d585d0cadf807c2af394257a684189/core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java#L99) ticks the TableWriter. 
7. `TableWriter.tick()`  executes the UPDATE command schedule in the step no. 1
8. The update command is successfully executed, because the TableWriter was returned to the pool in the step no. 5
9. The tests assert the UPDATE command cannot be executed -> Test failure.

Reproducer: Insert `Os.sleep(ThreadLocalRandom.current().nextInt(500));` before the [`drainQueue()`](https://github.com/jerrinot/questdb/blob/1bc8866146d585d0cadf807c2af394257a684189/core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java#L91)
```java
    @Override
    public boolean run(int workerId) {
        assert this.workerId == workerId;
        Os.sleep(ThreadLocalRandom.current().nextInt(500));
        boolean busy = drainQueue();
        // while ILP is hammering the database via multiple connections the writer
        // is likely to be very busy so commitTables() will run infrequently
        // commit should run regardless the busy flag but has to finish quickly
        // idea is to store the tables in a heap data structure being the tables most
        // desperately need a commit on the top
        if (!busy) {
            commitTables();
            tickWriters();
        }
        return busy;
    }
```
The randomized sleep mimics the hiccup observed in the logs attached to this issue. It usually fails with 1-3 executions.

**Comment by puzpuzpuz** [comment]
> ok, this is what's going on

Nice finding!

**Comment by jerrinot** [comment]
@puzpuzpuz thanks. the question is: how to fix it. one idea is to keep ingesting until the async operation is picked up and throws an exception. but perhaps there is a more elegant way.

**Comment by puzpuzpuz** [comment]
> but perhaps there is a more elegant way.

Would increasing `getWriterIdleTimeout()` help?

**Comment by jerrinot** [comment]
yeah, I think that's the way to go. it makes the test slower, but I guess you cannot eat your cake and have it too 🤷
