### ISSUE TITLE
FreeBSD  - Can't Start the Service

### ISSUE THREAD

**Issue by kevindirect** [questdb/questdb#2427]
### Describe the bug
When I try to start the service, I get the following exception after 'log configuration loaded':
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int io.questdb.std.Files.getFileSystemStatus(long)'
        at io.questdb@6.5/io.questdb.std.Files.getFileSystemStatus(Native Method)
        at io.questdb@6.5/io.questdb.std.Files.getFileSystemStatus(Files.java:165)
        at io.questdb@6.5/io.questdb.ServerMain.verifyFileSystem(ServerMain.java:645)
        at io.questdb@6.5/io.questdb.ServerMain.<init>(ServerMain.java:162)
        at io.questdb@6.5/io.questdb.ServerMain.main(ServerMain.java:332)
```

### To reproduce

`questdb.sh start`

### Expected Behavior

Database service is launched without exception

### Environment

```markdown
- **QuestDB version**: 6.5-rt-freebsd-amd64
- **OS**: FreeBSD 13.0-RELEASE-p2
- **Browser**: none
```

**Comment by kevindirect** [comment]
Any progress? I guess the native method needed for querying the fs isn't packaged? I don't know if other people have had trouble with freebsd, I'm using zfs which is a commonly used and suggested filesystem for freebsd.

Would the JVM free version be more likely to work?

**Comment by kevindirect** [comment]
Found the same problem using the no-jre version

**Comment by kevindirect** [comment]
Any updates?

**Comment by bluestreak01** [comment]
Sorry for the trouble. I can reproduce it, investigating

**Comment by kevindirect** [comment]
Thanks, it can initialize properly now.

This message is being printed to the stdout log though
`SYSTEM IS USING UNSUPPORTED FILE SYSTEM AND COULD BE UNSTABLE`
Is this because the db is on ZFS? I don't see it listed here: https://github.com/questdb/questdb/pull/2490/files

Is this a problem or is it a warning that can be safely ignored? If it initialized properly I guess questdb has access to whatever native fs functions required
