### ISSUE TITLE
Reader leaked resulting in max txn-inflight limit reached

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2441]
### To reproduce

Suspicious offending query is:

```SQL
SELECT
  timestamp as time,
  exchange,
  symbol,
  count() as trades
FROM
  table
WHERE
  symbol ~ '.*-?ETH' and
  timestamp BETWEEN '2022-08-17T13:05:43.981Z' AND '2022-08-17T19:05:43.981Z'
SAMPLE BY 1m
```

results in

```
2022-08-17T19:05:49.805401Z E i.q.c.p.PGWireServer
java.lang.StringIndexOutOfBoundsException: String index out of range: 8
        at java.lang.StringLatin1.charAt(StringLatin1.java:48)
        at java.lang.String.charAt(String.java:1515)
        at java.lang.Character.codePointAt(Character.java:8910)
        at java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4273)
        at java.util.regex.Pattern$Start.match(Pattern.java:3608)
        at java.util.regex.Matcher.search(Matcher.java:1728)
        at java.util.regex.Matcher.find(Matcher.java:745)
        at io.questdb.griffin.engine.functions.regex.MatchStrFunctionFactory$MatchConstPatternFunction.getBool(MatchStrFunctionFactory.java:100)
        at io.questdb.griffin.engine.table.AsyncFilteredRecordCursorFactory.filter(AsyncFilteredRecordCursorFactory.java:167)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.reduce(PageFrameReduceJob.java:175)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:132)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:106)
        at io.questdb.cairo.sql.async.PageFrameSequence.stealWork(PageFrameSequence.java:390)
        at io.questdb.cairo.sql.async.PageFrameSequence.dispatch(PageFrameSequence.java:369)
        at io.questdb.cairo.sql.async.PageFrameSequence.next(PageFrameSequence.java:294)
        at io.questdb.griffin.engine.table.AsyncFilteredRecordCursor.fetchNextFrame(AsyncFilteredRecordCursor.java:184)
        at io.questdb.griffin.engine.table.AsyncFilteredRecordCursor.of(AsyncFilteredRecordCursor.java:226)
        at io.questdb.griffin.engine.table.AsyncFilteredRecordCursorFactory.getCursor(AsyncFilteredRecordCursorFactory.java:129)
        at io.questdb.griffin.engine.table.SelectedRecordCursorFactory.getCursor(SelectedRecordCursorFactory.java:58)
        at io.questdb.griffin.engine.groupby.SampleByFillNoneRecordCursorFactory.getCursor(SampleByFillNoneRecordCursorFactory.java:97)
        at io.questdb.cutlass.pgwire.PGConnectionContext.setupFactoryAndCursor(PGConnectionContext.java:2488)
        at io.questdb.cutlass.pgwire.PGConnectionContext$PGConnectionBatchCallback.postCompile(PGConnectionContext.java:2593)
        at io.questdb.griffin.SqlCompiler.compileBatch(SqlCompiler.java:930)
        at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:2256)
        at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1550)
        at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:415)
        at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:81)
        at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:81)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:166)
        at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:106)
        at io.questdb.mp.Worker.run(Worker.java:116)
```

and subsequent TableReader leak

### Expected Behavior

No resource leak

### Environment

```markdown
- **QuestDB version**:6.5
```

**Comment by ideoma** [comment]
another potential leak can be when query like this 

```
[q=`select-group-by t_t, sum(q * p) u_v from (select [t_t, p, q, i_k] from s_ts timestamp (t_t) where i_k
 like 'ABC_DEF_S_%' and t_t >= '2022-08-01 00:00') sample by 1m align to calendar time zone 'UTC' with offset '00:00'`, fd=8]
```

is aborted 

```
2022-08-17T17:12:55.238422Z I i.q.c.h.p.JsonQueryProcessorState [8] query cancelled [q=`select
2022-08-17T17:12:55.238514Z E i.q.c.h.HttpResponseSink disconnected [errno=32, fd=8]
2022-08-17T17:12:55.238524Z I http-server scheduling disconnect [fd=8, reason=15]
2022-08-17T17:12:55.238539Z I http-server disconnected [ip=255.255.255.255, fd=8, src=queue]
``

**Comment by puzpuzpuz** [comment]
> another potential leak can be when query like this

The problem is in the following lines: https://github.com/questdb/questdb/blob/3fedfed87ff8ed5d29752472b0f34b1e13c30172/core/src/main/java/io/questdb/griffin/engine/groupby/AbstractSampleByNotKeyedRecordCursorFactory.java#L48-L49

We need to make sure that the base cursor gets closed whenever any of the above calls throws `CairoException`. To do that we may want to avoid eager fetch on `AsyncFilteredRecordCursor/AsyncFilteredNegativeLimitRecordCursor#of()` since this would allow us to obtain the cursor instance without worrying about potential `CairoException`. Or we could implement self-close logic there.

**Comment by puzpuzpuz** [comment]
Created #2454 to track the `StringIndexOutOfBoundsException` issue separately.
