### ISSUE TITLE
Attempted to read past the end of the stream

### ISSUE THREAD

**Issue by carbonhe** [questdb/questdb#2450]
### Describe the bug

Connection will be lost when inserting data too long (contains a string type column in base64 format). Tested under   [PostgreSQL wire protocol](https://questdb.io/docs/develop/insert-data#postgresql-wire-protocol).

### Demo Source Code
[QuestDbDemo.zip](https://github.com/questdb/questdb/files/9399374/QuestDbDemo.zip)

### To reproduce

1. Download and run demo souce code above
2. An error will occurred(sometime not) : 
```
Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|42_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
   at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|42_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|223_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at QuestDbDemo.Program.Main(String[] args) in D:\Playground\QuestDbDemo\QuestDbDemo\Program.cs:line 183
```

### Environment

```markdown
- **QuestDB version**: 6.5
- **OS**: Docker
- **Browser**:
```

**Comment by carbonhe** [comment]
I found the cause of the problem is that the [receive buffer](https://questdb.io/docs/reference/configuration#postgres-wire-protocol) is too small，just make it bigger.
