### ISSUE TITLE
Run QuestDB on Openshift Container Platform fails

### ISSUE THREAD

**Issue by sysarcher** [questdb/questdb#2456]
### Describe the bug

Running the default instructions to deploy QuestDB on OCP (OpenShift Container Platform) cluster fails with the following log:

```
$ oc logs -f my-questdb-0 
Found /root/.questdb mount, overwriting QUESTDB_DATA_DIR
No arguments found, start with default arguments
Running as 1000690000 user
QuestDB server 6.5
Copyright (C) 2014-2022, all rights reserved.

Log configuration loaded loaded using factory defaults.
Exception in thread "main" java.io.FileNotFoundException: /root/.questdb/public/version.txt (Permission denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at io.questdb@6.5/io.questdb.ServerMain.setPublicVersion(ServerMain.java:477)
        at io.questdb@6.5/io.questdb.ServerMain.extractSite0(ServerMain.java:554)
        at io.questdb@6.5/io.questdb.ServerMain.extractSite(ServerMain.java:503)
        at io.questdb@6.5/io.questdb.ServerMain.<init>(ServerMain.java:101)
        at io.questdb@6.5/io.questdb.ServerMain.main(ServerMain.java:332)
```

Applying the SCC `anyuid` to `system:authenticated` resolves this

```
oc adm policy add-scc-to-group anyuid system:authenticated
```
This way, any authenticated user can run pods with `anyuid`. Is this desired?

### To reproduce

1. Setup Openshift
2. Install QuestDB using `helm`
3. Get logs from `my-questdb-0` 

### Expected Behavior

QuestDB should run without `root` user privilege OR, have it documented somewhere

### Environment

```markdown
- **QuestDB version**: 6.5
- **OS**: CoreOS
- **Browser**: NA
```

**Comment by mariusgheorghies** [comment]
Hi @sysarcher can i see the pod yaml, where do you mount the volumes and the security context?
Please don't forget to delete any secret information from yaml output. 

What I see is that you mount the volume in the /root/.questdb/ directory but you are running questdb with `1000690000` id. That can create a problem because that id can't access /root/.questdb/
If you mount volume data into `/var/lib/questdb/db` and set the following security context into the statefulset the pod should be fine:
```
  securityContext:
    fsGroup: 10001
    runAsUser: 10001
    runAsGroup: 10001
```

**Comment by sysarcher** [comment]
Thank you @mariusgheorghies 

I'll try this out in the next couple of days. I'll let you know here.

**Comment by pswu11** [comment]
Hi @sysarcher have you tried out the recommendation and does it work out for you?
