### ISSUE TITLE
 CairoException [22] could not mmap when running O3 heavy ingestion

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2590]
### Describe the bug

I'm running O3-heavy ingestion:
```java
@Test
public void testFoo() throws Exception {
    Faker faker = new Faker();
    runInContext(r -> {
        try (Sender sender = Sender.builder().address(HOST)//.port(bindPort)
             .build()) {
            for (int i = 0; i < 1_000_000; i++) {
                String firstName = faker.name().firstName();
                String lastName = faker.name().lastName();
                Date birthday = faker.date().birthday(0, 51); // age of the person, chosen so oldest people are born shortly after epoch start
                sender.table("people")
                        .stringColumn("firstname", firstName)
                        .stringColumn("lastname", lastName)
                        .at(TimeUnit.MILLISECONDS.toNanos(birthday.getTime()));
                sender.flush();
            }
        }
    });
}
```
The table is partitioned by day. Thus the test results in:
1. a lot of O3 merges
2. a lot of partitions

I'm occasionally getting this error:
```
[...]
2022-10-05T13:00:03.104940Z I i.q.c.TableWriter merged partition [table=`people`, ts=2013-09-01T00:00:00.000000Z, txn=10]
2022-10-05T13:00:03.106090Z I i.q.c.TableWriter merged partition [table=`people`, ts=2014-08-10T00:00:00.000000Z, txn=10]
2022-10-05T13:00:03.106400Z I i.q.c.TableWriter merged partition [table=`people`, ts=2013-09-03T00:00:00.000000Z, txn=10]
2022-10-05T13:00:03.106439Z I i.q.c.TableWriter merged partition [table=`people`, ts=2014-08-09T00:00:00.000000Z, txn=10]
2022-10-05T13:00:03.106946Z E i.q.c.O3OpenColumnJob merge var error [table=people, e=
io.questdb.cairo.CairoException: [22] could not mmap  [size=0, offset=0, fd=306, memUsed=1151894402, fileLen=10]
	at io.questdb.cairo.CairoException.critical(CairoException.java:89)
	at io.questdb.cairo.TableUtils.mapRO(TableUtils.java:645)
	at io.questdb.cairo.TableUtils.mapRO(TableUtils.java:626)
	at io.questdb.cairo.O3OpenColumnJob.mergeVarColumn(O3OpenColumnJob.java:2236)
	at io.questdb.cairo.O3OpenColumnJob.mergeMidPartition(O3OpenColumnJob.java:1718)
	at io.questdb.cairo.O3OpenColumnJob.openColumn(O3OpenColumnJob.java:355)
	at io.questdb.cairo.O3PartitionJob.publishOpenColumnTaskContended(O3PartitionJob.java:1052)
	at io.questdb.cairo.O3PartitionJob.publishOpenColumnTasks(O3PartitionJob.java:882)
	at io.questdb.cairo.O3PartitionJob.processPartition(O3PartitionJob.java:495)
	at io.questdb.cairo.O3PartitionJob.processPartition(O3PartitionJob.java:565)
	at io.questdb.cairo.O3PartitionJob.doRun(O3PartitionJob.java:1102)
	at io.questdb.mp.AbstractQueueConsumerJob.run(AbstractQueueConsumerJob.java:39)
	at io.questdb.mp.Worker.run(Worker.java:118)
```
Please notice the `size` is 0. It appears as a bug in the O3 merge algorithm. `mmap()` is not allowed to be called with size 0. This test fails with the same error:
```java
@Test
public void testMapping() {
    try (Path path = new Path()) {
        path.of("/tmp/foo");
        long fd = TableUtils.openRO(FilesFacadeImpl.INSTANCE, path, LOG);
        TableUtils.mapRO(FilesFacadeImpl.INSTANCE, fd, 0, 0);
    }
}
```

### Environment

```markdown
- **QuestDB version**: 6.5.3
```

**Comment by jerrinot** [comment]
fixed by https://github.com/questdb/questdb/pull/2627
