### ISSUE TITLE
Flaky testRollbackDataOnStaleTransaction

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#2649]
### Describe the bug

Test closes more file descriptors than it supposed to:

```
2022-10-16T22:30:41.2758081Z 2022-10-16T22:30:41.219884Z I i.q.TestListener >>>> io.questdb.cutlass.pgwire.PGJobContextTest.testRollbackDataOnStaleTransaction
2022-10-16T22:30:41.2759475Z 2022-10-16T22:30:41.220087Z I i.q.c.AbstractCairoTest Starting test PGJobContextTest#testRollbackDataOnStaleTransaction
2022-10-16T22:30:41.2760732Z 2022-10-16T22:30:41.220455Z A pg-server listening on 0.0.0.0:0 [fd=35 backlog=64]
2022-10-16T22:30:41.2764290Z 2022-10-16T22:30:41.235935Z I i.q.c.p.PGJobContextTest os scheduled worker started [name=questdb-testing-2076]
2022-10-16T22:30:41.2765692Z 2022-10-16T22:30:41.235971Z I i.q.c.p.PGJobContextTest worker pool started [pool=testing]
2022-10-16T22:30:41.2767066Z 2022-10-16T22:30:41.235995Z I i.q.c.p.PGJobContextTest os scheduled worker started [name=questdb-testing-2077]
2022-10-16T22:30:41.2768384Z 2022-10-16T22:30:41.237881Z I pg-server connected [ip=127.0.0.1, fd=38]
2022-10-16T22:30:41.2769683Z 2022-10-16T22:30:41.238032Z I i.q.c.p.PGConnectionContext protocol [major=3, minor=0]
2022-10-16T22:30:41.2804236Z 2022-10-16T22:30:41.238037Z I i.q.c.p.PGConnectionContext property [name=user, value=admin]
2022-10-16T22:30:41.2805764Z 2022-10-16T22:30:41.238040Z I i.q.c.p.PGConnectionContext property [name=database, value=qdb]
2022-10-16T22:30:41.2807117Z 2022-10-16T22:30:41.238041Z I i.q.c.p.PGConnectionContext property [name=client_encoding, value=UTF8]
2022-10-16T22:30:41.2808419Z 2022-10-16T22:30:41.238042Z I i.q.c.p.PGConnectionContext property [name=DateStyle, value=ISO]
2022-10-16T22:30:41.2809675Z 2022-10-16T22:30:41.238042Z I i.q.c.p.PGConnectionContext property [name=TimeZone, value=GMT]
2022-10-16T22:30:41.2810964Z 2022-10-16T22:30:41.238043Z I i.q.c.p.PGConnectionContext property [name=extra_float_digits, value=2]
2022-10-16T22:30:41.2812426Z 2022-10-16T22:30:41.238282Z I i.q.c.p.PGConnectionContext parse [fd=38, q=SET extra_float_digits = 3]
2022-10-16T22:30:41.2813783Z 2022-10-16T22:30:41.238360Z I i.q.c.p.PGConnectionContext parse [fd=38, q=SET application_name = 'PostgreSQL JDBC Driver']
2022-10-16T22:30:41.2815096Z 2022-10-16T22:30:41.238557Z I i.q.c.p.PGConnectionContext parse [fd=38, q=BEGIN]
2022-10-16T22:30:41.2816350Z 2022-10-16T22:30:41.238572Z I i.q.c.p.PGConnectionContext parse [fd=38, q=create table xyz(a int)]
2022-10-16T22:30:41.2817589Z 2022-10-16T22:30:41.238683Z I i.q.c.CairoEngine locked [table=`xyz`, thread=3541]
2022-10-16T22:30:41.2822302Z 2022-10-16T22:30:41.240262Z I i.q.c.p.WriterPool created [table=`xyz`, thread=3541]
2022-10-16T22:30:41.2823568Z 2022-10-16T22:30:41.240283Z I i.q.c.TableWriter open 'xyz'
2022-10-16T22:30:41.2824977Z 2022-10-16T22:30:41.240549Z I i.q.c.TableWriter switched partition [path='/tmp/junit10584159117185975166/dbRoot/xyz/default']
2022-10-16T22:30:41.2826252Z 2022-10-16T22:30:41.240591Z I i.q.c.CairoEngine unlocked [table=`xyz`]
2022-10-16T22:30:41.2827452Z 2022-10-16T22:30:41.240682Z I i.q.c.p.PGConnectionContext parse [fd=38, q=insert into xyz values (100)]
2022-10-16T22:30:41.2828670Z 2022-10-16T22:30:41.240731Z I i.q.c.p.ReaderPool open 'xyz' [at=0:0]
2022-10-16T22:30:41.2829846Z 2022-10-16T22:30:41.241254Z I i.q.c.p.WriterPool >> [table=`xyz`, thread=3541]
2022-10-16T22:30:41.2831089Z 2022-10-16T22:30:41.241344Z I i.q.c.p.PGConnectionContext parse [fd=38, q=insert into xyz values (101)]
2022-10-16T22:30:41.2832395Z 2022-10-16T22:30:41.241707Z I i.q.c.p.PGConnectionContext parse [fd=38, q=insert into xyz values (102)]
2022-10-16T22:30:41.2833725Z 2022-10-16T22:30:41.242009Z I i.q.c.p.PGConnectionContext parse [fd=38, q=insert into xyz values (103)]
2022-10-16T22:30:41.2834949Z 2022-10-16T22:30:41.242326Z I i.q.c.p.PGConnectionContext parse [fd=38, q=xyz]
2022-10-16T22:30:41.2836298Z 2022-10-16T22:30:41.242478Z I i.q.g.SqlCompiler plan [q=`select-choose a from (select [a] from xyz)`, fd=38]
2022-10-16T22:30:41.2837525Z 2022-10-16T22:30:41.242627Z I pg-server scheduling disconnect [fd=38, reason=15]
2022-10-16T22:30:41.2838715Z 2022-10-16T22:30:41.242630Z I pg-server disconnected [ip=127.0.0.1, fd=38, src=queue]
2022-10-16T22:30:41.2839872Z 2022-10-16T22:30:41.242677Z I i.q.c.TableWriter tx rollback [name=xyz]
2022-10-16T22:30:41.2841178Z 2022-10-16T22:30:41.242729Z I i.q.c.TableWriter switched partition [path='/tmp/junit10584159117185975166/dbRoot/xyz/default']
2022-10-16T22:30:41.2842465Z 2022-10-16T22:30:41.242739Z I i.q.c.TableWriter tx rollback complete [name=xyz]
2022-10-16T22:30:41.2843619Z 2022-10-16T22:30:41.242742Z I i.q.c.p.WriterPool << [table=`xyz`, thread=3541]
2022-10-16T22:30:43.2808157Z 2022-10-16T22:30:43.242785Z I i.q.c.p.WriterPool >> [table=`xyz`, thread=3540]
2022-10-16T22:30:43.2811026Z 2022-10-16T22:30:43.242804Z I i.q.c.p.WriterPool << [table=`xyz`, thread=3540]
2022-10-16T22:30:43.2812471Z 2022-10-16T22:30:43.251171Z I pg-server connected [ip=127.0.0.1, fd=45]
2022-10-16T22:30:43.2813895Z 2022-10-16T22:30:43.251236Z I i.q.c.p.PGConnectionContext protocol [major=3, minor=0]
2022-10-16T22:30:43.2815330Z 2022-10-16T22:30:43.251242Z I i.q.c.p.PGConnectionContext property [name=user, value=admin]
2022-10-16T22:30:43.2816793Z 2022-10-16T22:30:43.251245Z I i.q.c.p.PGConnectionContext property [name=database, value=qdb]
2022-10-16T22:30:43.2818266Z 2022-10-16T22:30:43.251246Z I i.q.c.p.PGConnectionContext property [name=client_encoding, value=UTF8]
2022-10-16T22:30:43.2819723Z 2022-10-16T22:30:43.251247Z I i.q.c.p.PGConnectionContext property [name=DateStyle, value=ISO]
2022-10-16T22:30:43.2821205Z 2022-10-16T22:30:43.251248Z I i.q.c.p.PGConnectionContext property [name=TimeZone, value=GMT]
2022-10-16T22:30:43.2822683Z 2022-10-16T22:30:43.251249Z I i.q.c.p.PGConnectionContext property [name=extra_float_digits, value=2]
2022-10-16T22:30:43.2824340Z 2022-10-16T22:30:43.251515Z I i.q.c.p.PGConnectionContext parse [fd=45, q=SET extra_float_digits = 3]
2022-10-16T22:30:43.2825985Z 2022-10-16T22:30:43.251592Z I i.q.c.p.PGConnectionContext parse [fd=45, q=SET application_name = 'PostgreSQL JDBC Driver']
2022-10-16T22:30:43.2827693Z 2022-10-16T22:30:43.251765Z I i.q.c.p.PGConnectionContext parse [fd=45, q=xyz]
2022-10-16T22:30:43.2829173Z 2022-10-16T22:30:43.251910Z I i.q.g.SqlCompiler plan [q=`select-choose a from (select [a] from xyz)`, fd=45]
2022-10-16T22:30:43.2830642Z 2022-10-16T22:30:43.252069Z I pg-server scheduling disconnect [fd=45, reason=15]
2022-10-16T22:30:43.2832049Z 2022-10-16T22:30:43.252072Z I pg-server disconnected [ip=127.0.0.1, fd=45, src=queue]
2022-10-16T22:30:43.2833689Z 2022-10-16T22:30:43.252133Z I i.q.c.p.PGJobContextTest cleaned worker [name=testing, worker=1, total=2]
2022-10-16T22:30:43.2835486Z 2022-10-16T22:30:43.252136Z I i.q.c.p.PGJobContextTest os scheduled worker stopped [name=questdb-testing-2077]
2022-10-16T22:30:43.3838924Z 2022-10-16T22:30:43.351431Z I i.q.c.p.PGJobContextTest cleaned worker [name=testing, worker=0, total=2]
2022-10-16T22:30:43.3841286Z 2022-10-16T22:30:43.351444Z I i.q.c.p.PGJobContextTest os scheduled worker stopped [name=questdb-testing-2076]
2022-10-16T22:30:43.3842789Z 2022-10-16T22:30:43.351592Z I pg-server closed
2022-10-16T22:30:43.3844028Z 2022-10-16T22:30:43.351773Z I i.q.c.TableWriter closed 'xyz1'
2022-10-16T22:30:43.3847127Z 2022-10-16T22:30:43.351777Z I i.q.c.p.WriterPool closed [table=`xyz1`, reason=IDLE, by=3540]
2022-10-16T22:30:43.3848655Z 2022-10-16T22:30:43.353086Z I i.q.c.TableWriter closed 'xyz'
2022-10-16T22:30:43.3849896Z 2022-10-16T22:30:43.353089Z I i.q.c.p.WriterPool closed [table=`xyz`, reason=IDLE, by=3540]
2022-10-16T22:30:43.3851342Z 2022-10-16T22:30:43.353136Z I i.q.c.p.ReaderPool closed 'xyz' [at=0:0, reason=IDLE]
2022-10-16T22:30:43.3925641Z 2022-10-16T22:30:43.353765Z I i.q.c.AbstractCairoTest Tearing down test PGJobContextTest#testRollbackDataOnStaleTransaction
2022-10-16T22:30:43.3927600Z 2022-10-16T22:30:43.355238Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.pgwire.PGJobContextTest.testRollbackDataOnStaleTransaction : 
2022-10-16T22:30:43.3928885Z java.lang.AssertionError: file descriptors [17,26,28,29,18,22,14] expected:<14> but was:<7>
2022-10-16T22:30:43.3929866Z 	at org.junit.Assert.fail(Assert.java:89)
2022-10-16T22:30:43.3930775Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2022-10-16T22:30:43.3931734Z 	at org.junit.Assert.assertEquals(Assert.java:647)
2022-10-16T22:30:43.3932737Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:471)
2022-10-16T22:30:43.3933863Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:485)
2022-10-16T22:30:43.3935034Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:479)
2022-10-16T22:30:43.3936269Z 	at io.questdb.cutlass.pgwire.PGJobContextTest.testRollbackDataOnStaleTransaction(PGJobContextTest.java:5125)
2022-10-16T22:30:43.3937414Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-16T22:30:43.3938477Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-10-16T22:30:43.3939693Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-10-16T22:30:43.3940772Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-10-16T22:30:43.3941829Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-10-16T22:30:43.3943017Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-10-16T22:30:43.3944181Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-10-16T22:30:43.3945351Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-10-16T22:30:43.3946489Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-10-16T22:30:43.3947618Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-10-16T22:30:43.3948688Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-10-16T22:30:43.3950015Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2022-10-16T22:30:43.3951253Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2022-10-16T22:30:43.3952378Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-10-16T22:30:43.3953307Z 	at java.lang.Thread.run(Thread.java:829)
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by puzpuzpuz** [comment]
Couldn't reproduce this one on Linux and x86.

**Comment by bluestreak01** [comment]
This is likely to do with tests running as a group and perhaps logger configured to roll files on size.
