### ISSUE TITLE
Flaky testAlterCommandDropLastPartition

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#2692]
### Describe the bug

```
2022-10-26T15:45:31.6721150Z 2022-10-26T15:45:31.569117Z I i.q.TestListener >>>> io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropLastPartition
2022-10-26T15:45:31.6723350Z 2022-10-26T15:45:31.569594Z I i.q.c.AbstractCairoTest Starting test AlterTableLineTcpReceiverTest#testAlterCommandDropLastPartition
2022-10-26T15:45:31.6724760Z 2022-10-26T15:45:31.570453Z I i.q.c.l.t.LineTcpReceiver using default context
2022-10-26T15:45:31.6726030Z 2022-10-26T15:45:31.570615Z A IODispatcher listening on 0.0.0.0:9002 [fd=18 backlog=64]
2022-10-26T15:45:31.6727360Z 2022-10-26T15:45:31.572174Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-10-26T15:45:31.6728750Z 2022-10-26T15:45:31.576743Z I i.q.c.CairoEngine locked [table=`__syscolumn_versions_purge_log`, thread=498]
2022-10-26T15:45:32.4882910Z 2022-10-26T15:45:32.320037Z I i.q.c.p.WriterPool created [table=`__syscolumn_versions_purge_log`, thread=498]
2022-10-26T15:45:32.4884730Z 2022-10-26T15:45:32.320115Z I i.q.c.TableWriter open '__syscolumn_versions_purge_log'
2022-10-26T15:45:32.4887830Z 2022-10-26T15:45:32.322369Z I i.q.c.TableWriter purging non attached partitions [path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit7086517999077559104/dbRoot/__syscolumn_versions_purge_log]
2022-10-26T15:45:32.4890110Z 2022-10-26T15:45:32.322500Z I i.q.c.CairoEngine unlocked [table=`__syscolumn_versions_purge_log`]
2022-10-26T15:45:32.4892040Z 2022-10-26T15:45:32.322515Z I i.q.c.p.WriterPool >> [table=`__syscolumn_versions_purge_log`, thread=498]
2022-10-26T15:45:32.4893480Z 2022-10-26T15:45:32.322828Z I i.q.c.p.ReaderPool open '__syscolumn_versions_purge_log' [at=0:0]
2022-10-26T15:45:32.4896150Z 2022-10-26T15:45:32.324039Z I i.q.g.SqlCompiler plan [q=`select-choose ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed from (select [ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed] from __syscolumn_versions_purge_log timestamp (ts) where completed = null)`, fd=-1]
2022-10-26T15:45:32.4900500Z 2022-10-26T15:45:32.324446Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=__syscolumn_versions_purge_log, fd=-1]
2022-10-26T15:45:32.4902970Z 2022-10-26T15:45:32.325580Z I i.q.c.l.t.AbstractLineTcpReceiverTest worker pool started [pool=testing]
2022-10-26T15:45:32.4905600Z 2022-10-26T15:45:32.325627Z I i.q.c.l.t.AbstractLineTcpReceiverTest os scheduled worker started [name=questdb-testing-86]
2022-10-26T15:45:32.6509200Z 2022-10-26T15:45:32.529447Z I i.q.c.p.ReaderPool closed '__syscolumn_versions_purge_log' [at=0:0, reason=IDLE]
2022-10-26T15:45:32.6513370Z 2022-10-26T15:45:32.530234Z I i.q.c.p.WriterPool open [table=`plug`, thread=498]
2022-10-26T15:45:32.6515540Z 2022-10-26T15:45:32.530269Z I i.q.c.TableWriter open 'plug'
2022-10-26T15:45:32.6519390Z 2022-10-26T15:45:32.532040Z I i.q.c.TableWriter purging non attached partitions [path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit7086517999077559104/dbRoot/plug]
2022-10-26T15:45:32.6522710Z 2022-10-26T15:45:32.532181Z I i.q.c.p.WriterPool >> [table=`plug`, thread=498]
2022-10-26T15:45:32.6525560Z 2022-10-26T15:45:32.532864Z I i.q.c.TableWriter switched partition [path='/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit7086517999077559104/dbRoot/plug/2023-02-27']
2022-10-26T15:45:32.6530810Z 2022-10-26T15:45:32.533214Z I i.q.c.p.WriterPool << [table=`plug`, thread=498]
2022-10-26T15:45:32.6534620Z 2022-10-26T15:45:32.540240Z I IODispatcher connected [ip=127.0.0.1, fd=50]
2022-10-26T15:45:32.6536880Z 2022-10-26T15:45:32.540616Z I i.q.c.p.WriterPool >> [table=`plug`, thread=499]
2022-10-26T15:45:32.6540980Z 2022-10-26T15:45:32.540625Z I i.q.c.l.t.AlterTableLineTcpReceiverTest EV_GET plug
2022-10-26T15:45:32.6543260Z 2022-10-26T15:45:32.540649Z I i.q.c.l.t.AlterTableLineTcpReceiverTest Started waiting for writer ASYNC event
2022-10-26T15:45:32.6545520Z 2022-10-26T15:45:32.542422Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-10-26T15:45:32.6548100Z 2022-10-26T15:45:32.547144Z I i.q.c.p.ReaderPool open 'plug' [at=0:0]
2022-10-26T15:45:32.6627030Z 2022-10-26T15:45:32.548069Z I i.q.c.p.WriterPool busy [table=`plug`, owner=499, thread=499, reason=tcpIlp]
2022-10-26T15:45:32.6630160Z 2022-10-26T15:45:32.548172Z I i.q.g.e.o.OperationFutureImpl published ASYNC writer command [name=ALTER TABLE,tableName=plug,instance=5]
2022-10-26T15:45:32.6632530Z 2022-10-26T15:45:32.548349Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned plug to thread 0
2022-10-26T15:45:32.6634880Z 2022-10-26T15:45:32.548360Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=0, tableName=plug, nNetworkIoWorkers=1]
2022-10-26T15:45:32.6637160Z 2022-10-26T15:45:32.548837Z I IODispatcher scheduling disconnect [fd=50, reason=0]
2022-10-26T15:45:32.6641640Z 2022-10-26T15:45:32.548859Z I i.q.c.l.t.LineTcpWriterJob assigned table to writer thread [tableName=plug, threadId=0]
2022-10-26T15:45:32.6643890Z 2022-10-26T15:45:32.548901Z I IODispatcher disconnected [ip=127.0.0.1, fd=50, src=queue]
2022-10-26T15:45:32.6646260Z 2022-10-26T15:45:32.549180Z I i.q.c.l.t.AlterTableLineTcpReceiverTest Busy waiting for writer ASYNC event io.questdb.griffin.engine.ops.OperationFutureImpl@41657c87
2022-10-26T15:45:32.6776900Z 2022-10-26T15:45:32.549709Z I i.q.g.e.o.OperationFutureImpl writer command QUERY_STARTED response received [instance=5]
2022-10-26T15:45:32.6897360Z 2022-10-26T15:45:32.549711Z I i.q.c.TableWriter received async cmd [type=2, tableName=plug, tableId=1, correlationId=5, cursor=0]
2022-10-26T15:45:32.6987360Z 2022-10-26T15:45:32.549759Z I i.q.c.TableWriter closing last partition [table=plug]
2022-10-26T15:45:32.9205650Z 2022-10-26T15:45:32.754250Z I i.q.c.TableWriter purged [path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit7086517999077559104/dbRoot/plug/2023-02-27]
2022-10-26T15:45:32.9207670Z 2022-10-26T15:45:32.754275Z I i.q.c.TableWriter published async command complete event [type=2,tableName=plug,tableId=1,correlationId=5]
2022-10-26T15:45:32.9210050Z 2022-10-26T15:45:32.754277Z I i.q.g.e.o.OperationFutureImpl writer command response received [instance=5]
2022-10-26T15:45:32.9211550Z 2022-10-26T15:45:32.754306Z I i.q.c.l.t.AlterTableLineTcpReceiverTest Stopped waiting for writer ASYNC event
2022-10-26T15:45:32.9213040Z 2022-10-26T15:45:32.754342Z I i.q.c.p.ReaderPool open 'plug' [at=0:1]
2022-10-26T15:45:32.9214380Z 2022-10-26T15:45:32.917612Z I i.q.c.p.ReaderPool closed 'plug' [at=0:0, reason=IDLE]
2022-10-26T15:45:32.9215730Z 2022-10-26T15:45:32.917772Z I i.q.c.p.ReaderPool closed 'plug' [at=0:1, reason=IDLE]
2022-10-26T15:45:32.9217040Z 2022-10-26T15:45:32.917882Z I IODispatcher connected [ip=127.0.0.1, fd=47]
2022-10-26T15:45:32.9218990Z 2022-10-26T15:45:32.918109Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=0, tableName=plug, nNetworkIoWorkers=0]
2022-10-26T15:45:32.9220560Z 2022-10-26T15:45:32.918114Z I i.q.c.l.t.LineTcpMeasurementScheduler active table going idle [tableName=plug]
2022-10-26T15:45:32.9222150Z 2022-10-26T15:45:32.918125Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2022-10-26T15:45:32.548000Z[tableName=plug]
2022-10-26T15:45:32.9223620Z 2022-10-26T15:45:32.918140Z I i.q.c.p.WriterPool << [table=`plug`, thread=499]
2022-10-26T15:45:32.9224920Z 2022-10-26T15:45:32.918145Z I i.q.c.l.t.AlterTableLineTcpReceiverTest EV_RETURN plug
2022-10-26T15:45:32.9226220Z 2022-10-26T15:45:32.918211Z I i.q.c.p.ReaderPool open 'plug' [at=0:0]
2022-10-26T15:45:32.9228570Z 2022-10-26T15:45:32.919232Z E i.q.c.l.t.AbstractLineTcpReceiverTest Stopping ILP worker pool because of an error
2022-10-26T15:45:32.9229480Z java.lang.AssertionError: expected:<room	watts	timestamp
2022-10-26T15:45:32.9230930Z 6A	125	2023-02-27T00:00:00.000000Z
2022-10-26T15:45:32.9231590Z > but was:<room	watts	timestamp
2022-10-26T15:45:32.9232080Z >
2022-10-26T15:45:32.9232610Z 	at org.junit.Assert.fail(Assert.java:89)
2022-10-26T15:45:32.9233270Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2022-10-26T15:45:32.9233950Z 	at org.junit.Assert.assertEquals(Assert.java:120)
2022-10-26T15:45:32.9234650Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:327)
2022-10-26T15:45:32.9235420Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:310)
2022-10-26T15:45:32.9236890Z 	at io.questdb.test.tools.TestUtils.assertCursor(TestUtils.java:117)
2022-10-26T15:45:32.9237760Z 	at io.questdb.cairo.AbstractCairoTest.assertCursor(AbstractCairoTest.java:500)
2022-10-26T15:45:32.9239100Z 	at io.questdb.cairo.AbstractCairoTest.assertCursorTwoPass(AbstractCairoTest.java:504)
2022-10-26T15:45:32.9240110Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.assertTable(AbstractLineTcpReceiverTest.java:175)
2022-10-26T15:45:32.9241120Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.assertTable(AlterTableLineTcpReceiverTest.java:553)
2022-10-26T15:45:32.9242210Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.lambda$testAlterCommandDropLastPartition$2(AlterTableLineTcpReceiverTest.java:151)
2022-10-26T15:45:32.9243290Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$0(AbstractLineTcpReceiverTest.java:223)
2022-10-26T15:45:32.9244970Z 	at io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$0(AbstractCairoTest.java:488)
2022-10-26T15:45:32.9246350Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:468)
2022-10-26T15:45:32.9247670Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:485)
2022-10-26T15:45:32.9248540Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:479)
2022-10-26T15:45:32.9250540Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:213)
2022-10-26T15:45:32.9251620Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropLastPartition(AlterTableLineTcpReceiverTest.java:122)
2022-10-26T15:45:32.9252970Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-26T15:45:32.9253780Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-10-26T15:45:32.9254690Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-10-26T15:45:32.9256180Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-10-26T15:45:32.9256980Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-10-26T15:45:32.9257910Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-10-26T15:45:32.9259320Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-10-26T15:45:32.9260230Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-10-26T15:45:32.9261430Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-10-26T15:45:32.9262380Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-10-26T15:45:32.9263710Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-10-26T15:45:32.9264690Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2022-10-26T15:45:32.9265700Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2022-10-26T15:45:32.9267100Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-10-26T15:45:32.9267850Z 	at java.lang.Thread.run(Thread.java:829)
2022-10-26T15:45:33.1241180Z 2022-10-26T15:45:33.123241Z I i.q.c.TableWriter closed 'plug'
2022-10-26T15:45:33.1245360Z 2022-10-26T15:45:33.123258Z I i.q.c.p.WriterPool closed [table=`plug`, reason=IDLE, by=499]
2022-10-26T15:45:33.1256990Z 2022-10-26T15:45:33.123585Z I i.q.c.p.ReaderPool closed 'plug' [at=0:0, reason=IDLE]
2022-10-26T15:45:33.1267790Z 2022-10-26T15:45:33.124145Z I i.q.c.l.t.AbstractLineTcpReceiverTest cleaned worker [name=testing, worker=0, total=1]
2022-10-26T15:45:33.1271620Z 2022-10-26T15:45:33.124162Z I i.q.c.l.t.AbstractLineTcpReceiverTest os scheduled worker stopped [name=questdb-testing-86]
2022-10-26T15:45:33.1274130Z 2022-10-26T15:45:33.124266Z I i.q.c.l.t.LineTcpWriterJob line protocol writer closing [threadId=0]
2022-10-26T15:45:33.1279390Z 2022-10-26T15:45:33.124295Z I i.q.c.p.WriterPool << [table=`__syscolumn_versions_purge_log`, thread=498]
2022-10-26T15:45:33.1281860Z 2022-10-26T15:45:33.124853Z I i.q.c.l.t.TableUpdateDetails closing table parsers [tableName=plug]
2022-10-26T15:45:33.1283680Z 2022-10-26T15:45:33.124868Z I i.q.c.l.t.TableUpdateDetails closing table writer [tableName=plug]
2022-10-26T15:45:33.1285240Z 2022-10-26T15:45:33.124870Z I i.q.c.l.t.TableUpdateDetails closing table parsers [tableName=plug]
2022-10-26T15:45:33.1287200Z 2022-10-26T15:45:33.124881Z I IODispatcher disconnected [ip=127.0.0.1, fd=47, src=shutdown]
2022-10-26T15:45:33.1288400Z 2022-10-26T15:45:33.124989Z I IODispatcher closed
2022-10-26T15:45:33.1289680Z 2022-10-26T15:45:33.124998Z E i.q.c.l.t.AbstractLineTcpReceiverTest Stopping ILP receiver because of an error
2022-10-26T15:45:33.1290490Z java.lang.AssertionError: expected:<room	watts	timestamp
2022-10-26T15:45:33.1291490Z 6A	125	2023-02-27T00:00:00.000000Z
2022-10-26T15:45:33.1292090Z > but was:<room	watts	timestamp
2022-10-26T15:45:33.1292940Z >
2022-10-26T15:45:33.1293420Z 	at org.junit.Assert.fail(Assert.java:89)
2022-10-26T15:45:33.1294030Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2022-10-26T15:45:33.1294660Z 	at org.junit.Assert.assertEquals(Assert.java:120)
2022-10-26T15:45:33.1295320Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:327)
2022-10-26T15:45:33.1296470Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:310)
2022-10-26T15:45:33.1297200Z 	at io.questdb.test.tools.TestUtils.assertCursor(TestUtils.java:117)
2022-10-26T15:45:33.1297930Z 	at io.questdb.cairo.AbstractCairoTest.assertCursor(AbstractCairoTest.java:500)
2022-10-26T15:45:33.1298730Z 	at io.questdb.cairo.AbstractCairoTest.assertCursorTwoPass(AbstractCairoTest.java:504)
2022-10-26T15:45:33.1300150Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.assertTable(AbstractLineTcpReceiverTest.java:175)
2022-10-26T15:45:33.1301120Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.assertTable(AlterTableLineTcpReceiverTest.java:553)
2022-10-26T15:45:33.1302170Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.lambda$testAlterCommandDropLastPartition$2(AlterTableLineTcpReceiverTest.java:151)
2022-10-26T15:45:33.1303210Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$0(AbstractLineTcpReceiverTest.java:223)
2022-10-26T15:45:33.1304130Z 	at io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$0(AbstractCairoTest.java:488)
2022-10-26T15:45:33.1304920Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:468)
2022-10-26T15:45:33.1305670Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:485)
2022-10-26T15:45:33.1306460Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:479)
2022-10-26T15:45:33.1307320Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:213)
2022-10-26T15:45:33.1308320Z 	at io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropLastPartition(AlterTableLineTcpReceiverTest.java:122)
2022-10-26T15:45:33.1309200Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-26T15:45:33.1310010Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-10-26T15:45:33.1311120Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-10-26T15:45:33.1311970Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-10-26T15:45:33.1312700Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-10-26T15:45:33.1313570Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-10-26T15:45:33.1314450Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-10-26T15:45:33.1315310Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-10-26T15:45:33.1316170Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-10-26T15:45:33.1317000Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-10-26T15:45:33.1317790Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-10-26T15:45:33.1318620Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2022-10-26T15:45:33.1319570Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2022-10-26T15:45:33.1320420Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-10-26T15:45:33.1321100Z 	at java.lang.Thread.run(Thread.java:829)
2022-10-26T15:45:33.5781690Z 2022-10-26T15:45:33.495900Z I i.q.c.TableWriter closed '__syscolumn_versions_purge_log'
2022-10-26T15:45:33.5783570Z 2022-10-26T15:45:33.495907Z I i.q.c.p.WriterPool closed [table=`__syscolumn_versions_purge_log`, reason=POOL_CLOSED, by=498]
2022-10-26T15:45:33.5785220Z 2022-10-26T15:45:33.496041Z I i.q.c.AbstractCairoTest Tearing down test AlterTableLineTcpReceiverTest#testAlterCommandDropLastPartition
2022-10-26T15:45:33.5787350Z 2022-10-26T15:45:33.546583Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.line.tcp.AlterTableLineTcpReceiverTest.testAlterCommandDropLastPartition : 
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by puzpuzpuz** [comment]
I'm able to reproduce this one, so I'm picking it.
