### ISSUE TITLE
ILP client fails when interrupted in send()

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2713]
### Describe the bug

While profiling the ILP client I'm getting this error:
```
io.questdb.cutlass.line.LineSenderException: [4] send error
	at io.questdb.cutlass.line.tcp.PlainTcpLineChannel.send(PlainTcpLineChannel.java:100)
	at io.questdb.cutlass.line.tcp.DelegatingTlsChannel.writeToUpstreamAndClear(DelegatingTlsChannel.java:296)
	at io.questdb.cutlass.line.tcp.DelegatingTlsChannel.wrapLoop(DelegatingTlsChannel.java:246)
	at io.questdb.cutlass.line.tcp.DelegatingTlsChannel.send(DelegatingTlsChannel.java:199)
	at io.questdb.cutlass.line.AbstractLineSender.sendAll(AbstractLineSender.java:380)
	at io.questdb.cutlass.line.LineTcpSender.flush(LineTcpSender.java:81)
```
errno 4 is `EINTR` -> the thread was interrupted while in a syscall. we should restart the syscall instead of propagating the error. 

### To reproduce

- Run ILP client
- Start async profile in the wall mode
- Wait for the error

### Expected Behavior

`EINTR` is handled transparently by restarting the syscall

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by jerrinot** [comment]
fixed by https://github.com/questdb/questdb/pull/2739
