### ISSUE TITLE
Flaky LineTcpReceiverUpdateFuzzTest.testInsertUpdateSequential[NO_WAL]

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#2763]
### Describe the bug

```
2022-11-11T04:12:13.9949805Z 2022-11-11T04:12:13.950916Z I i.q.TestListener >>>> io.questdb.cutlass.line.tcp.LineTcpReceiverUpdateFuzzTest.testInsertUpdateSequential[NO_WAL]
2022-11-11T04:12:13.9950793Z 2022-11-11T04:12:13.951465Z I i.q.c.l.t.LineTcpReceiverUpdateFuzzTest random seeds: 478464893962L, 1668139933951L
2022-11-11T04:12:13.9951905Z 2022-11-11T04:12:13.951839Z I i.q.c.AbstractCairoTest Starting test LineTcpReceiverUpdateFuzzTest#testInsertUpdateSequential[NO_WAL]
2022-11-11T04:12:13.9952774Z 2022-11-11T04:12:13.954155Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-11-11T04:12:13.9953538Z 2022-11-11T04:12:13.958083Z I i.q.c.l.t.LineTcpReceiver using default context
2022-11-11T04:12:13.9954363Z 2022-11-11T04:12:13.958165Z A IODispatcher listening on 0.0.0.0:9002 [fd=21 backlog=64]
2022-11-11T04:12:13.9955172Z 2022-11-11T04:12:13.960393Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-11-11T04:12:13.9956034Z 2022-11-11T04:12:13.964490Z I i.q.c.CairoEngine locked [table=`__syscolumn_versions_purge_log`, thread=3969]
2022-11-11T04:12:13.9957415Z 2022-11-11T04:12:13.970469Z I i.q.c.p.WriterPool created [table=`__syscolumn_versions_purge_log`, thread=3969]
2022-11-11T04:12:13.9958363Z 2022-11-11T04:12:13.970495Z I i.q.c.TableWriter open '__syscolumn_versions_purge_log'
2022-11-11T04:12:13.9959417Z 2022-11-11T04:12:13.971032Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/junit15087144222600271481/dbRoot/__syscolumn_versions_purge_log]
2022-11-11T04:12:13.9960420Z 2022-11-11T04:12:13.972348Z I i.q.c.CairoEngine unlocked [table=`__syscolumn_versions_purge_log`]
2022-11-11T04:12:13.9961342Z 2022-11-11T04:12:13.972361Z I i.q.c.p.WriterPool >> [table=`__syscolumn_versions_purge_log`, thread=3969]
2022-11-11T04:12:13.9962333Z 2022-11-11T04:12:13.972539Z I i.q.c.p.AbstractMultiTenantPool open '__syscolumn_versions_purge_log' [at=0:0]
2022-11-11T04:12:13.9964342Z 2022-11-11T04:12:13.973093Z I i.q.g.SqlCompiler plan [q=`select-choose ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed from (select [ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed] from __syscolumn_versions_purge_log timestamp (ts) where completed = null)`, fd=-1]
2022-11-11T04:12:14.0006558Z 2022-11-11T04:12:13.973365Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=__syscolumn_versions_purge_log, fd=-1]
2022-11-11T04:12:14.0008561Z 2022-11-11T04:12:13.973947Z I i.q.c.l.t.AbstractLineTcpReceiverTest os scheduled worker started [name=questdb-testing-3198]
2022-11-11T04:12:14.0009662Z 2022-11-11T04:12:13.976029Z I i.q.c.l.t.AbstractLineTcpReceiverTest os scheduled worker started [name=questdb-testing-3199]
2022-11-11T04:12:14.0035354Z 2022-11-11T04:12:13.978161Z I i.q.c.l.t.AbstractLineTcpReceiverTest os scheduled worker started [name=questdb-testing-3200]
2022-11-11T04:12:14.0036739Z 2022-11-11T04:12:13.979749Z I i.q.c.l.t.AbstractLineTcpReceiverTest worker pool started [pool=testing]
2022-11-11T04:12:14.0037634Z 2022-11-11T04:12:13.979998Z I IODispatcher connected [ip=127.0.0.1, fd=50]
2022-11-11T04:12:14.0038571Z 2022-11-11T04:12:13.980236Z I i.q.c.l.t.AbstractLineTcpReceiverTest os scheduled worker started [name=questdb-testing-3201]
2022-11-11T04:12:14.0039619Z 2022-11-11T04:12:13.983773Z I IODispatcher connected [ip=127.0.0.1, fd=52]
2022-11-11T04:12:14.0041493Z 2022-11-11T04:12:13.991973Z I i.q.c.l.t.LineTcpMeasurementScheduler creating table [tableName=weather4]
2022-11-11T04:12:14.0042918Z 2022-11-11T04:12:14.003092Z I i.q.c.CairoEngine locked [table=`weather4`, thread=3973]
2022-11-11T04:12:14.0098210Z 2022-11-11T04:12:14.009335Z I i.q.c.p.WriterPool created [table=`weather4`, thread=3973]
2022-11-11T04:12:14.0099857Z 2022-11-11T04:12:14.009378Z I i.q.c.TableWriter open 'weather4'
2022-11-11T04:12:14.0119966Z 2022-11-11T04:12:14.011667Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/junit15087144222600271481/dbRoot/weather4]
2022-11-11T04:12:14.0169188Z Exception in thread "Thread-3445" java.lang.AssertionError: Update failed [e=io.questdb.cairo.pool.ex.EntryLockedException: [-1] table busy [reason=unknown], sql=update "weather4" set temperature=5258.0 where timestamp='2016-06-13T17:43:50.102349']
2022-11-11T04:12:14.0173615Z 	at org.junit.Assert.fail(Assert.java:89)
2022-11-11T04:12:14.0174852Z 	at io.questdb.cutlass.line.tcp.LineTcpReceiverUpdateFuzzTest.lambda$startUpdateThread$0(LineTcpReceiverUpdateFuzzTest.java:197)
2022-11-11T04:12:14.0176737Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-11T04:12:14.0178085Z 2022-11-11T04:12:14.014315Z I i.q.c.p.AbstractMultiTenantPool open 'weather4' [at=0:0]
2022-11-11T04:12:14.0179593Z 2022-11-11T04:12:14.014870Z I i.q.c.l.t.LineTcpReceiverUpdateFuzzTest update "weather4" set temperature=5258.0 where timestamp='2016-06-13T17:43:50.102349'
2022-11-11T04:12:14.0181944Z 2022-11-11T04:12:14.015083Z I i.q.c.p.AbstractMultiTenantPool 'weather4' is locked [owner=3973]
2022-11-11T04:12:14.0183190Z 2022-11-11T04:12:14.015261Z I i.q.c.p.WriterPool >> [table=`weather4`, thread=3975]
2022-11-11T04:12:14.0184240Z 2022-11-11T04:12:14.015284Z I i.q.c.p.WriterPool << [table=`weather4`, thread=3975]
2022-11-11T04:12:14.0185322Z 2022-11-11T04:12:14.015297Z I i.q.c.p.AbstractMultiTenantPool 'weather4' is locked [owner=3973]
2022-11-11T04:12:14.0186390Z 2022-11-11T04:12:14.017033Z I i.q.c.CairoEngine unlocked [table=`weather4`]
2022-11-11T04:12:14.0187430Z 2022-11-11T04:12:14.017381Z I i.q.c.p.WriterPool >> [table=`weather4`, thread=3973]
2022-11-11T04:12:14.0194747Z 2022-11-11T04:12:14.017964Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned weather4 to thread 0
2022-11-11T04:12:14.0195723Z 2022-11-11T04:12:14.017974Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=3, tableName=weather4, nNetworkIoWorkers=1]
2022-11-11T04:12:14.0196608Z 2022-11-11T04:12:14.018190Z I i.q.c.l.t.LineTcpMeasurementScheduler creating table [tableName=weather0]
2022-11-11T04:12:14.0197391Z 2022-11-11T04:12:14.018268Z I i.q.c.CairoEngine locked [table=`weather0`, thread=3970]
2022-11-11T04:12:14.0198174Z 2022-11-11T04:12:14.018828Z I i.q.c.p.AbstractMultiTenantPool open 'weather4' [at=0:0]
2022-11-11T04:12:14.0220296Z 2022-11-11T04:12:14.019295Z I i.q.c.p.WriterPool created [table=`weather0`, thread=3970]
2022-11-11T04:12:14.0221265Z 2022-11-11T04:12:14.019327Z I i.q.c.TableWriter open 'weather0'
2022-11-11T04:12:14.0222131Z 2022-11-11T04:12:14.019577Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/junit15087144222600271481/dbRoot/weather0]
2022-11-11T04:12:14.0222940Z 2022-11-11T04:12:14.020328Z I i.q.c.CairoEngine unlocked [table=`weather0`]
2022-11-11T04:12:14.0223670Z 2022-11-11T04:12:14.020375Z I i.q.c.p.WriterPool >> [table=`weather0`, thread=3970]
2022-11-11T04:12:14.0224427Z 2022-11-11T04:12:14.020446Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned weather0 to thread 1
2022-11-11T04:12:14.0225355Z 2022-11-11T04:12:14.020452Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=0, tableName=weather0, nNetworkIoWorkers=1]
2022-11-11T04:12:14.0226240Z 2022-11-11T04:12:14.020459Z I i.q.c.p.AbstractMultiTenantPool open 'weather0' [at=0:0]
2022-11-11T04:12:14.0227061Z 2022-11-11T04:12:14.020710Z I i.q.c.l.t.LineTcpMeasurementScheduler creating table [tableName=weather2]
2022-11-11T04:12:14.0227848Z 2022-11-11T04:12:14.020803Z I i.q.c.CairoEngine locked [table=`weather2`, thread=3970]
2022-11-11T04:12:14.0228678Z 2022-11-11T04:12:14.021357Z I i.q.c.l.t.LineTcpWriterJob assigned table to writer thread [tableName=weather0, threadId=1]
2022-11-11T04:12:14.0231830Z 2022-11-11T04:12:14.021935Z I i.q.c.p.WriterPool created [table=`weather2`, thread=3970]
2022-11-11T04:12:14.0233667Z 2022-11-11T04:12:14.021960Z I i.q.c.TableWriter open 'weather2'
2022-11-11T04:12:14.0234887Z 2022-11-11T04:12:14.022210Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/junit15087144222600271481/dbRoot/weather2]
2022-11-11T04:12:14.0237145Z 2022-11-11T04:12:14.022709Z I i.q.c.CairoEngine unlocked [table=`weather2`]
2022-11-11T04:12:14.0238277Z 2022-11-11T04:12:14.022738Z I i.q.c.p.WriterPool >> [table=`weather2`, thread=3970]
2022-11-11T04:12:14.0239423Z 2022-11-11T04:12:14.022970Z I i.q.c.TableWriter switched partition [path='/tmp/junit15087144222600271481/dbRoot/weather0/2016-06-13']
2022-11-11T04:12:14.0240710Z 2022-11-11T04:12:14.023141Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned weather2 to thread 2
2022-11-11T04:12:14.0241868Z 2022-11-11T04:12:14.023148Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=0, tableName=weather2, nNetworkIoWorkers=1]
2022-11-11T04:12:14.0243016Z 2022-11-11T04:12:14.023155Z I i.q.c.p.AbstractMultiTenantPool open 'weather2' [at=0:0]
2022-11-11T04:12:14.0244062Z 2022-11-11T04:12:14.023267Z I i.q.c.l.t.LineTcpMeasurementScheduler creating table [tableName=weather3]
2022-11-11T04:12:14.0245148Z 2022-11-11T04:12:14.023339Z I i.q.c.CairoEngine locked [table=`weather3`, thread=3973]
2022-11-11T04:12:14.0253821Z 2022-11-11T04:12:14.024112Z I i.q.c.l.t.LineTcpWriterJob assigned table to writer thread [tableName=weather2, threadId=2]
2022-11-11T04:12:14.0255627Z 2022-11-11T04:12:14.024720Z I i.q.c.TableWriter switched partition [path='/tmp/junit15087144222600271481/dbRoot/weather2/2016-06-13']
2022-11-11T04:12:14.0262270Z 2022-11-11T04:12:14.025762Z I i.q.c.p.WriterPool created [table=`weather3`, thread=3973]
2022-11-11T04:12:14.0263496Z 2022-11-11T04:12:14.025780Z I i.q.c.TableWriter open 'weather3'
2022-11-11T04:12:14.0268710Z 2022-11-11T04:12:14.026201Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/junit15087144222600271481/dbRoot/weather3]
2022-11-11T04:12:14.0299989Z 2022-11-11T04:12:14.028086Z I i.q.c.CairoEngine unlocked [table=`weather3`]
2022-11-11T04:12:14.0301289Z 2022-11-11T04:12:14.028119Z I i.q.c.p.WriterPool >> [table=`weather3`, thread=3973]
2022-11-11T04:12:14.0302584Z 2022-11-11T04:12:14.028273Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned weather3 to thread 3
2022-11-11T04:12:14.0303738Z 2022-11-11T04:12:14.028279Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=3, tableName=weather3, nNetworkIoWorkers=1]
2022-11-11T04:12:14.0304638Z 2022-11-11T04:12:14.028285Z I i.q.c.p.AbstractMultiTenantPool open 'weather3' [at=0:0]
2022-11-11T04:12:14.0305975Z 2022-11-11T04:12:14.028416Z I i.q.c.l.t.LineTcpMeasurementScheduler creating table [tableName=weather1]
2022-11-11T04:12:14.0306934Z 2022-11-11T04:12:14.028477Z I i.q.c.CairoEngine locked [table=`weather1`, thread=3973]
2022-11-11T04:12:14.0428712Z 2022-11-11T04:12:14.033062Z I i.q.c.p.WriterPool created [table=`weather1`, thread=3973]
2022-11-11T04:12:14.0434859Z 2022-11-11T04:12:14.033075Z I i.q.c.TableWriter open 'weather1'
2022-11-11T04:12:14.0446441Z 2022-11-11T04:12:14.033285Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/junit15087144222600271481/dbRoot/weather1]
2022-11-11T04:12:14.0448064Z 2022-11-11T04:12:14.033636Z I i.q.c.CairoEngine unlocked [table=`weather1`]
2022-11-11T04:12:14.0449189Z 2022-11-11T04:12:14.033676Z I i.q.c.p.WriterPool >> [table=`weather1`, thread=3973]
2022-11-11T04:12:14.0450211Z 2022-11-11T04:12:14.033716Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned weather1 to thread 1
2022-11-11T04:12:14.0457809Z 2022-11-11T04:12:14.033722Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=3, tableName=weather1, nNetworkIoWorkers=1]
2022-11-11T04:12:14.0459621Z 2022-11-11T04:12:14.033728Z I i.q.c.p.AbstractMultiTenantPool open 'weather1' [at=0:0]
2022-11-11T04:12:14.0460898Z 2022-11-11T04:12:14.033876Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=3, tableName=weather2, nNetworkIoWorkers=2]
2022-11-11T04:12:14.0462327Z 2022-11-11T04:12:14.033881Z I i.q.c.p.AbstractMultiTenantPool open 'weather2' [at=0:1]
2022-11-11T04:12:14.0463479Z 2022-11-11T04:12:14.033999Z I i.q.c.l.t.LineTcpWriterJob assigned table to writer thread [tableName=weather3, threadId=3]
2022-11-11T04:12:14.0464852Z 2022-11-11T04:12:14.034210Z I i.q.c.TableWriter switched partition [path='/tmp/junit15087144222600271481/dbRoot/weather3/2016-06-13']
2022-11-11T04:12:14.0466393Z 2022-11-11T04:12:14.036599Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=0, tableName=weather1, nNetworkIoWorkers=2]
2022-11-11T04:12:14.0467932Z 2022-11-11T04:12:14.036611Z I i.q.c.p.AbstractMultiTenantPool open 'weather1' [at=0:1]
2022-11-11T04:12:14.0469246Z 2022-11-11T04:12:14.036702Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=0, tableName=weather3, nNetworkIoWorkers=2]
2022-11-11T04:12:14.0470657Z 2022-11-11T04:12:14.036707Z I i.q.c.p.AbstractMultiTenantPool open 'weather3' [at=0:1]
2022-11-11T04:12:14.0471908Z 2022-11-11T04:12:14.036781Z I i.q.c.l.t.LineTcpWriterJob assigned table to writer thread [tableName=weather4, threadId=0]
2022-11-11T04:12:14.0473240Z 2022-11-11T04:12:14.036962Z I i.q.c.TableWriter switched partition [path='/tmp/junit15087144222600271481/dbRoot/weather4/2016-06-13']
2022-11-11T04:12:14.0474521Z 2022-11-11T04:12:14.040583Z I i.q.c.l.t.LineTcpWriterJob assigned table to writer thread [tableName=weather1, threadId=1]
2022-11-11T04:12:14.0475897Z 2022-11-11T04:12:14.040746Z I i.q.c.TableWriter switched partition [path='/tmp/junit15087144222600271481/dbRoot/weather1/2016-06-13']
2022-11-11T04:12:14.0477240Z 2022-11-11T04:12:14.040991Z I i.q.c.TableWriter switched to o3 [table=weather2]
2022-11-11T04:12:14.0532094Z 2022-11-11T04:12:14.049151Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=0, tableName=weather4, nNetworkIoWorkers=2]
2022-11-11T04:12:14.0533927Z 2022-11-11T04:12:14.049162Z I i.q.c.p.AbstractMultiTenantPool open 'weather4' [at=0:1]
2022-11-11T04:12:14.0630880Z 2022-11-11T04:12:14.056339Z I i.q.c.l.t.TableUpdateDetails network IO thread using table [workerId=3, tableName=weather0, nNetworkIoWorkers=2]
2022-11-11T04:12:14.0632921Z 2022-11-11T04:12:14.056349Z I i.q.c.p.AbstractMultiTenantPool open 'weather0' [at=0:1]
2022-11-11T04:12:14.0634238Z 2022-11-11T04:12:14.056547Z I i.q.c.TableWriter switched to o3 [table=weather3]
2022-11-11T04:12:14.0635517Z 2022-11-11T04:12:14.060575Z I i.q.c.TableWriter switched to o3 [table=weather1]
2022-11-11T04:12:14.0636594Z 2022-11-11T04:12:14.061272Z I i.q.c.TableWriter switched to o3 [table=weather0]
2022-11-11T04:12:14.0730008Z 2022-11-11T04:12:14.069885Z I i.q.c.TableWriter switched to o3 [table=weather4]
2022-11-11T04:12:14.5255035Z 2022-11-11T04:12:14.463353Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=0, tableName=weather0, nNetworkIoWorkers=1]
2022-11-11T04:12:14.5258389Z 2022-11-11T04:12:14.463366Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=0, tableName=weather2, nNetworkIoWorkers=1]
2022-11-11T04:12:14.5260720Z 2022-11-11T04:12:14.463373Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=0, tableName=weather1, nNetworkIoWorkers=1]
2022-11-11T04:12:14.5262871Z 2022-11-11T04:12:14.463380Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=0, tableName=weather3, nNetworkIoWorkers=1]
2022-11-11T04:12:14.5265011Z 2022-11-11T04:12:14.463386Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=0, tableName=weather4, nNetworkIoWorkers=1]
2022-11-11T04:12:14.5267125Z 2022-11-11T04:12:14.463540Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=3, tableName=weather4, nNetworkIoWorkers=0]
2022-11-11T04:12:14.5269148Z 2022-11-11T04:12:14.463544Z I i.q.c.l.t.LineTcpMeasurementScheduler active table going idle [tableName=weather4]
2022-11-11T04:12:14.5271209Z 2022-11-11T04:12:14.463552Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=3, tableName=weather3, nNetworkIoWorkers=0]
2022-11-11T04:12:14.5273545Z 2022-11-11T04:12:14.463554Z I i.q.c.l.t.LineTcpMeasurementScheduler active table going idle [tableName=weather3]
2022-11-11T04:12:14.5275954Z 2022-11-11T04:12:14.463567Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2022-11-11T04:12:14.153000Z[tableName=weather3]
2022-11-11T04:12:14.5278033Z 2022-11-11T04:12:14.464935Z I i.q.c.TableWriter sorted [table=weather3, o3RowCount=0]
2022-11-11T04:12:14.5281222Z 2022-11-11T04:12:14.464961Z I i.q.c.TableWriter o3 partition task [table=weather3, srcOooLo=0, srcOooHi=42, srcOooMax=43, o3RowCount=43, o3LagRowCount=0, srcDataMax=0, o3TimestampMin=2016-06-13T17:43:50.102303Z, o3Timestamp=2016-06-13T17:43:50.102303Z, o3TimestampMax=2016-06-13T17:43:50.102491Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=0, partitionSize=43, maxTimestamp=, last=true, append=true, pCount=1, flattenTimestamp=true, memUsed=1309366437]
2022-11-11T04:12:14.5287166Z 2022-11-11T04:12:14.465323Z I i.q.c.p.WriterPool << [table=`weather3`, thread=3973]
2022-11-11T04:12:14.5291340Z 2022-11-11T04:12:14.465366Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=3, tableName=weather1, nNetworkIoWorkers=0]
2022-11-11T04:12:14.5292599Z 2022-11-11T04:12:14.465369Z I i.q.c.l.t.LineTcpMeasurementScheduler active table going idle [tableName=weather1]
2022-11-11T04:12:14.5293807Z 2022-11-11T04:12:14.465378Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=3, tableName=weather2, nNetworkIoWorkers=0]
2022-11-11T04:12:14.5295077Z 2022-11-11T04:12:14.465380Z I i.q.c.l.t.LineTcpMeasurementScheduler active table going idle [tableName=weather2]
2022-11-11T04:12:14.5296114Z 2022-11-11T04:12:14.465387Z I i.q.c.l.t.TableUpdateDetails network IO thread released table [workerId=3, tableName=weather0, nNetworkIoWorkers=0]
2022-11-11T04:12:14.5297850Z 2022-11-11T04:12:14.465389Z I i.q.c.l.t.LineTcpMeasurementScheduler active table going idle [tableName=weather0]
2022-11-11T04:12:14.5300036Z 2022-11-11T04:12:14.465431Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2022-11-11T04:12:14.153000Z[tableName=weather1]
2022-11-11T04:12:14.5302396Z 2022-11-11T04:12:14.466626Z I i.q.c.TableWriter sorted [table=weather1, o3RowCount=0]
2022-11-11T04:12:14.5305353Z 2022-11-11T04:12:14.466640Z I i.q.c.TableWriter o3 partition task [table=weather1, srcOooLo=0, srcOooHi=47, srcOooMax=48, o3RowCount=48, o3LagRowCount=0, srcDataMax=0, o3TimestampMin=2016-06-13T17:43:50.102304Z, o3Timestamp=2016-06-13T17:43:50.102304Z, o3TimestampMax=2016-06-13T17:43:50.102500Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=0, partitionSize=48, maxTimestamp=, last=true, append=true, pCount=1, flattenTimestamp=true, memUsed=1384864165]
2022-11-11T04:12:14.5310063Z 2022-11-11T04:12:14.466861Z I i.q.c.p.WriterPool << [table=`weather1`, thread=3971]
2022-11-11T04:12:14.5312057Z 2022-11-11T04:12:14.466873Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2022-11-11T04:12:14.153000Z[tableName=weather0]
2022-11-11T04:12:14.5314427Z 2022-11-11T04:12:14.467515Z I i.q.c.TableWriter sorted [table=weather0, o3RowCount=0]
2022-11-11T04:12:14.5317384Z 2022-11-11T04:12:14.467524Z I i.q.c.TableWriter o3 partition task [table=weather0, srcOooLo=0, srcOooHi=40, srcOooMax=41, o3RowCount=41, o3LagRowCount=0, srcDataMax=0, o3TimestampMin=2016-06-13T17:43:50.102314Z, o3Timestamp=2016-06-13T17:43:50.102314Z, o3TimestampMax=2016-06-13T17:43:50.102498Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=0, partitionSize=41, maxTimestamp=, last=true, append=true, pCount=1, flattenTimestamp=true, memUsed=1460362149]
2022-11-11T04:12:14.5322124Z 2022-11-11T04:12:14.467668Z I i.q.c.p.WriterPool << [table=`weather0`, thread=3971]
2022-11-11T04:12:14.5324112Z 2022-11-11T04:12:14.467728Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2022-11-11T04:12:14.153000Z[tableName=weather4]
2022-11-11T04:12:14.5326821Z 2022-11-11T04:12:14.468368Z I i.q.c.TableWriter sorted [table=weather4, o3RowCount=0]
2022-11-11T04:12:14.5329816Z 2022-11-11T04:12:14.468379Z I i.q.c.TableWriter o3 partition task [table=weather4, srcOooLo=0, srcOooHi=28, srcOooMax=29, o3RowCount=29, o3LagRowCount=0, srcDataMax=0, o3TimestampMin=2016-06-13T17:43:50.102301Z, o3Timestamp=2016-06-13T17:43:50.102301Z, o3TimestampMax=2016-06-13T17:43:50.102494Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=0, partitionSize=29, maxTimestamp=, last=true, append=true, pCount=1, flattenTimestamp=true, memUsed=1535859877]
2022-11-11T04:12:14.5334517Z 2022-11-11T04:12:14.468528Z I i.q.c.p.WriterPool << [table=`weather4`, thread=3970]
2022-11-11T04:12:14.5336588Z 2022-11-11T04:12:14.481328Z I i.q.c.p.AbstractMultiTenantPool open 'weather0' [at=0:0]
2022-11-11T04:12:14.5338662Z 2022-11-11T04:12:14.481582Z I i.q.c.l.t.LineTcpReceiverUpdateFuzzTest table.getName(): weather0, tableName: weather0, table.size(): 41, reader.size(): 41
2022-11-11T04:12:14.5340900Z 2022-11-11T04:12:14.481638Z I i.q.c.p.AbstractMultiTenantPool open 'weather1' [at=0:0]
2022-11-11T04:12:14.5342953Z 2022-11-11T04:12:14.481741Z I i.q.c.l.t.LineTcpReceiverUpdateFuzzTest table.getName(): weather1, tableName: weather1, table.size(): 48, reader.size(): 48
2022-11-11T04:12:14.6444235Z 2022-11-11T04:12:14.562416Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2022-11-11T04:12:14.153000Z[tableName=weather2]
2022-11-11T04:12:14.6447064Z 2022-11-11T04:12:14.563195Z I i.q.c.TableWriter sorted [table=weather2, o3RowCount=0]
2022-11-11T04:12:14.6449773Z 2022-11-11T04:12:14.563216Z I i.q.c.TableWriter o3 partition task [table=weather2, srcOooLo=0, srcOooHi=38, srcOooMax=39, o3RowCount=39, o3LagRowCount=0, srcDataMax=0, o3TimestampMin=2016-06-13T17:43:50.102306Z, o3Timestamp=2016-06-13T17:43:50.102306Z, o3TimestampMax=2016-06-13T17:43:50.102490Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=0, partitionSize=39, maxTimestamp=, last=true, append=true, pCount=1, flattenTimestamp=true, memUsed=1611407925]
2022-11-11T04:12:14.6452115Z 2022-11-11T04:12:14.563476Z I i.q.c.p.WriterPool << [table=`weather2`, thread=3972]
2022-11-11T04:12:14.6453402Z 2022-11-11T04:12:14.563550Z I i.q.c.p.AbstractMultiTenantPool open 'weather2' [at=0:0]
2022-11-11T04:12:14.6454849Z 2022-11-11T04:12:14.563761Z I i.q.c.l.t.LineTcpReceiverUpdateFuzzTest table.getName(): weather2, tableName: weather2, table.size(): 39, reader.size(): 39
2022-11-11T04:12:14.6456267Z 2022-11-11T04:12:14.563881Z I i.q.c.p.AbstractMultiTenantPool open 'weather3' [at=0:0]
2022-11-11T04:12:14.6457717Z 2022-11-11T04:12:14.563990Z I i.q.c.l.t.LineTcpReceiverUpdateFuzzTest table.getName(): weather3, tableName: weather3, table.size(): 43, reader.size(): 43
2022-11-11T04:12:14.6459254Z 2022-11-11T04:12:14.564055Z I i.q.c.l.t.LineTcpReceiverUpdateFuzzTest table.getName(): weather4, tableName: weather4, table.size(): 29, reader.size(): 29


### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
Full log:

[65.txt.zip](https://github.com/questdb/questdb/files/9988989/65.txt.zip)

**Comment by glasstiger** [comment]
When a table is created CairoEngine locks the table as:
```
        writerPool.lock(tableName, lockReason);
        readerPool.lock(tableName);
        metadataPool.lock(tableName);
```
When the table is ready for use the locks are released as:
```
        readerPool.unlock(tableName);
        writerPool.unlock(tableName, writer, newTable);
        metadataPool.unlock(tableName);
```

When the test detects an EV_UNLOCKED event published by SRC_WRITER (TableWriter in this case) it considers the table ready for UPDATE.
Looking at the above unlock order it is clear that metadata can be still locked after a writer unlock event, hence the possibility of getting EntryLockedException from the metadata pool when UPDATE runs on a table just created by ILP.
Instead the test should wait for an EV_UNLOCKED event published by SRC_METADATA so we can be sure everything is released before we start the UPDATE.

Relevant section from log:
```
2022-11-11T04:12:14.0042918Z 2022-11-11T04:12:14.003092Z I i.q.c.CairoEngine locked [table=`weather4`, thread=3973]
2022-11-11T04:12:14.0098210Z 2022-11-11T04:12:14.009335Z I i.q.c.p.WriterPool created [table=`weather4`, thread=3973]
2022-11-11T04:12:14.0099857Z 2022-11-11T04:12:14.009378Z I i.q.c.TableWriter open 'weather4'
2022-11-11T04:12:14.0119966Z 2022-11-11T04:12:14.011667Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/junit15087144222600271481/dbRoot/weather4]
2022-11-11T04:12:14.0169188Z Exception in thread "Thread-3445" java.lang.AssertionError: Update failed [e=io.questdb.cairo.pool.ex.EntryLockedException: [-1] table busy [reason=unknown], sql=update "weather4" set temperature=5258.0 where timestamp='2016-06-13T17:43:50.102349']
2022-11-11T04:12:14.0173615Z 	at org.junit.Assert.fail(Assert.java:89)
2022-11-11T04:12:14.0174852Z 	at io.questdb.cutlass.line.tcp.LineTcpReceiverUpdateFuzzTest.lambda$startUpdateThread$0(LineTcpReceiverUpdateFuzzTest.java:197)
2022-11-11T04:12:14.0176737Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-11T04:12:14.0178085Z 2022-11-11T04:12:14.014315Z I i.q.c.p.AbstractMultiTenantPool open 'weather4' [at=0:0]
2022-11-11T04:12:14.0179593Z 2022-11-11T04:12:14.014870Z I i.q.c.l.t.LineTcpReceiverUpdateFuzzTest update "weather4" set temperature=5258.0 where timestamp='2016-06-13T17:43:50.102349'
2022-11-11T04:12:14.0181944Z 2022-11-11T04:12:14.015083Z I i.q.c.p.AbstractMultiTenantPool 'weather4' is locked [owner=3973]
2022-11-11T04:12:14.0183190Z 2022-11-11T04:12:14.015261Z I i.q.c.p.WriterPool >> [table=`weather4`, thread=3975]
2022-11-11T04:12:14.0184240Z 2022-11-11T04:12:14.015284Z I i.q.c.p.WriterPool << [table=`weather4`, thread=3975]
2022-11-11T04:12:14.0185322Z 2022-11-11T04:12:14.015297Z I i.q.c.p.AbstractMultiTenantPool 'weather4' is locked [owner=3973]
2022-11-11T04:12:14.0186390Z 2022-11-11T04:12:14.017033Z I i.q.c.CairoEngine unlocked [table=`weather4`]
2022-11-11T04:12:14.0187430Z 2022-11-11T04:12:14.017381Z I i.q.c.p.WriterPool >> [table=`weather4`, thread=3973]
```
