### ISSUE TITLE
NullPointerException upon shutdown/restart

### ISSUE THREAD

**Issue by Va1** [questdb/questdb#2777]
### Describe the bug

We are using QuestDB for ingesting quite big amounts of data in realtime (via ILP) and noticed that every time we restart the instance, pretty much every time before stopping it outputs series of NullPointerException stack traces of its worker threads.

So I am reporting this and asking two questions:
1. is this behaviour OK? (does not seem so, tbh)
2. how do we prevent this behaviour? (perhaps, there's a way to shut it down even more gracefully by running some command in the container or smth?)

Logs:
```
Tue Nov 15 12:03:56 UTC 2022 QuestDB is shutting down
Pre-touch magic number: 0
Exception in thread "questdb-worker-8" java.lang.NullPointerException: Cannot invoke "io.questdb.std.ThreadLocal.get()" because "io.questdb.cutlass.http.processors.QueryCache.TL_QUERY_CACHE" is null
      at io.questdb@6.5.3/io.questdb.cutlass.http.processors.QueryCache.getInstance(QueryCache.java:58)
      at io.questdb@6.5.3/io.questdb.cutlass.http.HttpServer.lambda$new$0(HttpServer.java:120)
      at io.questdb@6.5.3/io.questdb.std.Misc.free(Misc.java:46)
      at io.questdb@6.5.3/io.questdb.mp.WorkerPool.lambda$start$0(WorkerPool.java:158)
      at io.questdb@6.5.3/io.questdb.mp.Worker.run(Worker.java:155)
Exception in thread "questdb-worker-5" java.lang.NullPointerException: Cannot invoke "io.questdb.std.ThreadLocal.get()" because "io.questdb.cutlass.http.processors.QueryCache.TL_QUERY_CACHE" is null
      at io.questdb@6.5.3/io.questdb.cutlass.http.processors.QueryCache.getInstance(QueryCache.java:58)
      at io.questdb@6.5.3/io.questdb.cutlass.http.HttpServer.lambda$new$0(HttpServer.java:120)
      at io.questdb@6.5.3/io.questdb.std.Misc.free(Misc.java:46)
      at io.questdb@6.5.3/io.questdb.mp.WorkerPool.lambda$start$0(WorkerPool.java:158)
      at io.questdb@6.5.3/io.questdb.mp.Worker.run(Worker.java:155)
Exception in thread "questdb-worker-4" java.lang.NullPointerException: Cannot invoke "io.questdb.std.ThreadLocal.get()" because "io.questdb.cutlass.http.processors.QueryCache.TL_QUERY_CACHE" is null
      at io.questdb@6.5.3/io.questdb.cutlass.http.processors.QueryCache.getInstance(QueryCache.java:58)
      at io.questdb@6.5.3/io.questdb.cutlass.http.HttpServer.lambda$new$0(HttpServer.java:120)
      at io.questdb@6.5.3/io.questdb.std.Misc.free(Misc.java:46)
      at io.questdb@6.5.3/io.questdb.mp.WorkerPool.lambda$start$0(WorkerPool.java:158)
      at io.questdb@6.5.3/io.questdb.mp.Worker.run(Worker.java:155)
Exception in thread "questdb-worker-9" java.lang.NullPointerException: Cannot invoke "io.questdb.std.ThreadLocal.get()" because "io.questdb.cutlass.http.processors.QueryCache.TL_QUERY_CACHE" is null
      at io.questdb@6.5.3/io.questdb.cutlass.http.processors.QueryCache.getInstance(QueryCache.java:58)
      at io.questdb@6.5.3/io.questdb.cutlass.http.HttpServer.lambda$new$0(HttpServer.java:120)
      at io.questdb@6.5.3/io.questdb.std.Misc.free(Misc.java:46)
      at io.questdb@6.5.3/io.questdb.mp.WorkerPool.lambda$start$0(WorkerPool.java:158)
      at io.questdb@6.5.3/io.questdb.mp.Worker.run(Worker.java:155)
Exception in thread "questdb-worker-7" java.lang.NullPointerException: Cannot invoke "io.questdb.std.ThreadLocal.get()" because "io.questdb.cutlass.http.processors.QueryCache.TL_QUERY_CACHE" is null
      at io.questdb@6.5.3/io.questdb.cutlass.http.processors.QueryCache.getInstance(QueryCache.java:58)
      at io.questdb@6.5.3/io.questdb.cutlass.http.HttpServer.lambda$new$0(HttpServer.java:120)
      at io.questdb@6.5.3/io.questdb.std.Misc.free(Misc.java:46)
      at io.questdb@6.5.3/io.questdb.mp.WorkerPool.lambda$start$0(WorkerPool.java:158)
      at io.questdb@6.5.3/io.questdb.mp.Worker.run(Worker.java:155)
Exception in thread "questdb-worker-6" java.lang.NullPointerException: Cannot invoke "io.questdb.std.ThreadLocal.get()" because "io.questdb.cutlass.http.processors.QueryCache.TL_QUERY_CACHE" is null
      at io.questdb@6.5.3/io.questdb.cutlass.http.processors.QueryCache.getInstance(QueryCache.java:58)
      at io.questdb@6.5.3/io.questdb.cutlass.http.HttpServer.lambda$new$0(HttpServer.java:120)
      at io.questdb@6.5.3/io.questdb.std.Misc.free(Misc.java:46)
      at io.questdb@6.5.3/io.questdb.mp.WorkerPool.lambda$start$0(WorkerPool.java:158)
      at io.questdb@6.5.3/io.questdb.mp.Worker.run(Worker.java:155)
Exception in thread "questdb-worker-3" java.lang.NullPointerException: Cannot invoke "io.questdb.std.ThreadLocal.get()" because "io.questdb.cutlass.http.processors.QueryCache.TL_QUERY_CACHE" is null
      at io.questdb@6.5.3/io.questdb.cutlass.http.processors.QueryCache.getInstance(QueryCache.java:58)
      at io.questdb@6.5.3/io.questdb.cutlass.http.HttpServer.lambda$new$0(HttpServer.java:120)
      at io.questdb@6.5.3/io.questdb.std.Misc.free(Misc.java:46)
      at io.questdb@6.5.3/io.questdb.mp.WorkerPool.lambda$start$0(WorkerPool.java:158)
      at io.questdb@6.5.3/io.questdb.mp.Worker.run(Worker.java:155)
```

### To reproduce

Run QuestDB (in Kubernetes via an official Helm chart) and continuously stream data via ILP, then restart the K8S StatefulSet. Stopping K8S Pod will log the errors like I attached above.

### Expected Behavior

I expect QuestDB to not log, nor experience errors / exceptions when gracefully shutting down, even if there are open connections.

### Environment

- **QuestDB version**: 6.5.3
- **QuestDB official chart version**: 0.22.0
- **QuestDB image**: questdb/questdb:6.5.3

**Comment by bluestreak01** [comment]
This looks like a bug to me, which we will need to investigate. It looks harmless to the data, e.g. seems a SQL execution via REST triggers this.

**Comment by Va1** [comment]
@bluestreak01 yeah, the data is fine as far as i can tell.

> seems a SQL execution via REST triggers this

what do you mean by this?

**Comment by bluestreak01** [comment]
Thank you for clarifying that HTTP is disabled, it helped.

We should be enable to release the fix tomorrow.
