### ISSUE TITLE
error when parsing a query with an empty string

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2835]
### Describe the bug

Run this query: `select '' from long_sequence(1);`

The web console shows `An error occured, please try again` and this is in the log:
```
2022-11-29T16:43:44.532868Z C i.q.c.h.p.JsonQueryProcessorState [31] Uh-oh. Error!
java.lang.AssertionError
        at io.questdb.std.GenericLexer$FloatingSequence._subSequence(GenericLexer.java:508)
        at io.questdb.std.str.AbstractCharSequence.subSequence(AbstractCharSequence.java:60)
        at io.questdb.std.GenericLexer.unquote(GenericLexer.java:109)
        at io.questdb.griffin.SqlParser.createColumnAlias(SqlParser.java:160)
        at io.questdb.griffin.SqlParser.parseSelectClause(SqlParser.java:1577)
        at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:861)
        at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:788)
        at io.questdb.griffin.SqlParser.parseSelect(SqlParser.java:1468)
        at io.questdb.griffin.SqlParser.parse(SqlParser.java:2083)
        at io.questdb.griffin.SqlCompiler.compileExecutionModel(SqlCompiler.java:1109)
        at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1193)
        at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1146)
        at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:265)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:348)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:182)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:229)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:574)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:192)
        at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:85)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:169)
        at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:100)
        at io.questdb.mp.Worker.run(Worker.java:118)
```

As a user I'd expect an empty string to be selected. This also means an empty string cannot be inserted into a string column,  etc. 

### Environment

```markdown
- **QuestDB version**: 6.6.1
```

**Comment by bziobrowski** [comment]
It seems that PR disables empty quoted id validation as a side effect . 

select "" from long_sequence(1)  ;
triggers 
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.StringLatin1.charAt(StringLatin1.java:48)
        at java.lang.String.charAt(String.java:1512)
        at io.questdb.griffin.ExpressionParser.parseExpr(ExpressionParser.java:1236)
        at io.questdb.griffin.SqlParser.expr(SqlParser.java:2061)
        at io.questdb.griffin.SqlParser.parseSelectClause(SqlParser.java:1498)
        at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:858)
        at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:785)
        at io.questdb.griffin.SqlParser.parseSelect(SqlParser.java:1465)
        at io.questdb.griffin.SqlParser.parse(SqlParser.java:2080)
        at io.questdb.griffin.SqlCompiler.compileExecutionModel(SqlCompiler.java:1109)
        at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1193)
        at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1146)
        at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:265)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:348)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:182)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:229)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:573)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:192)
        at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:85)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:169)
        at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:100)
        at io.questdb.mp.Worker.run(Worker.java:118)
        
but on demo it returns 'Invalid column:' error . Will double check on latest master in a moment .
