### ISSUE TITLE
Flaky IODispatcherTest.testJsonQueryTimeoutResetOnEachQuery

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2941]
### Describe the bug

Occurred on linux-other:
```
2023-01-20T11:56:02.3168825Z Failed tests: 
2023-01-20T11:56:02.3169869Z   IODispatcherTest.testJsonQueryTimeoutResetOnEachQuery:4505->lambda$testJsonQueryTimeoutResetOnEachQuery$33:4510 'HTTP/1.1 400 Bad request
2023-01-20T11:56:02.3170944Z Server: questDB/1.0
2023-01-20T11:56:02.3171365Z Date: Thu, 1 Jan 1970 00:00:00 GMT
2023-01-20T11:56:02.3171868Z Transfer-Encoding: chunked
2023-01-20T11:56:02.3172404Z Content-Type: application/json; charset=utf-8
2023-01-20T11:56:02.3173074Z Keep-Alive: timeout=5, max=10000
2023-01-20T11:56:02.3173305Z 
2023-01-20T11:56:02.3173590Z 83
2023-01-20T11:56:02.3175659Z {"query":"select i, avg(l), max(l) from t group by i order by i asc limit 3","error":"timeout, query aborted [fd=36]","position":0}
2023-01-20T11:56:02.3177865Z 00
2023-01-20T11:56:02.3178242Z 
2023-01-20T11:56:02.3178699Z ' does not contain: HTTP/1.1 200 OK
2023-01-20T11:56:02.3179129Z Server: questDB/1.0
2023-01-20T11:56:02.3179700Z Date: Thu, 1 Jan 1970 00:00:00 GMT
2023-01-20T11:56:02.3180518Z Transfer-Encoding: chunked
2023-01-20T11:56:02.3182216Z Content-Type: application/json; charset=utf-8
2023-01-20T11:56:02.3182784Z Keep-Alive: timeout=5, max=10000
2023-01-20T11:56:02.3183558Z 
2023-01-20T11:56:02.3183900Z ea
2023-01-20T11:56:02.3184647Z {"query":"select i, avg(l), max(l) from t group by i order by i asc limit 3","columns":[{"name":"i","type":"INT"},{"name":"avg","type":"DOUBLE"},{"name":"max","type":"LONG"}],"dataset":[[0,55.0,100],[1,46.0,91],[2,47.0,92]],"count":3}
2023-01-20T11:56:02.3186185Z 00
2023-01-20T11:56:02.3186335Z 
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by jerrinot** [comment]
another [failure](https://dev.azure.com/questdb/questdb/_build/results?buildId=17070&view=logs&s=b1ea3234-5a2e-5e99-b54b-09a630ee02b3&j=2a8db746-6336-53bd-306b-3f5b3836e6eb), on windows-other:
```
2023-03-30T08:03:03.6765817Z 2023-03-30T08:03:03.656277Z I i.q.t.TestListener >>>> io.questdb.test.cutlass.http.IODispatcherTest.testJsonQueryTimeoutResetOnEachQuery
2023-03-30T08:03:03.6766931Z 2023-03-30T08:03:03.656794Z I i.q.t.c.h.IODispatcherTest os scheduled worker stopped [name=questdb-testing-105]
2023-03-30T08:03:03.6768072Z 2023-03-30T08:03:03.663549Z I i.q.c.t.t.InputFormatConfiguration loading input format config [resource=/text_loader.json]
2023-03-30T08:03:03.6769390Z 2023-03-30T08:03:03.670599Z I i.q.c.m.EngineMigration upgrading database [version=427]
2023-03-30T08:03:03.6770365Z 2023-03-30T08:03:03.670760Z I i.q.c.m.EngineMigration upgraded tables to 427
2023-03-30T08:03:03.8159015Z 2023-03-30T08:03:03.800009Z I i.q.c.TableUtils locked 'C:\Users\VSSADM~1\AppData\Local\Temp\junit7384983530154255092\tables.d.lock' [fd=2044]
2023-03-30T08:03:03.8163266Z 2023-03-30T08:03:03.800707Z I i.q.c.TableNameRegistryFileStore reloading tables file [path=C:\Users\VSSADM~1\AppData\Local\Temp\junit7384983530154255092\tables.d.0]
2023-03-30T08:03:03.8164631Z 2023-03-30T08:03:03.801539Z A IODispatcher listening on 0.0.0.0:9001 [fd=1752 backlog=64]
2023-03-30T08:03:03.8165775Z 2023-03-30T08:03:03.803945Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2023-03-30T08:03:03.8166838Z 2023-03-30T08:03:03.810502Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2023-03-30T08:03:03.8167931Z 2023-03-30T08:03:03.815871Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2023-03-30T08:03:03.8193437Z 2023-03-30T08:03:03.818980Z I i.q.t.c.h.HttpQueryTestBuilder worker pool started [pool=testing]
2023-03-30T08:03:03.8203158Z 2023-03-30T08:03:03.819665Z I i.q.t.c.h.HttpQueryTestBuilder os scheduled worker started [name=questdb-testing-106]
2023-03-30T08:03:03.8216294Z 2023-03-30T08:03:03.821295Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2023-03-30T08:03:03.8284564Z 2023-03-30T08:03:03.827918Z I i.q.c.TableUtils locked 'C:\Users\VSSADM~1\AppData\Local\Temp\junit7384983530154255092\t.lock' [fd=1844]
2023-03-30T08:03:03.8286009Z 2023-03-30T08:03:03.827969Z I i.q.c.CairoEngine locked [table=`t`, thread=298]
2023-03-30T08:03:03.8324812Z 2023-03-30T08:03:03.832123Z I i.q.c.TableWriter open 't'
2023-03-30T08:03:03.8784150Z 2023-03-30T08:03:03.862394Z I i.q.c.TableWriter switched partition [path='C:\Users\VSSADM~1\AppData\Local\Temp\junit7384983530154255092\t\default']
2023-03-30T08:03:03.8793082Z 2023-03-30T08:03:03.863695Z I i.q.c.CairoEngine unlocked [table=`t`]
2023-03-30T08:03:03.8794843Z 2023-03-30T08:03:03.878078Z I IODispatcher connected [ip=127.0.0.1, fd=1940]
2023-03-30T08:03:03.8796167Z 2023-03-30T08:03:03.878275Z I i.q.c.h.p.JsonQueryProcessorState [1940] exec [q='select i, avg(l), max(l) from t group by i order by i asc limit 3']
2023-03-30T08:03:03.8797636Z 2023-03-30T08:03:03.878292Z I i.q.c.h.p.QueryCache miss [thread=questdb-testing-106, sql=select i, avg(l), max(l) from t group by i order by i asc limit 3]
2023-03-30T08:03:03.8798933Z 2023-03-30T08:03:03.879023Z I i.q.c.p.ReaderPool open 't' [at=0:0]
2023-03-30T08:03:03.8805770Z 2023-03-30T08:03:03.880232Z I i.q.g.SqlCompiler plan [q=`select-group-by i, avg(l) avg, max(l) max from (select [i, l] from t) order by i limit 3`, fd=1940]
2023-03-30T08:03:04.1014375Z 2023-03-30T08:03:04.087488Z I i.q.c.h.p.JsonQueryProcessorState [1940] execute-new [skip: 0, stop: 9223372036854775807]
2023-03-30T08:03:04.1016691Z 2023-03-30T08:03:04.089608Z I i.q.c.TableReader open partition C:\Users\VSSADM~1\AppData\Local\Temp\junit7384983530154255092\t\default [rowCount=100, partitionNameTxn=-1, transientRowCount=100, partitionIndex=0, partitionCount=1]
2023-03-30T08:03:04.1020642Z 2023-03-30T08:03:04.090728Z I i.q.c.h.p.JsonQueryProcessorState [1940] query cancelled [q=`select i, avg(l), max(l) from t group by i order by i asc limit 3`, reason=`timeout, query aborted [fd=1940]`]
2023-03-30T08:03:04.1022357Z 2023-03-30T08:03:04.090778Z I i.q.c.h.HttpConnectionContext kicked out [fd=1940]
2023-03-30T08:03:04.1023497Z 2023-03-30T08:03:04.090824Z I IODispatcher scheduling disconnect [fd=1940, reason=5]
2023-03-30T08:03:04.1024587Z 2023-03-30T08:03:04.090841Z I IODispatcher disconnected [ip=127.0.0.1, fd=1940, src=queue]
2023-03-30T08:03:04.1025674Z 2023-03-30T08:03:04.090912Z E i.q.t.c.h.SendAndReceiveRequestBuilder server disconnected
2023-03-30T08:03:04.1027512Z 2023-03-30T08:03:04.091652Z I i.q.c.h.p.QueryCache closed
2023-03-30T08:03:04.1043796Z 2023-03-30T08:03:04.091658Z I i.q.t.c.h.HttpQueryTestBuilder cleaned worker [name=testing, worker=0, total=1]
2023-03-30T08:03:04.1044987Z 2023-03-30T08:03:04.091745Z I IODispatcher closed
2023-03-30T08:03:04.1045988Z 2023-03-30T08:03:04.093380Z I i.q.c.TableWriter closed 't'
2023-03-30T08:03:04.1047053Z 2023-03-30T08:03:04.093386Z I i.q.c.p.WriterPool closed [table=`t`, reason=POOL_CLOSED, by=298]
2023-03-30T08:03:04.1052987Z 2023-03-30T08:03:04.093396Z I i.q.c.p.WriterPool closed
2023-03-30T08:03:04.1054378Z 2023-03-30T08:03:04.093808Z I i.q.c.p.ReaderPool closed 't' [at=0:0, reason=POOL_CLOSED]
2023-03-30T08:03:04.1055536Z 2023-03-30T08:03:04.093814Z I i.q.c.p.ReaderPool closed
2023-03-30T08:03:04.1056536Z 2023-03-30T08:03:04.093819Z I i.q.c.p.MetadataPool closed
2023-03-30T08:03:04.1057540Z 2023-03-30T08:03:04.093821Z I i.q.c.p.WalWriterPool closed
2023-03-30T08:03:04.1059316Z 2023-03-30T08:03:04.097376Z I i.q.t.c.h.HttpQueryTestBuilder os scheduled worker stopped [name=questdb-testing-106]
2023-03-30T08:03:04.1716044Z 2023-03-30T08:03:04.106545Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.cutlass.http.IODispatcherTest.testJsonQueryTimeoutResetOnEachQuery : 
2023-03-30T08:03:04.1717006Z org.junit.ComparisonFailure: Server disconnected expected:<...meout=5, max=10000
2023-03-30T08:03:04.1717385Z [
2023-03-30T08:03:04.1717626Z f9
2023-03-30T08:03:04.1719366Z {"query":"select i, avg(l), max(l) from t group by i order by i asc limit 3","columns":[{"name":"i","type":"INT"},{"name":"avg","type":"DOUBLE"},{"name":"max","type":"LONG"}],"dataset":[[0,55.0,100],[1,46.0,91],[2,47.0,92]],"timestamp":-1,"count":3}
2023-03-30T08:03:04.1721202Z 00
2023-03-30T08:03:04.1721978Z ]> but was:<...meout=5, max=10000
2023-03-30T08:03:04.1722719Z []>
2023-03-30T08:03:04.1723479Z 	at org.junit.Assert.assertEquals(Assert.java:117)
2023-03-30T08:03:04.1725057Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:387)
2023-03-30T08:03:04.1726199Z 	at io.questdb.test.cutlass.http.SendAndReceiveRequestBuilder.executeExplicit(SendAndReceiveRequestBuilder.java:199)
2023-03-30T08:03:04.1727218Z 	at io.questdb.test.cutlass.http.SendAndReceiveRequestBuilder.executeWithSocket(SendAndReceiveRequestBuilder.java:383)
2023-03-30T08:03:04.1728271Z 	at io.questdb.test.cutlass.http.SendAndReceiveRequestBuilder.execute(SendAndReceiveRequestBuilder.java:111)
2023-03-30T08:03:04.1729285Z 	at io.questdb.test.cutlass.http.SendAndReceiveRequestBuilder.executeWithStandardHeaders(SendAndReceiveRequestBuilder.java:323)
2023-03-30T08:03:04.1730290Z 	at io.questdb.test.cutlass.http.IODispatcherTest.lambda$testJsonQueryTimeoutResetOnEachQuery$33(IODispatcherTest.java:4599)
2023-03-30T08:03:04.1731755Z 	at io.questdb.test.cutlass.http.HttpQueryTestBuilder.lambda$run$0(HttpQueryTestBuilder.java:250)
2023-03-30T08:03:04.1732949Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:555)
2023-03-30T08:03:04.1733887Z 	at io.questdb.test.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:84)
2023-03-30T08:03:04.1816352Z 	at io.questdb.test.cutlass.http.HttpQueryTestBuilder.run(HttpQueryTestBuilder.java:80)
2023-03-30T08:03:04.1824271Z 	at io.questdb.test.cutlass.http.IODispatcherTest.testJsonQueryTimeoutResetOnEachQuery(IODispatcherTest.java:4592)
2023-03-30T08:03:04.1825420Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-30T08:03:04.1826348Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-03-30T08:03:04.1827329Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-30T08:03:04.1828200Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2023-03-30T08:03:04.1829068Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-03-30T08:03:04.1829993Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-03-30T08:03:04.1830902Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-03-30T08:03:04.1832855Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-03-30T08:03:04.1833948Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2023-03-30T08:03:04.1834851Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2023-03-30T08:03:04.1866027Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2023-03-30T08:03:04.1867994Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2023-03-30T08:03:04.1869128Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-03-30T08:03:04.1869974Z 	at java.lang.Thread.run(Thread.java:829)
2023-03-30T08:03:04.1871280Z 2023-03-30T08:03:04.106857Z I i.q.t.TestListener <<<< io.questdb.test.cutlass.http.IODispatcherTest.testJsonQueryTimeoutResetOnEachQuery
```

**Comment by irufus** [comment]
I encountered this too while running mvn test as well
