### ISSUE TITLE
Multiple LT JOINs error on SYMBOL column

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#2976]
### Describe the bug

on this table:
```
CREATE TABLE 'tests' (
  Ticker SYMBOL capacity 256 CACHE,
  H FLOAT,
  P_T FLOAT,
  timestamp TIMESTAMP
) timestamp (timestamp) PARTITION BY MONTH;
```
After inserting data, calling from webui:
`tests LT JOIN (tests LT JOIN (tests) ON (Ticker)) ON (Ticker)`
resulting Ticker type changes to STRING instead of SYMBOL on Ticker1
This causes further problems when adding more ON statements. In the following select:
`tests LT JOIN (tests LT JOIN (tests LT JOIN (tests)) ON (Ticker)) ON (Ticker)`
The following error message occurs:
`right side column 'Ticker1' is of unsupported type`
Which is the default error message when trying to LT JOIN ON STRING column

### To reproduce

1. Create the table as outlined in description
2. insert data
3. perform the following query:`tests LT JOIN (tests LT JOIN (tests LT JOIN (tests)) ON (Ticker)) ON (Ticker)`
4. the error should be reproduced

### Expected Behavior

The data should be returned from the query

### Environment

```markdown
- **QuestDB version**: Updated to 7 but webui still shows 6.6.1
- **OS**:  Microsoft Windows 10 Pro
- **Browser**: Google Chrome
```

### Additional context

![image](https://user-images.githubusercontent.com/79865853/217516347-49f360e8-d5a8-40f8-ae49-dad065e977cd.png)

**Comment by superichmann** [comment]
mmm another issue related to this happens when receiving data from a working query such as:
`tests LT JOIN (tests LT JOIN (tests) ON (Ticker)) ON (Ticker)`
and then wrapping it with another select such as
`SELECT *,H1-H11 FROM(tests LT JOIN (tests LT JOIN (tests) ON (Ticker)) ON (Ticker))`

an exception occurs
```
2023-02-11T23:55:39.067368Z C i.q.c.h.p.JsonQueryProcessorState [15720] Uh-oh. Error!
java.lang.NullPointerException
	at io.questdb.griffin.engine.functions.columns.SymbolColumn.getSymbol(SymbolColumn.java:72)
	at io.questdb.cairo.sql.VirtualRecord.getSym(VirtualRecord.java:193)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.putSymValue(JsonQueryProcessorState.java:374)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.doQueryRecord(JsonQueryProcessorState.java:539)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.doRecordFetchLoop(JsonQueryProcessorState.java:628)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.doFirstRecordLoop(JsonQueryProcessorState.java:431)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.onQueryPrefix(JsonQueryProcessorState.java:680)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.resume(JsonQueryProcessorState.java:815)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.doResumeSend(JsonQueryProcessor.java:285)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect(JsonQueryProcessor.java:457)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeCachedSelect(JsonQueryProcessor.java:398)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:171)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:229)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:574)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:192)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:85)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:169)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:100)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

I am guessing it is related so I drop it here.. if further info is needed I am here :)

**Comment by jerrinot** [comment]
@superichmann thanks for a very good bug report. I can reproduce the issue and I understand the root cause. let's see what we can do about it.

**Comment by superichmann** [comment]
@jerrinot any updates? ;]

**Comment by jerrinot** [comment]
@superichmann I'm toying with various approaches. One idea is to extend the `LT JOIN` syntex to (optionally) accept number of rows to join. Right now `LT JOIN` always joins a single row from the right table. So when you need to join multiple rows then you need to nest the joins. as you did. If we extend `LT JOIN` then the need to nest `LT JOIN` disappears. but I am not sure if this is worth the extra syntax and implementation complexity. still experimenting.

**Comment by superichmann** [comment]
COol! Thanks man :)

**Comment by jerrinot** [comment]
@superichmann: Thanks again for this excellent report. The fix was just merged, and the next QuestDB release will include it. It should be released ~soon~ (probably in a matter of days)

**Comment by superichmann** [comment]
Awesome @jerrinot! Just in time, I will test when its out and update if there will be any issues
