### ISSUE TITLE
Flaky WalWriterFuzzTest.testWalWriteRollbackHeavyToFix

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3076]
### Describe the bug

Occurred on linux-griffin:
```
2023-03-17T19:39:31.0306436Z io.questdb.cairo.CairoException: [0] Partition '2022-02-25' does not exist in table 'testWalWriteRollbackHeavyToFix_nonwal' directory. Run [ALTER TABLE testWalWriteRollbackHeavyToFix_nonwal DROP PARTITION LIST '2022-02-25'] to repair the table or restore the partition directory.
2023-03-17T19:39:31.0308222Z 	at io.questdb.cairo.CairoException.critical(CairoException.java:55)
2023-03-17T19:39:31.0309921Z 	at io.questdb.cairo.TableReader.openPartition0(TableReader.java:827)
2023-03-17T19:39:31.0310817Z 	at io.questdb.cairo.TableReader.openPartition(TableReader.java:370)
2023-03-17T19:39:31.0311634Z 	at io.questdb.cairo.pool.ReaderPool$R.openPartition(ReaderPool.java:120)
2023-03-17T19:39:31.0312495Z 	at io.questdb.cairo.FullFwdDataFrameCursor.next(FullFwdDataFrameCursor.java:37)
2023-03-17T19:39:31.0313444Z 	at io.questdb.griffin.engine.table.DataFrameRecordCursorImpl.hasNext(DataFrameRecordCursorImpl.java:74)
2023-03-17T19:39:31.0314347Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:149)
2023-03-17T19:39:31.0315159Z 	at io.questdb.test.tools.TestUtils.assertSqlCursors(TestUtils.java:609)
2023-03-17T19:39:31.0315977Z 	at io.questdb.test.tools.TestUtils.assertSqlCursors(TestUtils.java:601)
2023-03-17T19:39:31.0316823Z 	at io.questdb.griffin.wal.WalWriterFuzzTest.lambda$runFuzz$3(WalWriterFuzzTest.java:629)
2023-03-17T19:39:31.0317738Z 	at io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$4(AbstractCairoTest.java:276)
2023-03-17T19:39:31.0318616Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:541)
2023-03-17T19:39:31.0319457Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:273)
2023-03-17T19:39:31.0320331Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:267)
2023-03-17T19:39:31.0321195Z 	at io.questdb.griffin.wal.WalWriterFuzzTest.runFuzz(WalWriterFuzzTest.java:575)
2023-03-17T19:39:31.0322111Z 	at io.questdb.griffin.wal.WalWriterFuzzTest.testWalWriteRollbackHeavyToFix(WalWriterFuzzTest.java:178)
```

[log.zip](https://github.com/questdb/questdb/files/11005436/log.zip)

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by sonukumar00** [comment]
It appears that the error occurred during a test of the QuestDB WALWriterFuzzTest, specifically during the `testWalWriteRollbackHeavyToFix` test case. This test is designed to validate the functionality of the WAL table by writing and rolling back transactions.

Based on the stack trace provided, it seems that the error occurred when attempting to open a partition in the `TableReader`. It's possible that this issue was caused by a problem with the directory structure for the partition or with the configuration of the test
