### ISSUE TITLE
ORDER BY TIMESTAMP DESC issues / crashes

### ISSUE THREAD

**Issue by andyb-ev** [questdb/questdb#3081]
### Describe the bug

Experiencing some unexpected behavior when using `order by timestamp desc`, including result counts that do not match what I expect and sometimes causes crashes of the QuestDB server

I have attached the logs for the quest server that include the crashes.

[LOGS.zip](https://github.com/questdb/questdb/files/11031934/LOGS.zip)

### To reproduce

I have attached a Gradle project that can be run with `./gradlew runSortDescRepro`

The source code is currently (but may change as I haven't gotten the same behavior as my actual system just yet):

[test-questdb.zip](https://github.com/questdb/questdb/files/11031913/test-questdb.zip)

```
package test.questdb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.Properties;
import java.util.Random;
import java.util.Set;
import io.questdb.client.Sender;

public class QuestDbSortDescRepro {

  // edit as needed
  static final String QUESTDB_ILP_ADDRESS = "questdb:9009";
  static final String QUESTDB_QUERY_JDBC_URL = "jdbc:postgresql://questdb:8812/qdb";
  static final Properties QUESTDB_QUERY_JDBC_PROPS = new Properties();
  static {
    QUESTDB_QUERY_JDBC_PROPS.put("user", "admin");
    QUESTDB_QUERY_JDBC_PROPS.put("password", "quest");
    QUESTDB_QUERY_JDBC_PROPS.put("sslmode", "disable");
  }

  static final String TABLE = "sort-desc-repro-3";
  
  static final String COL_ID = "id";
  static final String COL_LINKED_ID = "linkedId";
  static final String COL_STR_1 = "stringCol1";
  static final String COL_STR_2 = "stringCol2";
  static final String COL_DESC = "description";
  static final String COL_ACTIVE = "active";
  static final String COL_WHEN_START = "whenStartMs";
  static final String COL_WHEN_END = "whenEndMs";
  static final String COL_DESIGNATED_TIMESTAMP = "timestamp";

  static final Random RAND = new Random(System.currentTimeMillis());

  static final String[] IDS = genStrings(16, "generated-id-");
  static final String[] LINKED_IDS = genLinkedIds(IDS);
  static final String[] STR1_VALS = genStrings(8, "STR1-");
  static final String[] STR2_VALS = genStrings(4, "STR1-");

  static long minTimeMs = 0L;

  static String[] genStrings(int n, String base) {
    String[] out = new String[n];
    for (int j = 0; j < n; j++) {
      out[j] = base + j;
    }
    return out;
  }

  static String[] genLinkedIds(String[] idsBase) {
    String[] out = new String[idsBase.length];
    for (int j = 0; j < idsBase.length; j++) {
      out[j] = "linkedId-" + idsBase[j];
    }
    return out;
  }

  static String randString(int minLen, int maxLen) {
    StringBuilder buf = new StringBuilder();
    int len = RAND.nextInt(minLen, maxLen + 1);
    for (int j = 0; j < len; j++) {
      if (minLen > 10 && RAND.nextDouble() > 0.8) {
        // sometimes append a UTF-8 character
        buf.append("ü");
      } else {
        // A-Z, a-z
        buf.append((char) (RAND.nextBoolean() ? RAND.nextInt(0x41, 0x5B) : RAND.nextInt(0x61, 0x7b)));
      }
    }
    return buf.toString();
  }

  static <T> T randValue(T[] arr) {
    return arr[RAND.nextInt(0, arr.length)];
  }

  static final String t() {
    return String.format("[%-30s] ", Instant.now().atOffset(ZoneOffset.UTC).toString());
  }

  static void log(String fmt, Object... args) {
    System.out.printf(t() + fmt + "%n", args);
  }

  static void insertRow(int row, Sender ilp, Set<Long> allTimestamps) throws Exception {
    String id = randValue(IDS);
    String linkedId = randValue(LINKED_IDS);
    String desc = randString(32, 256);
    String str1 = randValue(STR1_VALS);
    String str2 = randValue(STR2_VALS);
    boolean active = RAND.nextBoolean();
    Long whenStartMs = System.currentTimeMillis() + RAND.nextInt(1, 1 + row);
    if (row > 2000) {
      whenStartMs += 300L;
    }
    if (minTimeMs == 0L || whenStartMs < minTimeMs) {
      minTimeMs = whenStartMs;
    }
    // mostly null
    Long whenEndMs = RAND.nextDouble() > 0.9 ? whenStartMs + RAND.nextLong(1000L, 2000L) : null;
    long tsNanos = whenStartMs * 1_000_000L;
    allTimestamps.add(tsNanos);
    ilp = ilp
        .table(TABLE)
        .symbol(COL_ID, id)
        .symbol(COL_LINKED_ID, linkedId)
        .stringColumn(COL_DESC, desc)
        .stringColumn(COL_STR_1, str1)
        .stringColumn(COL_STR_2, str2)
        .boolColumn(COL_ACTIVE, active)
        .longColumn(COL_WHEN_START, whenStartMs);
    if (whenEndMs != null) {
      ilp = ilp.longColumn(COL_WHEN_END, whenEndMs);
    }
    ilp.at(tsNanos);
  }

  static void insertData(int nRows) throws Exception {
    Set<Long> allTimestamps = new HashSet<>();
    try (Sender ilp = Sender.builder().address(QUESTDB_ILP_ADDRESS).build()) {
      log("insert [%d] rows into table [" + TABLE + "] ...", nRows);
      for (int j = 1; j <= nRows; j++) {
        insertRow(j, ilp, allTimestamps);
      }
      ilp.flush();
      log("insert [%d] rows - DONE [%d] unique timestamps", nRows, allTimestamps.size());
    }
    log("wait 5s for inserted data to settle ...");
    Thread.sleep(5000L);
    log("exit insertData()");
  }

  static int getCountStar(String query) throws Exception {
    int count = -1;
    try(Connection conn = DriverManager.getConnection(QUESTDB_QUERY_JDBC_URL, QUESTDB_QUERY_JDBC_PROPS);
        PreparedStatement stmt = conn.prepareStatement(query)) {
      log(" run query [%s] ...", stmt);
      try(ResultSet result = stmt.executeQuery()) {
        if (result.next()) {
          count = result.getInt(1);
        }
      }
      log(" query [%s] completed: count:[%d]", stmt, count);
    }
    return count;
  }

  static int getRowCount(String query) throws Exception {
    int count = 0;
    try(Connection conn = DriverManager.getConnection(QUESTDB_QUERY_JDBC_URL, QUESTDB_QUERY_JDBC_PROPS);
        PreparedStatement stmt = conn.prepareStatement(query)) {
      stmt.setFetchSize(100_000);
      log(" run query [%s] ...", stmt);
      try(ResultSet result = stmt.executeQuery()) {
        while(result.next()) {
          count++;
        }
      }
    } catch(Exception e) {
      log("  %n  ##### UNEXPECTED ERROR %s #####%n", e);
      e.printStackTrace();
      return -1;
    }
    log(" query [%s] completed: count:[%d]", query, count);
    return count;
  }

  static void performQueries() throws Exception {
    DateTimeFormatter timeFormat = DateTimeFormatter.ofPattern(
        "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
    String queryTimeFilter = timeFormat.format(
        Instant.ofEpochMilli(minTimeMs - (2 * 86_400_000L) )
        .atOffset(ZoneOffset.UTC));
    String queryBase = "select * from '" + TABLE
        + "' WHERE timestamp >= '" + queryTimeFilter + "' ORDER BY " + COL_DESIGNATED_TIMESTAMP + " ";

    int countStar = getCountStar("SELECT COUNT(*) FROM '" + TABLE + "'");
    int ascCount = getRowCount(queryBase + "ASC");
    int ascLimitCount = getRowCount(queryBase + "ASC LIMIT 100000");
    int descLimitCount = getRowCount(queryBase + "DESC LIMIT 100000");
    int descCount = getRowCount(queryBase + "DESC");

    boolean allEqual = countStar == descCount
        && descCount == descLimitCount && descCount == ascCount && descCount == ascLimitCount;
    log("%n -- QUERY RESULTS -- %n"
        + "  count(*)       = [%d]%n"
        + "  descCount      = [%d]%n"
        + "  descLimitCount = [%d]%n"
        + "  ascCount       = [%d]%n"
        + "  ascLimitCount  = [%d]%n"
        + "  allEqual       = [%b]%n"
        + " -----------------%n",
        countStar, descCount, descLimitCount, ascCount, ascLimitCount, allEqual);
  }

  public static void main(String[] args) {
    int exitCode = 0;
    log("enter");
    try {
      insertData(RAND.nextInt(4096, 8192));
      log("%n performing queries ...%n%n");
      performQueries();
    } catch (Throwable t) {
      t.printStackTrace();
      exitCode = 1;
    }
    log("exit");
    System.exit(exitCode);
  }
}
```

### Expected Behavior

All query counts are equal

Actual shows that at minimum the desc limit count is usually 0 or sometimes causes an EOF error on the JDBC connection and a crash on the QuestDB server.

e.g.
```
 -- QUERY RESULTS --
  count(*)       = [35732]
  descCount      = [35732]
  descLimitCount = [0]
  ascCount       = [35732]
  ascLimitCount  = [35732]
  allEqual       = [false]
 -----------------
```

### Environment

```markdown
- **QuestDB version**: 7.0.1 - Docker Image
- **OS**: Amazon Linux
- **Browser**: N/A (Java ILP Client, JDBC Postgres Query Client)
```

**Comment by andyb-ev** [comment]
Here's a couple crashes from a single run of the repro program which may be easier to parse:

[quest-single-run-crash.log.zip](https://github.com/questdb/questdb/files/11032000/quest-single-run-crash.log.zip)

Program output was:

```
[2023-03-21T17:49:00.214106200Z] enter
Log configuration loaded from default internal file.
[2023-03-21T17:49:00.700487Z   ] insert [6769] rows into table [sort-desc-repro-1] ...
2023-03-21T17:49:00.522020Z I i.q.c.l.t.PlainTcpLineChannel Send buffer size change from 65536 to 131072
[2023-03-21T17:49:01.696406200Z] insert [6769] rows - DONE [4035] unique timestamps
[2023-03-21T17:49:01.697319Z   ] wait 5s for inserted data to settle ...
[2023-03-21T17:49:06.709170500Z] exit insertData()
[2023-03-21T17:49:06.709170500Z] 
 performing queries ...


[2023-03-21T17:49:06.944322600Z]  run query [SELECT COUNT(*) FROM 'sort-desc-repro-1'] ...
[2023-03-21T17:49:06.974166600Z]  query [SELECT COUNT(*) FROM 'sort-desc-repro-1'] completed: count:[6769]
[2023-03-21T17:49:07.041618800Z]  run query [select * from 'sort-desc-repro-1' WHERE timestamp >= '2023-03-19T17:49:00.701Z' ORDER BY timestamp ASC] ...
[2023-03-21T17:49:07.212938100Z]  query [select * from 'sort-desc-repro-1' WHERE timestamp >= '2023-03-19T17:49:00.701Z' ORDER BY timestamp ASC] completed: count:[6769]
[2023-03-21T17:49:07.267893500Z]  run query [select * from 'sort-desc-repro-1' WHERE timestamp >= '2023-03-19T17:49:00.701Z' ORDER BY timestamp ASC LIMIT 100000] ...
[2023-03-21T17:49:07.429050500Z]  query [select * from 'sort-desc-repro-1' WHERE timestamp >= '2023-03-19T17:49:00.701Z' ORDER BY timestamp ASC LIMIT 100000] completed: count:[6769]
[2023-03-21T17:49:07.505061300Z]  run query [select * from 'sort-desc-repro-1' WHERE timestamp >= '2023-03-19T17:49:00.701Z' ORDER BY timestamp DESC LIMIT 100000] ...
[2023-03-21T17:49:07.685175600Z]   
  ##### UNEXPECTED ERROR org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend. #####

org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:383)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at test.questdb.QuestDbSortDescRepro.getRowCount(QuestDbSortDescRepro.java:161)
	at test.questdb.QuestDbSortDescRepro.performQueries(QuestDbSortDescRepro.java:187)
	at test.questdb.QuestDbSortDescRepro.main(QuestDbSortDescRepro.java:209)
Caused by: java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2120)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	... 7 more
[2023-03-21T17:49:10.158623100Z]  run query [select * from 'sort-desc-repro-1' WHERE timestamp >= '2023-03-19T17:49:00.701Z' ORDER BY timestamp DESC] ...
[2023-03-21T17:49:10.381623100Z]   
  ##### UNEXPECTED ERROR org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend. #####

org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:383)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
[2023-03-21T17:49:10.381623100Z] 
 -- QUERY RESULTS -- 
  count(*)       = [6769]
  descCount      = [-1]
  descLimitCount = [-1	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at test.questdb.QuestDbSortDescRepro.getRowCount(QuestDbSortDescRepro.java:161)
	at test.questdb.QuestDbSortDescRepro.performQueries(QuestDbSortDescRepro.java:188)
	at test.questdb.QuestDbSortDescRepro.main(QuestDbSortDescRepro.java:209)
Caused by: java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:467)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2120)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	... 7 more
]
  ascCount       = [6769]
  ascLimitCount  = [6769]
  allEqual       = [false]
 -----------------

[2023-03-21T17:49:10.381623100Z] exit
```

**Comment by bluestreak01** [comment]
thank you Andy, try the repro

**Comment by andyb-ev** [comment]
Here's what I see for an `EXPLAIN` on the sort desc + limit query:

![image](https://user-images.githubusercontent.com/120592098/226703675-2a42ab84-7292-48a3-a2fa-88058f1470d4.png)

**Comment by andyb-ev** [comment]
Here's an updated version of the Repro source code that models our insertion pattern slightly more realistically (insertions continue in the background).  The query vs insertion lock is not realistic but helps ensure that the result counts should be equal or close to equal.

```
package test.questdb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.Properties;
import java.util.Random;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import io.questdb.client.Sender;

public class QuestDbSortDescRepro {

  // edit as needed
  static final String QUESTDB_ILP_ADDRESS = "questdb:9009";
  static final String QUESTDB_QUERY_JDBC_URL = "jdbc:postgresql://questdb:8812/qdb";
  static final Properties QUESTDB_QUERY_JDBC_PROPS = new Properties();
  static {
    QUESTDB_QUERY_JDBC_PROPS.put("user", "admin");
    QUESTDB_QUERY_JDBC_PROPS.put("password", "quest");
    QUESTDB_QUERY_JDBC_PROPS.put("sslmode", "disable");
  }

  static final String TABLE = "sort-desc-repro-1";

  static final String COL_ID = "id";
  static final String COL_LINKED_ID = "linkedId";
  static final String COL_STR_1 = "stringCol1";
  static final String COL_STR_2 = "stringCol2";
  static final String COL_DESC = "description";
  static final String COL_ACTIVE = "active";
  static final String COL_WHEN_START = "whenStartMs";
  static final String COL_WHEN_END = "whenEndMs";
  static final String COL_DESIGNATED_TIMESTAMP = "timestamp";

  static final Random RAND = new Random(System.currentTimeMillis());

  static final String[] IDS = genStrings(16, "generated-id-");
  static final String[] LINKED_IDS = genLinkedIds(IDS);
  static final String[] STR1_VALS = genStrings(8, "STR1-");
  static final String[] STR2_VALS = genStrings(4, "STR1-");

  static final Lock QUEST_LOCK = new ReentrantLock();
  static final AtomicBoolean EXIT = new AtomicBoolean(false);
  static long minTimeMs = 0L;

  static String[] genStrings(int n, String base) {
    String[] out = new String[n];
    for (int j = 0; j < n; j++) {
      out[j] = base + j;
    }
    return out;
  }

  static String[] genLinkedIds(String[] idsBase) {
    String[] out = new String[idsBase.length];
    for (int j = 0; j < idsBase.length; j++) {
      out[j] = "linkedId-" + idsBase[j];
    }
    return out;
  }

  static String randString(int minLen, int maxLen) {
    StringBuilder buf = new StringBuilder();
    int len = RAND.nextInt(minLen, maxLen + 1);
    for (int j = 0; j < len; j++) {
      if (minLen > 10 && RAND.nextDouble() > 0.8) {
        // sometimes append a UTF-8 character
        buf.append("ü");
      } else {
        // A-Z, a-z
        buf.append((char) (RAND.nextBoolean() ? RAND.nextInt(0x41, 0x5B) : RAND.nextInt(0x61, 0x7b)));
      }
    }
    return buf.toString();
  }

  static <T> T randValue(T[] arr) {
    return arr[RAND.nextInt(0, arr.length)];
  }

  static final String t() {
    return String.format("[%-30s] ", Instant.now().atOffset(ZoneOffset.UTC).toString());
  }

  static void log(String fmt, Object... args) {
    System.out.printf(t() + fmt + "%n", args);
  }

  static void insertRow(int row, Sender ilp, Set<Long> allTimestamps) throws Exception {
    String id = randValue(IDS);
    String linkedId = randValue(LINKED_IDS);
    String desc = randString(32, 256);
    String str1 = randValue(STR1_VALS);
    String str2 = randValue(STR2_VALS);
    boolean active = RAND.nextBoolean();
    Long whenStartMs = System.currentTimeMillis() + RAND.nextInt(1, Math.max(2, row/2));
    if (row > 2000) {
      whenStartMs += 300L;
    }
    if (minTimeMs == 0L || whenStartMs < minTimeMs) {
      minTimeMs = whenStartMs;
    }
    // mostly null
    Long whenEndMs = RAND.nextDouble() > 0.9 ? whenStartMs + RAND.nextLong(1000L, 2000L) : null;
    long tsNanos = whenStartMs * 1_000_000L;
    allTimestamps.add(tsNanos);
    ilp = ilp
        .table(TABLE)
        .symbol(COL_ID, id)
        .symbol(COL_LINKED_ID, linkedId)
        .stringColumn(COL_DESC, desc)
        .stringColumn(COL_STR_1, str1)
        .stringColumn(COL_STR_2, str2)
        .boolColumn(COL_ACTIVE, active)
        .longColumn(COL_WHEN_START, whenStartMs);
    if (whenEndMs != null) {
      ilp = ilp.longColumn(COL_WHEN_END, whenEndMs);
    }
    ilp.at(tsNanos);
  }

  static void insertData(int nRows) throws Exception {
    Set<Long> allTimestamps = new HashSet<>();
    try (Sender ilp = Sender.builder().address(QUESTDB_ILP_ADDRESS).build()) {
      log("insert [%d] rows into table [" + TABLE + "] ...", nRows);
      for (int j = 1; j <= nRows; j++) {
        insertRow(j, ilp, allTimestamps);
      }
      ilp.flush();
      log("insert [%d] rows - DONE [%d] unique timestamps", nRows, allTimestamps.size());
    }
    log("wait 5s for inserted data to settle ...");

    // start background inserter thread
    Runnable backgroundInsert = () -> {
      int bgInsertCount = 0;
      try (Sender ilp = Sender.builder().address(QUESTDB_ILP_ADDRESS).build()) {
        while(true) {
          if (EXIT.get()) {
            break;
          }
          QUEST_LOCK.lock();
          
          try {
            insertRow(RAND.nextInt(1, 1000), ilp, new HashSet<>());
            ++bgInsertCount;
            if (bgInsertCount % 200 == 0) {
              ilp.flush();
              log("background-insert totals: [%d]", bgInsertCount);
              Thread.sleep(RAND.nextLong(250L, 500L));
            }
          } finally {
            QUEST_LOCK.unlock();
          }
        }
      } catch(Exception e) {
        log("ERROR - backgroundInsert() failed");
        e.printStackTrace();
      }
    };
    Thread.sleep(2000L);
    log("starting background data-insertion task");
    Thread backgroundInsertTask = new Thread(backgroundInsert, "Background ILP Insert");
    backgroundInsertTask.setDaemon(true);
    backgroundInsertTask.start();
    Thread.sleep(3000L);
    log("exit insertData()");
  }

  static int getCountStar(String query) throws Exception {
    int count = -1;
    try(Connection conn = DriverManager.getConnection(QUESTDB_QUERY_JDBC_URL, QUESTDB_QUERY_JDBC_PROPS);
        PreparedStatement stmt = conn.prepareStatement(query)) {
      log(" run query [%s] ...", stmt);
      try(ResultSet result = stmt.executeQuery()) {
        if (result.next()) {
          count = result.getInt(1);
        }
      }
      log(" query [%s] completed: count:[%d]", stmt, count);
    }
    return count;
  }

  static int getRowCount(String query) throws Exception {
    int count = 0;
    try(Connection conn = DriverManager.getConnection(QUESTDB_QUERY_JDBC_URL, QUESTDB_QUERY_JDBC_PROPS);
        PreparedStatement stmt = conn.prepareStatement(query)) {
      stmt.setFetchSize(100_000);
      log(" run query [%s] ...", stmt);
      try(ResultSet result = stmt.executeQuery()) {
        while(result.next()) {
          count++;
        }
      }
    } catch(Exception e) {
      log("  %n  ##### UNEXPECTED ERROR %s #####%n", e);
      e.printStackTrace();
      return -1;
    }
    log(" query [%s] completed: count:[%d]", query, count);
    return count;
  }

  static void performQueries() throws Exception {
    QUEST_LOCK.lock();
    try {
      log(" ==> starting queries in ~100ms ...%n");
      Thread.sleep(100L);
      DateTimeFormatter timeFormat = DateTimeFormatter.ofPattern(
          "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
      String queryTimeFilter = timeFormat.format(
          Instant.ofEpochMilli(System.currentTimeMillis() - (86_400_000L/24L) )
          //        Instant.ofEpochMilli(minTimeMs - (86_400_000L/24L) )
          .atOffset(ZoneOffset.UTC));
      String queryBase = "select * from '" + TABLE
          + "' WHERE timestamp >= '" + queryTimeFilter + "' ORDER BY " + COL_DESIGNATED_TIMESTAMP + " ";

      int countStar = getCountStar("SELECT COUNT(*) FROM '" + TABLE + "'");
      int ascCount = getRowCount(queryBase + "ASC");
      int ascLimitCount = getRowCount(queryBase + "ASC LIMIT 100000");
      int descCount = getRowCount(queryBase + "DESC");
      int descLimitCount = getRowCount(queryBase + "DESC LIMIT 100000");

      boolean allEqual = countStar == descCount
          && descCount == descLimitCount && descCount == ascCount && descCount == ascLimitCount;
      log("%n -- QUERY RESULTS -- %n"
          + "  count(*)       = [%d]%n"
          + "  descCount      = [%d]%n"
          + "  descLimitCount = [%d]%n"
          + "  ascCount       = [%d]%n"
          + "  ascLimitCount  = [%d]%n"
          + "  allEqual       = [%b]%n"
          + " -----------------%n",
          countStar, descCount, descLimitCount, ascCount, ascLimitCount, allEqual);
    } finally {
      QUEST_LOCK.unlock();
    }
  }

  public static void main(String[] args) {
    int exitCode = 0;
    log("enter");
    try {
      insertData(RAND.nextInt(1001, 4999));
      log("%n performing queries ...%n%n");
      performQueries();
      log("shutdown ...%n");
      EXIT.set(true);
      Thread.sleep(1000L);
    } catch (Throwable t) {
      t.printStackTrace();
      exitCode = 1;
    }
    log("exit");
    System.exit(exitCode);
  }
}
```

**Comment by bluestreak01** [comment]
is this result you'd expect?

```
[2023-03-21T19:48:12.251488600Z] enter
Log configuration loaded from default internal file.
[2023-03-21T19:48:12.808503600Z] insert [5921] rows into table [sort-desc-repro-3] ...
2023-03-21T19:48:12.424165Z I i.q.c.l.t.PlainTcpLineChannel Send buffer size change from 65536 to 131072
[2023-03-21T19:48:12.894508700Z] insert [5921] rows - DONE [3209] unique timestamps
[2023-03-21T19:48:12.894508700Z] wait 5s for inserted data to settle ...
[2023-03-21T19:48:17.908400Z   ] exit insertData()
[2023-03-21T19:48:17.908400Z   ] 
 performing queries ...


[2023-03-21T19:48:18.005539800Z]  run query [SELECT COUNT(*) FROM 'sort-desc-repro-3'] ...
[2023-03-21T19:48:18.024542Z   ]  query [SELECT COUNT(*) FROM 'sort-desc-repro-3'] completed: count:[16412]
[2023-03-21T19:48:18.027541600Z]  run query [select * from 'sort-desc-repro-3' WHERE timestamp >= '2023-03-19T19:48:12.810Z' ORDER BY timestamp ASC] ...
[2023-03-21T19:48:18.085544600Z]  query [select * from 'sort-desc-repro-3' WHERE timestamp >= '2023-03-19T19:48:12.810Z' ORDER BY timestamp ASC] completed: count:[16412]
[2023-03-21T19:48:18.087544400Z]  run query [select * from 'sort-desc-repro-3' WHERE timestamp >= '2023-03-19T19:48:12.810Z' ORDER BY timestamp ASC LIMIT 100000] ...
[2023-03-21T19:48:18.126545600Z]  query [select * from 'sort-desc-repro-3' WHERE timestamp >= '2023-03-19T19:48:12.810Z' ORDER BY timestamp ASC LIMIT 100000] completed: count:[16412]
[2023-03-21T19:48:18.128544600Z]  run query [select * from 'sort-desc-repro-3' WHERE timestamp >= '2023-03-19T19:48:12.810Z' ORDER BY timestamp DESC LIMIT 100000] ...
[2023-03-21T19:48:18.163546100Z]  query [select * from 'sort-desc-repro-3' WHERE timestamp >= '2023-03-19T19:48:12.810Z' ORDER BY timestamp DESC LIMIT 100000] completed: count:[16412]
[2023-03-21T19:48:18.166545300Z]  run query [select * from 'sort-desc-repro-3' WHERE timestamp >= '2023-03-19T19:48:12.810Z' ORDER BY timestamp DESC] ...
[2023-03-21T19:48:18.196546600Z]  query [select * from 'sort-desc-repro-3' WHERE timestamp >= '2023-03-19T19:48:12.810Z' ORDER BY timestamp DESC] completed: count:[16412]
[2023-03-21T19:48:18.196546600Z] 
 -- QUERY RESULTS -- 
  count(*)       = [16412]
  descCount      = [16412]
  descLimitCount = [16412]
  ascCount       = [16412]
  ascLimitCount  = [16412]
  allEqual       = [true]
 -----------------

[2023-03-21T19:48:18.196546600Z] exit
```

**Comment by andyb-ev** [comment]
Yes that's what I'd expect, the counts should be equal for the queries regardless of sort order or limiting, since all the rows in the table match and there are less rows in the table than the query limit.

**Comment by bluestreak01** [comment]
the original repo seems fixed, just tried the new ones - the counts are out, but there is no crashes. Looking into those

**Comment by andyb-ev** [comment]
could be a concurrency issue (data hasn't settled on the server-side yet so you could increase the sleep after the query method acquires the lock).

**Comment by bluestreak01** [comment]
i'll prep a draft PR, we will need to write a bunch of tests tomorrow and fix should be in nightly day after or we can cut a build for you?

**Comment by andyb-ev** [comment]
Thanks for the quick turnaround.  We can test on `nightly` for now since our use of QuestDB isn't in production yet, and just keep this ticket posted when the fix lands into an official release.
