### ISSUE TITLE
CairoException When Trying to Start Server (FreeBSD)

### ISSUE THREAD

**Issue by kevindirect** [questdb/questdb#3093]
### Describe the bug

We get a CarioException when trying to start the server:
```
io.questdb.cairo.CairoException: [0] cannot lock table name registry file [path=~/questdb/db]
        at io.questdb@7.0.1/io.questdb.cairo.CairoException.critical(CairoException.java:55)
        at io.questdb@7.0.1/io.questdb.cairo.TableNameRegistryRW.<init>(TableNameRegistryRW.java:39)
        at io.questdb@7.0.1/io.questdb.cairo.CairoEngine.<init>(CairoEngine.java:137)
        at io.questdb@7.0.1/io.questdb.ServerMain.<init>(ServerMain.java:80)
        at io.questdb@7.0.1/io.questdb.ServerMain.<init>(ServerMain.java:70)
        at io.questdb@7.0.1/io.questdb.ServerMain.<init>(ServerMain.java:66)
        at io.questdb@7.0.1/io.questdb.ServerMain.main(ServerMain.java:229)
```

### To reproduce

`questdb.sh start -d ~/questdb`

### Environment

```markdown
- **QuestDB version**: 7.0.1
- **OS**: FreeBSD 13.1-RELEASE-p7
- **Browser**: N/A
```

**Comment by ideoma** [comment]
This error may happen when 2 QuestDB processes run on the same box pointing to the same data directory.

Was it the only QeuestDB running?

**Comment by kevindirect** [comment]
The java runtime that came with questdb is on (`questdb/bin/java`), that seems to be all.
`questdb/bin/questdb.sh status -d <dir>` says it's not running and there is no questdb process or service running.

**Comment by Sohan064** [comment]
The java runtime that came with questdb is on (questdb/bin/java), that seems to be all.
questdb/bin/questdb.sh status -d <dir> says it's not running and there is no questdb process or service running.
