### ISSUE TITLE
questDB 7.1.1 java.lang.UnsupportedOperationException with table_partitions or SHOW PARTITIONS

### ISSUE THREAD

**Issue by remyantoniol** [questdb/questdb#3250]
### Describe the bug

Connecting to questdb using Npgsql in C#: the request SELECT * FROM table_partitions(table_name) does not work and the log reports:
_2023-04-19T12:28:27.675803Z I i.q.c.p.PGConnectionContext parse [fd=1572, q=SELECT * FROM table_partitions('F-WWCT_adc')]
2023-04-19T12:28:27.675823Z I i.q.c.p.PGConnectionContext query cache used [fd=1572]
2023-04-19T12:28:27.677517Z C i.q.c.p.PGWireServer internal error [ex=
java.lang.UnsupportedOperationException
	at io.questdb.griffin.engine.table.ShowPartitionsRecordCursorFactory$ShowPartitionsRecordCursor$PartitionsRecord.getLong(ShowPartitionsRecordCursorFactory.java:380)
	at io.questdb.cutlass.pgwire.PGConnectionContext.appendTimestampColumnBin(PGConnectionContext.java:960)
	at io.questdb.cutlass.pgwire.PGConnectionContext.appendRecord(PGConnectionContext.java:837)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor0(PGConnectionContext.java:2638)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor(PGConnectionContext.java:2622)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processExecute(PGConnectionContext.java:2208)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processExec(PGConnectionContext.java:2197)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1651)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:418)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:91)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:128)
	at io.questdb.mp.Worker.run(Worker.java:118)
]
2023-04-19T12:28:27.677624Z I pg-server scheduling disconnect [fd=1572, reason=17]_

**The same request within questDB console works fine.**

Same issue with SHOW PARTITIONS FROM table_name;

My connection is OK as other basics request (show tables, SELECT * FROM 'F-WWCT_adc', ..) are working.

I would expect the same result as the console

### Expected Behavior

I would expect the same result as the console

### Environment

```markdown
- **QuestDB version**: 7.1.1
- **OS**: windows 10
- **Browser**: Chrome
- **Npgsql**: 7.0.1
```

**Comment by bziobrowski** [comment]
What does your npgsql code look like ? 
It seems that you're trying to read a table_partitions output column with bad index or bad type.

**Comment by jerrinot** [comment]
it looks binary pgwire responses uses  `record.getLong()` to get a timestamp
```java
private void appendTimestampColumnBin(Record record, int columnIndex) {
        final long longValue = record.getLong(columnIndex);
        if (longValue == Numbers.LONG_NaN) {
            responseAsciiSink.setNullValue();
        } else {
            responseAsciiSink.putNetworkInt(Long.BYTES);
            // PG epoch starts at 2000 rather than 1970
            responseAsciiSink.putNetworkLong(longValue - Numbers.JULIAN_EPOCH_OFFSET_USEC);
        }
    }
```
while text responses uses `record.getTimestamp()`:
```java
private void appendTimestampColumn(Record record, int i) {
        long a;
        long longValue = record.getTimestamp(i);
        if (longValue == Numbers.LONG_NaN) {
            responseAsciiSink.setNullValue();
        } else {
            a = responseAsciiSink.skip();
            TimestampFormatUtils.PG_TIMESTAMP_FORMAT.format(longValue, null, null, responseAsciiSink);
            responseAsciiSink.putLenEx(a);
        }
    }
```
but the ShowPartitionRecord does assume `getLong()` to be used for long columns only:
```java
@Override
public long getLong(int col) {
    if (Column.NUM_ROWS.is(col)) {
        return numRows;
    }
    if (Column.DISK_SIZE.is(col)) {
        return partitionSize;
    }
    throw new UnsupportedOperationException();
}
```

So chances are the C# Postgres client asks for the binary mode and it fails while psql uses the text mode.

**Comment by bluestreak01** [comment]
this is a bug, there are a lot of places where we use `getLong()` and `getTimestamp()` on `timestamp` columns interchagebly, the function must provide `long` values for timestamp columns

**Comment by remyantoniol** [comment]
My  npgsql code:

var connectionString = $@"host={localhost};port={port};username={username};password={password};database={database};ServerCompatibilityMode=NoTypeLoading;";
using NpgsqlConnection connection = new NpgsqlConnection(connectionString);
connection.Open();                

//var sql = $"show PARTITIONS FROM '{table}_adc'";
//var sql = $"table_partitions('{table}_adc')";                               
//var sql = $"SELECT * FROM table_partitions('{table}_adc');";
var sql = $"SELECT * FROM table_partitions('F-WWCT_adc')";

using NpgsqlCommand command = new NpgsqlCommand(sql, connection);
using (var reader = command.ExecuteReader(System.Data.CommandBehavior.SequentialAccess))
{
	// never entering here
	
	while (reader.Read())
	{ 
		...                            
	}
}

**Comment by strongguy16** [comment]
SELECT * FROM table_partitions('table_name');
