### ISSUE TITLE
Flaky test WalWriterFuzzTest.testWalAddRemoveCommitFuzzO3

### ISSUE THREAD

**Issue by bziobrowski** [questdb/questdb#3255]
### Describe the bug

Test timed out.
https://dev.azure.com/questdb/questdb/_build/results?buildId=20598&view=logs&jobId=77f3b1d9-3966-5913-1475-fd2c175d0bc2&j=4955d095-2078-5b5d-31a1-99f71a7c612c&t=e558e7bf-9ebf-5c2e-7d87-eed2e40883cb

Stack trace : 
2023-04-19T15:48:18.496346Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.griffin.wal.WalWriterFuzzTest.testWalAddRemoveCommitFuzzO3 : 
org.junit.runners.model.TestTimedOutException: test timed out after 1200000 milliseconds
	at java.util.regex.Matcher.reset(Matcher.java:406)
	at java.util.regex.Matcher.find(Matcher.java:772)
	at java.util.Formatter.parse(Formatter.java:2702)
	at java.util.Formatter.format(Formatter.java:2655)
	at java.util.Formatter.format(Formatter.java:2609)
	at java.lang.String.format(String.java:2897)
	at io.questdb.test.tools.TestUtils.assertColumnValues(TestUtils.java:1470)
	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:195)
	at io.questdb.test.tools.TestUtils.assertSqlCursors(TestUtils.java:623)
	at io.questdb.test.tools.TestUtils.assertSqlCursors(TestUtils.java:615)
	at io.questdb.test.griffin.wal.WalWriterFuzzTest.lambda$runFuzz$3(WalWriterFuzzTest.java:706)
	at io.questdb.test.griffin.wal.WalWriterFuzzTest$$Lambda$991/0x0000000800690c40.run(Unknown Source)
	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$4(AbstractCairoTest.java:282)
	at io.questdb.test.AbstractCairoTest$$Lambda$326/0x0000000800365440.run(Unknown Source)
	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:555)
	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:279)
	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:273)
	at io.questdb.test.griffin.wal.WalWriterFuzzTest.runFuzz(WalWriterFuzzTest.java:645)
	at io.questdb.test.griffin.wal.WalWriterFuzzTest.testWalAddRemoveCommitFuzzO3(WalWriterFuzzTest.java:131)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:829)

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by jerrinot** [comment]
a failure in this test is reproducible with these seeds: 
```
s0 = 353427464356L;
s1 = 1737105041611L;
```
It provokes a file allocation failure (mimicking no disk space) so probably a different root cause than the one reported by @bziobrowski.

**Comment by jerrinot** [comment]
resolved by https://github.com/questdb/questdb/pull/5321
