### ISSUE TITLE
After power off and restart, the data table cannot be accessed

### ISSUE THREAD

**Issue by y1meng** [questdb/questdb#3276]
### Describe the bug

OS: Windows 10
QuestDB: 6.7

After a sudden power outage and restart of the computer, a data table is no longer accessible

Error Message: 
Npgsql.PostgresException (0x80004005): 00000: [-100]: Invalid metadata at fd=1184. Metadata version does not match runtime version [expected=426, actual=417]
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
...

At the same time, I found that other tables are accessed normally, and the table with errors generates a .lock file. I suspect it is locked?
#1448  At the same time, I found that many people have already had this problem, and I hope someone can tell me the solution, thank you

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by y1meng** [comment]
I tried to mount a broken qdbroot directory using the latest version 7.1.1 -d command option, the following error occurred...


2023-04-27T02:17:42.988926Z A server-main QuestDB server 7.1.1. Copyright (C) 2014-2023, all rights reserved.
2023-04-27T02:17:43.094423Z A server-main OS/Arch Windows/amd64 [AVX2,8, 64 bits, 12 processors]
2023-04-27T02:17:43.101443Z I server-main Web Console is up to date
2023-04-27T02:17:43.101530Z A server-main Server config: E:\qdbroot\conf\server.conf
2023-04-27T02:17:43.141115Z I i.q.c.t.t.InputFormatConfiguration loading input format config [resource=/text_loader.json]
2023-04-27T02:17:43.155845Z A server-main Config:
2023-04-27T02:17:43.155868Z A server-main  - http.enabled : true
2023-04-27T02:17:43.155891Z A server-main  - tcp.enabled  : true
2023-04-27T02:17:43.155909Z A server-main  - pg.enabled   : true
2023-04-27T02:17:43.155924Z A server-main  - attach partition suffix: .attachable
2023-04-27T02:17:43.155946Z A server-main  - open database [id=5106021167869373329.-4539684910708863324]
2023-04-27T02:17:43.156276Z A server-main  - db root: [path=E:\qdbroot\db, magic=0x2b] -> SUPPORTED
2023-04-27T02:17:43.156327Z A server-main  - backup root: NOT SET
2023-04-27T02:17:43.156498Z A server-main  - snapshot root: [path=E:\qdbroot\snapshot, magic=0x2b] -> SUPPORTED
2023-04-27T02:17:43.156524Z A server-main  - sql copy input root: NOT SET
2023-04-27T02:17:43.156541Z A server-main  - sql copy input worker root: NOT SET
2023-04-27T02:17:43.157917Z A server-main  - SQL JIT compiler mode: on
2023-04-27T02:17:43.159586Z C server-main found crash file [path=E:\qdbroot\db\crash+1.log]
2023-04-27T02:17:43.159684Z A server-main Metrics are disabled, health check endpoint will not consider unhandled errors
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000019043aa1860, pid=6948, tid=7848
#
# JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.8+10) (build 11.0.8+10-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.8+10-LTS, mixed mode, tiered, compressed oops, parallel gc, windows-amd64)
# Problematic frame:
# J 1406 c2 io.questdb.cairo.vm.api.MemoryCR.getInt(J)I io.questdb@7.1.1 (44 bytes) @ 0x0000019043aa1860 [0x0000019043aa1820+0x0000000000000040]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\qdbroot\db\hs_err_pid+6948.log
2023-04-27T02:17:43.194890Z I i.q.c.m.EngineMigration upgrading database [version=427]
2023-04-27T02:17:43.195763Z I i.q.c.m.EngineMigration upgrading [path=E:\qdbroot\db\AmmeterSummaryDataByDay, fromVersion=426, toVersion=427]
2023-04-27T02:17:43.195807Z I i.q.c.m.EngineMigration upgrading table [path=E:\qdbroot\db\AmmeterSummaryDataByDay, toVersion=427]
2023-04-27T02:17:43.196372Z I i.q.c.m.EngineMigration upgrading [path=E:\qdbroot\db\AmmeterSummaryDataByMinute, fromVersion=417, toVersion=427]
2023-04-27T02:17:43.196397Z I i.q.c.m.EngineMigration backing up meta file [path=E:\qdbroot\db\AmmeterSummaryDataByMinute\_meta, toPath=E:\qdbroot\db\AmmeterSummaryDataByMinute]
2023-04-27T02:17:43.196449Z I i.q.c.m.EngineMigration backup dest exists [to=E:\qdbroot\db\AmmeterSummaryDataByMinute\_meta.v417]
2023-04-27T02:17:43.196494Z I i.q.c.m.EngineMigration backing up [file=E:\qdbroot\db\AmmeterSummaryDataByMinute\_meta, to=E:\qdbroot\db\AmmeterSummaryDataByMinute\_meta.v417.1]
2023-04-27T02:17:43.197124Z I i.q.c.m.EngineMigration upgrading table [path=E:\qdbroot\db\AmmeterSummaryDataByMinute, toVersion=418]
2023-04-27T02:17:43.197297Z I i.q.c.m.MigrationActions rebuilding tx file [table=E:\qdbroot\db\AmmeterSummaryDataByMinute]
2023-04-27T02:17:43.197359Z I i.q.c.m.EngineMigration backup dest exists [to=E:\qdbroot\db\AmmeterSummaryDataByMinute\_txn.v417]
2023-04-27T02:17:43.197395Z I i.q.c.m.EngineMigration backup dest exists [to=E:\qdbroot\db\AmmeterSummaryDataByMinute\_txn.v417.1]
2023-04-27T02:17:43.197429Z I i.q.c.m.EngineMigration backing up [file=E:\qdbroot\db\AmmeterSummaryDataByMinute\_txn, to=E:\qdbroot\db\AmmeterSummaryDataByMinute\_txn.v417.2]
Compiled method (c2)     553 1406       4       io.questdb.cairo.vm.api.MemoryCR::getInt (44 bytes)
 total in heap  [0x0000019043aa1690,0x0000019043aa1928] = 664
 relocation     [0x0000019043aa17f8,0x0000019043aa1808] = 16
 main code      [0x0000019043aa1820,0x0000019043aa18a0] = 128
 stub code      [0x0000019043aa18a0,0x0000019043aa18b8] = 24
 oops           [0x0000019043aa18b8,0x0000019043aa18c8] = 16
 metadata       [0x0000019043aa18c8,0x0000019043aa18d8] = 16
 scopes data    [0x0000019043aa18d8,0x0000019043aa18f0] = 24
 scopes pcs     [0x0000019043aa18f0,0x0000019043aa1920] = 48
 dependencies   [0x0000019043aa1920,0x0000019043aa1928] = 8
Compiled method (c2)     556 1406       4       io.questdb.cairo.vm.api.MemoryCR::getInt (44 bytes)
 total in heap  [0x0000019043aa1690,0x0000019043aa1928] = 664
 relocation     [0x0000019043aa17f8,0x0000019043aa1808] = 16
 main code      [0x0000019043aa1820,0x0000019043aa18a0] = 128
 stub code      [0x0000019043aa18a0,0x0000019043aa18b8] = 24
 oops           [0x0000019043aa18b8,0x0000019043aa18c8] = 16
 metadata       [0x0000019043aa18c8,0x0000019043aa18d8] = 16
 scopes data    [0x0000019043aa18d8,0x0000019043aa18f0] = 24
 scopes pcs     [0x0000019043aa18f0,0x0000019043aa1920] = 48
 dependencies   [0x0000019043aa1920,0x0000019043aa1928] = 8
Could not load hsdis-amd64.dll; library not loadable; PrintAssembly is disabled

**Comment by Infinity-anuj** [comment]
The error message indicates that the metadata version expected by the database engine is 426, but the actual version found is 417, which means that the metadata is not compatible with the current version of the database engine. 

To resolve this issue, you can try the following steps:

Take a backup of the database before attempting any recovery operation.

Stop the database engine and make a copy of the affected table's data files, including the .lock file.

Attempt to repair the metadata by running the database engine's repair utility.

If repair does not work, restore the table from a backup.

If you don't have a backup, you may need to use a data recovery tool to attempt to recover the table data from the corrupted files.

**Comment by y1meng** [comment]
> The error message indicates that the metadata version expected by the database engine is 426, but the actual version found is 417, which means that the metadata is not compatible with the current version of the database engine.
> 
> To resolve this issue, you can try the following steps:
> 
> Take a backup of the database before attempting any recovery operation.
> 
> Stop the database engine and make a copy of the affected table's data files, including the .lock file.
> 
> Attempt to repair the metadata by running the database engine's repair utility.
> 
> If repair does not work, restore the table from a backup.
> 
> If you don't have a backup, you may need to use a data recovery tool to attempt to recover the table data from the corrupted files.

I am a development environment without backup,Can you tell me how to use the repair tool?

**Comment by y1meng** [comment]
@bluestreak01  
I recalled the relevant operations before the power outage and confirmed that it was caused by the power outage during the index addition process, and I have been able to reproduce this error. I conducted two power outage tests. The first time was only frequent insertion and query power outages did not cause Corruption, the second time was to add an index to a table, and then delete the index (I was testing the query speed at the time), the error was reproduced after the power was cut off immediately after deleting the index, I hope it can help you
