### ISSUE TITLE
CASE breaks unless the optional ELSE is used

### ISSUE THREAD

**Issue by javier** [questdb/questdb#3297]
### Describe the bug

According to the docs, CASE can be used with or without an ELSE block. If no ELSE, null will be returned for unmatched conditions.

In practice, when you issue a CASE statement with no ELSE, QuestDB crashes

### To reproduce

Go to any questdb installation, can be the demo site.

Do this (it will work)

```
WITH t as (
SELECT rnd_int(1,10,0) as i
  FROM long_sequence(15)
)
select i, 
CASE
  WHEN i % 2 = 0 THEN i
ELSE null  
END  
from t
```

Now the same but withoyt the ELSE block. It will crash

```
WITH t as (
SELECT rnd_int(1,10,0) as i
  FROM long_sequence(15)
)
select i, 
CASE
  WHEN i % 2 = 0 THEN i
END  
from t 
```
 

### Expected Behavior

I would expect ELSE to be optional

### Environment

```markdown
- **QuestDB version**: 7.1.1
- **OS**: OSx and Linux
- **Browser**: Chrome
```

**Comment by bluestreak01** [comment]
To clarify, this is not a "crash". HTTP server will disconnect the browser upon execution of the offending SQL. Database remains fully operational.

**Comment by bluestreak01** [comment]
I can repro this and SQL execution causes NPE in the code, which leads to disconnect (unexpected exception handing):

```
java.lang.NullPointerException: Cannot invoke "io.questdb.griffin.model.ExpressionNode.toSink(io.questdb.std.str.CharSink)" because "this.lhs" is null
	at io.questdb/io.questdb.griffin.model.ExpressionNode.toSink(ExpressionNode.java:222)
	at io.questdb/io.questdb.griffin.model.QueryModel.sinkColumns(QueryModel.java:1207)
	at io.questdb/io.questdb.griffin.model.QueryModel.toSink0(QueryModel.java:1269)
	at io.questdb/io.questdb.griffin.model.QueryModel.toSink(QueryModel.java:1173)
	at io.questdb/io.questdb.log.Logger.$(Logger.java:179)
	at io.questdb/io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1372)
	at io.questdb/io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1339)
	at io.questdb/io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:271)
	at io.questdb/io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:420)
	at io.questdb/io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:183)
	at io.questdb/io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:233)
	at io.questdb/io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:615)
	at io.questdb/io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:203)
	at io.questdb/io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:86)
	at io.questdb/io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb/io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:101)
	at io.questdb/io.questdb.mp.Worker.run(Worker.java:118)
```
