### ISSUE TITLE
Too Much Input Exception When SELECTing Many AVG Columns

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#3326]
### Describe the bug

When SELECTing 6000 columns AVG on the same SELECT there is an error.
ServerSide:
```
023-05-12T09:12:00.131416Z E i.q.s.BytecodeAssembler Too much input to generate io.questdb.griffin.engine.groupby.GroupByFunctionsUpdater. Bytecode is too long
2023-05-12T09:12:00.131435Z C i.q.c.p.PGWireServer internal error [ex=
io.questdb.std.ex.BytecodeException: Error in bytecode
	at io.questdb.std.ex.BytecodeException.<clinit>(BytecodeException.java:28)
	at io.questdb.std.BytecodeAssembler.endMethodCode(BytecodeAssembler.java:199)
	at io.questdb.griffin.engine.groupby.GroupByFunctionsUpdaterFactory.generateUpdateNew(GroupByFunctionsUpdaterFactory.java:220)
	at io.questdb.griffin.engine.groupby.GroupByFunctionsUpdaterFactory.getInstance(GroupByFunctionsUpdaterFactory.java:110)
	at io.questdb.griffin.engine.groupby.GroupByNotKeyedRecordCursorFactory.<init>(GroupByNotKeyedRecordCursorFactory.java:64)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectGroupBy(SqlCodeGenerator.java:3336)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2665)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2272)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2259)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:186)
	at io.questdb.griffin.SqlCompiler.generate(SqlCompiler.java:2731)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1322)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1271)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:268)
	at io.questdb.cutlass.pgwire.PGConnectionContext.compileQuery(PGConnectionContext.java:1192)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parseQueryText(PGConnectionContext.java:1699)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processParse(PGConnectionContext.java:2358)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1631)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:418)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:91)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:128)
	at io.questdb.mp.Worker.run(Worker.java:118)
]
```

ClientSide (.NET):
```
    Npgsql.NpgsqlException: Exception while reading from stream ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.

  Stack Trace: 
    NpgsqlReadBuffer.<Ensure>g__EnsureLong|42_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
    --- End of inner exception stack trace ---
    NpgsqlReadBuffer.<Ensure>g__EnsureLong|42_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
    NpgsqlConnector.<ReadMessage>g__ReadMessageLong|232_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
    NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
    NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
    NpgsqlDataReader.NextResult()
    NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
    NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
    NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
```

### To reproduce

Create a table with a lot of columns.
SELECT AVG of each of them:
`SELECT AVG(col1), AVG(col2), .... , AVG(colX) from tbl`

### Expected Behavior

the results of the query should be returned.

### Environment

```markdown
- **QuestDB version**:711
- **OS**:windows
- **Browser**:chrome
```

**Comment by ideoma** [comment]
Similar to #3312

**Comment by bluestreak01** [comment]
it would be interesting to know the usecase, may be there is a way to model this differently?

**Comment by superichmann** [comment]
all columns are double type
I would like to know which columns have the same underlying data in one select
AVG gives me a representation of that in one line with all columns. an alternative could be some kind of hash..
I know its not perfect and might be two columns that have different values but same AVG value but this is enough for me at the moment.. if you have other function that could help me with this I would love to hear about it. or any workaround. maybe some config change to increase size?

Thanks :]

**Comment by superichmann** [comment]
In order to bypass this issue I have reduced my number of columns to 4000 and it usualy works.
Sometimes I get a timeout error and here is the QDB log:
```
2023-05-22T14:48:10.921058Z E i.q.c.w.WalPurgeJob could not delete directory [path=C:\qdb\bin\qdbroot\db\Rocket~263\wal2, errno=5]
2023-05-22T14:48:10.921063Z I i.q.c.w.WalPurgeJob deleting WAL directory [table=Rocket~263, walId=3]
2023-05-22T14:48:10.921453Z E i.q.c.w.WalPurgeJob could not delete directory [path=C:\qdb\bin\qdbroot\db\Rocket~263\wal3, errno=5]
2023-05-22T14:48:40.926160Z I i.q.c.w.WalPurgeJob table=Rocket~263, discovered=[(wal2),(wal3)], nextToApply=[]
2023-05-22T14:48:40.926189Z I i.q.c.w.WalPurgeJob deleting WAL directory [table=Rocket~263, walId=2]
2023-05-22T14:48:40.926680Z E i.q.c.w.WalPurgeJob could not delete directory [path=C:\qdb\bin\qdbroot\db\Rocket~263\wal2, errno=5]
2023-05-22T14:48:40.926686Z I i.q.c.w.WalPurgeJob deleting WAL directory [table=Rocket~263, walId=3]
2023-05-22T14:48:40.926992Z E i.q.c.w.WalPurgeJob could not delete directory [path=C:\qdb\bin\qdbroot\db\Rocket~263\wal3, errno=5]
2023-05-22T14:49:10.928856Z I i.q.c.w.WalPurgeJob table=Rocket~263, discovered=[(wal2),(wal3)], nextToApply=[]
2023-05-22T14:49:10.928861Z I i.q.c.w.WalPurgeJob deleting WAL directory [table=Rocket~263, walId=2]
2023-05-22T14:49:10.929268Z E i.q.c.w.WalPurgeJob could not delete directory [path=C:\qdb\bin\qdbroot\db\Rocket~263\wal2, errno=5]
2023-05-22T14:49:10.929273Z I i.q.c.w.WalPurgeJob deleting WAL directory [table=Rocket~263, walId=3]
2023-05-22T14:49:10.929539Z E i.q.c.w.WalPurgeJob could not delete directory [path=C:\qdb\bin\qdbroot\db\Rocket~263\wal3, errno=5]
2023-05-22T14:49:24.748230Z I i.q.c.p.PGConnectionContext query cancelled [msg=`timeout, query aborted [fd=6884]`]
```

Any suggestions?

**Comment by superichmann** [comment]
Hi I still getting this issue on large selects.. what can we do?

**Comment by superichmann** [comment]
this still occurs on large queries, as i recall its due to an internal java limitation which cannot be solved.

**Comment by freddyrios** [comment]
I just ran into something that triggers the same: create table as () for a table with lots of columns.

It seems to come down to the same pattern used in multiple places in GroupByFunctionsUpdaterFactory.

For example, this random example: https://github.com/questdb/questdb/blob/e0c80644f78d9d8f79d0115757744e3c893ea724/core/src/main/java/io/questdb/griffin/engine/groupby/GroupByFunctionsUpdaterFactory.java#L215-L223

The method being generated has instructions for every field and ends up tripping the check of it being too large:

https://github.com/questdb/questdb/blob/e0c80644f78d9d8f79d0115757744e3c893ea724/core/src/main/java/io/questdb/std/BytecodeAssembler.java#L197-L204

Given the whole context it sounds a lot like the limit is about how big a a single method can be.

Suggestion: for larger fields count, split it into large field batches and generate a sub method for each batch. Then generate the main method, which calls each field batch method in sequence.

**Comment by nwoolmer** [comment]
The PR fixed the inserts, but did not fix the group by unfortunately.
