### ISSUE TITLE
count not mmap column error with Docker

### ISSUE THREAD

**Issue by miguelgrinberg** [questdb/questdb#3337]
### Describe the bug

I'm using the `docker run` command with a mounted folder on `/var/lib/questdb`, as documented in the Get Started / Data Persistence section. It appears that on macOS (possibly Windows as well, not sure), where Docker runs in its own Linux VM and there is a somewhat magical solution to allow folders from the host OS to be mounted into a container passing through the virtualization layer, the `mmap()` function isn't supported and returns errno 22.

It would probably make more sense to recommend the use of a volume for data persistence. I was able to work around this problem with the following Docker Compose configuration:

```yml
version: '3'

services:
  questdb:
    image: questdb/questdb
    restart: always
    environment:
      RUN_AS_ROOT: true
    ports:
      - "9000:9000"
      - "8812:8812"
    volumes:
      - questdb-data:/var/lib/questdb
      - ${PWD}/conf:/var/lib/questdb/conf
volumes:
  questdb-data:
```

### To reproduce

1. Install Docker Desktop or [podman](https://podman.io/) on macOS. If using `podman`, configure the `DOCKER_HOST` variable appropriately.
2. Start a QuestDB container as documented [here](https://questdb.io/docs/get-started/docker/#mounting-a-volume).

### Expected Behavior

The QuestDB instance would start normally.

### Environment

```markdown
- **QuestDB version**: 7.1.1
- **OS**: macOS Ventura 13.3.1, podman 4.5.0
- **Browser**: N/A
```

### Additional context

Docker logs:

```text
No arguments found, start with default arguments
Running as root user
Log configuration loaded from: /var/lib/questdb/conf/log.conf
2023-05-15T10:49:58.787100Z A server-main QuestDB server 7.1.1. Copyright (C) 2014-2023, all rights reserved.
2023-05-15T10:50:00.279248Z A server-main OS/Arch linux/amd64 [AVX2,8, 64 bits, 1 processors]
2023-05-15T10:50:00.382401Z I server-main extracted [path=/var/lib/questdb/public/qdb.css]
2023-05-15T10:50:00.396756Z I server-main extracted [path=/var/lib/questdb/public/qdb.js.LICENSE.txt]
2023-05-15T10:50:00.657774Z I server-main extracted [path=/var/lib/questdb/public/qdb.js]
2023-05-15T10:50:00.683132Z I server-main extracted [path=/var/lib/questdb/public/assets/favicon.svg]
2023-05-15T10:50:00.726068Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/loader.js]
2023-05-15T10:50:00.751609Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/loader.js.LICENSE.txt]
2023-05-15T10:50:00.800082Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/editor/editor.main.nls.js]
2023-05-15T10:50:01.255536Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/editor/editor.main.js]
2023-05-15T10:50:01.304262Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/editor/editor.main.nls.js.LICENSE.txt]
2023-05-15T10:50:01.335043Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/editor/editor.main.js.LICENSE.txt]
2023-05-15T10:50:01.373894Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/editor/editor.main.css]
2023-05-15T10:50:01.490569Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/base/worker/workerMain.js.LICENSE.txt]
2023-05-15T10:50:01.561588Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/base/worker/workerMain.js]
2023-05-15T10:50:01.587381Z I server-main extracted [path=/var/lib/questdb/public/assets/favicon.ico]
2023-05-15T10:50:01.608762Z I server-main extracted [path=/var/lib/questdb/public/assets/console-configuration.json]
2023-05-15T10:50:01.624730Z I server-main extracted [path=/var/lib/questdb/public/index.html]
2023-05-15T10:50:01.649636Z I server-main extracted [path=/var/lib/questdb/public/573e9313e05d89f4acb5d005476c61bb.woff]
2023-05-15T10:50:02.142992Z I server-main extracted [path=/var/lib/questdb/public/assets/vs/base/browser/ui/codicons/codicon/codicon.ttf]
2023-05-15T10:50:02.163563Z I server-main extracted [path=/var/lib/questdb/public/d0b483ce9717b92b4bf815d5d4db597a.woff]
2023-05-15T10:50:02.185352Z I server-main extracted [path=/var/lib/questdb/public/6437d5f4c14e01aaf4801aef3909151b.woff]
2023-05-15T10:50:02.212661Z I server-main extracted [path=/var/lib/questdb/public/7dafb1a4bab4938a38b2d68d9c4575a9.woff]
2023-05-15T10:50:02.267755Z I server-main extracted [path=/var/lib/questdb/public/a940d584750708f5435ce2c523498ddb.woff]
2023-05-15T10:50:02.298724Z I server-main extracted [path=/var/lib/questdb/conf/mime.types]
2023-05-15T10:50:02.315843Z I server-main extracted [path=/var/lib/questdb/conf/server.conf]
2023-05-15T10:50:02.322087Z A server-main Server config: /var/lib/questdb/conf/server.conf
io.questdb.Bootstrap$BootstrapException: io.questdb.cairo.CairoException: [22] could not mmap column [fd=6, size=4096]
2023-05-15T10:50:02.580993Z E server-main
io.questdb.cairo.CairoException: [22] could not mmap column [fd=6, size=4096]

        at io.questdb@7.1.1/io.questdb.Bootstrap.<init>(Bootstrap.java:178)
        at io.questdb@7.1.1/io.questdb.Bootstrap.<init>(Bootstrap.java:74)
        at io.questdb@7.1.1/io.questdb.ServerMain.<init>(ServerMain.java:66)
        at io.questdb@7.1.1/io.questdb.ServerMain.main(ServerMain.java:216)
Caused by: io.questdb.cairo.CairoException: [22] could not mmap column [fd=6, size=4096]
        at io.questdb@7.1.1/io.questdb.std.ThreadLocal.get(ThreadLocal.java:46)
        at io.questdb@7.1.1/io.questdb.cairo.CairoException.critical(CairoException.java:53)
        at io.questdb@7.1.1/io.questdb.cairo.TableUtils.mapRW(TableUtils.java:814)
        at io.questdb@7.1.1/io.questdb.cairo.TableUtils.mapRW(TableUtils.java:789)
        at io.questdb@7.1.1/io.questdb.cairo.TableUtils.mapRWOrClose(TableUtils.java:821)
        at io.questdb@7.1.1/io.questdb.PropServerConfiguration.<init>(PropServerConfiguration.java:528)
        at io.questdb@7.1.1/io.questdb.Bootstrap.<init>(Bootstrap.java:157)
        ... 3 more
```

**Comment by bluestreak01** [comment]
The recommended (test and supported) method of running QuestDB on Mac is via `homebrew`

**Comment by miguelgrinberg** [comment]
Thanks for your prompt response!

This isn't a big problem for me. As I mentioned above using a volume instead of a shared folder works great. Just wanted to alert you that the method you are recommending for Docker usage is not reliable and leave a record of my volume-based solution in case others find similar issues as I did.

Consider that my preference of Docker over a local install is likely shared by many, as this is a much cleaner way to install software without affecting other installed applications. I work with different databases and having them containerized is extremely convenient, especially if I need to switch between different versions of the same one.

I think it would be a good idea to add a note in the Docker section of the docs regarding this potential issue with shared folders. And if/when you do want to open the can of worms and debug this, maybe there is a way to recognize when `mmap()` isn't available and log this in a less obscure way than the current error. Thanks!

**Comment by bberak** [comment]
Thanks for posting this @miguelgrinberg -- I ran into the same issue and your solution worked great 🙏
