### ISSUE TITLE
Missed me? ;]

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#3383]
### Describe the bug

`SELECT amount,price1 FROM (SELECT * FROM (trades b LT JOIN (trades a WHERE a.timestamp>'2023' and a.price>1111 and a.symbol='ETH-USD') on symbol WHERE b.timestamp>'2023' and b.amount > 1 and b.symbol='ETH-USD')) WHERE date_trunc('day', timestamp) = date_trunc('day', timestamp1)`

qdb cloud reproducer.. same behavior on my windows machine, my error:
```
2023-05-22T19:46:11.897117Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=a, fd=2732]
2023-05-22T19:46:11.897413Z C i.q.c.p.PGWireServer internal error [ex=
io.questdb.cairo.sql.InvalidColumnException
	at io.questdb.cairo.sql.InvalidColumnException.<clinit>(InvalidColumnException.java:28)
	at io.questdb.cairo.sql.RecordMetadata.getColumnIndex(RecordMetadata.java:61)
	at io.questdb.griffin.SqlCodeGenerator.lookupColumnIndexesUsingVanillaNames(SqlCodeGenerator.java:4395)
	at io.questdb.griffin.SqlCodeGenerator.processJoinContext(SqlCodeGenerator.java:4462)
	at io.questdb.griffin.SqlCodeGenerator.generateJoins(SqlCodeGenerator.java:1588)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2680)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2276)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2263)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3636)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:2910)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2667)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2276)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2263)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3636)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:2910)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2667)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2276)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2263)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3636)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:2910)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2667)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2276)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2263)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:186)
	at io.questdb.griffin.SqlCompiler.generate(SqlCompiler.java:2685)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1248)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1213)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:207)
	at io.questdb.cutlass.pgwire.PGConnectionContext.compileQuery(PGConnectionContext.java:1194)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parseQueryText(PGConnectionContext.java:1707)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processParse(PGConnectionContext.java:2359)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1639)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:421)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:91)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:128)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

### To reproduce

[demo.questdb.io](demo.questdb.io)

### Expected Behavior

should return data

### Environment

```markdown
- **QuestDB version**: 7.1.3
- **OS**: windows 1
- **Browser**: chrome
```

**Comment by superichmann** [comment]
Hi guys thanks for the fix :] when will the update find its way to the windows release?

**Comment by abrahammcgotliebson** [comment]
Same issue here
