### ISSUE TITLE
AssertionError in SAMPLE BY

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3389]
### Describe the bug

```sql
CREATE TABLE 't2' (
  s1 SYMBOL capacity 256 CACHE index capacity 256,
  s2 SYMBOL capacity 256 CACHE index capacity 256,
  d1 DOUBLE,  
  ts TIMESTAMP
) timestamp (ts) PARTITION BY DAY;

SELECT last(ts) as time, s1, last(d1) as dd
FROM t2 
WHERE ts BETWEEN '2023-05-16T05:47:36.59Z' AND '2023-05-18T05:47:36.592Z' 
AND s2 = ('xyz')
SAMPLE BY 5m
GROUP BY s1;
```

When the server is run with the `-ea` flag, the following error occurs:
```
2023-05-23T14:17:31.034707Z C i.q.c.h.p.JsonQueryProcessorState [26] Uh-oh. Error!
java.lang.AssertionError
	at io.questdb.griffin.engine.table.DeferredSingleSymbolFilterDataFrameRecordCursorFactory.getCursorInstance(DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java:128)
	at io.questdb.griffin.engine.table.AbstractDataFrameRecordCursorFactory.getCursor(AbstractDataFrameRecordCursorFactory.java:57)
	at io.questdb.griffin.engine.table.DataFrameRecordCursorFactory.getCursor(DataFrameRecordCursorFactory.java:42)
	at io.questdb.griffin.engine.groupby.SampleByFillNoneRecordCursorFactory.getCursor(SampleByFillNoneRecordCursorFactory.java:87)
	at io.questdb.griffin.engine.table.VirtualRecordCursorFactory.getCursor(VirtualRecordCursorFactory.java:70)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.of(JsonQueryProcessorState.java:817)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.of(JsonQueryProcessorState.java:803)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect(JsonQueryProcessor.java:550)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeNewSelect(JsonQueryProcessor.java:536)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:425)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:184)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:234)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:616)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:204)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:86)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:101)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

### Environment

```markdown
- **QuestDB version**: latest master
- **OS**:
- **Browser**:
```

**Comment by Madhuryabarche10** [comment]
Kindly assign me this query .

**Comment by am-1145** [comment]
Instead of symbol capacity 256 you can use VARCHAR(256) it may resolve your issue
