### ISSUE TITLE
WAL Writer fuzz test failure

### ISSUE THREAD

**Issue by glasstiger** [questdb/questdb#3396]
### Describe the bug

One-off failure of `WalWriterFuzzTest.testWalWriteRollbackHeavy()`.

```
2023-05-23T14:30:40.8779960Z org.junit.ComparisonFailure: Row 2378 column sym_top[SYMBOL] expected:<...8870621803019343449	[TFEBGYEPRSZPSJJVRNFDJKWJNHTCDQOCDLYHHRVQFOLYZUUZJSNMREXBPHZVKLVTHENSPCIHMBZGNJNXNRNEZPOCSWBGGSKCYQEBHRFEUGZYGBDYNPZXWJPEHYIEVEKWTMJKRKXYXPPMGDTWREJFLXQNJWXOVJBKTMCFFTXOUEMVOCBSTCZXQXJSTTIQHYBZXMNHDZGSFBIKXIMGQLYUOFVJDVDQNRDYXGIQZNCVSDXKRJJEBJKVHNMLECHSLKSOMPPEMPGIEYIUVOOJQUGVVUJCTQVFNNFGWCLGIQOWORFSCEVZTESOVBUPMCSSDRFMYUSKKXDOGJXVGQSJGETNSTXGGJXJDWMFCOTISHZEKGXDYPLWQQVSJVGYFDZSJQGOLQYYVXTDIWTEZYUENXCMZRRXENEHDQJJDMCTMNTSDZCORWCZCMIZKRCLBNTVBZWJTWUUZXBVDKRKFBPOBPBCJSOMUZUSNDKDQGLQWYPKPUNIOWLNQPHJLXBWWVHICFMXPTVVLQCXLWKGHEXQUTVUSHFDUKXTOWFIYELPFTKYEEJMKXXTHFFNOIBBPHWGFJCBYHQCQHWBDXMHEJNFCBUGGBOHOIKPWTPHXUDLHENTYRHJEVHGWOHUTKQDEXXLXBVRPWTGLQBVCTUJRFVJZZTOD]V	> but was:<...8870621803019343449	[XFWPQ]V	>
2023-05-23T14:30:40.8782866Z 	at org.junit.Assert.assertEquals(Assert.java:117)
2023-05-23T14:30:40.8787241Z 	at io.questdb.test.tools.TestUtils.assertColumnValues(TestUtils.java:1474)
2023-05-23T14:30:40.8792036Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:193)
2023-05-23T14:30:40.8796180Z 	at io.questdb.test.tools.TestUtils.assertSqlCursors(TestUtils.java:608)
2023-05-23T14:30:40.8800354Z 	at io.questdb.test.tools.TestUtils.assertSqlCursors(TestUtils.java:600)
2023-05-23T14:30:40.8805862Z 	at io.questdb.test.griffin.wal.WalWriterFuzzTest.lambda$runFuzz$6(WalWriterFuzzTest.java:553)
2023-05-23T14:30:40.8811191Z 	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$4(AbstractCairoTest.java:285)
2023-05-23T14:30:40.8817168Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:540)
2023-05-23T14:30:40.8820531Z 	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:282)
2023-05-23T14:30:40.8826528Z 	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:276)
2023-05-23T14:30:40.8831345Z 	at io.questdb.test.griffin.wal.WalWriterFuzzTest.runFuzz(WalWriterFuzzTest.java:519)
2023-05-23T14:30:40.8836673Z 	at io.questdb.test.griffin.wal.WalWriterFuzzTest.testWalWriteRollbackHeavy(WalWriterFuzzTest.java:202)
2023-05-23T14:30:40.8841567Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-05-23T14:30:40.8847105Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-05-23T14:30:40.8852512Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-23T14:30:40.8855940Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2023-05-23T14:30:40.8861183Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-05-23T14:30:40.8865936Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-05-23T14:30:40.8871462Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-05-23T14:30:40.8876845Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-05-23T14:30:40.8882717Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2023-05-23T14:30:40.8887042Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2023-05-23T14:30:40.8891140Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2023-05-23T14:30:40.8898454Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2023-05-23T14:30:40.8904165Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2023-05-23T14:30:40.8906573Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-05-23T14:30:40.8909510Z 	at java.lang.Thread.run(Thread.java:829)
```

Full log:
[30.txt](https://github.com/questdb/questdb/files/11553655/30.txt)

### To reproduce

Can be tricky.
Tried to run it in loop until failure, used the random seeds from the log.
Stopped it after 1700 runs, could not reproduce it locally on MacBook M1.
Failure happened on the `Building on AWS on linux-amd64-zfs` build.

### Expected Behavior

No intermittent test failures.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by ideoma** [comment]
@puzpuzpuz let's review partition squashing code, perhaps it's prone to issues you're aware of.

**Comment by puzpuzpuz** [comment]
That could be the case. It's simple to test locally on Linux - going to do it tomorrow.

**Comment by puzpuzpuz** [comment]
Update: I'm not able to reproduce this on enterprise after running the test 10K times. Also, ZFS issues usually manifest themselves as all-zeroes data which doesn't look to be the case here.
