### ISSUE TITLE
AssertionError in long-chained LT JOIN query

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3428]
### Describe the bug

Create a table:
```sql
CREATE TABLE 'train' (
  id INT,
  date timestamp,
  store_nbr INT,
  family SYMBOL,
  sales DOUBLE,
  onpromotion DOUBLE
) timestamp (date) PARTITION BY YEAR WAL;
```

The data can be taken from #3411

Run the query:
```sql
SELECT * FROM (select s.id from train s LT JOIN (train r LT JOIN (train q LT JOIN (train p LT JOIN (train o LT JOIN (train n LT JOIN (train m LT JOIN (train l LT JOIN (train k LT JOIN (train j LT JOIN (train i LT JOIN (train h LT JOIN (train g LT JOIN (train f LT JOIN (train e LT JOIN (train d LT JOIN (train c LT JOIN (train b LT JOIN (train a WHERE  a.date<'2017-07-16' AND a.date>'2012-12-29') ON (store_nbr,family) WHERE  b.date<'2017-07-16' AND b.date>'2012-12-29') ON (store_nbr,family) WHERE  c.date<'2017-07-16' AND c.date>'2012-12-29') ON (store_nbr,family) WHERE  d.date<'2017-07-16' AND d.date>'2012-12-29') ON (store_nbr,family) WHERE  e.date<'2017-07-16' AND e.date>'2012-12-29') ON (store_nbr,family) WHERE  f.date<'2017-07-16' AND f.date>'2012-12-29') ON (store_nbr,family) WHERE  g.date<'2017-07-16' AND g.date>'2012-12-29') ON (store_nbr,family) WHERE  h.date<'2017-07-16' AND h.date>'2012-12-29') ON (store_nbr,family) WHERE  i.date<'2017-07-16' AND i.date>'2012-12-29') ON (store_nbr,family) WHERE  j.date<'2017-07-16' AND j.date>'2012-12-29') ON (store_nbr,family) WHERE  k.date<'2017-07-16' AND k.date>'2012-12-29') ON (store_nbr,family) WHERE  l.date<'2017-07-16' AND l.date>'2012-12-29') ON (store_nbr,family) WHERE  m.date<'2017-07-16' AND m.date>'2012-12-29') ON (store_nbr,family) WHERE  n.date<'2017-07-16' AND n.date>'2012-12-29') ON (store_nbr,family) WHERE  o.date<'2017-07-16' AND o.date>'2012-12-29') ON (store_nbr,family) WHERE  p.date<'2017-07-16' AND p.date>'2012-12-29') ON (store_nbr,family) WHERE  q.date<'2017-07-16' AND q.date>'2012-12-29') ON (store_nbr,family) WHERE  r.date<'2017-07-16' AND r.date>'2012-12-29') ON (store_nbr,family) WHERE  s.date<'2017-07-16' AND s.date>'2012-12-29' LIMIT 594,99999999999999999);
```

Observe an error:
```
2023-05-30T13:07:03.243508Z C i.q.c.h.p.JsonQueryProcessorState [94] Uh-oh. Error!
java.lang.AssertionError
	at io.questdb.griffin.engine.join.JoinRecordMetadata.addAlias(JoinRecordMetadata.java:157)
	at io.questdb.griffin.engine.join.JoinRecordMetadata.add(JoinRecordMetadata.java:90)
	at io.questdb.griffin.SqlCodeGenerator.createFullFatJoin(SqlCodeGenerator.java:561)
	at io.questdb.griffin.SqlCodeGenerator.generateJoins(SqlCodeGenerator.java:1619)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2686)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2282)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2269)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3642)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:2916)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2673)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2282)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2269)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3642)
	at io.questdb.griffin.SqlCodeGenerator.generateNoSelect(SqlCodeGenerator.java:2135)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2688)
        ...
```

### Environment

```markdown
- **QuestDB version**: latest `master`
- **OS**:
- **Browser**:
```

**Comment by bziobrowski** [comment]
Minimized sql case :
```
WITH train_lim as (select id, date, sf, store_nbr, family, sales, onpromotion from train where date < '2017-07-16' AND date > '2012-12-29')
SELECT s.id 
FROM train_lim s 
LT JOIN 
(
    SELECT * FROM train_lim  
    LT JOIN 
    (
        SELECT * FROM train_lim 
    ) ON (store_nbr, family)
) ON (store_nbr, family)
```
