### ISSUE TITLE
Stuck in table lock while writing using HTTP REST API

### ISSUE THREAD

**Issue by saurabhk3** [questdb/questdb#3439]
### Describe the bug

I started writing into the table using HTTP REST API, it was working fine and after sometime I noticed that the table is getting stuck and the writer is not able to write to the table .

If I write the same data in a new table then it is able to write to it, the issue starts to coming out after the row count in the table starts increasing.

I also tried to write using ILP protocol, then I'm getting Error 104, Connection reset by peer.

### To reproduce

1. Start writing to a table using HTTP REST API through python
2. After the table has say more than 150k records, the issue seems to be coming.

### Expected Behavior

It should write to the table instead of acquiring lock and getting stuck forever .

### Environment

```markdown
- **QuestDB version**: 7.0.1
- **OS**: Ubuntu 22.04.2 LTS
```

### Additional context

2023-05-31T12:48:51.297492Z A server-main enjoy
2023-05-31T12:52:31.324541Z I http-server connected [ip=193.148.250.63, fd=114]
2023-05-31T12:52:31.325823Z I i.q.c.t.TextLoader configured [table=`9839131_preprocessed_V_L_1_0`, overwrite=false, durable=false, atomicity=2, partitionBy=NONE, timestamp=null, timestampFo
rmat=null]
2023-05-31T12:52:31.342409Z I i.q.c.t.TextDelimiterScanner scan result [table=`9839131_preprocessed_V_L_1_0`, delimiter=',', priority=10, mean=1045.0, stddev=0.0]
2023-05-31T12:52:31.343215Z I i.q.s.ObjectPool pool resize [class=io.questdb.std.str.DirectByteCharSequence$Factory, size=128]
2023-05-31T12:52:31.343861Z I i.q.s.ObjectPool pool resize [class=io.questdb.std.str.DirectByteCharSequence$Factory, size=256]
2023-05-31T12:52:31.345559Z I i.q.s.ObjectPool pool resize [class=io.questdb.std.str.DirectByteCharSequence$Factory, size=512]
2023-05-31T12:52:31.348577Z I i.q.s.ObjectPool pool resize [class=io.questdb.std.str.DirectByteCharSequence$Factory, size=1024]
2023-05-31T12:52:31.350696Z I i.q.s.ObjectPool pool resize [class=io.questdb.std.str.DirectByteCharSequence$Factory, size=2048]
2023-05-31T12:52:31.417019Z I i.q.c.t.AbstractTextLexer resizing 1024 -> 5508 [table=9839131_preprocessed_V_L_1_0]
2023-05-31T12:52:31.418995Z I i.q.c.p.WriterPool open [table=`9839131_preprocessed_V_L_1_0`, thread=42]
2023-05-31T12:52:31.419066Z I i.q.c.TableWriter open '9839131_preprocessed_V_L_1_0'
2023-05-31T12:52:31.419239Z I i.q.c.TableUtils locked '/home/saurabh/.questdb/db/9839131_preprocessed_V_L_1_0.lock' [fd=115]
2023-05-31T12:52:31.497434Z I i.q.c.TableWriter switched partition [path='/home/saurabh/.questdb/db/9839131_preprocessed_V_L_1_0/default']
2023-05-31T12:52:31.513019Z I i.q.c.p.WriterPool >> [table=`9839131_preprocessed_V_L_1_0`, thread=42]
2023-05-31T12:52:31.513130Z I i.q.c.t.CairoTextWriter mis-detected [table=9839131_preprocessed_V_L_1_0, column=0, type=STRING]
2023-05-31T12:52:31.516692Z I i.q.c.t.CairoTextWriter cannot update metadata attributes o3MaxLag and maxUncommittedRows when the table exists and parameter overwrite is false
2023-05-31T12:52:31.566860Z C server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@6581dc0a, ex=
java.lang.AssertionError
        at io.questdb.cairo.TableWriter.setRowValueNotNull(TableWriter.java:6073)
        at io.questdb.cairo.TableWriter$RowImpl.putDouble(TableWriter.java:6911)
        at io.questdb.cutlass.text.types.DoubleAdapter.write(DoubleAdapter.java:61)
        at io.questdb.cutlass.text.CairoTextWriter.onField(CairoTextWriter.java:237)
        at io.questdb.cutlass.text.CairoTextWriter.onFieldsNonPartitioned(CairoTextWriter.java:162)
        at io.questdb.cutlass.text.AbstractTextLexer.triggerLine(AbstractTextLexer.java:394)
        at io.questdb.cutlass.text.AbstractTextLexer.onLineEnd(AbstractTextLexer.java:436)
        at io.questdb.cutlass.text.CsvTextLexer.doSwitch(CsvTextLexer.java:42)
        at io.questdb.cutlass.text.AbstractTextLexer.parse0(AbstractTextLexer.java:303)
        at io.questdb.cutlass.text.AbstractTextLexer.parse(AbstractTextLexer.java:102)
        at io.questdb.cutlass.text.AbstractTextLexer.parse(AbstractTextLexer.java:97)
        at io.questdb.cutlass.text.TextLoader.parse(TextLoader.java:222)
        at io.questdb.cutlass.text.TextLoader.parseStructure(TextLoader.java:337)
        at io.questdb.cutlass.text.TextLoader.parse(TextLoader.java:226)
        at io.questdb.cutlass.http.processors.TextImportProcessor.onChunk(TextImportProcessor.java:97)
        at io.questdb.cutlass.http.HttpMultipartContentParser.onChunkWithRetryHandle(HttpMultipartContentParser.java:258)
        at io.questdb.cutlass.http.HttpMultipartContentParser.parse(HttpMultipartContentParser.java:222)
        at io.questdb.cutlass.http.HttpConnectionContext.parseMultipartResult(HttpConnectionContext.java:683)
        at io.questdb.cutlass.http.HttpConnectionContext.continueConsumeMultipart(HttpConnectionContext.java:396)
        at io.questdb.cutlass.http.HttpConnectionContext.consumeMultipart(HttpConnectionContext.java:380)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:588)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:203)
        at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:86)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
        at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:101)
        at io.questdb.mp.Worker.run(Worker.java:118)

**Comment by bziobrowski** [comment]
Could you please try upgrading to  7.0.1 and reproducing the issue ?

**Comment by saurabhk3** [comment]
We are using 7.0.1 only

**Comment by saurabhk3** [comment]
@puzpuzpuz sure, I'll update to latest release.
Regarding your 2nd point, I've one more instance of Questdb running on a separate machine and there it wrote properly using the same code.

**Comment by puzpuzpuz** [comment]
That's really weird since the error looks a lot like a sneaky bug.

**Comment by saurabhk3** [comment]
I'll upgrade it to latest release and if the issue is still coming will let you know!

**Comment by chinmay74810** [comment]
Error looks a lot like a sneaky bug.
