### ISSUE TITLE
Flaky LineTcpReceiverTest.testMetaDataSizeToHitExactly16K test

### ISSUE THREAD

**Issue by bziobrowski** [questdb/questdb#3464]
### Describe the bug

Test failed in mac-other. 
It often takes 5+ minutes to finish in CI . 

2023-06-09T15:16:03.4356750Z 2023-06-09T15:16:03.434991Z I i.q.c.p.WriterPool << [table=`ĐĽĐµŃ‚ĐµĐľŃ€ĐľĐ»ĐľĐłĐ¸Ń‡Đ˝Đľ_Đ˛Ń€ĐµĐĽĐµ~1`, thread=1020]
2023-06-09T15:16:03.4359220Z 2023-06-09T15:16:03.435247Z I i.q.c.p.ReaderPool open 'ĐĽĐµŃ‚ĐµĐľŃ€ĐľĐ»ĐľĐłĐ¸Ń‡Đ˝Đľ_Đ˛Ń€ĐµĐĽĐµ~1' [at=0:0]
2023-06-09T15:16:03.4374550Z 2023-06-09T15:16:03.437216Z I i.q.t.AbstractCairoTest Tearing down test LineTcpReceiverTest#testMetaDataSizeToHitExactly16K[WITH_WAL]
2023-06-09T15:16:03.4378780Z 2023-06-09T15:16:03.437470Z I i.q.c.p.ReaderPool closed 'ĐĽĐµŃ‚ĐµĐľŃ€ĐľĐ»ĐľĐłĐ¸Ń‡Đ˝Đľ_Đ˛Ń€ĐµĐĽĐµ~1' [at=0:0, reason=POOL_CLOSED]
2023-06-09T15:16:04.6920460Z 2023-06-09T15:16:04.691161Z I i.q.c.TableWriter closed 'ĐĽĐµŃ‚ĐµĐľŃ€ĐľĐ»ĐľĐłĐ¸Ń‡Đ˝Đľ_Đ˛Ń€ĐµĐĽĐµ'
2023-06-09T15:16:04.6931740Z 2023-06-09T15:16:04.691166Z I i.q.c.p.WriterPool closed [table=`ĐĽĐµŃ‚ĐµĐľŃ€ĐľĐ»ĐľĐłĐ¸Ń‡Đ˝Đľ_Đ˛Ń€ĐµĐĽĐµ~1`, reason=POOL_CLOSED, by=1020]
2023-06-09T15:16:04.6932990Z 2023-06-09T15:16:04.691517Z I i.q.c.w.s.TableSequencerAPI releasing idle table sequencer [tableDir=ĐĽĐµŃ‚ĐµĐľŃ€ĐľĐ»ĐľĐłĐ¸Ń‡Đ˝Đľ_Đ˛Ń€ĐµĐĽĐµ~1]
2023-06-09T15:16:08.5748090Z 2023-06-09T15:16:07.833570Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.testMetaDataSizeToHitExactly16K[WITH_WAL] duration_ms=107297 : 
2023-06-09T15:16:08.5749310Z java.lang.AssertionError: expected:<256> but was:<213>
2023-06-09T15:16:08.5749910Z 	at org.junit.Assert.fail(Assert.java:89)
2023-06-09T15:16:08.5750530Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2023-06-09T15:16:08.5751160Z 	at org.junit.Assert.assertEquals(Assert.java:647)
2023-06-09T15:16:08.5751760Z 	at org.junit.Assert.assertEquals(Assert.java:633)
2023-06-09T15:16:08.5752440Z 	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.testMetaDataSizeToHitExactly16K(LineTcpReceiverTest.java:594)
2023-06-09T15:16:08.5753130Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-09T15:16:08.5753800Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-06-09T15:16:08.5754510Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-09T15:16:08.5755180Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2023-06-09T15:16:08.5755790Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-06-09T15:16:08.5757150Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-06-09T15:16:08.5757850Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-06-09T15:16:08.5758530Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-06-09T15:16:08.5759210Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2023-06-09T15:16:08.5759860Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2023-06-09T15:16:08.5760530Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2023-06-09T15:16:08.5761220Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2023-06-09T15:16:08.5761930Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2023-06-09T15:16:08.5762600Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-06-09T15:16:08.5763200Z 	at java.lang.Thread.run(Thread.java:829)
2023-06-09T15:16:08.5764060Z 2023-06-09T15:16:07.833667Z I i.q.t.TestListener <<<< io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.testMetaDataSizeToHitExactly16K[WITH_WAL] duration_ms=107297

### Environment

```markdown
- **QuestDB version**: latest master
- **OS**: mac
- **Browser**:
```

**Comment by bziobrowski** [comment]
[test_log.txt](https://github.com/questdb/questdb/files/11707977/test_log.txt)
