### ISSUE TITLE
NullPointerException: Cannot read field "type" because "column" is null

### ISSUE THREAD

**Issue by YuanchengJiang** [questdb/questdb#3468]
### Describe the bug

```
java.lang.NullPointerException: Cannot read field "type" because "column" is null
	at io.questdb.griffin.SqlOptimiser.isSimpleIntegerColumn(SqlOptimiser.java:2071)
	at io.questdb.griffin.SqlOptimiser.pushOperationOutsideAgg(SqlOptimiser.java:3026)
	at io.questdb.griffin.SqlOptimiser.rewriteAggregate(SqlOptimiser.java:3314)
	at io.questdb.griffin.SqlOptimiser.rewriteSelectClause0(SqlOptimiser.java:3945)
	at io.questdb.griffin.SqlOptimiser.rewriteSelectClause(SqlOptimiser.java:3865)
	at io.questdb.griffin.SqlOptimiser.rewriteSelectClause(SqlOptimiser.java:3852)
	at io.questdb.griffin.SqlOptimiser.rewriteSelectClause(SqlOptimiser.java:3852)
	at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:4707)
	at io.questdb.griffin.SqlCompiler.compileExecutionModel0(SqlCompiler.java:1192)
	at io.questdb.griffin.SqlCompiler.compileExecutionModel(SqlCompiler.java:1181)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1264)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1233)
	at io.questdb.griffin.SqlCompiler.compileBatch(SqlCompiler.java:274)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:2243)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1663)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:406)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:95)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:132)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

### To reproduce

```
create table test(time TIMESTAMP NOT NULL, symbol STRING NOT NULL);
insert into test values ('2023-04-14 19:10:48.002','INTC');
SELECT test.time AS ref0, test.symbol AS ref1 FROM test GROUP BY test.time, test.symbol ORDER BY SUM(1, -1);
```

### Environment

```markdown
- **QuestDB version**: 7.2.0
- **OS**: ubuntu 20.04
- **Browser**:
```

**Comment by puzpuzpuz** [comment]
Fixed by #3479
