### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0 at io.questdb.std.LongList.extendAndSet

### ISSUE THREAD

**Issue by YuanchengJiang** [questdb/questdb#3469]
### Describe the bug

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at io.questdb.std.LongList.extendAndSet(LongList.java:232)
	at io.questdb.griffin.engine.functions.bool.InLongFunctionFactory.parseToLong(InLongFunctionFactory.java:89)
	at io.questdb.griffin.engine.functions.bool.InLongFunctionFactory.newInstance(InLongFunctionFactory.java:80)
	at io.questdb.griffin.FunctionParser.checkAndCreateFunction(FunctionParser.java:386)
	at io.questdb.griffin.FunctionParser.createFunction(FunctionParser.java:779)
	at io.questdb.griffin.FunctionParser.visit(FunctionParser.java:311)
	at io.questdb.griffin.PostOrderTreeTraversalAlgo.traverse(PostOrderTreeTraversalAlgo.java:86)
	at io.questdb.griffin.FunctionParser.parseFunction(FunctionParser.java:239)
	at io.questdb.griffin.SqlCodeGenerator.compileBooleanFilter(SqlCodeGenerator.java:177)
	at io.questdb.griffin.SqlCodeGenerator.generateFilter0(SqlCodeGenerator.java:1349)
	at io.questdb.griffin.SqlCodeGenerator.generateFilter(SqlCodeGenerator.java:1334)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2295)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3672)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectGroupBy(SqlCodeGenerator.java:3166)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2690)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:200)
	at io.questdb.griffin.SqlCompiler.generate(SqlCompiler.java:2692)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1268)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1233)
	at io.questdb.griffin.SqlCompiler.compileBatch(SqlCompiler.java:274)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:2243)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1663)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:406)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:95)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:132)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

### To reproduce

```
SELECT COUNT(*) FROM telemetry WHERE telemetry.event>(telemetry.event IN ());
```

### Environment

```markdown
- **QuestDB version**: 7.2.0
- **OS**: ubuntu 20.04
```

**Comment by puzpuzpuz** [comment]
Fixed by #3479
