### ISSUE TITLE
InvalidColumnException on LT JOIN SELECT

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#3509]
### Describe the bug

InvalidColumnException error occurs on some LT JOIN SELECTs with specific column.

### To reproduce

1. Download&Install QDB 7.2 for windows
2. Download [this](https://www.kaggle.com/competitions/store-sales-time-series-forecasting/data?select=train.csv) dataset
3. import into qdb, default settings
4. run this
```
CREATE TABLE 'train' (
  id DOUBLE,
  date TIMESTAMP,
  store_nbr DOUBLE,
  family SYMBOL,
  sales DOUBLE,
  onpromotion DOUBLE
) timestamp(date);
```
6. run this
`INSERT INTO train SELECT * FROM train.csv`
8. run this
`SELECT sales1 FROM (train d LT JOIN (train c LT JOIN (train b LT JOIN (train a WHERE a.date<'2017-08-01' and a.date>'2017-06-15' AND a.family='HOME AND KITCHEN I') ON family WHERE b.date<'2017-08-01' and b.date>'2017-06-15' AND b.family='HOME AND KITCHEN I') ON family WHERE c.date<'2017-08-01' and c.date>'2017-06-15' AND c.family='HOME AND KITCHEN I') ON family WHERE d.date<'2017-08-01' and d.date>'2017-06-15' AND d.family='HOME AND KITCHEN I') LIMIT 3,99999999999999999`
10. observe error, search log for `InvalidColumnException`

### Expected Behavior

the result of the query should be returned

### Environment

```markdown
- **QuestDB version**: 7.2
- **OS**: windows
- **Browser**: chrome latest
```

### Additional context

```
2023-06-23T11:23:07.384305Z I i.q.c.h.p.JsonQueryProcessorState [2256] exec [q='SELECT sales1 FROM (train d LT JOIN (train c LT JOIN (train b LT JOIN (train a WHERE a.date<'2017-08-01' and a.date>'2017-06-15' AND a.family='HOME AND KITCHEN I') ON family WHERE b.date<'2017-08-01' and b.date>'2017-06-15' AND b.family='HOME AND KITCHEN I') ON family WHERE c.date<'2017-08-01' and c.date>'2017-06-15' AND c.family='HOME AND KITCHEN I') ON family WHERE d.date<'2017-08-01' and d.date>'2017-06-15' AND d.family='HOME AND KITCHEN I') LIMIT 3,99999999999999999']
2023-06-23T11:23:07.384320Z I i.q.c.h.p.QueryCache miss [thread=questdb-shared-3, sql=SELECT sales1 FROM (train d LT JOIN (train c LT JOIN (train b LT JOIN (train a WHERE a.date<'2017-08-01' and a.date>'2017-06-15' AND a.family='HOME AND KITCHEN I') ON family WHERE b.date<'2017-08-01' and b.date>'2017-06-15' AND b.family='HOME AND KITCHEN I') ON family WHERE c.date<'2017-08-01' and c.date>'2017-06-15' AND c.family='HOME AND KITCHEN I') ON family WHERE d.date<'2017-08-01' and d.date>'2017-06-15' AND d.family='HOME AND KITCHEN I') LIMIT 3,99999999999999999]
2023-06-23T11:23:07.386101Z I i.q.g.SqlCompiler plan [q=`select-choose sales1 from (select-choose [_xQdbA2.sales sales1] d.id id, d.date date, d.store_nbr store_nbr, d.family family, d.sales sales, d.onpromotion onpromotion, _xQdbA2.id id1, _xQdbA2.date date1, _xQdbA2.store_nbr store_nbr1, _xQdbA2.family family1, _xQdbA2.sales sales1, _xQdbA2.onpromotion onpromotion1, _xQdbA2.id1 id11, _xQdbA2.date1 date11, _xQdbA2.store_nbr1 store_nbr11, _xQdbA2.family1 family11, _xQdbA2.sales1 sales11, _xQdbA2.onpromotion1 onpromotion11, _xQdbA2.id11 id111, _xQdbA2.date11 date111, _xQdbA2.store_nbr11 store_nbr111, _xQdbA2.family11 family111, _xQdbA2.sales11 sales111, _xQdbA2.onpromotion11 onpromotion111 from (select [family, date] from train d timestamp (date) lt join select [sales] from (select-choose [c.sales sales] c.id id, c.date date, c.store_nbr store_nbr, c.family family, c.sales sales, c.onpromotion onpromotion, _xQdbA3.id id1, _xQdbA3.date date1, _xQdbA3.store_nbr store_nbr1, _xQdbA3.family family1, _xQdbA3.sales sales1, _xQdbA3.onpromotion onpromotion1, _xQdbA3.id1 id11, _xQdbA3.date1 date11, _xQdbA3.store_nbr1 store_nbr11, _xQdbA3.family1 family11, _xQdbA3.sales1 sales11, _xQdbA3.onpromotion1 onpromotion11 from (select [sales, family, date] from train c timestamp (date) lt join (select-choose b.id id, b.date date, b.store_nbr store_nbr, b.family family, b.sales sales, b.onpromotion onpromotion, _xQdbA4.id id1, _xQdbA4.date date1, _xQdbA4.store_nbr store_nbr1, _xQdbA4.family family1, _xQdbA4.sales sales1, _xQdbA4.onpromotion onpromotion1 from (select [id, date, store_nbr, family, sales, onpromotion] from train b timestamp (date) lt join select [id, date, store_nbr, family, sales, onpromotion] from (select-choose [id, date, store_nbr, family, sales, onpromotion] id, date, store_nbr, family, sales, onpromotion from (select [id, date, store_nbr, family, sales, onpromotion] from train a timestamp (date) where date < '2017-08-01' and date > '2017-06-15' and family = 'HOME AND KITCHEN I' and family = 'HOME AND KITCHEN I') a) _xQdbA4 on family = b.family where family = 'HOME AND KITCHEN I' and date < '2017-08-01' and date > '2017-06-15' and family = 'HOME AND KITCHEN I') b) _xQdbA3 on b.family = c.family where family = 'HOME AND KITCHEN I' and date < '2017-08-01' and date > '2017-06-15' and family = 'HOME AND KITCHEN I') c) _xQdbA2 on c.family = d.family where family = 'HOME AND KITCHEN I' and date < '2017-08-01' and date > '2017-06-15') d) limit 3,99999999999999999`, fd=2256]
2023-06-23T11:23:07.386496Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=d, fd=2256]
2023-06-23T11:23:07.386915Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=c, fd=2256]
2023-06-23T11:23:07.387567Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=b, fd=2256]
2023-06-23T11:23:07.388228Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=a, fd=2256]
2023-06-23T11:23:07.405448Z C i.q.c.h.p.JsonQueryProcessorState [2256] Uh-oh. Error!
io.questdb.cairo.sql.InvalidColumnException
	at io.questdb.cairo.sql.InvalidColumnException.<clinit>(InvalidColumnException.java:28)
	at io.questdb.cairo.sql.RecordMetadata.getColumnIndex(RecordMetadata.java:61)
	at io.questdb.griffin.SqlCodeGenerator.lookupColumnIndexesUsingVanillaNames(SqlCodeGenerator.java:4431)
	at io.questdb.griffin.SqlCodeGenerator.processJoinContext(SqlCodeGenerator.java:4498)
	at io.questdb.griffin.SqlCodeGenerator.generateJoins(SqlCodeGenerator.java:1602)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2701)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3672)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:2931)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2688)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3672)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:2931)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2688)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3672)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectGroupBy(SqlCodeGenerator.java:3225)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2690)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3672)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectVirtual(SqlCodeGenerator.java:3410)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2692)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:3672)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:2931)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2688)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:200)
	at io.questdb.griffin.SqlCompiler.generate(SqlCompiler.java:2692)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1268)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1233)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:220)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:421)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:184)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:234)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:627)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:209)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:86)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:101)
	at io.questdb.mp.Worker.run(
2023-06-23T11:23:07.405605Z I i.q.c.h.HttpConnectionContext kicked out [fd=2256]
2023-06-23T11:23:07.405608Z I http-server scheduling disconnect [fd=2256, reason=5]
2023-06-23T11:23:07.405626Z I http-server disconnected [ip=127.0.0.1, fd=2256, src=queue]
```

**Comment by superichmann** [comment]
it seems that I did not put the lt join aliases at the correct place so here is the correct select and bug is solved as well
```
SELECT sales1 FROM 
((train d LT JOIN 
(train c LT JOIN 
(train b LT JOIN 
(train) a ON family WHERE a.date<'2017-08-01' and a.date>'2017-06-15' AND a.family='HOME AND KITCHEN I') b
 ON family WHERE b.date<'2017-08-01' and b.date>'2017-06-15' AND b.family='HOME AND KITCHEN I') c
  ON family WHERE c.date<'2017-08-01' and c.date>'2017-06-15' AND c.family='HOME AND KITCHEN I') d
    WHERE d.date<'2017-08-01' and d.date>'2017-06-15' AND d.family='HOME AND KITCHEN I')
    LIMIT 3,99999999999999999
```
