### ISSUE TITLE
Unable to create table using 7.2 embedded on windows

### ISSUE THREAD

**Issue by sarunas-stasaitis** [questdb/questdb#3538]
### Describe the bug

Provided code fails on 7.2, works on 7.1

```
import io.questdb.cairo.CairoConfiguration;
import io.questdb.cairo.CairoEngine;
import io.questdb.cairo.DefaultCairoConfiguration;
import io.questdb.griffin.SqlCompiler;
import io.questdb.griffin.SqlException;
import io.questdb.griffin.SqlExecutionContextImpl;

public class CreateTable {

    public static void main(String[] args) throws SqlException {

        String qdbDir = "F:/test/questdb";

        CairoConfiguration configuration = new DefaultCairoConfiguration(qdbDir);
        try(CairoEngine engine = new CairoEngine(configuration)) {
            final SqlExecutionContextImpl ctx = new SqlExecutionContextImpl(engine, 1);
            try (SqlCompiler compiler = new SqlCompiler(engine)) {
                compiler.compile("""
                    CREATE TABLE IF NOT EXISTS entries (
                        instant TIMESTAMP,
                        level SYMBOL,
                        logger SYMBOL CAPACITY 4096,
                        className SYMBOL CAPACITY 4096,
                        methodName SYMBOL CAPACITY 4096,
                        message STRING
                    ) timestamp(instant) PARTITION BY DAY WAL
                    """, ctx);
            }
        }
    }
}

```

### To reproduce

1. Run main with 7.2, where `qdbDir` points to an empty directory

### Expected Behavior

Expected output:

```
Log configuration loaded from default internal file.
2023-07-04T08:30:19.426088Z I i.q.c.t.t.InputFormatConfiguration loading input format config [resource=/text_loader.json]
2023-07-04T08:30:19.594221Z I i.q.c.m.EngineMigration upgrading database [version=427]
2023-07-04T08:30:19.597286Z I i.q.c.m.EngineMigration upgraded tables to 427
2023-07-04T08:30:19.607830Z I i.q.c.TableUtils locked 'F:\test\questdb\tables.d.lock' [fd=2488]
2023-07-04T08:30:19.609049Z I i.q.c.TableNameRegistryFileStore reloading tables file [path=F:\test\questdb\tables.d.0]
2023-07-04T08:30:19.711256Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2023-07-04T08:30:20.221710Z I i.q.c.TableUtils locked 'F:\test\questdb\entries~1.lock' [fd=2316]
2023-07-04T08:30:20.221906Z I i.q.c.CairoEngine locked [table=`entries~1`, thread=1]
2023-07-04T08:30:20.259810Z I i.q.c.p.WriterPool created [table=`entries~1`, thread=1]
2023-07-04T08:30:20.277935Z I i.q.c.TableWriter open 'entries'

Process finished with exit code 0
```

Actual output:

```
Log configuration loaded from default internal file.
2023-07-04T08:31:51.292940Z I i.q.c.t.t.InputFormatConfiguration loading input format config [resource=/text_loader.json]
2023-07-04T08:31:51.334329Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2023-07-04T08:31:51.711426Z I i.q.c.m.EngineMigration upgrading database [version=427]
2023-07-04T08:31:51.714011Z I i.q.c.m.EngineMigration upgraded tables to 427
2023-07-04T08:31:51.725991Z I i.q.c.TableNameRegistryFileStore reloading tables file [path=F:\test\questdb\tables.d.0]
Exception in thread "main" io.questdb.griffin.SqlException: [27] Could not create table, Write permission denied
	at io.questdb.std.ThreadLocal.get(ThreadLocal.java:46)
	at io.questdb.griffin.SqlException.position(SqlException.java:105)
	at io.questdb.griffin.SqlException.$(SqlException.java:48)
	at io.questdb.griffin.SqlCompiler.createTable(SqlCompiler.java:1644)
	at io.questdb.griffin.SqlCompiler.executeWithRetries(SqlCompiler.java:1783)
	at io.questdb.griffin.SqlCompiler.createTableWithRetries(SqlCompiler.java:1731)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1270)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1233)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:220)
	at lt.energyadvice.test.questdb.CreateTable.main(CreateTable.java:22)
2023-07-04T08:31:51.889642Z E i.q.g.SqlCompiler could not create table [error=
io.questdb.cairo.CairoException: [-1] Write permission denied
]
2023-07-04T08:31:51.890772Z I i.q.c.p.WriterPool closed
2023-07-04T08:31:51.890829Z I i.q.c.p.ReaderPool closed
2023-07-04T08:31:51.890871Z I i.q.c.p.MetadataPool closed
2023-07-04T08:31:51.890918Z I i.q.c.p.WalWriterPool closed

Process finished with exit code 1

```

### Environment

```markdown
- **QuestDB version**: 7.2
- **OS**: Windows 10
```

**Comment by sarunas-stasaitis** [comment]
Table creation with added `.with(AllowAllSecurityContext.INSTANCE, null);` works.
