### ISSUE TITLE
Database backup fails

### ISSUE THREAD

**Issue by 100le** [questdb/questdb#3560]
This issue is regarding the same tables that were reported at -> https://github.com/questdb/questdb/issues/3500 

After applying the suggested workaround the tables were altered successfully but now the database backup fails constantly.
I upgraded now to the latest version 7.2.1 were the mentioned issue was fixed, i converted the tables again to Non-WAL and then back to WAL but i cannot still do a successful backup running the query 'BACKUP database;' from the QuestDB Console.

Error message: "backup dir already exists [path=/backup/questdb/tmp/sensor_sample_431886/, table=sensor_sample_431886]"

I removed manually all directories in the backup/questdb directory and tried again but again the above issue is shown.

### Environment

```markdown
- **QuestDB version**: 7.2.1
- **OS**: CentOS
- **Browser**: Any
```

### Additional context

Logs from questdb:

```2023-07-11T19:41:42.514687Z C i.q.c.h.p.JsonQueryProcessorState [319] Uh-oh. Err                                                                                                                                                             or!
java.lang.AssertionError: index out of bounds, 14 >= 14
        at io.questdb.std.ObjList.getQuick(ObjList.java:173)
        at io.questdb.cairo.AbstractRecordMetadata.getColumnMetadata(AbstractRec                                                                                                                                                             ordMetadata.java:63)
        at io.questdb.cairo.AbstractRecordMetadata.getColumnType(AbstractRecordM                                                                                                                                                             etadata.java:73)
        at io.questdb.griffin.RecordToRowCopierUtils.generateCopier(RecordToRowC                                                                                                                                                             opierUtils.java:156)
        at io.questdb.griffin.SqlCompiler$DatabaseBackupAgent.backupTable(SqlCom                                                                                                                                                             piler.java:3031)
        at io.questdb.griffin.SqlCompiler$DatabaseBackupAgent.sqlDatabaseBackup(                                                                                                                                                             SqlCompiler.java:3124)
        at io.questdb.griffin.SqlCompiler$DatabaseBackupAgent.sqlBackup(SqlCompi                                                                                                                                                             ler.java:3110)
        at io.questdb.griffin.SqlCompiler.lambda$registerKeywordBasedExecutors$1                                                                                                                                                             (SqlCompiler.java:2667)
        at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1231)
        at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:219)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(Js                                                                                                                                                             onQueryProcessor.java:421)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQu                                                                                                                                                             eryProcessor.java:184)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComple                                                                                                                                                             te(JsonQueryProcessor.java:234)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpCo                                                                                                                                                             nnectionContext.java:627)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(H                                                                                                                                                             ttpConnectionContext.java:209)
        at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:86)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODisp                                                                                                                                                             atcher.java:189)
        at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:101)
        at io.questdb.mp.Worker.run(Worker.java:118)

2023-07-11T19:41:42.515921Z I i.q.c.h.HttpConnectionContext kicked out [fd=319]
```

**Comment by bluestreak01** [comment]
hi @100le, are you running QuestDB instance in cloud environment or custom hardware?

**Comment by 100le** [comment]
Its a dedicated server with CentOS installed. We are managing our own QuestDB instance using the Linux
64-bit rt distribution.

**Comment by 100le** [comment]
To be even scarier, now the inserts are failing which were working before the version upgrade and when the tables were non-WAL.
Exceptio:
`
2023-07-11T20:02:30.085328Z I i.q.c.w.WalWriter closed 'sensor_sample_975429'
2023-07-11T20:02:30.091378Z C i.q.c.p.PGWireServer internal error [ex=
java.lang.AssertionError
        at io.questdb.std.IntList.getQuick(IntList.java:135)
        at io.questdb.std.IntList.get(IntList.java:115)
        at io.questdb.cairo.TxReader.getSymbolValueCount(TxReader.java:337)
        at io.questdb.cairo.wal.WalWriter.configureSymbolTable(WalWriter.java:956)
        at io.questdb.cairo.wal.WalWriter.<init>(WalWriter.java:150)
        at io.questdb.cairo.pool.WalWriterPool$WalWriterTenant.<init>(WalWriterPool.java:66)
        at io.questdb.cairo.pool.WalWriterPool.newTenant(WalWriterPool.java:50)
        at io.questdb.cairo.pool.WalWriterPool.newTenant(WalWriterPool.java:34)
        at io.questdb.cairo.pool.AbstractMultiTenantPool.get(AbstractMultiTenantPool.java:91)
        at io.questdb.cairo.CairoEngine.getTableWriterAPI(CairoEngine.java:500)
        at io.questdb.cutlass.pgwire.PGConnectionContext.getTableWriterAPI(PGConnectionContext.java:347)
        at io.questdb.griffin.engine.ops.InsertOperationImpl.createMethod(InsertOperationImpl.java:65)
        at io.questdb.cutlass.pgwire.PGConnectionContext.executeInsert(PGConnectionContext.java:1301)
        at io.questdb.cutlass.pgwire.PGConnectionContext.processExecute(PGConnectionContext.java:2155)
        at io.questdb.cutlass.pgwire.PGConnectionContext.processExec(PGConnectionContext.java:2141)
        at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1631)
        at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:406)
        at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
        at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:95)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
        at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:132)
        at io.questdb.mp.Worker.run(Worker.java:118)
]

`

**Comment by bluestreak01** [comment]
Were there any power failures on the server?

**Comment by 100le** [comment]
Not that i was aware off. Last system boot was 3 months ago. 
P.S. The above exception in the previous comment is not appearing now when i converted back the tables to Non-WAL.

**Comment by bluestreak01** [comment]
as a workaround for the backup, I would suggest you try this method: https://questdb.io/docs/reference/sql/snapshot/

`SNAPSHOT PREPARE` puts database in "ready" mode after which you can copy database directories elsewhere. After that `SNAPSHOT COMPLETE` to put database in "normal" mode

**Comment by bluestreak01** [comment]
please ping me on slack if you're there, we will try to diagnose the issue
