### ISSUE TITLE
NullPointerException in COUNT(SELECT DISTINCT ...) query

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3564]
### Describe the bug

```sql
create table x (s string, ts timestamp) timestamp(ts) partition by day;
```

Query
```sql
COUNT(SELECT DISTINCT s FROM x WHERE right(s, 1)='/');
```

leads to the following NPE:
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "l" is null
	at io.questdb.std.Chars.equals(Chars.java:293)
	at io.questdb.griffin.SqlParser.rewriteCount0(SqlParser.java:2008)
	at io.questdb.griffin.PostOrderTreeTraversalAlgo.traverse(PostOrderTreeTraversalAlgo.java:86)
	at io.questdb.griffin.SqlParser.rewriteCount(SqlParser.java:1991)
	at io.questdb.griffin.SqlParser.rewriteKnownStatements(SqlParser.java:2023)
	at io.questdb.griffin.SqlParser.expr(SqlParser.java:2182)
	at io.questdb.griffin.SqlParser.parseSelectFrom(SqlParser.java:1701)
	at io.questdb.griffin.SqlParser.parseFromClause(SqlParser.java:1113)
	at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:921)
	at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:816)
	at io.questdb.griffin.SqlParser.parseSelect(SqlParser.java:1550)
	at io.questdb.griffin.SqlParser.parse(SqlParser.java:2237)
	at io.questdb.griffin.SqlCompiler.compileExecutionModel(SqlCompiler.java:1179)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1265)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1234)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:219)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:421)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:184)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:234)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:627)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:209)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:86)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:101)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

### Environment

```markdown
- **QuestDB version**: 7.2.1
- **OS**:
- **Browser**:
```

**Comment by ritik94155** [comment]
Right extracts number of character not the string so number can't be equal to a string. We can use here Substring() to fetch character
