### ISSUE TITLE
bug in case function with symbols

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3600]
### Describe the bug

CASE function does not work well with Symbol. Run this SQL:
```sql
SELECT CASE WHEN s = '1' THEN 'Important' ELSE 'Not important' END FROM (
  select rnd_symbol('1', '2') as s from long_sequence(5)
);
```
This fails with this error in the server log:
```
2023-07-26T15:00:59.653158Z I i.q.g.SqlCompiler parse [fd=103, q=SELECT CASE WHEN s = '1' THEN 'Important' ELSE 'Not important' END FROM (
  select rnd_symbol('1', '2') as s from long_sequence(5)
)]
2023-07-26T15:00:59.653892Z I i.q.g.SqlCompiler plan [q=`select-virtual switch(s,'1','Important','Not important') switch from (select-virtual [rnd_symbol('1','2') s] rnd_symbol('1','2') s from (long_sequence(5)))`, fd=103]
2023-07-26T15:00:59.655463Z E i.q.g.FunctionParser exception in function factory: 
java.lang.UnsupportedOperationException
	at io.questdb.griffin.engine.functions.CharFunction.getSymbol(CharFunction.java:182)
	at io.questdb.griffin.engine.functions.conditional.SwitchFunctionFactory.getSymbol(SwitchFunctionFactory.java:160)
	at io.questdb.griffin.engine.functions.conditional.SwitchFunctionFactory.getCharSequenceKeyedFunction(SwitchFunctionFactory.java:182)
	at io.questdb.griffin.engine.functions.conditional.SwitchFunctionFactory.newInstance(SwitchFunctionFactory.java:122)
	at io.questdb.griffin.FunctionParser.checkAndCreateFunction(FunctionParser.java:386)
	at io.questdb.griffin.FunctionParser.createFunction(FunctionParser.java:779)
	at io.questdb.griffin.FunctionParser.visit(FunctionParser.java:311)
	at io.questdb.griffin.PostOrderTreeTraversalAlgo.traverse(PostOrderTreeTraversalAlgo.java:96)
	at io.questdb.griffin.FunctionParser.parseFunction(FunctionParser.java:239)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectVirtualWithSubQuery(SqlCodeGenerator.java:3439)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectVirtual(SqlCodeGenerator.java:3411)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2692)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2283)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:200)
	at io.questdb.griffin.SqlCompiler.generate(SqlCompiler.java:2768)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1380)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1345)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:223)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:424)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:187)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:237)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:627)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:209)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:86)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:101)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

Tested on 1ea150b6c49da0ab1

**Comment by jerrinot** [comment]
this is working fine as of QuestDB 8.0
