### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: 0 with ORDER BY empty string

### ISSUE THREAD

**Issue by YuanchengJiang** [questdb/questdb#3623]
### Describe the bug

QuestDB: consuming input failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.lang.String.charAt(String.java:1513)
	at io.questdb.griffin.SqlOptimiser.rewriteOrderByPosition(SqlOptimiser.java:3789)
	at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:4715)
	at io.questdb.griffin.SqlCompiler.compileExecutionModel0(SqlCompiler.java:1296)
	at io.questdb.griffin.SqlCompiler.compileExecutionModel(SqlCompiler.java:1285)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1380)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1349)
	at io.questdb.griffin.SqlCompiler.compileBatch(SqlCompiler.java:279)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:2282)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1695)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:412)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:95)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:132)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

### To reproduce

```
SELECT 1 FROM telemetry ORDER BY ""
```

### Environment

```markdown
- **QuestDB version**: v7.3.0
```

**Comment by puzpuzpuz** [comment]
@bziobrowski looks like we were working on the same issues concurrently. :(

Could you assign yourself to the issue you're working on next time to prevent such races?
