### ISSUE TITLE
UUID, jdbc and WAL

### ISSUE THREAD

**Issue by stekman-sartorius** [questdb/questdb#3627]
### Describe the bug

UPDATE not working over JDBC if column is of UUID type and table is WAL.

### To reproduce

1. Create a table with UUID field and WAL enabled using JDBC, example from my application:
 `create table if not exists "metadata" ( datasetId uuid not null, createdAt timestamp not null, updatedAt timestamp not null, rowCount int, colCount int, missing int, statistics uuid, state string not null ) timestamp(createdAt) partition by DAY;
`
2. Insert some data:
`insert into "metadata"(datasetId, createdAt, updatedAt, state) values('d2d37ead-eb1b-4837-b3ee-a44d441099d5', '2023-08-08T12:04:44.993036Z', '2023-08-08T12:04:44.993039Z', 'Importing');`
3. Update the data:
`update "metadata" set statistics = '8a00ac25-318f-4b65-8a62-ed6bb579e44a', updatedAt='2023-08-08T12:04:45.022326Z' where datasetId = 'd2d37ead-eb1b-4837-b3ee-a44d441099d5';`
4. Query the table and statistics are not updated

Logs from quest:
```server-main unhandled error [job=io.questdb.cairo.wal.ApplyWal2TableJob@20f5281c, ex=
2023-08-08 14:32:08 java.lang.UnsupportedOperationException: unsupported column type: UUID
2023-08-08 14:32:08     at io.questdb.cairo.wal.WalEventCursor$SqlInfo.populateIndexedVariables(WalEventCursor.java:388)
2023-08-08 14:32:08     at io.questdb.cairo.wal.WalEventCursor$SqlInfo.populateBindVariableService(WalEventCursor.java:330)
2023-08-08 14:32:08     at io.questdb.cairo.wal.ApplyWal2TableJob.processWalSql(ApplyWal2TableJob.java:455)
2023-08-08 14:32:08     at io.questdb.cairo.wal.ApplyWal2TableJob.processWalCommit(ApplyWal2TableJob.java:433)
2023-08-08 14:32:08     at io.questdb.cairo.wal.ApplyWal2TableJob.applyOutstandingWalTransactions(ApplyWal2TableJob.java:335)
2023-08-08 14:32:08     at io.questdb.cairo.wal.ApplyWal2TableJob.applyWAL(ApplyWal2TableJob.java:523)
2023-08-08 14:32:08     at io.questdb.cairo.wal.ApplyWal2TableJob.doRun(ApplyWal2TableJob.java:572)
2023-08-08 14:32:08     at io.questdb.mp.AbstractQueueConsumerJob.run(AbstractQueueConsumerJob.java:41)
2023-08-08 14:32:08     at io.questdb.mp.Worker.run(Worker.java:118)
```

Without WAL on the table it works.

### Expected Behavior

statistics is updated

### Environment

```markdown
- **QuestDB version**:
Bug does not exist in version 7.0.0 and before, reproduced in 7.1 and 7.3
- **OS**:
Docker/Linux
- **Browser**:
n/a
```

**Comment by ideoma** [comment]
Thanks for submitting the issue. This is not clear

> Works in version 7.0.0, not in versions after.

Do you mean the bug is reproducible on 7.0 and not reproducible on say latest (7.3) version?

**Comment by stekman-sartorius** [comment]
> Thanks for submitting the issue. This is not clear
> 
> > Works in version 7.0.0, not in versions after.
> 
> Do you mean the bug is reproducible on 7.0 and not reproducible on say latest (7.3) version?

I updated the text, to clarify. Thanks.

**Comment by stekman-sartorius** [comment]
Great work and fast! Thanks!
