### ISSUE TITLE
Internal error when joining tables with a dot in a name

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3653]
### Describe the bug

**Reproducer**
1. create empty tables with dots in names:
```sql
CREATE TABLE "t.1" (ts TIMESTAMP, i INT) timestamp(ts) PARTITION by hour;
CREATE TABLE "t.2" (ts TIMESTAMP, i INT) timestamp(ts) PARTITION by hour;
```

2. run this query:
```sql
select * from t.1
asof join t.2;
```

This is enough to generate an internal error. With `-ea`:
```
2023-08-15T15:20:55.409113Z C i.q.c.h.p.JsonQueryProcessorState [156] Uh-oh. Error!
java.lang.AssertionError: wtf? t.1.ts
	at io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(SqlCodeGenerator.java:3025)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2701)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2309)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2296)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:199)
	at io.questdb.griffin.SqlCompilerImpl.generateFactory(SqlCompilerImpl.java:2803)
	at io.questdb.griffin.SqlCompilerImpl.generate(SqlCompilerImpl.java:2799)
	at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:1422)
	at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1389)
	at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:231)
	at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:101)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:421)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:183)
```

without `-ea`:
```
2023-08-15T15:23:52.310317Z C i.q.c.h.p.JsonQueryProcessorState [178] Uh-oh. Error!
java.lang.ArrayIndexOutOfBoundsException
```

**Root cause analysis**
The login in [`getColumnIndexQuiet()`](https://github.com/questdb/questdb/blob/372fdfe4afcf192d5275633616c7dd186b8c0932/core/src/main/java/io/questdb/griffin/engine/join/JoinRecordMetadata.java#L122-L137) is fragile. It splits a `t.1.ts` as:
- `t` - table alias
- `1.ts` - column name. 
 
While it should have been like this:
- `t.1` - table alias
- `ts` - column name

The problem is that it is impossible to tell from a string `t.1.ts` what part is a table alias and what is a column name. because both tables and columns can have a dot in a name. 

**Possible solution/hack**
Try all possible dots and perhaps one of them is a alias-column separator.
Problem: This could cause issue in pathological cases, for example when joining
- table: `a` with a column `bc`
- table `ab` with a column `c` 
These 2 cases could get mixed up.

**Comment by DHRUV6029** [comment]
Can i work on this if it is Open?
