### ISSUE TITLE
Internal error due to case-sensitive SQL UPDATE

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3656]
### Describe the bug
It looks SQL UPDATE treated table name as case-sensitive. 

Reproducer
```
CREATE TABLE TICKS (
    ts TIMESTAMP,
    tk SYMBOL,
    p DOUBLE
) TIMESTAMP(ts) PARTITION BY DAY WAL
DEDUP UPSERT KEYS(ts, tk);

INSERT INTO TICKS VALUES ('2023-07-14', 'QQQ', 78.56);
INSERT INTO TICKS VALUES ('2023-07-14', 'AAA', 78.56);

update ticks set tk = 'QQQ';
```

The UPDATE ends with an internal error:
```
2023-08-16T12:19:10.487745Z I i.q.g.SqlCompilerImpl parse [fd=121, q=update ticks set tk = 'QQQ']
2023-08-16T12:19:10.487853Z I i.q.c.h.p.JsonQueryProcessor cached query plan cannot be used because table schema has changed [table='ticks']
2023-08-16T12:19:10.487869Z I i.q.g.SqlCompilerImpl parse [fd=121, q=update ticks set tk = 'QQQ']
2023-08-16T12:19:10.487945Z C i.q.c.h.p.JsonQueryProcessorState [121] Uh-oh. Error!
io.questdb.cairo.sql.TableReferenceOutOfDateException: cached query plan cannot be used because table schema has changed [table='ticks']
	at io.questdb.cairo.sql.TableReferenceOutOfDateException.of(TableReferenceOutOfDateException.java:41)
	at io.questdb.griffin.SqlOptimiser.validateUpdateColumns(SqlOptimiser.java:4766)
	at io.questdb.griffin.SqlOptimiser.optimiseUpdate(SqlOptimiser.java:4715)
	at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel0(SqlCompilerImpl.java:1352)
	at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel(SqlCompilerImpl.java:1325)
	at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:1418)
	at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1389)
	at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:231)
	at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:101)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:421)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:183)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:233)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:627)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:209)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:84)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:99)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

the same with pgwire:
```
2023-08-16T12:22:30.749888Z I i.q.g.SqlCompilerImpl parse [fd=25, q=update ticks set tk = 'QQQ' where true]
2023-08-16T12:22:30.751305Z C i.q.c.p.PGWireServer internal error [ex=
io.questdb.cairo.sql.TableReferenceOutOfDateException: cached query plan cannot be used because table schema has changed [table='ticks']
	at io.questdb.cairo.sql.TableReferenceOutOfDateException.of(TableReferenceOutOfDateException.java:41)
	at io.questdb.griffin.SqlOptimiser.validateUpdateColumns(SqlOptimiser.java:4766)
	at io.questdb.griffin.SqlOptimiser.optimiseUpdate(SqlOptimiser.java:4715)
	at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel0(SqlCompilerImpl.java:1352)
	at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel(SqlCompilerImpl.java:1325)
	at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:1418)
	at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1389)
	at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:231)
	at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:101)
	at io.questdb.cutlass.pgwire.PGConnectionContext.compileQuery(PGConnectionContext.java:1202)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parseQueryText(PGConnectionContext.java:1721)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processParse(PGConnectionContext.java:2248)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1656)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:413)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:82)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:91)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:128)
	at io.questdb.mp.Worker.run(Worker.java:118)
``` 

but when I change the `UPDATE` to `update TICKS set tk = 'QQQ';` then it's working fine!

### Environment

```markdown
- **QuestDB version**: 7.3.1
```

Edit: Turns out it's not related to dedup. I can reproduce it even without dedup!

**Comment by hui-jie-lim** [comment]
hello @marregui , I figured I'd still love to contribute. Can I work on this please? 

I think I have identified the underlying issue here thats in [griffin](https://github.com/questdb/questdb/tree/master/core/src/main/java/io/questdb/griffin) SqlOptimiser
