### ISSUE TITLE
Returning exceptions to the console

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#367]
**Describe the bug**
In the web console, if a user sends a query which results in an exception, the console will appear in `running` state with the animated progress bar. This gives a false impression that the query is being executed. However, the server does not process the query, and the console will not update again to the `ready` state. Instead, it will stay in this state forever unless the user clicks on `STOP`.

**To Reproduce**
Run SQL which results in an exception in the web console (will add the next one I find here)

**Expected behavior**
The console should clearly display a failed status. 

Ideally, information about the exception should be available to be sent to the team to get support. Otherwise, this requires the user to manually find the logs. One way of doing this would be a button to allow to copy the last `n` lines of the latest logs to the clipboard.

**Screenshots**
Console looking busy
![Screenshot 2020-06-05 at 22 21 42](https://user-images.githubusercontent.com/52114895/83923873-10a0a180-a77b-11ea-9655-4c6d8023a192.png)

![Screenshot 2020-06-05 at 22 21 46](https://user-images.githubusercontent.com/52114895/83923869-0e3e4780-a77b-11ea-9c15-677b1d58284b.png)

**Comment by TheTanc** [comment]
Here is an instance where this happens. It uses the HTTP API instead of the web console, but the result is the same: exception server-side which is not returned to the user.

```
2020-06-08T13:49:22.446632Z I http-server connected [ip=127.0.0.1, fd=16]
2020-06-08T13:49:22.446942Z I i.q.c.h.p.JsonQueryProcessorState [16] exec [q='CREATE TABLE weather(timestamp timestamp, windSpeed int, skyCover symbol, tempF int, rain1H double, snowDepth int) timestamp(timestamp);']
2020-06-08T13:49:22.446964Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-3, sql=CREATE TABLE weather(timestamp timestamp, windSpeed int, skyCover symbol, tempF int, rain1H double, snowDepth int) timestamp(timestamp);]
2020-06-08T13:49:22.447373Z I i.q.c.p.WriterPool locked [table=`weather`, thread=16]
2020-06-08T13:49:22.447409Z I i.q.c.p.ReaderPool locked [table=`weather`, thread=16]
2020-06-08T13:49:22.447454Z I i.q.c.p.ReaderPool unlocked [table=`weather`]
2020-06-08T13:49:22.447549Z I i.q.c.h.p.JsonQueryProcessorState [16] syntax-error [q=`CREATE TABLE weather(timestamp timestamp, windSpeed int, skyCover symbol, tempF int, rain1H double, snowDepth int) timestamp(timestamp);`, at=13, message=`table already exists`]
2020-06-08T13:49:22.447645Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=16, lastRequestBytesSent=399, nCompletedRequests=1, totalBytesSent=0]
2020-06-08T13:49:22.448221Z I http-server disconnected [ip=127.0.0.1, fd=16]
2020-06-08T13:49:22.448701Z I i.q.c.h.HttpServer pushed
2020-06-08T13:49:39.847296Z I http-server connected [ip=127.0.0.1, fd=16]
2020-06-08T13:49:40.854453Z I i.q.c.t.TextLoader configured [table=`weather`, overwrite=false, durable=false, atomicity=2]
2020-06-08T13:49:40.857976Z I i.q.c.t.TextDelimiterScanner scan result [table=`weather`, delimiter=',', priority=10, mean=5.0, stddev=0.0]
2020-06-08T13:49:40.867250Z I i.q.c.p.WriterPool open [table=`weather`, thread=15]
2020-06-08T13:49:40.867338Z I i.q.c.TableWriter open 'weather'
2020-06-08T13:49:40.867560Z I i.q.c.ReadWriteMemory open /Users/tanc/Desktop/db/weather/_txn [fd=18]
2020-06-08T13:49:40.867926Z I i.q.c.ReadOnlyMemory open /Users/tanc/Desktop/db/weather/_meta [fd=19, pageSize=4096, size=196]
2020-06-08T13:49:40.868700Z I i.q.c.AppendMemory open /Users/tanc/Desktop/db/weather/default/timestamp.d [fd=20, pageSize=16777216]
2020-06-08T13:49:40.868770Z I i.q.c.AppendMemory open /Users/tanc/Desktop/db/weather/default/tempF.d [fd=21, pageSize=16777216]
2020-06-08T13:49:40.868787Z I i.q.c.TableWriter switched partition to '/Users/tanc/Desktop/db/weather/default'
2020-06-08T13:49:40.868877Z I i.q.c.p.WriterPool >> [table=`weather`, thread=15]
2020-06-08T13:49:40.868894Z I i.q.c.p.WriterPool << [table=`weather`, thread=15]
2020-06-08T13:49:40.869430Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@5bf94ab0, ex=
io.questdb.cairo.CairoException: [0] column count mismatch [textColumnCount=6, tableColumnCount=2, table=weather]
	at io.questdb.std.ThreadLocal.initialValue(ThreadLocal.java:36)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at io.questdb.cairo.CairoException.instance(CairoException.java:39)
	at io.questdb.cutlass.text.CairoTextWriter.openWriterAndOverrideImportTypes(CairoTextWriter.java:237)
	at io.questdb.cutlass.text.CairoTextWriter.prepareTable(CairoTextWriter.java:302)
	at io.questdb.cutlass.text.TextLoader.parseStructure(TextLoader.java:226)
	at io.questdb.cutlass.text.TextLoader.parse(TextLoader.java:172)
	at io.questdb.cutlass.http.processors.TextImportProcessor.onChunk(TextImportProcessor.java:262)
	at io.questdb.cutlass.http.HttpMultipartContentParser.parse(HttpMultipartContentParser.java:213)
	at io.questdb.cutlass.http.HttpConnectionContext.consumeMultipart(HttpConnectionContext.java:265)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:339)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:158)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:84)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:147)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:88)
	at io.questdb.mp.Worker.run(Worker.java:115)
]
```

**Comment by mpsq** [comment]
@TheTanc Could you provide some steps to reproduce this? This may have been fixed already, if not, I will see what I can do from the Console.

**Comment by TheTanc** [comment]
Hey, I am unable to reproduce currently. Most exceptions we encounter are fixed almost immediately. @bluestreak01 would it make sense to have a `throwException()` func in SQL to be able to test the console behaviour?

**Comment by bluestreak01** [comment]
This is server issue, when "unknown" exception occurs server does not respond back to http client. Server doesn't hang though.

**Comment by bluestreak01** [comment]
This is an ambiguous bug report. The log provided shows that error occurred when importing a file.
