### ISSUE TITLE
Software caused connection abort (0x00002745/10053)

### ISSUE THREAD

**Issue by Kamronbek1** [questdb/questdb#3675]
### Describe the bug

I'm trying to get data from database but,after 5min django app failures with exception 
**psycopg.OperationalError: sending query failed: Software caused connection abort (0x00002745/10053)**

### To reproduce

class HistoryApiView(APIView):

    def get(self, request, *args, **kwargs):
        query = "SELECT token,content_id,broadcast_id,episode_id,timestamp FROM splay_history"
        cursor = settings.CONNECTION.cursor()
        cursor.execute(query)
        data = cursor.fetchall()
        page_size = int(request.query_params.get('page_size', 10))
        page_number = int(request.query_params.get('page', 1))
        start_index = (page_number - 1) * page_size
        end_index = page_number * page_size
        data = data[start_index:end_index]
        keys = ["token", "content_id", "broadcast_id", "episode_id", "timestamp"]
        result = [dict(zip(keys, sub)) for sub in data]
        return JsonResponse(result, safe=False)
        
        
        
_settings.py_

CONN_STR = 'user=admin password=quest host=127.0.0.1 port=8812 dbname=qdb'
CONNECTION = pg.connect(CONN_STR, gssencmode="disable", sslmode="disable")

### Environment

```markdown
- **QuestDB version**:7.3.1
- **OS**:Windows 11 and Ubuntu
- **Browser**: chrome
```

### Additional context

Internal Server Error: /history
Traceback (most recent call last):
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\api\v1\Splay_Stat\views.py", line 52, in get
    cursor.execute(query)
  File "C:\Users\kageyoshi\PycharmProjects\Splay_Stat\venv\Lib\site-packages\psycopg\cursor.py", line 737, in execute
    raise ex.with_traceback(None)

**Comment by ideoma** [comment]
This error looks like QuestDB is down or bound to the incorrect address. Do you run QuestDB as a docker?
Please attach relevant QuestDB logs.

**Comment by Kamronbek1** [comment]
No,I'm running QuestDB as windows service, but when my app down by that error,QuestDB still working well.After restarting my app it works,but after 5min and more time I have error like that,Why QuestDB automatically closes client connection?
I have updated server config line.tcp.net.connection.timeout=0, but not worked

**Comment by puzpuzpuz** [comment]
> I have updated server config line.tcp.net.connection.timeout=0, but not worked

Since you're using PGWire protocol, you should be changing `pg.net.idle.timeout`.
