### ISSUE TITLE
Exception querying timestamp

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#3676]
### To reproduce

```
drop table abc
```

```
CREATE TABLE 'abc' (
  a SHORT,
  b STRING,
  c SYMBOL capacity 256 CACHE index capacity 256,
  d SYMBOL capacity 256 CACHE index capacity 256,
  e SYMBOL capacity 256 CACHE index capacity 256,
  f SYMBOL capacity 256 CACHE,
  g SYMBOL capacity 256 CACHE index capacity 256,
  h SYMBOL capacity 256 CACHE index capacity 256,
  i SYMBOL capacity 256 CACHE,
  j SYMBOL capacity 256 CACHE,
  k SYMBOL capacity 256 CACHE,
  l FLOAT,
  m FLOAT,
  n STRING,
  o SYMBOL capacity 256 CACHE index capacity 256,
  p STRING,
  q STRING,
  st TIMESTAMP,
  r LONG,
  s SHORT,
  t SYMBOL capacity 256 CACHE,
  u LONG,
  v BOOLEAN,
  w LONG,
  x UUID,
  y UUID,
  z SYMBOL capacity 1024 CACHE,
  a1 SYMBOL capacity 1024 CACHE,
  b2 SYMBOL capacity 16384 CACHE,
  b3 SYMBOL capacity 1024 CACHE,
  b4 SYMBOL capacity 1024 CACHE,
  b5 SYMBOL capacity 65536 CACHE
) timestamp (st) PARTITION BY HOUR WAL;
```

```
select st from abc
limit -1
```

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at io.questdb.std.ObjList.get(ObjList.java:145)
	at io.questdb.griffin.SqlOptimiser.rewriteNegativeLimit(SqlOptimiser.java:3440)
	at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:4686)
	at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel0(SqlCompilerImpl.java:1336)
	at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel(SqlCompilerImpl.java:1325)
	at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:1418)
	at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1389)
	at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:231)
	at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:101)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:421)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:183)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:233)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:627)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:209)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:84)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:99)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

### Environment

```markdown
- **QuestDB version**: 7.3.1 master (3995c31210c70664d4b3ebfe63fac1cdd516adea)
```

**Comment by ideoma** [comment]
regression in #3644
