### ISSUE TITLE
Flaky test LineTcpReceiverUpdateFuzzTest.testInsertUpdateWithColumnAdds

### ISSUE THREAD

**Issue by bziobrowski** [questdb/questdb#3736]
### Describe the bug

Test failed on mac-other:

2023-09-12T14:56:02.2534720Z 2023-09-12T14:56:01.105764Z E i.q.t.c.l.t.AbstractLineTcpReceiverTest Stopping ILP receiver because of an error
2023-09-12T14:56:02.2535670Z java.lang.AssertionError: Table: weather2
2023-09-12T14:56:02.2536670Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.assertTable(AbstractLineTcpReceiverFuzzTest.java:195)
2023-09-12T14:56:02.2537750Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.lambda$runTest$2(AbstractLineTcpReceiverFuzzTest.java:521)
2023-09-12T14:56:02.2538830Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$2(AbstractLineTcpReceiverTest.java:299)
2023-09-12T14:56:02.2539750Z 	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$7(AbstractCairoTest.java:923)
2023-09-12T14:56:02.2540750Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:568)
2023-09-12T14:56:02.2541720Z 	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:920)
2023-09-12T14:56:02.2542760Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:291)
2023-09-12T14:56:02.2543820Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:315)
2023-09-12T14:56:02.2544880Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:500)
2023-09-12T14:56:02.2545940Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:473)
2023-09-12T14:56:02.2547060Z 	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverUpdateFuzzTest.testInsertUpdateWithColumnAdds(LineTcpReceiverUpdateFuzzTest.java:131)
2023-09-12T14:56:02.2548060Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-09-12T14:56:02.2549040Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-09-12T14:56:02.2550060Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-12T14:56:02.2551050Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2023-09-12T14:56:02.2552020Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-09-12T14:56:02.2553000Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-09-12T14:56:02.2554040Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-09-12T14:56:02.2555040Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-09-12T14:56:02.2556040Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2023-09-12T14:56:02.2557040Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2023-09-12T14:56:02.2558340Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2023-09-12T14:56:02.2559340Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2023-09-12T14:56:02.2560870Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2023-09-12T14:56:02.2561890Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-09-12T14:56:02.2562820Z 	at java.lang.Thread.run(Thread.java:829)
2023-09-12T14:56:02.2564160Z 	[CIRCULAR REFERENCE:java.lang.AssertionError: expected:<terďż˝let	temperature1	temperature	humidity	hQmďż˝rsďż˝klet	terďż˝let1	notes	25B5@	timestamp	notes1	notes0	temperature0	25B5@1	25B5@0	terďż˝let0	humidity0	hQmďż˝rsďż˝klet0	hQmďż˝rsďż˝klet1	humidity1
2023-09-12T14:56:02.2565470Z 5224.0	83.0	83.0	25.0	10.0	europeP	noteX	64.0	2016-06-13T17:43:50.102301Z			NaN	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2566660Z europeQ	NaN	84.0	21.0	10.0	europeR		67.0	2016-06-13T17:43:50.102303Z			80.0	NaN	66.0		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2567850Z europeB	84.0	83.0	24.0	15.0		noteC	64.0	2016-06-13T17:43:50.102305Z			86.0	NaN	NaN	europeN	NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2569040Z 	NaN	88.0	21.0	NaN	europeI	noteR	60.0	2016-06-13T17:43:50.102307Z			81.0	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2570220Z europeR	NaN	86.0	NaN	18.0		noteP	62.0	2016-06-13T17:43:50.102311Z	noteT		85.0	63.0	NaN		26.0	NaN	NaN	NaN
2023-09-12T14:56:02.2571360Z 	NaN	NaN	25.0	14.0		noteV	62.0	2016-06-13T17:43:50.102312Z			80.0	NaN	67.0		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2572550Z europeV	NaN	81.0	21.0	NaN		noteD	62.0	2016-06-13T17:43:50.102317Z		noteV	NaN	NaN	NaN	europeV	NaN	12.0	NaN	NaN
2023-09-12T14:56:02.2573790Z 	82.0	81.0	25.0	14.0		noteG	68.0	2016-06-13T17:43:50.102318Z			NaN	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2574980Z 	NaN	88.0	20.0	13.0			64.0	2016-06-13T17:43:50.102321Z	noteF	noteG	81.0	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2576130Z 	NaN	85.0	20.0	13.0		noteY	NaN	2016-06-13T17:43:50.102322Z			87.0	64.0	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2577330Z europeB	NaN	85.0	28.0	16.0		noteX	64.0	2016-06-13T17:43:50.102327Z	noteY	noteB	84.0	NaN	64.0		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2578500Z europeP	83.0	85.0	NaN	15.0		noteH	60.0	2016-06-13T17:43:50.102328Z			83.0	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2579440Z 	NaN	83.0	NaN	13.0		noteV	65.0	2
2023-09-12T14:56:02.2580540Z 2023-09-12T14:56:01.107142Z I i.q.c.p.ReaderPool closed 'weather0~' [at=0:0, reason=POOL_CLOSED]
2023-09-12T14:56:02.2581720Z 2023-09-12T14:56:01.107602Z I i.q.c.p.ReaderPool closed 'weather2~' [at=0:0, reason=POOL_CLOSED]
2023-09-12T14:56:02.2582890Z 2023-09-12T14:56:01.108061Z I i.q.c.p.ReaderPool closed 'weather1~' [at=0:0, reason=POOL_CLOSED]
2023-09-12T14:56:02.2583990Z 2023-09-12T14:56:01.145751Z I i.q.c.TableWriter closed 'weather0'
2023-09-12T14:56:02.2585130Z 2023-09-12T14:56:01.145756Z I i.q.c.p.WriterPool closed [table=`weather0~`, reason=POOL_CLOSED, by=3461]
2023-09-12T14:56:02.2586240Z 2023-09-12T14:56:01.189413Z I i.q.c.TableWriter closed 'weather2'
2023-09-12T14:56:02.2587390Z 2023-09-12T14:56:01.189418Z I i.q.c.p.WriterPool closed [table=`weather2~`, reason=POOL_CLOSED, by=3461]
2023-09-12T14:56:02.2588500Z 2023-09-12T14:56:01.194268Z I i.q.c.TableWriter closed 'weather1'
2023-09-12T14:56:02.2589850Z 2023-09-12T14:56:01.194272Z I i.q.c.p.WriterPool closed [table=`weather1~`, reason=POOL_CLOSED, by=3461]
2023-09-12T14:56:02.2591080Z 2023-09-12T14:56:01.194346Z I i.q.c.p.MetadataPool closed 'weather0~' [at=0:0, reason=POOL_CLOSED]
2023-09-12T14:56:02.2592270Z 2023-09-12T14:56:01.194405Z I i.q.c.p.MetadataPool closed 'weather0~' [at=0:1, reason=POOL_CLOSED]
2023-09-12T14:56:02.2593460Z 2023-09-12T14:56:01.194443Z I i.q.c.p.MetadataPool closed 'weather2~' [at=0:0, reason=POOL_CLOSED]
2023-09-12T14:56:02.2594640Z 2023-09-12T14:56:01.194476Z I i.q.c.p.MetadataPool closed 'weather2~' [at=0:1, reason=POOL_CLOSED]
2023-09-12T14:56:02.2595800Z 2023-09-12T14:56:01.194508Z I i.q.c.p.MetadataPool closed 'weather2~' [at=0:2, reason=POOL_CLOSED]
2023-09-12T14:56:02.2597280Z 2023-09-12T14:56:01.194699Z I i.q.c.p.MetadataPool closed 'weather2~' [at=0:3, reason=POOL_CLOSED]
2023-09-12T14:56:02.2598490Z 2023-09-12T14:56:01.194739Z I i.q.c.p.MetadataPool closed 'weather1~' [at=0:0, reason=POOL_CLOSED]
2023-09-12T14:56:02.2599910Z 2023-09-12T14:56:01.194781Z I i.q.c.p.MetadataPool closed 'weather1~' [at=0:1, reason=POOL_CLOSED]
2023-09-12T14:56:02.2601150Z 2023-09-12T14:56:01.194945Z I i.q.t.AbstractCairoTest Tearing down test LineTcpReceiverUpdateFuzzTest#testInsertUpdateWithColumnAdds[NO_WAL]
2023-09-12T14:56:02.2602390Z 2023-09-12T14:56:01.195208Z I i.q.t.AbstractTest Finished test LineTcpReceiverUpdateFuzzTest#testInsertUpdateWithColumnAdds[NO_WAL]
2023-09-12T14:56:02.2603350Z thread random
2023-09-12T14:56:02.2604210Z random seeds: 598768342951L, 1694530561223L
2023-09-12T14:56:02.2605450Z 2023-09-12T14:56:01.216175Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.cutlass.line.tcp.LineTcpReceiverUpdateFuzzTest.testInsertUpdateWithColumnAdds[NO_WAL] duration_ms=15216 : 
2023-09-12T14:56:02.2606490Z java.lang.AssertionError: Table: weather2
2023-09-12T14:56:02.2607480Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.assertTable(AbstractLineTcpReceiverFuzzTest.java:195)
2023-09-12T14:56:02.2608550Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.lambda$runTest$2(AbstractLineTcpReceiverFuzzTest.java:521)
2023-09-12T14:56:02.2609640Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$2(AbstractLineTcpReceiverTest.java:299)
2023-09-12T14:56:02.2610680Z 	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$7(AbstractCairoTest.java:923)
2023-09-12T14:56:02.2611670Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:568)
2023-09-12T14:56:02.2612650Z 	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:920)
2023-09-12T14:56:02.2613680Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:291)
2023-09-12T14:56:02.2614740Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:315)
2023-09-12T14:56:02.2615790Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:500)
2023-09-12T14:56:02.2616860Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:473)
2023-09-12T14:56:02.2618020Z 	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverUpdateFuzzTest.testInsertUpdateWithColumnAdds(LineTcpReceiverUpdateFuzzTest.java:131)
2023-09-12T14:56:02.2619040Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-09-12T14:56:02.2620080Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-09-12T14:56:02.2621210Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-12T14:56:02.2622190Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2023-09-12T14:56:02.2623160Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-09-12T14:56:02.2624170Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-09-12T14:56:02.2625170Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-09-12T14:56:02.2626170Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-09-12T14:56:02.2627160Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2023-09-12T14:56:02.2628150Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2023-09-12T14:56:02.2629130Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2023-09-12T14:56:02.2630130Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2023-09-12T14:56:02.2631150Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2023-09-12T14:56:02.2632460Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-09-12T14:56:02.2633660Z 	at java.lang.Thread.run(Thread.java:829)
2023-09-12T14:56:02.2634990Z Caused by: java.lang.AssertionError: expected:<terďż˝let	temperature1	temperature	humidity	hQmďż˝rsďż˝klet	terďż˝let1	notes	25B5@	timestamp	notes1	notes0	temperature0	25B5@1	25B5@0	terďż˝let0	humidity0	hQmďż˝rsďż˝klet0	hQmďż˝rsďż˝klet1	humidity1
2023-09-12T14:56:02.2636300Z 5224.0	83.0	83.0	25.0	10.0	europeP	noteX	64.0	2016-06-13T17:43:50.102301Z			NaN	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2637480Z europeQ	NaN	84.0	21.0	10.0	europeR		67.0	2016-06-13T17:43:50.102303Z			80.0	NaN	66.0		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2638720Z europeB	84.0	83.0	24.0	15.0		noteC	64.0	2016-06-13T17:43:50.102305Z			86.0	NaN	NaN	europeN	NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2639880Z 	NaN	88.0	21.0	NaN	europeI	noteR	60.0	2016-06-13T17:43:50.102307Z			81.0	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2641130Z europeR	NaN	86.0	NaN	18.0		noteP	62.0	2016-06-13T17:43:50.102311Z	noteT		85.0	63.0	NaN		26.0	NaN	NaN	NaN
2023-09-12T14:56:02.2642290Z 	NaN	NaN	25.0	14.0		noteV	62.0	2016-06-13T17:43:50.102312Z			80.0	NaN	67.0		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2643480Z europeV	NaN	81.0	21.0	NaN		noteD	62.0	2016-06-13T17:43:50.102317Z		noteV	NaN	NaN	NaN	europeV	NaN	12.0	NaN	NaN
2023-09-12T14:56:02.2644650Z 	82.0	81.0	25.0	14.0		noteG	68.0	2016-06-13T17:43:50.102318Z			NaN	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2645790Z 	NaN	88.0	20.0	13.0			64.0	2016-06-13T17:43:50.102321Z	noteF	noteG	81.0	NaN	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2646940Z 	NaN	85.0	20.0	13.0		noteY	NaN	2016-06-13T17:43:50.102322Z			87.0	64.0	NaN		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2647990Z europeB	NaN	85.0	28.0	16.0		noteX	64.0	2016-06-13T17:43:50.102327Z	noteY	noteB	84.0	NaN	64.0		NaN	NaN	NaN	NaN
2023-09-12T14:56:02.2649100Z europeP	83.0	85.0	NaN	15.0		noteH	60.0	2016-06-13T17:43:50
2023-09-12T14:56:02.2650550Z 2023-09-12T14:56:01.216302Z I i.q.t.TestListener <<<< io.questdb.test.cutlass.line.tcp.LineTcpReceiverUpdateFuzzTest.testInsertUpdateWithColumnAdds[NO_WAL] duration_ms=15216

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
@ideoma we (@glasstiger and I) have questions about command/event timeouts in async command processing. There two timeouts:

- getWriterAsyncCommandBusyWaitTimeout()
- getWriterAsyncCommandMaxTimeout()

From method names it looks as if "busy" could be a busy loop timeout and "max" is less aggressive type of wait. It makes me think that the "future" will wait up to the "max" timeout using different methods. However, this is not the case as the log above shows that "update" times out 6s into the test with "max" being set to 30.

The "busy" wait is actually an ACK wait, e.g. async cmd got picked up, and "max"-"busy" is timeout for actual cmd processing. The system is liable to timeout fully only after "busy" timeout elapsing if cmd has not been picked up yet (which is often the case on CI). I find this confusing. Specifically the fact "update" can sometime timeout after busy, sometimes after max and it is highly non-deterministic which one is picked.

Can you think of any reason NOT to remove the concept of "busy" timeout and have only one value? We feel it is the best option to have only one timeout.
