### ISSUE TITLE
Python module quest-connect not compatible with Windows

### ISSUE THREAD

**Issue by Shionigami** [questdb/questdb#3748]
### Describe the bug

Hi. 

I am starting development of a script to push data to questdb, using SQLAlchemy. But, I got the following failure:
```
Traceback (most recent call last):
  File "C:\ws\GIT\toolanalysis\python\test_sqlalchemy.py", line 8, in <module>
    engine = create_engine("questdb://admin:quest@localhost:8812/qdb")
  File "<string>", line 2, in create_engine
  File "C:\TCC\Tools\python3\3.9.1-2_WIN64\lib\site-packages\sqlalchemy\util\deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "C:\TCC\Tools\python3\3.9.1-2_WIN64\lib\site-packages\sqlalchemy\engine\create.py", line 518, in create_engine
    entrypoint = u._get_entrypoint()
  File "C:\TCC\Tools\python3\3.9.1-2_WIN64\lib\site-packages\sqlalchemy\engine\url.py", line 662, in _get_entrypoint
    cls = registry.load(name)
  File "C:\TCC\Tools\python3\3.9.1-2_WIN64\lib\site-packages\sqlalchemy\util\langhelpers.py", line 341, in load
    return impl.load()
  File "C:\TCC\Tools\python3\3.9.1-2_WIN64\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\TCC\Tools\python3\3.9.1-2_WIN64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\TCC\Tools\python3\3.9.1-2_WIN64\lib\site-packages\questdb_connect\__init__.py", line 67, in <module>
    time.tzset()
AttributeError: module 'time' has no attribute 'tzset' 
```

I have googled the issue, and looks like it is because "tzset" is not supported on Windows. 

Could you please provide an update of the quest-connect module, to add support of Windows? 

Thanks!

### To reproduce

Use SQLAlchemy for questdb on Windows.
My tests were done with the example provided in the official documentation.

### Expected Behavior

Python scripts runs without failure.

### Environment

```markdown
- **QuestDB version**: 7.3.1
- **OS**: Windows 10
- **Browser**: Google Chrome
```

**Comment by filippopovic** [comment]
+1

**Comment by marregui** [comment]
Hola! sure!, this is now a top priority, just saw the issue buried here :P . As soon as I can fireup a windows box I will fix it, release it.

Will get back to you this week.

**Comment by marregui** [comment]
I have pushed the fix on https://github.com/questdb/questdb-connect/commit/6dfc49397db91b0bfe7a17b890ed2345231be691 

:p I must apologise!! I usually code on a mac, I was not aware that tzset is only available on Unix systems.

I will be pushing a release on pypi today. I will also start recording release notes to track changes.

**Comment by Shionigami** [comment]
The update works, thanks :D
Just copied the code to make quick test. 

I was thinking it would have side effects to just disable that code, but with the example provided in the doc, works so far. 

I'll give you other feedbacks if I find anything else :)

Thanks!

**Comment by marregui** [comment]
thank you @Shionigami :D 

all feedback is appreciated!. I am working on a release to fix a pending minor unrelated issue. So there will be some noise on pypi soon.

Best!

**Comment by Shionigami** [comment]
Hi @marregui !

Wanted to know if there is any plan to deploy the update? 
I have installed questdb-connect 1.0.10 (latest update), but the fix is missing. 

Thanks!

**Comment by marregui** [comment]
yes, I am going to attempt to do it today!. I have been trying out the latest release of superset, which is 3.0.0 I believe. I work on a Mac M1 and there was no arm64 image, so I am transitioning onto my intel mac to test it (had not touched this mac in a while), then I will deploy a test release in the 0.0.1xx range to test (0.0.102), and I will also test in windows.

**Comment by marregui** [comment]
hola 1.0.11 was released with a fix, thank you for the report
