### ISSUE TITLE
Flaky test: ServerMainShowPartitionsTest.testServerMainShowPartitions()

### ISSUE THREAD

**Issue by glasstiger** [questdb/questdb#3811]
### Describe the bug

Error in log:
```
2023-10-04T21:05:01.5288150Z testServerMainShowPartitions[WITH_WAL-null](io.questdb.test.ServerMainShowPartitionsTest)  Time elapsed: 10.554 sec  <<< FAILURE!
2023-10-04T21:05:01.5288950Z java.lang.AssertionError: expected:<count
2023-10-04T21:05:01.5289390Z 1000000
2023-10-04T21:05:01.5289710Z > but was:<count
2023-10-04T21:05:01.5290190Z 0
2023-10-04T21:05:01.5290510Z >
2023-10-04T21:05:01.5290850Z 	at org.junit.Assert.fail(Assert.java:89)
2023-10-04T21:05:01.5291670Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2023-10-04T21:05:01.5292080Z 	at org.junit.Assert.assertEquals(Assert.java:120)
2023-10-04T21:05:01.5292480Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:362)
2023-10-04T21:05:01.5292900Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:345)
2023-10-04T21:05:01.5293330Z 	at io.questdb.test.tools.TestUtils.assertSql(TestUtils.java:643)
2023-10-04T21:05:01.5293760Z 	at io.questdb.test.ServerMainShowPartitionsTest.waitForData(ServerMainShowPartitionsTest.java:200)
2023-10-04T21:05:01.5294280Z 	at io.questdb.test.ServerMainShowPartitionsTest.lambda$testServerMainShowPartitions$2(ServerMainShowPartitionsTest.java:128)
```

Full log:
[206.txt](https://github.com/questdb/questdb/files/12810067/206.txt)

### Environment

```markdown
- **QuestDB version**:
- **OS**: Mac (mac-other CI)
- **Browser**:
```

**Comment by jerrinot** [comment]
a failure on Windows-Other. Logs: https://gist.github.com/jerrinot/33aaf64f7a6ec114d1ccf0de1ba59fde

**Comment by jerrinot** [comment]
the test is racy. I can reproduce the failure linked above by injecting a bit of sleeping here: https://github.com/questdb/questdb/blob/9626172376e59e2de743753b1bf8d6f0356e9199/core/src/test/java/io/questdb/test/ServerMainShowPartitionsTest.java#L143
The Windows CI is a 🐌 , it injects sleeps by default....

I will send a fix it.

**Comment by jerrinot** [comment]
turns out the failure reported by @glasstiger has a different root cause from the failure I reported.
https://github.com/questdb/questdb/pull/4721 should fix both.
