### ISSUE TITLE
ModuleNotFoundError: No module named 'pyarrow'

### ISSUE THREAD

**Issue by devfinwiz** [questdb/questdb#3823]
### Describe the bug

Reference: https://py-questdb-client.readthedocs.io/en/latest/examples.html#pandas-basics

```
from questdb.ingress import Sender, IngressError

import sys
import pandas as pd

def example(host: str = 'localhost', port: int = 9009):
    df = pd.DataFrame({
            'pair': ['USDGBP', 'EURJPY'],
            'traded_price': [0.83, 142.62],
            'qty': [100, 400],
            'limit_price': [0.84, None],
            'timestamp': [
                pd.Timestamp('2022-08-06 07:35:23.189062', tz='UTC'),
                pd.Timestamp('2022-08-06 07:35:23.189062', tz='UTC')]})
    try:
        with Sender(host, port) as sender:
            sender.dataframe(
                df,
                table_name='trades',  # Table name to insert into.
                symbols=['pair'],  # Columns to be inserted as SYMBOL types.
                at='timestamp')  # Column containing the designated timestamps.

    except IngressError as e:
        sys.stderr.write(f'Got error: {e}\n')

if __name__ == '__main__':
    example()
```

```
Traceback (most recent call last):
  File "src\questdb\dataframe.pxi", line 441, in questdb.ingress._dataframe_may_import_deps
ModuleNotFoundError: No module named 'pyarrow'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Dev.Juneja\Downloads\questtest\test.py", line 27, in <module>
    example()
  File "c:\Users\Dev.Juneja\Downloads\questtest\test.py", line 17, in example
    sender.dataframe(
  File "src\questdb\ingress.pyx", line 1640, in questdb.ingress.Sender.dataframe
  File "src\questdb\dataframe.pxi", line 2160, in questdb.ingress._dataframe
  File "src\questdb\dataframe.pxi", line 443, in questdb.ingress._dataframe_may_import_deps
ImportError: Missing dependencies: `pandas`, `numpy` and `pyarrow` must all be installed to use the `.dataframe()` method. 
See: https://py-questdb-client.readthedocs.io/en/latest/installation.html.
```

### To reproduce

Refer to the description.

### Environment

```markdown
- **QuestDB version**: 7.3.2 (questdb image), 1.1.0 (QuestDB client library for Python)
- **OS**: Windows 10
- **Browser**: Chrome
```

**Comment by devfinwiz** [comment]
Solves the issue when pyarrow is explicitly downloaded.
