### ISSUE TITLE
java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#3849]
### Describe the bug

```
2023-10-15T09:19:56.382235Z C i.q.c.p.PGWireServer internal error [ex=
java.lang.ArithmeticException: / by zero
	at io.questdb.griffin.engine.functions.math.RemIntFunctionFactory$Func.getInt(RemIntFunctionFactory.java:61)
	at io.questdb.griffin.engine.functions.IntFunction.getDouble(IntFunction.java:70)
	at io.questdb.griffin.engine.functions.conditional.CoalesceFunctionFactory$TwoDoubleCoalesceFunction.getDouble(CoalesceFunctionFactory.java:456)
	at io.questdb.griffin.engine.functions.groupby.CountDoubleGroupByFunction.computeFirst(CountDoubleGroupByFunction.java:40)
	at io.questdb.griffin.engine.groupby.GroupByFunctionsUpdaterAsm/0x00000008010d3440.updateNew(Unknown Source)
	at io.questdb.griffin.engine.groupby.GroupByRecordCursorFactory$GroupByRecordCursor.hasNext(GroupByRecordCursorFactory.java:179)
	at io.questdb.griffin.engine.AbstractVirtualFunctionRecordCursor.hasNext(AbstractVirtualFunctionRecordCursor.java:78)
	at io.questdb.griffin.engine.groupby.GroupByRecordCursorFactory$GroupByRecordCursor.hasNext(GroupByRecordCursorFactory.java:173)
	at io.questdb.griffin.engine.groupby.GroupByNotKeyedRecordCursorFactory$GroupByNotKeyedRecordCursor.hasNext(GroupByNotKeyedRecordCursorFactory.java:147)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor0(PGConnectionContext.java:2702)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor(PGConnectionContext.java:2693)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processExecute(PGConnectionContext.java:2387)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processExec(PGConnectionContext.java:2379)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1870)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:515)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:86)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:124)
	at io.questdb.mp.Worker.run(Worker.java:118)
]
```

### To reproduce

repro for demo:
`select passenger_count%pickup_location_id from trips WHERE rate_code_id='Group ride'`
I think its happening since `INT` columns are involved and not `DOUBLE`.

### Expected Behavior

not sure, maybe return null?

### Environment

```markdown
- **QuestDB version**: 7.3.3
- **OS**: windows 10
- **Browser**: Postgres client
```

**Comment by rishh98** [comment]
Hi @superichmann 
i am new to Open Source Contributions
can you assign this issue to me?

**Comment by puzpuzpuz** [comment]
@rishh98 no prob, I've assigned you.
