### ISSUE TITLE
flaky PGJobContextTest.testCancelRunningQuery test

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#3977]
```
expected PSQLException with cancel message for query: insert into dest select count(*)::timestamp, 0, 0.0 from tab t1 join tab t2 on t1.x = t2.x where t1.x > 0

java.lang.AssertionError: expected PSQLException with cancel message for query: insert into dest select count(*)::timestamp, 0, 0.0 from tab t1 join tab t2 on t1.x = t2.x where t1.x > 0
	at org.junit.Assert.fail(Assert.java:89)
	at io.questdb.test.cutlass.pgwire.PGJobContextTest.lambda$testCancelRunningQuery$16(PGJobContextTest.java:2382)
	at io.questdb.test.cutlass.pgwire.PGJobContextTest.lambda$assertWithPgServer$169(PGJobContextTest.java:9800)
```

[165.txt](https://github.com/questdb/ui/files/13391980/165.txt)

https://dev.azure.com/questdb/questdb/_build/results?buildId=57324&view=ms.vss-test-web.build-test-results-tab&runId=223807&resultId=101806&paneView=debug

**Comment by ideoma** [comment]
Dup of #3180
