### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#4065]
### Describe the bug

Many OutOfMemoryError when querying from postgres interface since 7,3,7. On the client app I get exception from the queries.
~40gb memory is available on pc
Happens only when running many queries (for over an hour) from client app.
see npgsql .NET conf below.
see edited qdb conf file entries below.

from logfile:

```
2023-12-15T21:00:12.560433Z C server-main unhandled error [job=io.questdb.network.IODispatcherWindows@6622fc65, ex=
java.lang.OutOfMemoryError
	at jdk.internal.misc.Unsafe.allocateMemory(Unsafe.java:618)
	at sun.misc.Unsafe.allocateMemory(Unsafe.java:460)
	at io.questdb.std.Unsafe.malloc(Unsafe.java:72)
	at io.questdb.cutlass.pgwire.PGConnectionContext.of(PGConnectionContext.java:553)
	at io.questdb.cutlass.pgwire.PGConnectionContext.of(PGConnectionContext.java:63)
	at io.questdb.network.IOContextFactoryImpl.newInstance(IOContextFactoryImpl.java:66)
	at io.questdb.network.AbstractIODispatcher.addPending(AbstractIODispatcher.java:225)
	at io.questdb.network.AbstractIODispatcher.accept(AbstractIODispatcher.java:344)
	at io.questdb.network.IODispatcherWindows.queryFdSets(IODispatcherWindows.java:124)
	at io.questdb.network.IODispatcherWindows.runSerially(IODispatcherWindows.java:173)
	at io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:40)
	at io.questdb.mp.Worker.run(Worker.java:148)
]
```

### To reproduce

Queries characteristics:

- Nested WITH SELECTs (3 levels)
- Nested SELECTs in the main WITH
- LT JOIN

example:
```
WITH Y AS (SELECT * FROM (tbl WHERE col1 != '0' AND col1 != '1' AND col1 != '2') WHERE  timestamp<'2023-03-30' AND timestamp>='2023-03-28'),
X AS (SELECT * FROM ((Y LT JOIN (Y) ON joinCol) WHERE timestamp1 IS NOT NULL) ) 
SELECT mainCol/1.3475 as 'mainCol/1.3475',joinCol as 'joinCol',col5 as 'col5',col1 as 'col1',c_0_A as 'c_0_A',c_1_A as 'c_1_A',c_2_B as 'c_2_B',c_3_B as 'c_3_B',c_4_C as 'c_4_C',c_5_C as 'c_5_C',c_6_D as 'c_6_D',c_7_D as 'c_7_D',c_8_D as 'c_8_D',c_9_D as 'c_9_D',c_10_E as 'c_10_E',c_11_E as 'c_11_E',c_12_E as 'c_12_E',c_13_G as 'c_13_G',c_14_G as 'c_14_G',c_15_H as 'c_15_H',c_16_H as 'c_16_H',c_17_H as 'c_17_H',c_18_H as 'c_18_H',c_19_H as 'c_19_H',c_20_H as 'c_20_H',c_21_H as 'c_21_H',c_22_H as 'c_22_H',c_23_I as 'c_23_I',c_24_I as 'c_24_I',c_25_I as 'c_25_I',c_26_K as 'c_26_K',c_27_K as 'c_27_K',c_28_L as 'c_28_L',c_29_L as 'c_29_L',c_30_M as 'c_30_M',c_31_M as 'c_31_M',c_32_M as 'c_32_M',c_33_M as 'c_33_M',c_34_M as 'c_34_M',c_35_O as 'c_35_O',c_36_P as 'c_36_P',c_37_R as 'c_37_R',c_38_R as 'c_38_R',c_39_S as 'c_39_S',c_40_S as 'c_40_S',c_41_S as 'c_41_S',c_42_S as 'c_42_S',c_43_S as 'c_43_S',c_44_S as 'c_44_S',c_45_T as 'c_45_T',c_46_T as 'c_46_T',c_47_T as 'c_47_T',c_48_T as 'c_48_T',c_49_T as 'c_49_T',c_50_T as 'c_50_T',c_51_T as 'c_51_T',c_52_T as 'c_52_T',c_53_T as 'c_53_T',c_54_T as 'c_54_T',c_55_T as 'c_55_T',c_56_U as 'c_56_U',c_57_U as 'c_57_U',c_58_U as 'c_58_U',timestamp as 'timestamp',col5 as 'col5',i_100_H1 as 'i_100_H1' FROM X
```

### Expected Behavior

Queries should be returned without errors

### Environment

```markdown
- **QuestDB version**: 7.3.7
- **OS**:Windows 10 Pro 22H2
- **Browser**: .NET Npgsql 8.0.1 with pooling
`connectionString = $@"host={Host};port={Port};username={Username};password={Password};database={Database};ServerCompatibilityMode=NoTypeLoading;Pooling=true;MaxPoolSize=99999;Timeout=1024;CommandTimeout=99999;"; // max is 1024`
```

### Additional context

Edited conf entries, changed them due to past bugs.
```
pg.net.connection.limit=99999
query.timeout.sec=8192
cairo.reader.pool.max.segments=256
cairo.sql.join.context.pool.capacity=2048
pg.net.connection.timeout=8192000
pg.recv.buffer.size=100M
pg.send.buffer.size=100M
pg.max.blob.size.on.query=2048k
cairo.default.symbol.capacity=32768
cairo.index.value.block.size=32768
line.default.partition.by=YEAR
shared.worker.count=16
cairo.sql.window.max.recursion=1024
```

**Comment by bziobrowski** [comment]
It could be that high number of connections combined with big send/receive buffers uses up all available system memory.
Please lower the number of connections (to default or a few hundreds at most) and double check that unneeded connections are closed properly .
