### ISSUE TITLE
Flaky TableNameRegistryTest.testFuzz

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#4119]
### To reproduce

Happeneded on windows-cairo:
```
testFuzz(io.questdb.test.cairo.TableNameRegistryTest)  Time elapsed: 1,368.896 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 1200000 milliseconds
	at java.base@11.0.21/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.21/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
	at app//io.questdb.std.Os.park(Os.java:149)
	at app//io.questdb.mp.SOCountDownLatch.await(SOCountDownLatch.java:55)
	at app//io.questdb.test.cairo.TableNameRegistryTest.testFuzz(TableNameRegistryTest.java:613)

testFuzz(io.questdb.test.cairo.TableNameRegistryTest)  Time elapsed: 1,368.896 sec  <<< ERROR!
java.lang.Exception: Appears to be stuck in thread Thread-32958
	at app//io.questdb.mp.AbstractMSequence.availableIndex(AbstractMSequence.java:50)
	at app//io.questdb.mp.MPSequence.availableIndex(MPSequence.java:31)
	at app//io.questdb.mp.FanOut.availableIndex(FanOut.java:100)
	at app//io.questdb.mp.MPSequence.next(MPSequence.java:55)
	at app//io.questdb.mp.AbstractSSequence.nextBully(AbstractSSequence.java:54)
	at app//io.questdb.mp.MPSequence.nextBully(MPSequence.java:31)
	at app//io.questdb.log.Logger.nextWaiting(Logger.java:408)
	at app//io.questdb.log.Logger.xCriticalW(Logger.java:340)
	at app//io.questdb.log.Logger.critical(Logger.java:265)
	at app//io.questdb.cairo.wal.seq.TableSequencerAPI.forAllWalTables(TableSequencerAPI.java:169)
	at app//io.questdb.cairo.wal.CheckWalTransactionsJob.checkMissingWalTransactions(CheckWalTransactionsJob.java:62)
	at app//io.questdb.cairo.wal.CheckWalTransactionsJob.runSerially(CheckWalTransactionsJob.java:105)
	at app//io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:40)
	at app//io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:49)
	at app//io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1338)
	at app//io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1331)
	at app//io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1345)
	at app//io.questdb.test.cairo.TableNameRegistryTest.testFuzz0(TableNameRegistryTest.java:960)
	at app//io.questdb.test.cairo.TableNameRegistryTest.lambda$testFuzz$16(TableNameRegistryTest.java:603)

```

### QuestDB version:

latest master

### OS, in case of Docker specify Docker and the Host OS:

Windows

### File System, in case of Docker specify Host File System:

ntfs

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by puzpuzpuz** [comment]
Another variation of the flakiness:
```
2024-01-11T11:43:55.5535787Z 2024-01-11T11:43:55.515190Z I i.q.t.TestListener >>>> io.questdb.test.cairo.TableNameRegistryTest.testFuzz
2024-01-11T11:43:55.5536867Z 2024-01-11T11:43:55.517927Z I i.q.t.AbstractTest Starting test TableNameRegistryTest#testFuzz
2024-01-11T11:43:55.5537858Z 2024-01-11T11:43:55.520147Z I i.q.c.TableNameRegistryStore reloading tables file [path=C:\Users\VSSADM~1\AppData\Local\Temp\junit14046539177092086536\dbRoot\tables.d.0, threadId=33482]
2024-01-11T11:43:55.5538615Z random seeds: 648076132200L, 1704973435520L
2024-01-11T11:43:55.5539225Z random seeds: 648077329600L, 1704973435520L
2024-01-11T11:43:55.5540011Z 2024-01-11T11:43:55.523650Z I i.q.t.AbstractCairoTest random seeds: 648076132200L, 1704973435520L
2024-01-11T11:43:55.5540915Z 2024-01-11T11:43:55.524867Z I i.q.t.AbstractCairoTest random seeds: 648077329600L, 1704973435520L
2024-01-11T11:43:55.5541770Z 2024-01-11T11:43:55.528767Z I i.q.t.AbstractCairoTest random seeds: 648081248900L, 1704973435520L
2024-01-11T11:43:55.5542464Z random seeds: 648081248900L, 1704973435520L
2024-01-11T11:43:55.5543053Z random seeds: 648082747300L, 1704973435520L
2024-01-11T11:43:55.5543811Z 2024-01-11T11:43:55.530263Z I i.q.t.AbstractCairoTest random seeds: 648082747300L, 1704973435520L
2024-01-11T11:43:55.5544773Z 2024-01-11T11:43:55.543007Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33486, q=create table JXMEIPKMER33486(a int, t timestamp) timestamp(t) partition by day wal]
2024-01-11T11:43:55.5545783Z 2024-01-11T11:43:55.546843Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33485, q=create table HODUWLQNEB33485(a int, t timestamp) timestamp(t) partition by day wal]
2024-01-11T11:43:55.5546785Z 2024-01-11T11:43:55.547387Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33484, q=create table TPYVFSSKCU33484(a int, t timestamp) timestamp(t) partition by day wal]
2024-01-11T11:43:55.5547704Z 2024-01-11T11:43:55.547745Z I i.q.c.CairoEngine locked [table=`JXMEIPKMER33486~1`, thread=33486]
2024-01-11T11:43:55.5548645Z 2024-01-11T11:43:55.550421Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33483, q=create table XYFLWXWNTE33483(a int, t timestamp) timestamp(t) partition by day wal]
2024-01-11T11:43:55.5594425Z 2024-01-11T11:43:55.555527Z I i.q.c.CairoEngine locked [table=`HODUWLQNEB33485~2`, thread=33485]
2024-01-11T11:43:55.5596723Z 2024-01-11T11:43:55.555886Z I i.q.c.CairoEngine locked [table=`TPYVFSSKCU33484~3`, thread=33484]
2024-01-11T11:43:55.5597677Z 2024-01-11T11:43:55.555977Z I i.q.c.CairoEngine locked [table=`XYFLWXWNTE33483~4`, thread=33483]
2024-01-11T11:43:55.6489699Z 2024-01-11T11:43:55.646983Z I i.q.c.p.WriterPool created [table=`JXMEIPKMER33486~1`, thread=33486]
2024-01-11T11:43:55.6491446Z 2024-01-11T11:43:55.647016Z I i.q.c.TableWriter open 'JXMEIPKMER33486'
2024-01-11T11:43:55.6648298Z 2024-01-11T11:43:55.653301Z I i.q.c.CairoEngine unlocked [table=`JXMEIPKMER33486`]
2024-01-11T11:43:55.6655775Z 2024-01-11T11:43:55.662877Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33486, q=rename table JXMEIPKMER33486 to OQFWKMDTNB33486]
2024-01-11T11:43:55.6657613Z 2024-01-11T11:43:55.663087Z I i.q.c.w.WalWriter open 'JXMEIPKMER33486~1'
2024-01-11T11:43:55.6662392Z 2024-01-11T11:43:55.665903Z I i.q.c.w.WalWriter opened WAL segment [path='C:\Users\VSSADM~1\AppData\Local\Temp\junit14046539177092086536\dbRoot\JXMEIPKMER33486~1\wal1\0\_event.i']
2024-01-11T11:43:55.6940335Z 2024-01-11T11:43:55.693045Z I i.q.c.CairoEngine renaming table [from='JXMEIPKMER33486', to='OQFWKMDTNB33486', wal=1', seqTxn=1]
2024-01-11T11:43:55.6948882Z 2024-01-11T11:43:55.694506Z I i.q.c.p.WriterPool created [table=`HODUWLQNEB33485~2`, thread=33485]
2024-01-11T11:43:55.6950112Z 2024-01-11T11:43:55.694541Z I i.q.c.TableWriter open 'HODUWLQNEB33485'
2024-01-11T11:43:55.7254544Z 2024-01-11T11:43:55.708738Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33486, q=create table JXMEIPKMER33486(a int, t timestamp) timestamp(t) partition by day wal]
2024-01-11T11:43:55.7257195Z 2024-01-11T11:43:55.709130Z I i.q.c.CairoEngine unlocked [table=`HODUWLQNEB33485`]
2024-01-11T11:43:55.7258651Z 2024-01-11T11:43:55.709180Z I i.q.c.CairoEngine locked [table=`JXMEIPKMER33486~5`, thread=33486]
2024-01-11T11:43:55.7263296Z 2024-01-11T11:43:55.709424Z I i.q.c.p.WriterPool created [table=`XYFLWXWNTE33483~4`, thread=33483]
2024-01-11T11:43:55.7264686Z 2024-01-11T11:43:55.709452Z I i.q.c.TableWriter open 'XYFLWXWNTE33483'
2024-01-11T11:43:55.7276440Z 2024-01-11T11:43:55.724034Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33485, q=rename table HODUWLQNEB33485 to HODUWLQNEB33485]
2024-01-11T11:43:55.7277457Z 2024-01-11T11:43:55.724359Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33485, q=drop table HODUWLQNEB33485]
2024-01-11T11:43:55.7278315Z 2024-01-11T11:43:55.724869Z I i.q.c.CairoEngine unlocked [table=`XYFLWXWNTE33483`]
2024-01-11T11:43:55.7279213Z 2024-01-11T11:43:55.725015Z I i.q.c.w.s.TableSequencerAPI dropping wal table [name=HODUWLQNEB33485, dirName=HODUWLQNEB33485~2]
2024-01-11T11:43:55.7280175Z 2024-01-11T11:43:55.725928Z I i.q.c.p.WriterPool created [table=`TPYVFSSKCU33484~3`, thread=33484]
2024-01-11T11:43:55.7280984Z 2024-01-11T11:43:55.725959Z I i.q.c.TableWriter open 'TPYVFSSKCU33484'
2024-01-11T11:43:55.7562790Z 2024-01-11T11:43:55.740842Z I i.q.c.CairoEngine unlocked [table=`TPYVFSSKCU33484`]
2024-01-11T11:43:55.7579587Z 2024-01-11T11:43:55.741121Z I i.q.c.w.s.TableSequencerAPI closed table sequencer [table=HODUWLQNEB33485, distressed=false, dropped=true]
2024-01-11T11:43:55.7581141Z 2024-01-11T11:43:55.741249Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33485, q=create table HODUWLQNEB33485(a int, t timestamp) timestamp(t) partition by day wal]
2024-01-11T11:43:55.7582271Z 2024-01-11T11:43:55.741282Z I i.q.c.p.WriterPool >> [table=`JXMEIPKMER33486~1`, thread=33483]
2024-01-11T11:43:55.7583615Z 2024-01-11T11:43:55.741681Z I i.q.c.CairoEngine locked [table=`HODUWLQNEB33485~6`, thread=33485]
2024-01-11T11:43:55.7584479Z 2024-01-11T11:43:55.743973Z I i.q.c.p.WriterPool << [table=`JXMEIPKMER33486~1`, thread=33483]
2024-01-11T11:43:55.7585121Z 2024-01-11T11:43:55.744173Z I i.q.c.p.WriterPool >> [table=`HODUWLQNEB33485~2`, thread=33483]
2024-01-11T11:43:55.7585992Z 2024-01-11T11:43:55.744178Z I i.q.c.TableWriter closing table files [table=HODUWLQNEB33485, dirName=HODUWLQNEB33485~2]
2024-01-11T11:43:55.7586811Z 2024-01-11T11:43:55.744480Z I i.q.c.TableWriter closed 'HODUWLQNEB33485'
2024-01-11T11:43:55.7587467Z 2024-01-11T11:43:55.745401Z I i.q.c.p.WriterPool closed [table=`HODUWLQNEB33485~2`, reason=DISTRESSED, by=33483]
2024-01-11T11:43:55.7588212Z 2024-01-11T11:43:55.745956Z C i.q.c.w.s.TableSequencerAPI could not process table sequencer [table=HODUWLQNEB33485, errno=0, error=
2024-01-11T11:43:55.7588960Z io.questdb.cairo.CairoException: [0] Cannot append. File does not exist: C:\Users\VSSADM~1\AppData\Local\Temp\junit14046539177092086536\dbRoot\HODUWLQNEB33485~2\_txn
2024-01-11T11:43:55.7589546Z 	at io.questdb.cairo.CairoException.instance(CairoException.java:310)
2024-01-11T11:43:55.7590052Z 	at io.questdb.cairo.CairoException.critical(CairoException.java:69)
2024-01-11T11:43:55.7590431Z 	at io.questdb.cairo.TxReader.openTxnFile(TxReader.java:511)
2024-01-11T11:43:55.7590775Z 	at io.questdb.cairo.TxReader.ofRO(TxReader.java:382)
2024-01-11T11:43:55.7591190Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.checkNotifyOutstandingTxnInWal(CheckWalTransactionsJob.java:85)
2024-01-11T11:43:55.7591651Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.lambda$new$0(CheckWalTransactionsJob.java:56)
2024-01-11T11:43:55.7592077Z 	at io.questdb.cairo.wal.seq.TableSequencerAPI.forAllWalTables(TableSequencerAPI.java:167)
2024-01-11T11:43:55.7592531Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.checkMissingWalTransactions(CheckWalTransactionsJob.java:62)
2024-01-11T11:43:55.7592972Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.runSerially(CheckWalTransactionsJob.java:105)
2024-01-11T11:43:55.7593367Z 	at io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:40)
2024-01-11T11:43:55.7593712Z 	at io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:49)
2024-01-11T11:43:55.7594075Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1338)
2024-01-11T11:43:55.7594472Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1331)
2024-01-11T11:43:55.7594875Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1345)
2024-01-11T11:43:55.7595279Z 	at io.questdb.test.cairo.TableNameRegistryTest.testFuzz0(TableNameRegistryTest.java:960)
2024-01-11T11:43:55.7595697Z 	at io.questdb.test.cairo.TableNameRegistryTest.lambda$testFuzz$16(TableNameRegistryTest.java:603)
2024-01-11T11:43:55.7596083Z 	at java.lang.Thread.run(Thread.java:829)
2024-01-11T11:43:55.7596334Z ]
2024-01-11T11:43:55.7596843Z 2024-01-11T11:43:55.746663Z I i.q.g.SqlCompilerImpl parse [fd=-1, thread=33483, q=drop table XYFLWXWNTE33483]
2024-01-11T11:43:55.7597405Z 2024-01-11T11:43:55.756030Z C i.q.c.w.s.TableSequencerAPI could not process table sequencer [table=HODUWLQNEB33485, errno=0, error=
2024-01-11T11:43:55.7598179Z io.questdb.cairo.CairoException: [0] Cannot append. File does not exist: C:\Users\VSSADM~1\AppData\Local\Temp\junit14046539177092086536\dbRoot\HODUWLQNEB33485~2\_txn
2024-01-11T11:43:55.7598645Z 	at io.questdb.cairo.CairoException.instance(CairoException.java:310)
2024-01-11T11:43:55.7599028Z 	at io.questdb.cairo.CairoException.critical(CairoException.java:69)
2024-01-11T11:43:55.7599392Z 	at io.questdb.cairo.TxReader.openTxnFile(TxReader.java:511)
2024-01-11T11:43:55.7599730Z 	at io.questdb.cairo.TxReader.ofRO(TxReader.java:382)
2024-01-11T11:43:55.7600134Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.checkNotifyOutstandingTxnInWal(CheckWalTransactionsJob.java:85)
2024-01-11T11:43:55.7600595Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.lambda$new$0(CheckWalTransactionsJob.java:56)
2024-01-11T11:43:55.7601025Z 	at io.questdb.cairo.wal.seq.TableSequencerAPI.forAllWalTables(TableSequencerAPI.java:167)
2024-01-11T11:43:55.7601457Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.checkMissingWalTransactions(CheckWalTransactionsJob.java:62)
2024-01-11T11:43:55.7601978Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.runSerially(CheckWalTransactionsJob.java:105)
2024-01-11T11:43:55.7602376Z 	at io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:40)
2024-01-11T11:43:55.7602895Z 	at io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:49)
2024-01-11T11:43:55.7603258Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1338)
2024-01-11T11:43:55.7603651Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1331)
2024-01-11T11:43:55.7604036Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1345)
2024-01-11T11:43:55.7604490Z 	at io.questdb.test.cairo.TableNameRegistryTest.testFuzz0(TableNameRegistryTest.java:960)
2024-01-11T11:43:55.7604915Z 	at io.questdb.test.cairo.TableNameRegistryTest.lambda$testFuzz$16(TableNameRegistryTest.java:603)
2024-01-11T11:43:55.7605286Z 	at java.lang.Thread.run(Thread.java:829)
2024-01-11T11:43:55.7605537Z ]
2024-01-11T11:43:55.7606076Z 2024-01-11T11:43:55.756741Z C i.q.c.w.s.TableSequencerAPI could not process table sequencer [table=HODUWLQNEB33485, errno=0, error=
2024-01-11T11:43:55.7606557Z io.questdb.cairo.CairoException: [0] Cannot append. File does not exist: C:\Users\VSSADM~1\AppData\Local\Temp\junit14046539177092086536\dbRoot\HODUWLQNEB33485~2\_txn
2024-01-11T11:43:55.7606987Z 	at io.questdb.cairo.CairoException.instance(CairoException.java:310)
2024-01-11T11:43:55.7607353Z 	at io.questdb.cairo.CairoException.critical(CairoException.java:69)
2024-01-11T11:43:55.7607707Z 	at io.questdb.cairo.TxReader.openTxnFile(TxReader.java:511)
2024-01-11T11:43:55.7608061Z 	at io.questdb.cairo.TxReader.ofRO(TxReader.java:382)
2024-01-11T11:43:55.7608470Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.checkNotifyOutstandingTxnInWal(CheckWalTransactionsJob.java:85)
2024-01-11T11:43:55.7608925Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.lambda$new$0(CheckWalTransactionsJob.java:56)
2024-01-11T11:43:55.7609350Z 	at io.questdb.cairo.wal.seq.TableSequencerAPI.forAllWalTables(TableSequencerAPI.java:167)
2024-01-11T11:43:55.7609779Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.checkMissingWalTransactions(CheckWalTransactionsJob.java:62)
2024-01-11T11:43:55.7610229Z 	at io.questdb.cairo.wal.CheckWalTransactionsJob.runSerially(CheckWalTransactionsJob.java:105)
2024-01-11T11:43:55.7610618Z 	at io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:40)
2024-01-11T11:43:55.7611332Z 	at io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:49)
2024-01-11T11:43:55.7612236Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1338)
2024-01-11T11:43:55.7612740Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1331)
2024-01-11T11:43:55.7613141Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1345)
2024-01-11T11:43:55.7613531Z 	at io.questdb.test.cairo.TableNameRegistryTest.testFuzz0(TableNameRegistryTest.java:960)
2024-01-11T11:43:55.7613964Z 	at io.questdb.test.cairo.TableNameRegistryTest.lambda$testFuzz$16(TableNameRegistryTest.java:603)
2024-01-11T11:43:55.7614332Z 	at java.lang.Thread.run(Thread.java:829)
2024-01-11T11:43:55.7614581Z ]
...
```
