### ISSUE TITLE
Flaky test PGJobContextTest.testExecuteAndCancelSqlCommands

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#4154]
### To reproduce

```
random seeds: 602460973177L, 1705949065518L
```

see log attached. This is especially concerning

```
2024-01-22T18:44:51.7513967Z 2024-01-22T18:44:45.812980Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=tab~8, error=
2024-01-22T18:44:51.7515223Z java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -4 out of bounds for long[16]
2024-01-22T18:44:51.7516087Z 	at java.lang.System.arraycopy(Native Method)
2024-01-22T18:44:51.7516879Z 	at io.questdb.std.LongList.removeIndexBlock(LongList.java:362)
2024-01-22T18:44:51.7517795Z 	at io.questdb.cairo.wal.WalTxnDetails.readObservableTxnMeta(WalTxnDetails.java:101)
2024-01-22T18:44:51.7518799Z 	at io.questdb.cairo.TableWriter.readWalTxnDetails(TableWriter.java:1937)
2024-01-22T18:44:51.7519817Z 	at io.questdb.cairo.wal.ApplyWal2TableJob.applyOutstandingWalTransactions(ApplyWal2TableJob.java:233)
2024-01-22T18:44:51.7520850Z 	at io.questdb.cairo.wal.ApplyWal2TableJob.applyWal(ApplyWal2TableJob.java:505)
2024-01-22T18:44:51.7521797Z 	at io.questdb.cairo.wal.ApplyWal2TableJob.doRun(ApplyWal2TableJob.java:560)
2024-01-22T18:44:51.7522755Z 	at io.questdb.mp.AbstractQueueConsumerJob.run(AbstractQueueConsumerJob.java:44)
2024-01-22T18:44:51.7523720Z 	at io.questdb.mp.Job.run(Job.java:57)
2024-01-22T18:44:51.7524622Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1335)
2024-01-22T18:44:51.7525592Z 	at io.questdb.test.AbstractCairoTest.drainWalQueue(AbstractCairoTest.java:1327)
2024-01-22T18:44:51.7526684Z 	at io.questdb.test.cutlass.pgwire.PGJobContextTest.lambda$testExecuteAndCancelSqlCommands$30(PGJobContextTest.java:3090)
2024-01-22T18:44:51.7527647Z 	at java.lang.Thread.run(Thread.java:829)
2024-01-22T18:44:51.7528293Z ]

```

### QuestDB version:

7.3.9

### OS, in case of Docker specify Docker and the Host OS:

Linux, ARM64

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

[178.zip](https://github.com/questdb/questdb/files/14022410/178.zip)

**Comment by glasstiger** [comment]
we should repoen https://github.com/questdb/questdb/issues/4144

**Comment by glasstiger** [comment]
another failure:
```
2024-01-22T11:23:46.3311270Z 2024-01-22T11:23:46.270436Z I i.q.t.TestListener >>>> io.questdb.test.cutlass.pgwire.PGJobContextTest.testExecuteAndCancelSqlCommands[NO_WAL]
2024-01-22T11:23:46.3316310Z 2024-01-22T11:23:46.270478Z I i.q.t.c.p.PGJobContextTest random seeds: 1434230362177L, 1705922626270L
2024-01-22T11:23:46.3318380Z 2024-01-22T11:23:46.270910Z I i.q.t.AbstractTest Starting test PGJobContextTest#testExecuteAndCancelSqlCommands[NO_WAL]
2024-01-22T11:23:46.3320590Z 2024-01-22T11:23:46.272348Z I i.q.c.TableNameRegistryStore reloading tables file [path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit2885401098709940184/dbRoot/tables.d.0, threadId=15177]
2024-01-22T11:23:46.3322500Z 2024-01-22T11:23:46.272442Z I i.q.t.c.p.PGJobContextTest fragmentation params [sendBufferSize=3584, forceSendFragmentationChunkSize=62, recvBufferSize=5632, forceRecvFragmentationChunkSize=42]
2024-01-22T11:23:46.3324460Z 2024-01-22T11:23:46.272526Z I i.q.t.AbstractCairoTest Tearing down test PGJobContextTest#testExecuteAndCancelSqlCommands[NO_WAL]
2024-01-22T11:23:46.3330050Z 2024-01-22T11:23:46.272791Z I i.q.t.AbstractTest Finished test PGJobContextTest#testExecuteAndCancelSqlCommands[NO_WAL]
2024-01-22T11:23:46.3332140Z 2024-01-22T11:23:46.273405Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.cutlass.pgwire.PGJobContextTest.testExecuteAndCancelSqlCommands[NO_WAL] duration_ms=3 : 
2024-01-22T11:23:46.3333840Z org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
2024-01-22T11:23:46.3337670Z 	at org.junit.Assume.assumeThat(Assume.java:106)
2024-01-22T11:23:46.3339440Z 	at org.junit.Assume.assumeTrue(Assume.java:50)
2024-01-22T11:23:46.3343830Z 	at io.questdb.test.cutlass.pgwire.PGJobContextTest.testExecuteAndCancelSqlCommands(PGJobContextTest.java:2937)
2024-01-22T11:23:46.3347450Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-01-22T11:23:46.3350570Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-01-22T11:23:46.3353230Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-01-22T11:23:46.3355860Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2024-01-22T11:23:46.3357790Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2024-01-22T11:23:46.3360890Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-01-22T11:23:46.3364850Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2024-01-22T11:23:46.3368330Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-01-22T11:23:46.3372120Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-01-22T11:23:46.3376180Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2024-01-22T11:23:46.3378520Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2024-01-22T11:23:46.3381610Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2024-01-22T11:23:46.3384750Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2024-01-22T11:23:46.3389760Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-01-22T11:23:46.3402670Z 	at java.lang.Thread.run(Thread.java:829)
2024-01-22T11:23:46.3419050Z 2024-01-22T11:23:46.273487Z I i.q.t.TestListener <<<< io.questdb.test.cutlass.pgwire.PGJobContextTest.testExecuteAndCancelSqlCommands[NO_WAL] duration_ms=3
```

[206.txt.zip](https://github.com/questdb/questdb/files/14022505/206.txt.zip)
