### ISSUE TITLE
`AssertionError` with `WHERE` clause containing 4 or more `AND` clauses with `=`, `>=` and `<=` operators *Bug*

### ISSUE THREAD

**Issue by tomaszkstech** [questdb/questdb#4187]
### To reproduce

Using QuestDB Console, create two tables with the following statements
```
CREATE TABLE 'WorkflowEvent' (
  CreateDate timestamp,
  Id uuid,
  TenantId int,
  UserId int,
  EventTypeId int
) timestamp (CreateDate) partition by hour wal;

CREATE TABLE 'WorkflowEventAction' (
  CreateDate TIMESTAMP,
  WorkflowEventId UUID,
  ActionTypeId INT,
  Message STRING
) timestamp (CreateDate) PARTITION BY HOUR WAL;
```
Run the select statement from QuestDB Console 
```
SELECT  1
FROM    WorkflowEvent el

JOIN    WorkflowEventAction ep0
  ON    el.CreateDate = ep0.CreateDate
  and   el.Id = ep0.WorkflowEventId
  and   ep0.ActionTypeId = 13
  and   ep0.Message = '2'

join    WorkflowEventAction ep
  on    el.CreateDate = ep.CreateDate
  and   el.Id = ep.WorkflowEventId
  and   ep.ActionTypeId = 8

WHERE   el.UserId = 19
  and   el.TenantId = 24024
  and   el.EventTypeId = 1
  and   el.CreateDate >= to_timestamp('2024-01-26T18:26:14.000000Z', 'yyyy-MM-ddTHH:mm:ss.SSSUUUZ') 
  and   el.CreateDate <= to_timestamp('2024-01-26T18:47:49.994262Z', 'yyyy-MM-ddTHH:mm:ss.SSSUUUZ')
```
And Following exception occurs
```
2024-02-02T10:48:08.882425Z C i.q.c.h.p.JsonQueryProcessorState [33] internal error [ex=
java.lang.AssertionError
        at io.questdb.griffin.SqlOptimiser.mergeContexts(SqlOptimiser.java:2156)
        at io.questdb.griffin.SqlOptimiser.addJoinContext(SqlOptimiser.java:397)
        at io.questdb.griffin.SqlOptimiser.analyseEquals(SqlOptimiser.java:720)
        at io.questdb.griffin.SqlOptimiser.processJoinConditions(SqlOptimiser.java:2992)
        at io.questdb.griffin.SqlOptimiser.optimiseJoins(SqlOptimiser.java:2759)
        at io.questdb.griffin.SqlOptimiser.optimiseJoins(SqlOptimiser.java:2777)
        at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:5082)
        at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel0(SqlCompilerImpl.java:1379)
        at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel(SqlCompilerImpl.java:1368)
        at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:1463)
        at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1432)
        at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:234)
        at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:104)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileAndExecuteQuery(JsonQueryProcessor.java:436)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:189)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:247)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:869)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:253)
        at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:81)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
        at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:85)
        at io.questdb.mp.Worker.run(Worker.java:148)
```
This problem occurs on `Linux` and `Windows`, however `Container Image` does not suffer from this issue, which is most likely due to Java's `assert` not being enabled (`-ea` argument on startup)

When I update `WHERE` statement by replacing `ColumnName = ...` with `ColumnName IN (...)` the problem 'goes away'
```
WHERE   el.UserId IN (19)
  and   el.TenantId = 24024
  and   el.EventTypeId = 1
  and   el.CreateDate >= to_timestamp('2024-01-26T18:26:14.000000Z', 'yyyy-MM-ddTHH:mm:ss.SSSUUUZ') 
  and   el.CreateDate <= to_timestamp('2024-01-26T18:47:49.994262Z', 'yyyy-MM-ddTHH:mm:ss.SSSUUUZ')
```
The `IN` is not specific to UserId column, could be different column

I am not able to find exact cause of this, however I did observe the assertion failing when `a.slaveIndex = -1` and `b.slaveIndex = 0`
https://github.com/questdb/questdb/blob/a46922fe3ae9809e94b3fe2e4257ca4b1fb97bb5/core/src/main/java/io/questdb/griffin/SqlOptimiser.java#L2156

### QuestDB version:

7.3.9

### OS, in case of Docker specify Docker and the Host OS:

Windows 11, (VM) Ubuntu 20.04.6 LTS

### File System, in case of Docker specify Host File System:

Windows, Linux, Container

### Full Name:

Tomasz Ksiezarek

### Affiliation:

C#

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [ ] Yes, I have

**Comment by gaurichaudhari9** [comment]
Hi, @shwetarkadam and I (@gaurichaudhari9) would like to work on this issue collaboratively since this would be our first open source contribution. Can both of us be the assignees?
