### ISSUE TITLE
Flaky SnapshotFuzzTest.testFullFuzz

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#4210]
### To reproduce

linux-griffin:
```
2024-02-14T09:14:15.873035Z I i.q.t.AbstractTest Starting test SnapshotFuzzTest#testFullFuzzEjectedTransactions
random seeds: 1177683092955L, 1707902055873L
...
io.questdb.cairo.CairoException: [2] could not open read-only [file=/tmp/junit16820482392854590098/dbRoot/testFullFuzz~2/_meta]
	at io.questdb.cairo.CairoException.instance(CairoException.java:310)
	at io.questdb.cairo.CairoException.critical(CairoException.java:69)
	at io.questdb.cairo.TableUtils.openRO(TableUtils.java:1147)
	at io.questdb.cairo.vm.MemoryCMRImpl.openFile(MemoryCMRImpl.java:115)
	at io.questdb.cairo.vm.MemoryCMRImpl.of(MemoryCMRImpl.java:88)
	at io.questdb.cairo.vm.MemoryCMRImpl.smallFile(MemoryCMRImpl.java:103)
	at io.questdb.cairo.TableReaderMetadata.load(TableReaderMetadata.java:238)
	at io.questdb.cairo.DatabaseSnapshotAgentImpl.rebuildTableFiles(DatabaseSnapshotAgentImpl.java:174)
	at io.questdb.cairo.DatabaseSnapshotAgentImpl.lambda$recoverSnapshot$0(DatabaseSnapshotAgentImpl.java:504)
	at io.questdb.std.FilesFacadeImpl.iterateDir(FilesFacadeImpl.java:255)
	at io.questdb.cairo.DatabaseSnapshotAgentImpl.recoverSnapshot(DatabaseSnapshotAgentImpl.java:444)
	at io.questdb.cairo.CairoEngine.recoverSnapshot(CairoEngine.java:886)
	at io.questdb.test.griffin.wal.SnapshotFuzzTest.restoreSnapshot(SnapshotFuzzTest.java:142)
	at io.questdb.test.griffin.wal.SnapshotFuzzTest.lambda$runFuzzWithSnapshot$1(SnapshotFuzzTest.java:197)
```

### QuestDB version:

latest master

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by ideoma** [comment]
Fixed in #4212
