### ISSUE TITLE
Flaky PGJobContextTest.testRunAlterWhenTableLockedAndAlterTakesTooLong()

### ISSUE THREAD

**Issue by glasstiger** [questdb/questdb#4222]
### To reproduce

Intermittent CI build failure.

Full log: 
[201.txt.zip](https://github.com/questdb/questdb/files/14346853/201.txt.zip)

```
2024-02-20T13:49:11.890578Z I i.q.t.AbstractCairoTest Tearing down test PGJobContextTest#testRunAlterWhenTableLockedAndAlterTakesTooLong[NO_WAL]
2024-02-20T13:49:11.890716Z I i.q.t.AbstractTest Finished test PGJobContextTest#testRunAlterWhenTableLockedAndAlterTakesTooLong[NO_WAL]
2024-02-20T13:49:11.893824Z I i.q.t.c.p.PGJobContextTest os scheduled worker stopped [name=pgwire_1]
random seeds: 1804945292400L, 1708436951897L
2024-02-20T13:49:11.902003Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.cutlass.pgwire.PGJobContextTest.testRunAlterWhenTableLockedAndAlterTakesTooLong[NO_WAL] duration_ms=3783 : 
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.questdb.test.cutlass.pgwire.PGJobContextTest.testAddColumnBusyWriter(PGJobContextTest.java:10325)
	at io.questdb.test.cutlass.pgwire.PGJobContextTest.lambda$testRunAlterWhenTableLockedAndAlterTakesTooLong$115(PGJobContextTest.java:7466)
	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$7(AbstractCairoTest.java:917)
	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:619)
	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:914)
	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:908)
	at io.questdb.test.cutlass.pgwire.PGJobContextTest.testRunAlterWhenTableLockedAndAlterTakesTooLong(PGJobContextTest.java:7452)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:829)
2024-02-20T13:49:11.902204Z I i.q.t.TestListener <<<< io.questdb.test.cutlass.pgwire.PGJobContextTest.testRunAlterWhenTableLockedAndAlterTakesTooLong[NO_WAL] duration_ms=3783
```

### QuestDB version:

7.3.10-SNAPSHOT

### OS, in case of Docker specify Docker and the Host OS:

OS name: "windows server 2022", version: "10.0", arch: "amd64", family: "windows" (windows-other build)

### File System, in case of Docker specify Host File System:

db root: [path=C:\Users\VSSADM~1\AppData\Local\Temp\junit3949181730815152129\dbRoot\db, magic=0x2b] -> SUPPORTED (windows-other build)

### Full Name:

Imre Aranyosi

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by glasstiger** [comment]
happened again.

full log:

[391.txt.zip](https://github.com/user-attachments/files/18771602/391.txt.zip)
