### ISSUE TITLE
Flaky test DirectUtf8SinkTest.testCreateEmpty

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#4243]
### To reproduce

```
2024-02-23T17:09:02.881012Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.std.str.DirectUtf8SinkTest.testCreateEmpty duration_ms=207 : 
java.lang.AssertionError: expected:<1> but was:<4>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.questdb.test.std.str.DirectUtf8SinkTest.testCreateEmpty(DirectUtf8SinkTest.java:108)

```

### QuestDB version:

7.3.10

### OS, in case of Docker specify Docker and the Host OS:

na

### File System, in case of Docker specify Host File System:

na

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by ideoma** [comment]
Fails at last line here:

```Java
@Test
    public void testCreateEmpty() {
        System.gc(); // This test is sensitive to GC deallocating GcUtf8String memory
        final long mallocCount0 = Unsafe.getMallocCount();
        final long reallocCount0 = Unsafe.getReallocCount();
        final long freeCount0 = Unsafe.getFreeCount();
        final long memUsed0 = Unsafe.getMemUsedByTag(MemoryTag.NATIVE_DIRECT_UTF8_SINK);
        final Supplier<Long> getMallocCount = () -> Unsafe.getMallocCount() - mallocCount0;
        final Supplier<Long> getReallocCount = () -> Unsafe.getReallocCount() - reallocCount0;
        final Supplier<Long> getFreeCount = () -> Unsafe.getFreeCount() - freeCount0;
        final Supplier<Long> getMemUsed = () -> Unsafe.getMemUsedByTag(MemoryTag.NATIVE_DIRECT_UTF8_SINK) - memUsed0;

        try (DirectUtf8Sink sink = new DirectUtf8Sink(0)) {
            Assert.assertEquals(0, sink.size());
            Assert.assertEquals(32, sink.capacity());
            final long ptr = sink.ptr();
            Assert.assertNotEquals(0, ptr);
            Assert.assertEquals(1, getMallocCount.get().longValue());
```

**Comment by ideoma** [comment]
One more

```
2024-03-01T18:35:32.485433Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.std.str.DirectUtf8SinkTest.testCreateEmpty duration_ms=251 : 
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.questdb.test.std.str.DirectUtf8SinkTest.testCreateEmpty(DirectUtf8SinkTest.java:110)

```
