### ISSUE TITLE
Internal error due to a bad filter

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#4591]
### To reproduce

Go to the demo box and run this: 
```sql
select * from trades WHERE
timestamp = (select max(timestamp) from trades)
```

It produces this error:
```
2024-05-27T16:58:42.779066Z E i.q.c.s.a.PageFrameReduceJob reduce error [ex=
java.lang.UnsupportedOperationException
	at io.questdb.griffin.engine.functions.CursorFunction.getLong(CursorFunction.java:123)
	at io.questdb.griffin.engine.functions.eq.EqLongFunctionFactory$Func.getBool(EqLongFunctionFactory.java:58)
	at io.questdb.griffin.engine.table.AsyncFilteredRecordCursorFactory.filter(AsyncFilteredRecordCursorFactory.java:230)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.reduce(PageFrameReduceJob.java:243)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:190)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.run(PageFrameReduceJob.java:152)
	at io.questdb.mp.Worker.run(Worker.java:151)
]
```
A REST user will get this error: `unexpected filter error`

In fact, it's just a syntax error. Ideally, it should state QuestDB does not support scalar queries. but that's nice-to-have. 
Also: It should not produce such scary log message. 

Q: Why EqLongFunctionFactory matches with a cursor function? 

### QuestDB version:

7.3.4-snapshot (demo box)

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

dunno

### Full Name:

Jaromir Hamala

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by jerrinot** [comment]
dup of https://github.com/questdb/questdb/issues/4627
