### ISSUE TITLE
Unexpected Filter error

### ISSUE THREAD

**Issue by Sibsankar01** [questdb/questdb#4627]
### To reproduce

Go to the demo box and run this:

select * from trades WHERE
timestamp = (select max(timestamp) from trades)
It produces this error:

2024-05-27T16:58:42.779066Z E i.q.c.s.a.PageFrameReduceJob reduce error [ex=
java.lang.UnsupportedOperationException
	at io.questdb.griffin.engine.functions.CursorFunction.getLong(CursorFunction.java:123)
	at io.questdb.griffin.engine.functions.eq.EqLongFunctionFactory$Func.getBool(EqLongFunctionFactory.java:58)
	at io.questdb.griffin.engine.table.AsyncFilteredRecordCursorFactory.filter(AsyncFilteredRecordCursorFactory.java:230)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.reduce(PageFrameReduceJob.java:243)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:190)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.run(PageFrameReduceJob.java:152)
	at io.questdb.mp.Worker.run(Worker.java:151)
]

### QuestDB version:

7.3.4-snapshot (demo box)

### OS, in case of Docker specify Docker and the Host OS:

windows

### File System, in case of Docker specify Host File System:

dunno

### Full Name:

Sibsankar Maity

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by puzpuzpuz** [comment]
This syntax is not supported. If you need the row with max timestamp, it's as simple as this:
```sql
SELECT *
FROM trades
LIMIT -1;
```

If you want a row with the max timestamp for each currency pair, the query is this one:
```sql
SELECT *
FROM trades
LATEST ON timestamp PARTITION BY symbol;
```

**Comment by jerrinot** [comment]
@Sibsankar01 Why are you copying an existing issue? This issue is a carbon copy of an already [existing issue](https://github.com/questdb/questdb/issues/4591), down to the timestamps in the log snippet:
<img width="879" alt="image" src="https://github.com/questdb/questdb/assets/158619/21c2ecf4-1e43-47d4-9f05-7c5c7f412172">

The already existing issue:
<img width="879" alt="image" src="https://github.com/questdb/questdb/assets/158619/635e42f0-b5dd-4194-b1cf-da17c5528430">

This issue is adding nothing new. You're just wasting the time of the maintainers, helping absolutely no one. If you genuinely want to understand more about QuestDB, join us on [QuestDB Slack](https://slack.questdb.io/) where all the maintainers hang out. But stop cloning existing issues - it's utterly counterproductive and irritating! Don't do that.
