### ISSUE TITLE
Cannot run 8.0.0 on ARM64 machine

### ISSUE THREAD

**Issue by kaon** [questdb/questdb#4635]
### To reproduce

1. Download no JRE version from release pages.
2. Run questdb.sh after extraction

* Reverted to 7.4.2 after failure *

### QuestDB version:

8.0.0

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 20.04.6 LTS

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

F Wong

### Affiliation:

Personal

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

java.lang.UnsatisfiedLinkError: /tmp/libquestdb9433430817609727446.so: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/libquestdb9433430817609727446.so)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1957)
        at io.questdb@8.0.0/io.questdb.std.Os.loadLib(Os.java:247)
        at io.questdb@8.0.0/io.questdb.std.Os.loadLib(Os.java:225)
        at io.questdb@8.0.0/io.questdb.std.Os.<clinit>(Os.java:299)
        at io.questdb@8.0.0/io.questdb.Bootstrap.<clinit>(Bootstrap.java:686)
        at io.questdb@8.0.0/io.questdb.ServerMain.<init>(ServerMain.java:74)
        at io.questdb@8.0.0/io.questdb.ServerMain.main(ServerMain.java:167)
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class io.questdb.std.Os
        at io.questdb@8.0.0/io.questdb.log.LogFactory.<clinit>(LogFactory.java:1157)
        at io.questdb@8.0.0/io.questdb.ServerMain.main(ServerMain.java:170)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/libquestdb9433430817609727446.so: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/libquestdb9433430817609727446.so) [in thread "main"]
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1957)
        at io.questdb@8.0.0/io.questdb.std.Os.loadLib(Os.java:247)
        at io.questdb@8.0.0/io.questdb.std.Os.loadLib(Os.java:225)
        at io.questdb@8.0.0/io.questdb.std.Os.<clinit>(Os.java:299)
        at io.questdb@8.0.0/io.questdb.Bootstrap.<clinit>(Bootstrap.java:686)
        at io.questdb@8.0.0/io.questdb.ServerMain.<init>(ServerMain.java:74)
        at io.questdb@8.0.0/io.questdb.ServerMain.main(ServerMain.java:167)

**Comment by bluestreak01** [comment]
could you show us output of:

```
ldd --version
```

**Comment by puzpuzpuz** [comment]
> Ubuntu 20.04.6 LTS

You should try on a newer Ubuntu version. Your Ubuntu version uses an outdated glibc version.

**Comment by kaon** [comment]
@puzpuzpuz  Thanks for your advice. I overlooked the "breaking changes" section.

**Comment by baldersheim** [comment]
Was it intentional to require glib 2.28 for x86_64, and 2.33 for aarch64 ?
Then rhel 8 variants must stick to latest quest db 7 if they release for aarch64.
This is rather cumbersome. Any particular reason why a newer glibc is required for aarch64 ?
