### ISSUE TITLE
Flaky Test ServerMainFlushQueryCacheTest.testFlushQueryCache

### ISSUE THREAD

**Issue by siddharth0815** [questdb/questdb#4683]
### To reproduce

Build : https://dev.azure.com/questdb/questdb/_build/results?buildId=93730&view=logs&s=b1ea3234-5a2e-5e99-b54b-09a630ee02b3&j=d09f5293-c9fd-59aa-4afb-b3372a468ff9
```
2024-06-15T21:10:33.967644Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.PropServerConfigurationTest.testImportWorkRootCantBeTheSameAsOtherInstanceDirectories2 duration_ms=0 : 
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
	at org.junit.Assume.assumeThat(Assume.java:106)
	at org.junit.Assume.assumeTrue(Assume.java:50)
	at io.questdb.test.PropServerConfigurationTest.testImportWorkRootCantBeTheSameAsOtherInstanceDirectories2(PropServerConfigurationTest.java:695)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

```
Full logs: [https://dev.azure.com/questdb/6c9c1a0a-74cf-4f7b-bf65-24ae4f3cd61d/_apis/build/builds/93730/logs/200](https://dev.azure.com/questdb/6c9c1a0a-74cf-4f7b-bf65-24ae4f3cd61d/_apis/build/builds/93730/logs/200)

### QuestDB version:

8

### OS, in case of Docker specify Docker and the Host OS:

MacOS

### File System, in case of Docker specify Host File System:

NA

### Full Name:

Siddharth Agarwal

### Affiliation:

Zeta Suite

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by glasstiger** [comment]
Happened again.

Full log:
[251.txt.zip](https://github.com/user-attachments/files/15912484/251.txt.zip)

Cannot reproduce it, but because the query cache is cleared asynchronously, I wonder if the SQL command clearing the cache could stay in the cache sometimes somehow.

**Comment by jerrinot** [comment]
another failure, Linux-other. Logs: https://gist.github.com/jerrinot/0c892b1edd9c7e397a65f3cd7ce5594a
