### ISSUE TITLE
Flaky Test TableNameRegistryTest.testConcurrentCreateDropRemove

### ISSUE THREAD

**Issue by siddharth0815** [questdb/questdb#4694]
### To reproduce

testConcurrentCreateDropRemove(io.questdb.test.cairo.TableNameRegistryTest)  Time elapsed: 3.013 sec  <<< ERROR!
java.lang.RuntimeException: io.questdb.cairo.CairoException: [2] could not remove table [name=tab3, dirName=tab3~]
	at io.questdb.cairo.CairoException.instance(CairoException.java:319)
	at io.questdb.cairo.CairoException.critical(CairoException.java:69)
	at io.questdb.cairo.CairoEngine.drop(CairoEngine.java:372)
	at io.questdb.griffin.SqlCompilerImpl.dropTable(SqlCompilerImpl.java:2997)
	at io.questdb.griffin.SqlCompilerImpl$DropStatementCompiler.executorSelector(SqlCompilerImpl.java:3672)
	at io.questdb.griffin.SqlCompilerImpl.lambda$registerKeywordBasedExecutors$0(SqlCompilerImpl.java:3073)
	at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1519)
	at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:235)
	at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:128)
	at io.questdb.cairo.CairoEngine.drop(CairoEngine.java:392)
	at io.questdb.cairo.CairoEngine.drop(CairoEngine.java:387)
	at io.questdb.test.AbstractCairoTest.drop(AbstractCairoTest.java:1299)
	at io.questdb.test.cairo.TableNameRegistryTest.lambda$testConcurrentCreateDropRemove$0(TableNameRegistryTest.java:83)

### QuestDB version:

8

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

NA

### Full Name:

Siddharth Agarwal

### Affiliation:

Zeta Suite

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

Logs: https://dev.azure.com/questdb/questdb/_build/results?buildId=94393&view=logs&j=8f858363-769a-553b-1632-ee3f98937717&t=a97a846a-22f8-5861-c99e-c283c78c1111

**Comment by glasstiger** [comment]
happened again.

logs:
[315.txt.zip](https://github.com/user-attachments/files/17366611/315.txt.zip)
