### ISSUE TITLE
SAMPLE BY in combination with string constant as field fails

### ISSUE THREAD

**Issue by mrosi** [questdb/questdb#4724]
### To reproduce

Query fails if there is combination of constant string as field and sample by clause:
- in this case: `'SIP' as feed_table,` and `sample by 5m align to calendar`
- if I clear one of this parts, query works
```
2024-06-27T11:18:17.183817Z E i.q.g.e.QueryProgress err [id=-1, sql=`with srctbl as (
  select
      period_start_time,
      cal_timestamp_time nas_timestamp,
      'SIP' as feed_table,
      device_name,
      application_name,
      application_group,
      source_host_ip_address,
      destination_host_ip_address,
      message_name,
      user_agent,
      response_description,
      response_code,
      min(controlplane_response_time_usec) min_response_time_usec,
      max(controlplane_response_time_usec) max_response_time_usec,
      sum(controlplane_response_time_usec) total_response_time_usec,
      count(controlplane_response_time_usec) count_response_time,
      count() events
  from (
    select * from (
    select
      controlplane_transaction_start_time as period_start_time,
      *
    from nAS_ControlPlane_SIP
    where
      cal_timestamp_time > dateadd('m',-10,now())
      and cal_timestamp_time < dateadd('m',-5,now())
      and not controlplane_transaction_start_time is null
    order by 1 asc

    )
    timestamp(period_start_time)
  ) sample by 5m align to calendar
)
select * from srctbl limit 10
`, principal=admin, cache=false, time=1313893, msg=Cannot read field "token" because the return value of "io.questdb.griffin.model.QueryModel.getTimestamp()" is null, errno=0, pos=0]
2024-06-27T11:18:17.184226Z C i.q.c.h.p.JsonQueryProcessorState [2988] internal error [ex=
java.lang.NullPointerException: Cannot read field "token" because the return value of "io.questdb.griffin.model.QueryModel.getTimestamp()" is null
        at io.questdb.griffin.SqlOptimiser.rewriteSelectClause0(SqlOptimiser.java:5109)
        at io.questdb.griffin.SqlOptimiser.rewriteSelectClause(SqlOptimiser.java:4701)
        at io.questdb.griffin.SqlOptimiser.rewriteSelectClause(SqlOptimiser.java:4688)
        at io.questdb.griffin.SqlOptimiser.rewriteSelectClause(SqlOptimiser.java:4688)
        at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:5702)
        at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel0(SqlCompilerImpl.java:1477)
        at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel(SqlCompilerImpl.java:1466)
        at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:1574)
        at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1541)
        at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:235)
        at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:128)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileAndExecuteQuery(JsonQueryProcessor.java:468)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:191)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:266)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:915)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:256)
        at io.questdb.cutlass.http.HttpServer.handleClientOperation(HttpServer.java:307)
        at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:114)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
        at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:118)
        at io.questdb.mp.Worker.run(Worker.java:151)
, q=`with srctbl as (
  select
      period_start_time,
      cal_timestamp_time nas_timestamp,
      'SIP' as feed_table,
      device_name,
      application_name,
      application_group,
      source_host_ip_address,
      destination_host_ip_address,
      message_name,
      user_agent,
      response_description,
      response_code,
      min(controlplane_response_time_usec) min_response_time_usec,
      max(controlplane_response_time_usec) max_response_time_usec,
      sum(controlplane_response_time_usec) total_response_time_usec,
      count(controlplane_response_time_usec) count_response_time,
      count() events
  from (
    select * from (
    select
      controlplane_transaction_start_time as period_start_time,
      *
    from nAS_ControlPlane_SIP
    where
      cal_timestamp_time > dateadd('m',-10,now())
      and cal_timestamp_time < dateadd('m',-5,now())
      and not controlplane_transaction_start_time is null
    order by 1 asc

    )
    timestamp(period_start_time)
  ) sample by 5m align to calendar
)
select * from srctbl limit 10
`]
```

### QuestDB version:

8.0.1

### OS, in case of Docker specify Docker and the Host OS:

RHEL 9

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Martin Rosicky

### Affiliation:

Simac/Vodafone

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

Last working version was 7.4.0

**Comment by puzpuzpuz** [comment]
@mrosi could you also share schema for the `nAS_ControlPlane_SIP` and `srctbl` tables?

**Comment by mrosi** [comment]
hi Andrei,
`srctbl` is part of the query, `nAS_ControlPlane_SIP` schema is here:
```sql
CREATE TABLE 'nAS_ControlPlane_SIP' (
  cal_timestamp_time TIMESTAMP,
  controlplane_transaction_start_time TIMESTAMP,
  device_name SYMBOL capacity 64 CACHE,
  device_ip_address SYMBOL capacity 64 CACHE,
  application_protocol_type_code SYMBOL capacity 16 CACHE,
  application_name SYMBOL capacity 8 CACHE,
  application_group SYMBOL capacity 8 CACHE,
  message_protocol_type_code SYMBOL capacity 128 CACHE,
  message_name SYMBOL capacity 128 CACHE,
  user_agent SYMBOL capacity 256 CACHE,
  controlplane_transaction_status_name SYMBOL capacity 8 CACHE,
  response_description SYMBOL capacity 256 CACHE,
  apn_name SYMBOL capacity 16384 CACHE,
  client_server_entry_type_name SYMBOL capacity 8 CACHE,
  celltype_name SYMBOL capacity 8 CACHE,
  rat_name SYMBOL capacity 8 CACHE,
  b_rat_name SYMBOL capacity 8 CACHE,
  visited_plmn_name SYMBOL capacity 16384 CACHE,
  home_plmn_name SYMBOL capacity 16384 CACHE,
  destination_host_diameter_name SYMBOL capacity 128 CACHE,
  destination_realm_diameter_name SYMBOL capacity 128 CACHE,
  origin_host_diameter_name SYMBOL capacity 128 CACHE,
  origin_realm_diameter_name SYMBOL capacity 128 CACHE,
  source_host_ip_address STRING,
  destination_host_ip_address STRING,
  subscriber_ip_address STRING,
  calling_address STRING,
  called_address STRING,
  response_code INT,
  onnet_flag INT,
  qos_class_id INT,
  subscriber_id LONG,
  subscriber_msisdn LONG,
  userequipment_imeisv STRING,
  controlplane_response_time_usec LONG,
  userequipment_sv STRING,
  userequipment_tac STRING,
  controlplane_transaction_id LONG,
  cell_area LONG,
  cell_id LONG,
  cell_updated_flag INT,
  cell_mcc STRING,
  cell_mnc STRING,
  trackingarea_code INT
) timestamp (cal_timestamp_time) PARTITION BY HOUR WAL;
```

**Comment by puzpuzpuz** [comment]
Thanks for the update!

**Comment by mrosi** [comment]
Hi,
I've found 'simple' workaround ... just move `'SIP' as feed_table,` to subqeury.
So that working query looks like this:
```sql
  select
      period_start_time,
      cal_timestamp_time nas_timestamp,
      feed_table,
      device_name,
      application_name,
      application_group,
      source_host_ip_address,
      destination_host_ip_address,
      message_name,
      user_agent,
      response_description,
      response_code,
      min(controlplane_response_time_usec) min_response_time_usec,
      max(controlplane_response_time_usec) max_response_time_usec,
      sum(controlplane_response_time_usec) total_response_time_usec,
      count(controlplane_response_time_usec) count_response_time,
      count() events
  from (
    select * from (
    select
      controlplane_transaction_start_time as period_start_time,
      'SIP' as feed_table,
      *
    from nAS_ControlPlane_SIP
    where
      cal_timestamp_time > dateadd('m',-10,now())
      and cal_timestamp_time < dateadd('m',-5,now())
      and not controlplane_transaction_start_time is null
    order by 1 asc

    )
    timestamp(period_start_time)
  ) sample by 5m align to calendar
)
select * from srctbl limit 10
```

**Comment by puzpuzpuz** [comment]
@mrosi sorry for the delay. I started looking into this bug, so hopefully, it'll be gone in the next release. Great that you've found a workaround.
