### ISSUE TITLE
Explain Query Error: QuestDB is not reachable [500]

### ISSUE THREAD

**Issue by John3927** [questdb/questdb#4805]
### To reproduce

I am running EXPLAIN on a query like this:

```SQL
explain Select data."Device", "Attribute", Value, "Time" from data
join sensors on "Device" where (sensors.column = 'AB' and "Floor" = '50')
```

Where data is a table with > 150 million rows, and device is a table with ~5000 rows. The above query throws the error:

QuestDB is not reachable [500].

However, when I query it like this: 

```SQL
explain Select data."Device", "Attribute", Value, "Time" from data
join sensors on "Device" where (sensors.column = 'AB', "Floor" = '50')
```

There is no error.

Moreover, I ran the first EXPLAIN statement when "data" had about 30 million rows.

Any idea as to why it is happening?

### QuestDB version:

8.0.3

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 24.04 LTS

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Johnny Kung

### Affiliation:

Academical

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by puzpuzpuz** [comment]
EXPLAIN statements don't access the data, so the number of rows present in the table makes no difference. Could you check your server logs for any ` E ` and ` C ` messages after running the problematic queries? Also, would be great if you could share the table schema.

**Comment by John3927** [comment]
I might have remembered wrong about the first query succeeding. It might have been a similar, but different, EXPLAIN statement that succeeded before.

Schemas:

```SQL
CREATE TABLE 'data' (
  Device SYMBOL capacity 4096 CACHE index capacity 256,
  Attribute SYMBOL capacity 512 CACHE index capacity 256,
  Attribute_index INT,
  Value DOUBLE,
  Time TIMESTAMP
) timestamp (Time) PARTITION BY DAY WAL;
```


```SQL
CREATE TABLE 'sensors' (
  Device SYMBOL capacity 4096 CACHE index capacity 256,
  Device_UUID SYMBOL capacity 4096 CACHE index capacity 256,
  Type SYMBOL capacity 4 CACHE,
  hashcode TIMESTAMP,
  rack_type SYMBOL capacity 256 CACHE,
  row SYMBOL capacity 256 CACHE index capacity 256,
  col SYMBOL capacity 256 CACHE index capacity 256,
  front_rear SYMBOL capacity 256 CACHE,
  device_type SYMBOL capacity 256 CACHE,
  Floor SYMBOL capacity 32 CACHE index capacity 256
) timestamp (hashcode) PARTITION BY YEAR WAL DEDUP UPSERT KEYS(Device_name, hashcode);
```

This is a WAL table with a hashcode timestamp is due to the QuestDB package on python. The DataFrame function requires the table to be a WAL table, so I created a hash for them in my pre-processing step.


There is indeed a C message in the log:

```
2024-07-24T01:52:18.023951Z C i.q.c.h.p.JsonQueryProcessorState [24] internal error [ex=
java.lang.AssertionError
	at io.questdb.std.IntList.getQuick(IntList.java:139)
	at io.questdb.griffin.engine.table.DataFrameRecordCursorFactory.getBaseColumnName(DataFrameRecordCursorFactory.java:90)
	at io.questdb.griffin.BasePlanSink.putBaseColumnName(BasePlanSink.java:132)
	at io.questdb.griffin.engine.table.DeferredSymbolIndexFilteredRowCursorFactory.toPlan(DeferredSymbolIndexFilteredRowCursorFactory.java:97)
	at io.questdb.griffin.TextPlanSink.child(TextPlanSink.java:78)
	at io.questdb.griffin.engine.table.DataFrameRecordCursorFactory.toPlanInner(DataFrameRecordCursorFactory.java:224)
	at io.questdb.griffin.engine.table.DataFrameRecordCursorFactory.toPlan(DataFrameRecordCursorFactory.java:158)
	at io.questdb.griffin.TextPlanSink.child(TextPlanSink.java:75)
	at io.questdb.griffin.TextPlanSink.child(TextPlanSink.java:64)
	at io.questdb.griffin.engine.join.HashJoinLightRecordCursorFactory.toPlan(HashJoinLightRecordCursorFactory.java:109)
	at io.questdb.griffin.TextPlanSink.child(TextPlanSink.java:75)
	at io.questdb.griffin.engine.table.SelectedRecordCursorFactory.toPlan(SelectedRecordCursorFactory.java:118)
	at io.questdb.griffin.TextPlanSink.of(TextPlanSink.java:126)
	at io.questdb.griffin.engine.ExplainPlanFactory$ExplainPlanRecordCursor.of(ExplainPlanFactory.java:149)
	at io.questdb.griffin.engine.ExplainPlanFactory.getCursor(ExplainPlanFactory.java:59)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.of(JsonQueryProcessorState.java:879)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeExplain(JsonQueryProcessor.java:535)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileAndExecuteQuery(JsonQueryProcessor.java:477)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:191)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:266)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:915)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:256)
	at io.questdb.cutlass.http.HttpServer.handleClientOperation(HttpServer.java:307)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:114)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:118)
	at io.questdb.mp.Worker.run(Worker.java:151)
, q=`explain Select data."Device", "Attribute", Value, "Time" from data
join sensors on "Device" where (sensors."row" = 'AB' and "Floor" = '50')`]
2024-07-24T01:52:18.024621Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=24, lastRequestBytesSent=441, nCompletedRequests=3, totalBytesSent=2607]

```

Thank you for the response.

**Comment by John3927** [comment]
Changing the columns in the SELECT clause to * works:

```SQL
explain Select * from data
join sensors on "Device" where (sensors.column = 'AB' and "Floor" = '50')
```

This query succeeds.

**Comment by puzpuzpuz** [comment]
Indeed I got an unhandled exception on this query:
```sql
explain Select data."Device", "Attribute", Value, "Time" from data
join sensors on "Device" where (sensors."col" = 'AB' and "Floor" = '50')
```

```
2024-07-25T06:32:56.469116Z C i.q.c.h.p.JsonQueryProcessorState [33] internal error [ex=
java.lang.AssertionError
	at io.questdb.std.IntList.getQuick(IntList.java:139)
	at io.questdb.griffin.engine.table.DataFrameRecordCursorFactory.getBaseColumnName(DataFrameRecordCursorFactory.java:90)
	at io.questdb.griffin.BasePlanSink.putBaseColumnName(BasePlanSink.java:139)
	at io.questdb.griffin.engine.table.DeferredSymbolIndexFilteredRowCursorFactory.toPlan(DeferredSymbolIndexFilteredRowCursorFactory.java:97)
	at io.questdb.griffin.TextPlanSink.child(TextPlanSink.java:78)
	at io.questdb.griffin.engine.table.DataFrameRecordCursorFactory.toPlanInner(DataFrameRecordCursorFactory.java:224)
	at io.questdb.griffin.engine.table.DataFrameRecordCursorFactory.toPlan(DataFrameRecordCursorFactory.java:158)
	at io.questdb.griffin.TextPlanSink.child(TextPlanSink.java:75)
	at io.questdb.griffin.TextPlanSink.child(TextPlanSink.java:64)
	at io.questdb.griffin.engine.join.HashJoinLightRecordCursorFactory.toPlan(HashJoinLightRecordCursorFactory.java:109)
	at io.questdb.griffin.TextPlanSink.child(TextPlanSink.java:75)
	at io.questdb.griffin.engine.table.SelectedRecordCursorFactory.toPlan(SelectedRecordCursorFactory.java:118)
	at io.questdb.griffin.TextPlanSink.of(TextPlanSink.java:126)
	at io.questdb.griffin.engine.ExplainPlanFactory$ExplainPlanRecordCursor.of(ExplainPlanFactory.java:143)
	at io.questdb.griffin.engine.ExplainPlanFactory.getCursor(ExplainPlanFactory.java:58)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.of(JsonQueryProcessorState.java:879)
       ...
```

So, it's definitely a bug.
