### ISSUE TITLE
OOM logging is badly formatted

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#4806]
### To reproduce

```
2024-07-22T17:51:34.453589Z I i.q.c.TableWriter o3 commit [table=testWalWriteFullRandom_nonwal, o3RowCount=1769558]
sun.misc.Unsafe.allocateMemory() OutOfMemoryError [RSS_MEM_USED=4368849184, size=1055916032, memoryTag=45], original message: 2024-07-22T17:51:36.654908Z C i.q.c.TableWriter could not sort varsize o3 column [table=testWalWriteFullRandom_nonwal, column=var_top, type=VARCHAR, long0=1717520080960, long1=-1, long2=-1, long3=-1, errno=-1, ex=sun.misc.Unsafe.allocateMemory() OutOfMemoryError [RSS_MEM_USED=4368849184, size=1055916032, memoryTag=45], original message: ]

2024-07-22T17:51:37.098299Z I i.q.c.p.WriterPool << [table=`testWalWriteFullRandom_nonwal~`, thread=811]
2024-07-22T17:51:37.124256Z E i.q.t.AbstractCairoTest Error in test: 
io.questdb.cairo.CairoException: [-1] commit failed, see logs for details [table=testWalWriteFullRandom_nonwal, tableDir=testWalWriteFullRandom_nonwal~]
	at io.questdb.cairo.CairoException.instance(CairoException.java:323)
	at io.questdb.cairo.CairoException.critical(CairoException.java:69)
	at io.questdb.cairo.TableWriter.checkO3Errors(TableWriter.java:3399)
	at io.questdb.cairo.TableWriter.consumeColumnTasks(TableWriter.java:3706)
	at io.questdb.cairo.TableWriter.dispatchColumnTasks(TableWriter.java:4631)
	at io.questdb.cairo.TableWriter.o3Commit(TableWriter.java:5478)
	at io.questdb.cairo.TableWriter.commit(TableWriter.java:3525)
	at io.questdb.cairo.TableWriter.commit(TableWriter.java:994)
	at io.questdb.test.griffin.wal.FuzzRunner.applyNonWal(FuzzRunner.java:233)
	at io.questdb.test.griffin.wal.FuzzRunner.runFuzz(FuzzRunner.java:800)
	at io.questdb.test.griffin.wal.AbstractFuzzTest.lambda$fullRandomFuzz$0(AbstractFuzzTest.java:135)
	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$8(AbstractCairoTest.java:975)
	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:582)
	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:972)
	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:955)
	at io.questdb.test.griffin.wal.AbstractFuzzTest.fullRandomFuzz(AbstractFuzzTest.java:135)
	at io.questdb.test.griffin.wal.WalWriterFuzzTest.testWalWriteFullRandom(WalWriterFuzzTest.java:209)
```

- OOM exception is logged using `println`, not using loggers
- The logging is times nested, OOM inside OOM
- RSS limit is not logged, only used memory and (allocation?) size.

### QuestDB version:

8.0.3+

### OS, in case of Docker specify Docker and the Host OS:

Windows

### File System, in case of Docker specify Host File System:

ntfs

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by ideoma** [comment]
The ouptut is taken from CI running test with ceeds
```Java   
    @Test
    public void testWalWriteFullRandom() throws Exception {
        Rnd rnd = generateRandom(LOG, 2740134506100L, 1721669829168L);
        setRandomAppendPageSize(rnd);
        setFuzzProperties(rnd);
        fullRandomFuzz(rnd);
    }
```

**Comment by animeshchaudhri** [comment]
@ideoma  Can I work on this issue ?

**Comment by ideoma** [comment]
@animeshchaudhri  sure, please have a go.

**Comment by animeshchaudhri** [comment]
@ideoma Hey I can't figure out some stuff and need a little bit of guidance can I get your email or discord?

**Comment by ideoma** [comment]
Feel free to join our Slack https://slack.questdb.io/ , there is #contributors channel there or send a DM message to me there.

**Comment by shubh07sx** [comment]
Hi @ideoma , I saw that no one was working on it so i have raised a PR. Please have a look!
#5094

**Comment by DSHarshraj** [comment]
If this isn't closed I am taking on this. @ideoma

**Comment by ghost** [comment]
Hi @ideoma @bluestreak01
I've been working on the following enhancements related to OOM (Out-Of-Memory) exception logging and memory reporting:

1. Exception Logging Enhancement
   - Previously, OOM exceptions were being logged using the print() function.
   - This has now been updated to use LOG.error() for better logging practices and structured error reporting.
`LOG.error().$(exceptionObject).$()`

2. RSS Memory Limit Logging & Human-Readable Format
   - RSS memory limits were not previously included in the exception logs. I've added a new field RSS Limit with the value obtained from getRssMemLimit().
   - Memory values (which were previously in bytes) are now converted to GB for better readability.

3. Nested OOM Logging
    - I'm currently unable to test nested OOM scenarios locally, and it's unclear what's preventing the tests from running.
    - Guidance on how to effectively run and test this application locally would be greatly appreciated.


Please let me know if there are any suggestions or areas that need further improvement. Thanks!

**Comment by bluestreak01** [comment]
hi @sadmravi do you have a PR ?

**Comment by ghost** [comment]
Hi @bluestreak01, I’ve created a PR with improved OOM logging and memory formatting—could you please take a look?

**Comment by bluestreak01** [comment]
you cannot log out of Unsafe, it is a circular dependency, LOG uses Unsafe, Unsafe uses LOG etc. It would be good to run tests before review.

**Comment by ghost** [comment]
Hi @bluestreak01, I tried running the tests locally but got errors while setting up the environment. Could you please guide me on how to set it up?

**Comment by bluestreak01** [comment]
exception is question is thrown out of here: https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/std/Unsafe.java#L254

it is not a matter of adding additional logging, it is a matter of cleaning up the existing logging

I understand the problem this way:
- cairo exception is logged into stderr (printed), which mangles the log formatting
- when exception is constructed, the memory volumes should be logged as human-readable values, e.g. MiBs, GiBs or whatever. There is existing code that does that, it just has to be called
- the OOM is NOT nested, despite what the issue claims, if stderr print is removed - exception will be logged once
- this is also not "limit" exception, there is no need to log limit here, perhaps reword the message: we got exception from the OS, not via breaching our own limit, the limit is logged here: https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/std/Unsafe.java#L331


So, we don't need extra code, we need to tidy up the existing.

**Comment by Stacvirus** [comment]
Hi @ideoma, please can I work on this issue?

**Comment by Stacvirus** [comment]
Hi @ideoma @bluestreak01 have opened a PR, please have a look: #6839
