### ISSUE TITLE
Flaky TextLoaderTest.testBrokenUtf8Header

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#4823]
### To reproduce

```
2024-07-25T19:13:10.4198729Z 2024-07-25T19:13:10.415860Z I i.q.t.TestListener >>>> io.questdb.test.cutlass.text.TextLoaderTest.testBrokenUtf8Header[1]
2024-07-25T19:13:10.4201724Z 2024-07-25T19:13:10.416159Z I i.q.t.AbstractTest Starting test TextLoaderTest#testBrokenUtf8Header[1]
2024-07-25T19:13:10.4206848Z 2024-07-25T19:13:10.417276Z I i.q.c.TableNameRegistryStore reloading tables file [path=/tmp/junit16446519946058318935/dbRoot/tables.d.0, threadId=35403]
2024-07-25T19:13:10.4211049Z 2024-07-25T19:13:10.417429Z I i.q.c.t.TextLoader configured [table=`test`, overwrite=false, atomicity=1, partitionBy=NONE, timestamp=null, timestampFormat=null]
2024-07-25T19:13:10.4214887Z 2024-07-25T19:13:10.417990Z I i.q.c.t.TextDelimiterScanner scan result [table=`test`, delimiter=',', priority=10, mean=8.0, stddev=0.0]
2024-07-25T19:13:10.4217868Z 2024-07-25T19:13:10.418690Z I i.q.c.CairoEngine locked [table=`test~`, thread=35403]
2024-07-25T19:13:10.4256303Z 2024-07-25T19:13:10.425225Z I i.q.c.p.WriterPool created [table=`test~`, thread=35403]
2024-07-25T19:13:10.4258780Z 2024-07-25T19:13:10.425241Z I i.q.c.TableWriter open 'test'
2024-07-25T19:13:10.4287629Z 2024-07-25T19:13:10.428306Z I i.q.c.TableWriter switched partition [path=/test~/default]
2024-07-25T19:13:10.4299913Z 2024-07-25T19:13:10.429473Z I i.q.c.CairoEngine unlocked [table=`test`]
2024-07-25T19:13:10.4300625Z 2024-07-25T19:13:10.429482Z I i.q.c.p.WriterPool >> [table=`test~`, thread=35403]
2024-07-25T19:13:10.4324173Z 2024-07-25T19:13:10.431932Z I i.q.c.p.WriterPool << [table=`test~`, thread=35403]
2024-07-25T19:13:10.4337497Z 2024-07-25T19:13:10.433312Z I i.q.c.TableWriter closed 'test'
2024-07-25T19:13:10.4340700Z 2024-07-25T19:13:10.433314Z I i.q.c.p.WriterPool closed [table=`test~`, reason=POOL_CLOSED, by=35403]
2024-07-25T19:13:10.4344479Z 2024-07-25T19:13:10.433322Z I i.q.t.AbstractCairoTest Tearing down test TextLoaderTest#testBrokenUtf8Header[1]
2024-07-25T19:13:10.4348507Z 2024-07-25T19:13:10.433375Z I i.q.t.AbstractTest Finished test TextLoaderTest#testBrokenUtf8Header[1]
2024-07-25T19:13:10.4445660Z 2024-07-25T19:13:10.440199Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.cutlass.text.TextLoaderTest.testBrokenUtf8Header[1] duration_ms=25 : 
2024-07-25T19:13:10.4464111Z java.lang.AssertionError: expected:<{"columnCount":9,"columns":[{"index":0,"name":"№ПП","type":"INT"},{"index":1,"name":"ОбъектыКонтрольногоМероприятия","type":"VARCHAR"},{"index":2,"name":"ВидКонтрольногоМероприятия","type":"VARCHAR"},{"index":3,"name":"ТемаКонтрольногоМероприятия","type":"VARCHAR"},{"index":4,"name":"ПроверяемыйПериод","type":"VARCHAR"},{"index":5,"name":"f5","type":"VARCHAR"},{"index":6,"name":"ОкончаниеПроверки","type":"VARCHAR"},{"index":7,"name":"ВыявленныеНарушенияНедостатки","type":"VARCHAR"},{"index":8,"name":"РезультатыПроверки","type":"VARCHAR"}],"timestampIndex":-1}> but was:<{"columnCount":9,"columns":[{"index":0,"name":"№ПП","type":"INT"},{"index":1,"name":"ОбъектыКонтрольногоМероприятия","type":"VARCHAR"},{"index":2,"name":"ВидКонтрольногоМероприятия","type":"VARCHAR"},{"index":3,"name":"ТемаКонтрольногоМероприятия","type":"VARCHAR"},{"index":4,"name":"ПроверяемыйПериод","type":"VARCHAR"},{"index":5,"name":"НачалоПроверки","type":"VARCHAR"},{"index":6,"name":"ОкончаниеПроверки","type":"VARCHAR"},{"index":7,"name":"ВыявленныеНарушенияНедостатки","type":"VARCHAR"},{"index":8,"name":"РезультатыПроверки","type":"VARCHAR"}],"timestampIndex":-1}>
2024-07-25T19:13:10.4469747Z 	at org.junit.Assert.fail(Assert.java:89)
2024-07-25T19:13:10.4470201Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2024-07-25T19:13:10.4472125Z 	at org.junit.Assert.assertEquals(Assert.java:120)
2024-07-25T19:13:10.4472930Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:411)
2024-07-25T19:13:10.4473984Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:394)
2024-07-25T19:13:10.4474829Z 	at io.questdb.test.cutlass.text.TextLoaderTest.playText(TextLoaderTest.java:3674)
2024-07-25T19:13:10.4475979Z 	at io.questdb.test.cutlass.text.TextLoaderTest.lambda$testBrokenUtf8Header$7(TextLoaderTest.java:387)
2024-07-25T19:13:10.4476871Z 	at io.questdb.test.cutlass.text.TextLoaderTest.lambda$assertNoLeak$75(TextLoaderTest.java:3387)
2024-07-25T19:13:10.4478378Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:582)
2024-07-25T19:13:10.4480098Z 	at io.questdb.test.cutlass.text.TextLoaderTest.assertNoLeak(TextLoaderTest.java:3385)
2024-07-25T19:13:10.4482531Z 	at io.questdb.test.cutlass.text.TextLoaderTest.assertNoLeak(TextLoaderTest.java:3381)
2024-07-25T19:13:10.4484689Z 	at io.questdb.test.cutlass.text.TextLoaderTest.testBrokenUtf8Header(TextLoaderTest.java:303)
2024-07-25T19:13:10.4486405Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-25T19:13:10.4487973Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-07-25T19:13:10.4490572Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-25T19:13:10.4492044Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2024-07-25T19:13:10.4495472Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2024-07-25T19:13:10.4496549Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-07-25T19:13:10.4498241Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2024-07-25T19:13:10.4500534Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-07-25T19:13:10.4501925Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-07-25T19:13:10.4504057Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2024-07-25T19:13:10.4506264Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2024-07-25T19:13:10.4507851Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2024-07-25T19:13:10.4510896Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2024-07-25T19:13:10.4514034Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-07-25T19:13:10.4514809Z 	at java.lang.Thread.run(Thread.java:829)
2024-07-25T19:13:10.4518173Z 	Suppressed: java.lang.AssertionError: file descriptors, expected: [16,17,18,19], actual: [16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43] expected:<4> but was:<27>
2024-07-25T19:13:10.4519053Z 		at org.junit.Assert.fail(Assert.java:89)
2024-07-25T19:13:10.4519966Z 		at org.junit
2024-07-25T19:13:10.4522883Z 2024-07-25T19:13:10.440496Z I i.q.t.TestListener <<<< io.questdb.test.cutlass.text.TextLoaderTest.testBrokenUtf8Header[1] duration_ms=25
```

### QuestDB version:

8.1.1-SNAPSHOT

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

zfs

### Full Name:

Vlad Ilyushchenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

not sure OS/FS matter, looks like text parsing bug

**Comment by ideoma** [comment]
This may be the fix 
https://github.com/questdb/questdb/pull/4915/commits/e2b7b28dc1e1b8baf27e3c07aa938cdf8008756d
from
https://github.com/questdb/questdb/pull/4915
