### ISSUE TITLE
Flaky ServerMainBackupDatabaseTest.testServerMainBackupDatabase

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#4873]
### To reproduce

Reproducible on Linux with both ext4 and ZFS. Random seeds: 1292636664526599L, 1723798038419L

```
java.lang.AssertionError: expected min rows: 74839, actual: 65263

	at junit@4.13.2/org.junit.Assert.fail(Assert.java:89)
	at junit@4.13.2/org.junit.Assert.assertTrue(Assert.java:42)
	at io.questdb.test/io.questdb.test.ServerMainBackupDatabaseTest.lambda$testServerMainBackupDatabase$1(ServerMainBackupDatabaseTest.java:198)
	at io.questdb.test/io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:685)
	at io.questdb.test/io.questdb.test.ServerMainBackupDatabaseTest.testServerMainBackupDatabase(ServerMainBackupDatabaseTest.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at junit@4.13.2/org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at junit@4.13.2/org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at junit@4.13.2/org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at junit@4.13.2/org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at junit@4.13.2/org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at junit@4.13.2/org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at junit@4.13.2/org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at junit@4.13.2/org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### QuestDB version:

latest master

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4, zfs

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by bluestreak01** [comment]
`BACKUP DATABASE` on ZFS is flaky? It is deprecated anyway

**Comment by puzpuzpuz** [comment]
No, it looks like the test itself is flaky, on ext4 and zfs.
