### ISSUE TITLE
SAMPLE ... FROM ... TO .. causes Internal Server Exception when used with WHERE

### ISSUE THREAD

**Issue by juocal** [questdb/questdb#4964]
### To reproduce

When i execute the following query, I get an "Internal Server Exception":

```
WITH inner_timeseries as (
  SELECT
    timestamp,
    AVG(value) as value
  FROM
    timeseries_entry
  WHERE
    timeseriesId IN (2143)
    AND timestamp >= '2024-09-17T22:00:00.000000Z'
    AND timestamp <= '2024-09-18T22:00:00.000000Z' SAMPLE BY 15m FILL(PREV)
  ORDER BY
    timestamp
)
SELECT
  timestamp,
  AVG(value) as value
FROM
  inner_timeseries
WHERE
  timestamp >= '2024-09-17T22:00:00.000000Z'
  AND timestamp <= '2024-09-18T22:00:00.000000Z' SAMPLE BY 15m
FROM
  '2024-09-17T22:00:00.000000Z' TO '2024-09-18T22:00:00.000000Z' FILL(0)
ORDER BY
  timestamp;
```

The exception stacktrace looks like this:
```
2024-09-18T00:56:45.157214Z C i.q.c.h.p.JsonQueryProcessorState [146031300306] internal error [ex=
java.lang.NullPointerException: Cannot read field "token" because "this.timestamp" is null
        at io.questdb.griffin.SqlOptimiser$RewriteSampleByFromToVisitor.visit(SqlOptimiser.java:6243)
        at io.questdb.griffin.PostOrderTreeTraversalAlgo.traverse(PostOrderTreeTraversalAlgo.java:86)
        at io.questdb.griffin.SqlOptimiser.rewriteSampleByFromTo(SqlOptimiser.java:4846)
        at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:6069)
        at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel0(SqlCompilerImpl.java:1550)
        at io.questdb.griffin.SqlCompilerImpl.compileExecutionModel(SqlCompilerImpl.java:1539)
        at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:1663)
        at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1615)
        at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:236)
        at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:128)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileAndExecuteQuery(JsonQueryProcessor.java:480)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:192)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:273)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:915)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:256)
        at io.questdb.cutlass.http.HttpServer.handleClientOperation(HttpServer.java:320)
        at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:114)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
        at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:118)
        at io.questdb.mp.Worker.run(Worker.java:151)
```

The error does not happen, when I remove the WHERE-Clause in the outer SELECT like this:
```
WITH inner_timeseries as (
  SELECT
    timestamp,
    AVG(value) as value
  FROM
    timeseries_entry
  WHERE
    timeseriesId IN (2143)
    AND timestamp >= '2024-09-17T22:00:00.000000Z'
    AND timestamp <= '2024-09-18T22:00:00.000000Z' SAMPLE BY 15m FILL(PREV)
  ORDER BY
    timestamp
)
SELECT
  timestamp,
  AVG(value) as value
FROM
  inner_timeseries
SAMPLE BY 15m
FROM
  '2024-09-17T22:00:00.000000Z' TO '2024-09-18T22:00:00.000000Z' FILL(0)
ORDER BY
  timestamp;
```

### QuestDB version:

8.1.1

### OS, in case of Docker specify Docker and the Host OS:

Windows Docker

### File System, in case of Docker specify Host File System:

fat32

### Full Name:

Julien Ostermann

### Affiliation:

Fraunhofer

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by juocal** [comment]
After additional investigation, I realized, that sometimes, after a couple of same queries, the values will be all 0 (as requested with the outer "FILL(0.0)". Although data is present (and should be returned) from the database for this timestamp!

When I alter the name "inner_timeseries" of the WITH-Operator to a different name with each query/request, the data is always correct!

It seems, that something is cached and "reused" for the outer sampling query. Which eventually leads to a all values being wrong.

**Comment by juocal** [comment]
Any update on this issue?
