### ISSUE TITLE
Questdb container corrupted after fatal crash repeatedly while inserting same data

### ISSUE THREAD

**Issue by theTruthQuest** [questdb/questdb#5009]
### To reproduce

dont know how to replicate the error on anybody else's system..

### QuestDB version:

8.1.1

### OS, in case of Docker specify Docker and the Host OS:

Docker and Linux Mint 22 (Ubuntu 22)

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Gaurav Kathuria

### Affiliation:

Self

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

# #[crash+0.log](https://github.com/user-attachments/files/17232317/crash%2B0.log)
[hs_err_pid+1.log](https://github.com/user-attachments/files/17232319/hs_err_pid%2B1.log)
@
The fatal crash happened when I was running  a python code using a loop to insert ohlcv data of 5000 stocks in to questdb that I was using through docker. the data was being inserted in batches of 20 stocks. first data of 20 stocks were fetched in 5 second resolution so about 5 million row per batch... First 5 batches were successful. during insertion of 6th batch... crash happened.. and the questdb container never started again... always exits with 127 error.. I removed the questdb container and image and reinstalled... the crash happened again on the 6th batch...
For temporary purposes, I used clickhouse to check if there is something wrong with data.. but it worked in clickhouse... though I want to use questdb because clickhouse doesn't have realtime deduplication and so many other things, that I love about questdb.. Please help

**Comment by ideoma** [comment]
Hey, thanks for the report

Good news, we have the fix, it's already merged:
https://github.com/questdb/questdb/pull/4966

but not yet released. It would be good if you could try the nightly docker image

**Comment by ideoma** [comment]
Hey @theTruthQuest can you please have another look with the nightly docker build, it would be very useful to know if you still can reproduce the problem.

**Comment by theTruthQuest** [comment]
> Hey @theTruthQuest can you please have another look with the nightly docker build, it would be very useful to know if you still can reproduce the problem.

Hi, I did try with the nightly image. Same error exactly at the same time (the 6th batch)....

Traceback (most recent call last):
  File "/home/........................................lLoop5s.py", line 111, in <module>
    sender.dataframe(combined_df, table_name='historical_5s', at='timestamp')
  File "src/questdb/ingress.pyx", line 2403, in questdb.ingress.Sender.dataframe
  File "src/questdb/dataframe.pxi", line 2396, in questdb.ingress._dataframe
  File "src/questdb/dataframe.pxi", line 2389, in questdb.ingress._dataframe
  File "src/questdb/dataframe.pxi", line 2365, in questdb.ingress._dataframe
  File "src/questdb/dataframe.pxi", line 2244, in questdb.ingress._dataframe_handle_auto_flush
questdb.ingress.IngressError: Could not flush buffer: http://localhost:9000/write?precision=n: Connection Failed: Connect error: Connection refused (os error 111) - See https://py-questdb-client.readthedocs.io/en/v2.0.3/troubleshooting.html#inspecting-and-debugging-errors#flush-failed


2024-10-03T17:26:58.959042Z I i.q.c.TableWriter processing WAL [path=/historical_5s~7/wal1/131, roLo=150000, roHi=225000, seqTxn=400, tsMin=2024-07-03T05:18:35.000000Z, tsMax=2024-07-29T03:53:45.000000Z, commitToTs=]
2024-10-03T17:26:58.962910Z I i.q.c.TableWriter processing WAL [path=/historical_5s~7/wal1/132, roLo=0, roHi=75000, seqTxn=401, tsMin=2024-07-29T03:53:50.000000Z, tsMax=2024-08-21T08:23:35.000000Z, commitToTs=]
2024-10-03T17:26:58.966805Z I i.q.c.TableWriter processing WAL [path=/historical_5s~7/wal1/132, roLo=75000, roHi=150000, seqTxn=402, tsMin=2024-08-21T08:23:40.000000Z, tsMax=2024-09-13T06:32:00.000000Z, commitToTs=294247-01-10T04:00:54.775807Z]
2024-10-03T17:26:58.966977Z I i.q.c.TableWriter sorting WAL [table=TableToken{tableName=historical_5s, dirName=historical_5s~7, tableId=7, isWal=true, isSystem=false}, ordered=true, lagRowCount=825000, walRowLo=75000, walRowHi=150000]
2024-10-03T17:26:59.022228Z I i.q.c.TableWriter WAL dedup sorted commit index [table=TableToken{tableName=historical_5s, dirName=historical_5s~7, tableId=7, isWal=true, isSystem=false}, totalRows=900000, lagRows=825000]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f417ef3ad62, pid=1, tid=55
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.11.9.1 (17.0.11+9) (build 17.0.11+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.11.9.1 (17.0.11+9-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# J 1857 c1 sun.misc.Unsafe.getLong(J)J jdk.unsupported@17.0.11 (8 bytes) @ 0x00007f417ef3ad62 [0x00007f417ef3acc0+0x00000000000000a2]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h" (or dumping to /var/lib/questdb/core.1)
#
# An error report file with more information is saved as:
# /var/lib/questdb/db/hs_err_pid+1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/
#

[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f4197b5450f]

**Comment by ideoma** [comment]
@theTruthQuest 
Thanks for trying.

Could you share your python code?
