### ISSUE TITLE
Error while running JMH benchmark 

### ISSUE THREAD

**Issue by mick2004** [questdb/questdb#503]
**Describe the bug**
Below error is thrown while running JMH benchmark.

Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
	at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:98)
	at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:122)
	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:263)
	at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
	at org.openjdk.jmh.Main.main(Main.java:71)

**To Reproduce**

From cli:

1. Checkout and build the code via mvn clean install
2. Run benchmark via below command:

     java -jar <<Quest DB codebase Home folder>>/benchmarks/target/benchmarks.jar Log4jBenchmark

3.See error

From Intellij:

1.Checkout code in intellij
2.Build code
3.Right click Log4jBenchmark and run
4.See error

**Expected behavior**
JMH benchmark should run

**Environment (please complete the following information):**
 - OS: MacOS
 - IDE:Intellij
<img width="1440" alt="Screenshot 2020-07-14 at 1 29 16 AM" src="https://user-images.githubusercontent.com/2042132/87335365-c3ca9a80-c572-11ea-89ca-6ca334c81ffd.png">
<img width="1440" alt="Screenshot 2020-07-14 at 1 30 17 AM" src="https://user-images.githubusercontent.com/2042132/87335380-c88f4e80-c572-11ea-8ddc-3abe65283bf1.png">

**Additional context**

**Comment by bluestreak01** [comment]
Yeah, we don’t have this solved. It broke when we moved to java11. I spent two hours fiddling with versions and settings to no avail and gave up.
