### ISSUE TITLE
Support for AWS Graviton instances

### ISSUE THREAD

**Issue by matyasberry** [questdb/questdb#5146]
### Is your feature request related to a problem?

Running questDB 7.4 embedded on Graviton3, on top of an ALPINE docker image, results in the following stack trace:
```
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libquestdb13659913623987804481.so: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /tmp/libquestdb13659913623987804481.so)  
    at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)                                                                                                                                             
    at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)                                                                                                                
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)                                                                                                                           
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) 
```

JIT for queries is disabled, because of https://github.com/questdb/questdb/issues/4338

### Describe the solution you'd like.

Allow QuestDB running on AWS Graviton instances mostly for the price/performance benefit

### Full Name:

Matyas

### Affiliation:

Exberry

**Comment by jerrinot** [comment]
hello @matyasberry,
QuestDB does not support Alpine-based docker containers. Can you please try to:
1. Use the latest QuestDB version instead of 7.x
2. Use a base image with glibc instead of musl? E.g. Ubuntu or Debian base images are popular among our users.

**Comment by matyasberry** [comment]
@jerrinot Are you suggesting, that Graviton3 is OK, as long as the base image would be Debian/Ubuntu?

**Comment by jerrinot** [comment]
I run QuestDB on an ARM-based Linux computer and it works fine. Just don't expect amazing query performance: Since vectorization and JIT are supported only on amd64.

I use the `Any (no JVM)` package from https://questdb.io/download/ It requires you to install ARM port of JVM - it should be packaged for your Linux distribution. So install it while building a container image.

**Comment by matyasberry** [comment]
Yes, sorted, thanks.
