### ISSUE TITLE
java.lang.NullPointerException  Cannot read field "writer" because "e" is null

### ISSUE THREAD

**Issue by simplyrahul1** [questdb/questdb#5151]
### To reproduce

I'm getting this error when multiple servers are posting ILP data  via UDP port  after 2 hours or so.

   at io.questdb@8.1.1/io.questdb.cutlass.line.udp.LineUdpParserImpl.switchTable(LineUdpParserImpl.java:504)
    at io.questdb@8.1.1/io.questdb.cutlass.line.udp.LineUdpParserImpl.onEvent(LineUdpParserImpl.java:155)
    at io.questdb@8.1.1/io.questdb.cutlass.line.udp.LineUdpLexer.fireEvent(LineUdpLexer.java:133)
    at io.questdb@8.1.1/io.questdb.cutlass.line.udp.LineUdpLexer.fireEventTransition(LineUdpLexer.java:141)
    at io.questdb@8.1.1/io.questdb.cutlass.line.udp.LineUdpLexer.onSpace(LineUdpLexer.java:203)
    at io.questdb@8.1.1/io.questdb.cutlass.line.udp.LineUdpLexer.parsePartial(LineUdpLexer.java:338)
    at io.questdb@8.1.1/io.questdb.cutlass.line.udp.LineUdpLexer.parse(LineUdpLexer.java:97)
    at io.questdb@8.1.1/io.questdb.cutlass.line.udp.LinuxMMLineUdpReceiver.runSerially(LinuxMMLineUdpReceiver.java:63)
    at io.questdb@8.1.1/io.questdb.cutlass.line.udp.AbstractLineProtoUdpReceiver.lambda$start$0(AbstractLineProtoUdpReceiver.java:127)
    at java.base/java.lang.Thread.run(Thread.java:840)

### QuestDB version:

questdb-8.1.1-rt-linux-x86-64.tar.gz

### OS, in case of Docker specify Docker and the Host OS:

Rocky 09 Linux

### File System, in case of Docker specify Host File System:

XFS

### Full Name:

Rahul Sinha

### Affiliation:

Developer

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by simplyrahul1** [comment]
Hi @nwoolmer ,
Thank you for your response. 
So as i understood, ILP/UDP is available but not supported anymore ? 
I'm trying to use this as current application are sending traffic over UDP to InfluxDB. and changing the implementation on all the application would not be feasible. Also since the applications are sending stats every x seconds, UDP makes sense for us in production.
Ideally, if incompatible payload is received, I would have preferred Quest UDP interface to simply drop it or pass it to DLQ file.
in the current scenario, it stops processing any more traffic.

Thanks for your time.

Regards,
Rahul
