### ISSUE TITLE
Flaky DedupTest.dedup/varchar_dedup.test

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#5165]
### To reproduce

linux-other:
```
306Z 2024-11-15T03:54:59.289768Z I i.q.t.TestListener >>>> io.questdb.test.sqllogictest.dedup.DedupTest.test[dedup/varchar_dedup.test]
2024-11-15T03:54:59.2918669Z 2024-11-15T03:54:59.290382Z I i.q.t.AbstractTest Starting test DedupTest#test[dedup/varchar_dedup.test]
2024-11-15T03:54:59.2919006Z 2024-11-15T03:54:59.291252Z I i.q.c.p.m.PGConnectionContextModern disconnected on read [code=-2]
2024-11-15T03:54:59.2919313Z 2024-11-15T03:54:59.291288Z I pg-server disconnected [ip=127.0.0.1, fd=176093663190, src=queue]
2024-11-15T03:54:59.2919610Z 2024-11-15T03:54:59.291419Z I pg-server connected [ip=127.0.0.1, fd=176093663311]
2024-11-15T03:54:59.3149191Z 2024-11-15T03:54:59.314607Z I i.q.g.e.QueryProgress exe [id=27, sql=`create table x (s varchar, x int, ts timestamp)
2024-11-15T03:54:59.3149953Z timestamp(ts) partition by DAY WAL DEDUP UPSERT KEYS(ts, s);`, principal=admin, cache=false, jit=false]
2024-11-15T03:54:59.3165461Z 2024-11-15T03:54:59.316329Z I i.q.c.CairoEngine locked [table=`x~1`, thread=239]
2024-11-15T03:54:59.3378799Z 2024-11-15T03:54:59.333161Z I i.q.c.CairoEngine unlocked [table=`TableToken{tableName=x, dirName=x~1, tableId=1, isWal=true, isSystem=false}`]
2024-11-15T03:54:59.3379829Z 2024-11-15T03:54:59.334561Z I i.q.g.e.QueryProgress fin [id=27, sql=`create table x (s varchar, x int, ts timestamp)
2024-11-15T03:54:59.3380321Z timestamp(ts) partition by DAY WAL DEDUP UPSERT KEYS(ts, s);`, principal=admin, cache=false, jit=false, time=20122873]
2024-11-15T03:54:59.3380735Z 2024-11-15T03:54:59.334613Z I i.q.c.p.m.PGConnectionContextModern create prepared statement [name=s97]
2024-11-15T03:54:59.3381134Z 2024-11-15T03:54:59.335625Z I i.q.g.e.QueryProgress exe [id=-1, sql=`insert into x(s, x, ts)
2024-11-15T03:54:59.3381480Z values
2024-11-15T03:54:59.3382025Z ('1234¢6789©', 01, '2020-01-01T00:00:00.000Z'),
2024-11-15T03:54:59.3382411Z (NULL,         -1, '2020-01-01T00:00:00.000Z'),
2024-11-15T03:54:59.3382841Z ('؆c',         10, '2020-01-03T00:00:00.000Z'),
2024-11-15T03:54:59.3383271Z ('؆',          02, '2020-01-01T00:00:00.000Z'),
2024-11-15T03:54:59.3383768Z ('1234¢6789©', 03, '2020-01-01T00:00:00.000Z'),
2024-11-15T03:54:59.3384311Z ('؆c',         20, '2020-01-03T00:00:00.000Z');`, principal=admin, cache=false, jit=false]
2024-11-15T03:54:59.3459213Z 2024-11-15T03:54:59.345486Z I i.q.g.e.QueryProgress fin [id=-1, sql=`insert into x(s, x, ts)
2024-11-15T03:54:59.3459875Z values
2024-11-15T03:54:59.3460372Z ('1234¢6789©', 01, '2020-01-01T00:00:00.000Z'),
2024-11-15T03:54:59.3460767Z (NULL,         -1, '2020-01-01T00:00:00.000Z'),
2024-11-15T03:54:59.3461195Z ('؆c',         10, '2020-01-03T00:00:00.000Z'),
2024-11-15T03:54:59.3461893Z ('؆',          02, '2020-01-01T00:00:00.000Z'),
2024-11-15T03:54:59.3462312Z ('1234¢6789©', 03, '2020-01-01T00:00:00.000Z'),
2024-11-15T03:54:59.3462805Z ('؆c',         20, '2020-01-03T00:00:00.000Z');`, principal=admin, cache=false, jit=false, time=10505386]
2024-11-15T03:54:59.3494289Z 2024-11-15T03:54:59.346863Z I i.q.c.p.m.PGConnectionContextModern create prepared statement [name=s98]
2024-11-15T03:54:59.3495030Z 2024-11-15T03:54:59.347779Z I i.q.c.w.WalWriter open 'x~1'
2024-11-15T03:54:59.3495459Z 2024-11-15T03:54:59.348348Z I i.q.c.w.WalWriter opened WAL segment [path=/x~1/wal1/0/_event.i']
2024-11-15T03:54:59.3520309Z 2024-11-15T03:54:59.351687Z I i.q.c.w.WalWriter committed data block [wal=/x~1/wal1/0, segmentTxn=0, seqTxn=1, rowLo=0, roHi=6, minTs=2020-01-01T00:00:00.000000Z, maxTs=2020-01-03T00:00:00.000000Z]
2024-11-15T03:54:59.3568911Z 2024-11-15T03:54:59.352665Z I i.q.c.p.WriterPool open [table=`x~1`, thread=244]
2024-11-15T03:54:59.3569741Z 2024-11-15T03:54:59.352748Z I i.q.c.TableWriter open 'x'
2024-11-15T03:54:59.3570448Z 2024-11-15T03:54:59.353767Z I i.q.c.p.WriterPool >> [table=`x~1`, thread=244]
2024-11-15T03:54:59.3571171Z 2024-11-15T03:54:59.354239Z I i.q.c.TableWriter processing WAL [path=/x~1/wal1/0, roLo=0, roHi=6, seqTxn=1, tsMin=2020-01-01T00:00:00.000000Z, tsMax=2020-01-03T00:00:00.000000Z, commitToTs=294247-01-10T04:00:54.775807Z]
2024-11-15T03:54:59.3572287Z 2024-11-15T03:54:59.354417Z I i.q.c.TableWriter switched partition [path=/x~1/2020-01-01]
2024-11-15T03:54:59.3573315Z 2024-11-15T03:54:59.354531Z I i.q.c.TableWriter sorting WAL [table=TableToken{tableName=x, dirName=x~1, tableId=1, isWal=true, isSystem=false}, ordered=false, lagRowCount=0, walRowLo=0, walRowHi=6]
2024-11-15T03:54:59.3574452Z 2024-11-15T03:54:59.354567Z I i.q.c.TableWriter WAL dedup sorted commit index [table=TableToken{tableName=x, dirName=x~1, tableId=1, isWal=true, isSystem=false}, totalRows=6, lagRows=0]
2024-11-15T03:54:59.3575589Z 2024-11-15T03:54:59.354835Z I i.q.c.TableWriter o3 partition task [table=x, partitionTs=2020-01-01T00:00:00.000000Z, partitionIndex=-1, last=false, append=false, ro=false, srcOooLo=0, srcOooHi=2, srcOooMax=4, o3RowCount=4, o3LagRowCount=0, srcDataMax=0, o3Ts=2020-01-01T00:00:00.000000Z, newSize=3, maxTs=, pCount=1, flattenTs=true, memUsed=119.855 MiB, rssMemUsed=19.6 MiB]
2024-11-15T03:54:59.3577670Z 2024-11-15T03:54:59.354879Z I i.q.c.TableWriter o3 partition task [table=x, partitionTs=2020-01-03T00:00:00.000000Z, partitionIndex=-1, last=false, append=false, ro=false, srcOooLo=3, srcOooHi=3, srcOooMax=4, o3RowCount=4, o3LagRowCount=0, srcDataMax=0, o3Ts=2020-01-03T00:00:00.000000Z, newSize=1, maxTs=, pCount=2, flattenTs=false, memUsed=119.886 MiB, rssMemUsed=19.631 MiB]
2024-11-15T03:54:59.3578754Z 2024-11-15T03:54:59.355864Z I i.q.c.TableWriter switched partition [path=/x~1/2020-01-03]
2024-11-15T03:54:59.3579146Z 2024-11-15T03:54:59.356176Z I i.q.c.w.ApplyWal2TableJob job finished [table=x~1, seqTxn=1, transactions=1, rows=6, time=1ms, rate=3003rows/s, physicalWrittenRowsMultiplier=0.67]
2024-11-15T03:54:59.3579511Z 2024-11-15T03:54:59.356223Z I i.q.c.p.WriterPool << [table=`x~1`, thread=244]
2024-11-15T03:54:59.3606172Z 2024-11-15T03:54:59.360410Z I i.q.c.p.m.PGConnectionContextModern create prepared statement [name=s99]
2024-11-15T03:54:59.3700587Z Error running test file '/home/vsts/work/1/s/core/target/test-classes/sqllogictest/test/dedup/varchar_dedup.test': query failed: db error: ERROR: string is outside of file boundary [offset=0, len=875770417, dataLim=12]
2024-11-15T03:54:59.3701450Z [SQL] select s, x, ts from x order by ts, s;
2024-11-15T03:54:59.3702037Z at /home/vsts/work/1/s/core/target/test-classes/sqllogictest/test/dedup/varchar_dedup.test:27
2024-11-15T03:54:59.3702763Z 2024-11-15T03:54:59.363329Z I i.q.g.e.QueryProgress exe [id=29, sql=`select wait_wal_table('x');`, principal=admin, cache=false, jit=false]
2024-11-15T03:54:59.3703686Z 2024-11-15T03:54:59.363377Z I i.q.g.e.QueryProgress fin [id=29, sql=`select wait_wal_table('x');`, principal=admin, cache=false, jit=false, time=53499]
2024-11-15T03:54:59.3704234Z 2024-11-15T03:54:59.364288Z I i.q.c.p.m.PGConnectionContextModern create prepared statement [name=s100]
2024-11-15T03:54:59.3704611Z 2024-11-15T03:54:59.364636Z I i.q.g.e.QueryProgress exe [id=30, sql=`select s, x, ts from x order by ts, s;`, principal=admin, cache=true, jit=false]
2024-11-15T03:54:59.3705212Z 2024-11-15T03:54:59.365050Z I i.q.c.TableReader open partition [path=/x~1/2020-01-01, rowCount=3, partitionIndex=0, partitionCount=2]
2024-11-15T03:54:59.3705671Z 2024-11-15T03:54:59.367092Z E i.q.g.e.QueryProgress err [id=30, sql=`select s, x, ts from x order by ts, s;`, principal=admin, cache=true, jit=false, time=2448096, msg=string is outside of file boundary [offset=0, len=875770417, dataLim=12], errno=0, pos=0]
2024-11-15T03:54:59.3706121Z 2024-11-15T03:54:59.368929Z I i.q.t.AbstractTest Finished test DedupTest#test[dedup/varchar_dedup.test]
2024-11-15T03:54:59.3706466Z 2024-11-15T03:54:59.369200Z I i.q.c.p.ReaderPool closed 'x~1' [at=0:0, reason=POOL_CLOSED]
2024-11-15T03:54:59.3706770Z 2024-11-15T03:54:59.369531Z I i.q.c.TableWriter closed 'x'
2024-11-15T03:54:59.3707078Z 2024-11-15T03:54:59.369545Z I i.q.c.p.WriterPool closed [table=`x~1`, reason=POOL_CLOSED, by=247]
2024-11-15T03:54:59.3707591Z 2024-11-15T03:54:59.369647Z I i.q.c.w.s.TableSequencerAPI releasing idle table sequencer [tableDir=x~1]
2024-11-15T03:54:59.3707933Z 2024-11-15T03:54:59.369658Z I i.q.c.p.SequencerMetadataPool closed 'x~1' [at=0:0, reason=POOL_CLOSED]
2024-11-15T03:54:59.3708242Z 2024-11-15T03:54:59.369894Z I i.q.c.w.WalWriter closed 'x'
2024-11-15T03:54:59.3708596Z 2024-11-15T03:54:59.369897Z I i.q.c.p.WalWriterPool closed 'x~1' [at=0:0, reason=POOL_CLOSED]
2024-11-15T03:54:59.3816671Z 2024-11-15T03:54:59.381276Z I i.q.c.p.m.PGConnectionContextModern disconnected on read [code=-2]
2024-11-15T03:54:59.3817306Z 2024-11-15T03:54:59.381301Z I pg-server disconnected [ip=127.0.0.1, fd=176093663311, src=queue]
2024-11-15T03:54:59.3912086Z 2024-11-15T03:54:59.390734Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.sqllogictest.dedup.DedupTest.test[dedup/varchar_dedup.test] duration_ms=101 : 
2024-11-15T03:54:59.3913059Z java.lang.RuntimeException: error while run: Error running test file '/home/vsts/work/1/s/core/target/test-classes/sqllogictest/test/dedup/varchar_dedup.test': query failed: db error: ERROR: string is outside of file boundary [offset=0, len=875770417, dataLim=12]
2024-11-15T03:54:59.3913755Z [SQL] select s, x, ts from x order by ts, s;
2024-11-15T03:54:59.3914384Z at /home/vsts/work/1/s/core/target/test-classes/sqllogictest/test/dedup/varchar_dedup.test:27
2024-11-15T03:54:59.3914656Z 	at io.questdb.test.Sqllogictest.run(Native Method)
2024-11-15T03:54:59.3914946Z 	at io.questdb.test.sqllogictest.AbstractSqllogicTestRunner.test(AbstractSqllogicTestRunner.java:176)
2024-11-15T03:54:59.3915231Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-11-15T03:54:59.3915504Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-11-15T03:54:59.3915811Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-15T03:54:59.3916103Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2024-11-15T03:54:59.3916383Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2024-11-15T03:54:59.3916679Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-11-15T03:54:59.3916970Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2024-11-15T03:54:59.3917266Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-11-15T03:54:59.3917569Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-11-15T03:54:59.3917858Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2024-11-15T03:54:59.3918158Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2024-11-15T03:54:59.3918479Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2024-11-15T03:54:59.3918918Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-11-15T03:54:59.3919178Z 	at java.lang.Thread.run(Thread.java:829)
2024-11-15T03:54:59.3919459Z 2024-11-15T03:54:59.390839Z I i.q.t.TestListener <<<< io.questdb.test.sqllogictest.dedup.DedupTest.test[dedup/varchar_dedup.test] duration_ms=101
```

### QuestDB version:

latest master

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by ideoma** [comment]
I think I fixed that on one of the PRs
