### ISSUE TITLE
NPE on AtomicBooleanCircuitBreaker.cancelledFlag

### ISSUE THREAD

**Issue by Dapeng960208** [questdb/questdb#5215]
### To reproduce

When I was using version 8.2, the following error message would appear during the query. I have confirmed that there is no problem with the query statement, but the problem is accidental, and the error message is as follows:

`Cannot invoke java.util.concurrent.atomic.AtomicBoolean.get() because "this.cancelledFlag" is null`

I have never experienced this problem with version 7.4

### QuestDB version:

8.2

### OS, in case of Docker specify Docker and the Host OS:

centos 7.9

### File System, in case of Docker specify Host File System:

linux centos

### Full Name:

jian peng

### Affiliation:

1332606303@qq.com

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by Dapeng960208** [comment]
> 您好，您还有其他详细信息吗？您使用哪种数据库客户端？您是快速发出相同的查询，还是发出许多不同的查询？是否有许多并发客户端，或者它发生在一个安静的系统？另请分享您正在运行的查询。


def get_jobs_count_by_day(quest_db_engine, host_name: str | None = None, queues: list[str] | None = None,
                          host_names: list | None = None,
                          username: str | None = None, start_time: datetime | None = None,
                          end_time: datetime | None = None):
    filter_conditions = ["is_deleted=false", "status != 'UNKWN'"]
    params = {}

    if host_name:
        filter_conditions.append("execute_host LIKE :host_name")
        params["host_name"] = f"%{host_name}%"
    if queues:
        filter_conditions.append("queue IN :queues")
        params["queues"] = tuple(queues)
    if host_names:
        filter_conditions.append("execute_host IN :host_names")
        params['host_names'] = tuple(host_names)
    if username:
        filter_conditions.append("username LIKE :username")
        params["username"] = f"%{username}%"
    if start_time and end_time:
        filter_conditions.append('submit_time BETWEEN :start_time AND :end_time')
        params['start_time'] = str(start_time)
        params['end_time'] = str(end_time)
    filter_command = " WHERE " + " AND ".join(filter_conditions)
    query_command = f"""
    SELECT date, count() AS job_count
        FROM (SELECT to_str(submit_time, 'yyyy-MM-dd') AS date FROM jobs {filter_command})
        GROUP BY date;
    """
    result = []
    with quest_db_engine.connect() as conn:
        jobs_count = conn.execute(text(query_command), params).fetchall()
        if len(jobs_count) == 0:
            return result
        for submit_time, jobs in jobs_count:
            result.append([submit_time, jobs])
    return result

**Comment by Dapeng960208** [comment]
`

def get_jobs_count_by_day(quest_db_engine, host_name: str | None = None, queues: list[str] | None = None,
                          host_names: list | None = None,
                          username: str | None = None, start_time: datetime | None = None,
                          end_time: datetime | None = None):
    filter_conditions = ["is_deleted=false", "status != 'UNKWN'"]
    params = {}

    if host_name:
        filter_conditions.append("execute_host LIKE :host_name")
        params["host_name"] = f"%{host_name}%"
    if queues:
        filter_conditions.append("queue IN :queues")
        params["queues"] = tuple(queues)
    if host_names:
        filter_conditions.append("execute_host IN :host_names")
        params['host_names'] = tuple(host_names)
    if username:
        filter_conditions.append("username LIKE :username")
        params["username"] = f"%{username}%"
    if start_time and end_time:
        filter_conditions.append('submit_time BETWEEN :start_time AND :end_time')
        params['start_time'] = str(start_time)
        params['end_time'] = str(end_time)
    filter_command = " WHERE " + " AND ".join(filter_conditions)
    query_command = f"""
    SELECT date, count() AS job_count
        FROM (SELECT to_str(submit_time, 'yyyy-MM-dd') AS date FROM jobs {filter_command})
        GROUP BY date;
    """
    result = []
    with quest_db_engine.connect() as conn:
        jobs_count = conn.execute(text(query_command), params).fetchall()
        if len(jobs_count) == 0:
            return result
        for submit_time, jobs in jobs_count:
            result.append([submit_time, jobs])
    return result
`

**Comment by Dapeng960208** [comment]
> 您好，您还有其他详细信息吗？您使用哪种数据库客户端？您是快速发出相同的查询，还是发出许多不同的查询？是否有许多并发客户端，或者它发生在一个安静的系统？另请分享您正在运行的查询。


def get_jobs_count_by_day(quest_db_engine, host_name: str | None = None, queues: list[str] | None = None,
                          host_names: list | None = None,
                          username: str | None = None, start_time: datetime | None = None,
                          end_time: datetime | None = None):
    filter_conditions = ["is_deleted=false", "status != 'UNKWN'"]
    params = {}

    if host_name:
        filter_conditions.append("execute_host LIKE :host_name")
        params["host_name"] = f"%{host_name}%"
    if queues:
        filter_conditions.append("queue IN :queues")
        params["queues"] = tuple(queues)
    if host_names:
        filter_conditions.append("execute_host IN :host_names")
        params['host_names'] = tuple(host_names)
    if username:
        filter_conditions.append("username LIKE :username")
        params["username"] = f"%{username}%"
    if start_time and end_time:
        filter_conditions.append('submit_time BETWEEN :start_time AND :end_time')
        params['start_time'] = str(start_time)
        params['end_time'] = str(end_time)
    filter_command = " WHERE " + " AND ".join(filter_conditions)
    query_command = f"""
    SELECT date, count() AS job_count
        FROM (SELECT to_str(submit_time, 'yyyy-MM-dd') AS date FROM jobs {filter_command})
        GROUP BY date;
    """
    result = []
    with quest_db_engine.connect() as conn:
        jobs_count = conn.execute(text(query_command), params).fetchall()
        if len(jobs_count) == 0:
            return result
        for submit_time, jobs in jobs_count:
            result.append([submit_time, jobs])
    return result

**Comment by Dapeng960208** [comment]
File "/srv/prod/lsf/lsf-api/./crud/jobCrud.py", line 656, in get_jobs_count_by_day
    jobs_count = conn.execute(text(query_command), params).fetchall()
  File "/root/python3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/root/python3/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/python3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/python3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/root/python3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/root/python3/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/root/python3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/root/python3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/root/python3/lib/python3.10/site-packages/questdb_connect/__init__.py", line 65, in execute
    return super().execute(remove_public_schema(query), vars)
psycopg2.DatabaseError: Cannot invoke "java.util.concurrent.atomic.AtomicBoolean.get()" because "this.cancelledFlag" is null
LINE 1:
        ^

**Comment by Dapeng960208** [comment]
Using the latest 8.2.0 docker version. The same code has never shown this error in version 7.4, and this error is accidental.

**Comment by Dapeng960208** [comment]
This is a complete system with high concurrency. Tens of thousands of pieces of data are inserted every minute, but they only appear at query time

**Comment by mtopolnik** [comment]
Can you provide us with the logs where this error shows up?

**Comment by Dapeng960208** [comment]
2024-12-02T05:16:16.486260Z E i.q.c.s.a.PageFrameReduceJob reduce error [error=
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicBoolean.get()" because "this.cancelledFlag" is null
        at io.questdb.cairo.sql.AtomicBooleanCircuitBreaker.isCancelled(AtomicBooleanCircuitBreaker.java:148)
        at io.questdb.cairo.sql.AtomicBooleanCircuitBreaker.getState(AtomicBooleanCircuitBreaker.java:79)
        at io.questdb.cairo.sql.AtomicBooleanCircuitBreaker.getState(AtomicBooleanCircuitBreaker.java:84)
        at io.questdb.cairo.sql.SqlExecutionCircuitBreakerWrapper.getState(SqlExecutionCircuitBreakerWrapper.java:92)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.reduce(PageFrameReduceJob.java:240)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:194)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.run(PageFrameReduceJob.java:148)
        at io.questdb.mp.Worker.run(Worker.java:152)
, id=31092, taskType=1, frameIndex=212, frameCount=232]
2024-12-02T05:16:16.487974Z E i.q.c.s.a.PageFrameReduceJob reduce error [error=
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicBoolean.get()" because "this.cancelledFlag" is null
        at io.questdb.cairo.sql.AtomicBooleanCircuitBreaker.isCancelled(AtomicBooleanCircuitBreaker.java:148)
        at io.questdb.cairo.sql.AtomicBooleanCircuitBreaker.getState(AtomicBooleanCircuitBreaker.java:79)
        at io.questdb.cairo.sql.AtomicBooleanCircuitBreaker.getState(AtomicBooleanCircuitBreaker.java:84)
        at io.questdb.cairo.sql.SqlExecutionCircuitBreakerWrapper.getState(SqlExecutionCircuitBreakerWrapper.java:92)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.reduce(PageFrameReduceJob.java:240)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:194)
        at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:104)
        at io.questdb.cairo.sql.async.PageFrameSequence.stealWork(PageFrameSequence.java:581)
        at io.questdb.cairo.sql.async.PageFrameSequence.dispatch(PageFrameSequence.java:526)
        at io.questdb.cairo.sql.async.PageFrameSequence.next(PageFrameSequence.java:348)
        at io.questdb.griffin.engine.table.AsyncGroupByRecordCursor.buildMap(AsyncGroupByRecordCursor.java:193)
        at io.questdb.griffin.engine.table.AsyncGroupByRecordCursor.hasNext(AsyncGroupByRecordCursor.java:141)
        at io.questdb.griffin.engine.QueryProgress$RegisteredRecordCursor.hasNext(QueryProgress.java:319)
        at io.questdb.cutlass.pgwire.modern.PGPipelineEntry.outCursor(PGPipelineEntry.java:1883)
        at io.questdb.cutlass.pgwire.modern.PGPipelineEntry.outCursor(PGPipelineEntry.java:1854)
        at io.questdb.cutlass.pgwire.modern.PGPipelineEntry.msgSync(PGPipelineEntry.java:680)
        at io.questdb.cutlass.pgwire.modern.PGConnectionContextModern.syncPipeline(PGConnectionContextModern.java:1312)
        at io.questdb.cutlass.pgwire.modern.PGConnectionContextModern.msgSync0(PGConnectionContextModern.java:1142)
        at io.questdb.cutlass.pgwire.modern.PGConnectionContextModern.msgSync(PGConnectionContextModern.java:1138)
        at io.questdb.cutlass.pgwire.modern.PGConnectionContextModern.msgQuery(PGConnectionContextModern.java:1111)
        at io.questdb.cutlass.pgwire.modern.PGConnectionContextModern.parseMessage(PGConnectionContextModern.java:1239)
        at io.questdb.cutlass.pgwire.modern.PGConnectionContextModern.handleClientOperation(PGConnectionContextModern.java:450)
        at io.questdb.cutlass.pgwire.modern.PGWireServerModern$1.lambda$$0(PGWireServerModern.java:111)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
        at io.questdb.cutlass.pgwire.modern.PGWireServerModern$1.run(PGWireServerModern.java:141)
        at io.questdb.mp.Worker.run(Worker.java:152)
, id=31092, taskType=1, frameIndex=213, frameCount=232]
2024-12-02T05:16:16.577088Z E i.q.g.e.QueryProgress err [id=8642066, sql=`SELECT queue, SUM(max_mem) AS mem, SUM(alloc_slot) AS slot,
                SUM(
                    DATEDIFF(
                        'h',
                        CASE
                            WHEN submit_time > '2024-12-01T00:00:00'::timestamp THEN submit_time
                            ELSE CAST('2024-12-01T00:00:00'::timestamp AS TIMESTAMP)
                        END,
                        CASE
                            WHEN finished_time < CAST('2024-12-02T00:00:00'::timestamp AS TIMESTAMP) THEN finished_time
                            ELSE CAST('2024-12-02T00:00:00'::timestamp AS TIMESTAMP)
                        END
                    )
                ) AS total_runtime,
                COUNT(*) AS count
            FROM
                jobs
            WHERE
                execute_host LIKE '%cicgms13%'
                AND (
                    updated_at BETWEEN '2024-12-01T00:00:00'::timestamp AND '2024-12-02T00:00:00'::timestamp
                    OR submit_time BETWEEN '2024-12-01T00:00:00'::timestamp AND '2024-12-02T00:00:00'::timestamp
                )
            GROUP BY queue;`, principal=admin, cache=false, jit=false, time=155541311, msg=Cannot invoke "java.util.concurrent.atomic.AtomicBoolean.get()" because "this.cancelledFlag" is null, errno=-1, pos=0]
