### ISSUE TITLE
Pg test PGJobContextTest.testInsert2 failed, PSQLException: No results were returned by the query

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#5230]
### To reproduce

```
2024-12-05T16:28:38.4993912Z 2024-12-05T16:28:38.336526Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.cutlass.pgwire.PGJobContextTest.testInsert2[LEGACY, WITH_WAL] duration_ms=150 : 
2024-12-05T16:28:38.4994349Z org.postgresql.util.PSQLException: No results were returned by the query.
2024-12-05T16:28:38.4995146Z 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:138)
2024-12-05T16:28:38.4995715Z 	at io.questdb.test.cutlass.pgwire.BasePGTest.execSelectWithParam(BasePGTest.java:547)
2024-12-05T16:28:38.4997652Z 	at io.questdb.test.cutlass.pgwire.PGJobContextTest.lambda$testInsert2$55(PGJobContextTest.java:5105)
2024-12-05T16:28:38.4998165Z 	at io.questdb.test.cutlass.pgwire.BasePGTest.lambda$assertWithPgServer$1(BasePGTest.java:419)
2024-12-05T16:28:38.4999313Z 	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$8(AbstractCairoTest.java:1070)
2024-12-05T16:28:38.5000338Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:665)
2024-12-05T16:28:38.5001344Z 	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:1067)
2024-12-05T16:28:38.5002721Z 	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:1050)
2024-12-05T16:28:38.5004268Z 	at io.questdb.test.cutlass.pgwire.BasePGTest.assertWithPgServer(BasePGTest.java:412)
2024-12-05T16:28:38.5005727Z 	at io.questdb.test.cutlass.pgwire.BasePGTest.assertWithPgServer(BasePGTest.java:432)
2024-12-05T16:28:38.5007340Z 	at io.questdb.test.cutlass.pgwire.PGJobContextTest.testInsert2(PGJobContextTest.java:5049)
2024-12-05T16:28:38.5008603Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-12-05T16:28:38.5010420Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-12-05T16:28:38.5012186Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-12-05T16:28:38.5013309Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2024-12-05T16:28:38.5014676Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2024-12-05T16:28:38.5016261Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2024-12-05T16:28:38.5017839Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2024-12-05T16:28:38.5019359Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2024-12-05T16:28:38.5020782Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2024-12-05T16:28:38.5022211Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2024-12-05T16:28:38.5023660Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2024-12-05T16:28:38.5025326Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2024-12-05T16:28:38.5027297Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2024-12-05T16:28:38.5028262Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-12-05T16:28:38.5029202Z 	at java.lang.Thread.run(Thread.java:829)

```

CI run 
https://dev.azure.com/questdb/questdb/_build/results?buildId=122505&view=logs&jobId=c0bb9d20-e9be-57fa-945f-b9f8bd553868&j=c0bb9d20-e9be-57fa-945f-b9f8bd553868&t=09cde99e-ef9a-59b7-9c74-87bb40755441

[477.zip](https://github.com/user-attachments/files/18035969/477.zip)

### QuestDB version:

8.2.1

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

zfs

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by ideoma** [comment]
Test in the legacy mode will be disabled in #5026
