### ISSUE TITLE
Backup not consistent with ZFS

### ISSUE THREAD

**Issue by enricobenedos** [questdb/questdb#5239]
### To reproduce

1. Execute backup script created reading db docs
```bash
# Delete snapshots old than 14 days
zfs list -t snapshot | grep zpool-docker@ | cut -f1 -d ' ' | sort | head -n -14 | xargs --no-run-if-empty -L1 zfs destroy

# Prepare DB for zfs snapshot and check for success execution
psql -h 'localhost' -p '8812' -U 'admin' -c 'CHECKPOINT CREATE'
psql -h 'localhost' -p '8812' -U 'admin' -c 'SELECT * FROM checkpoint_status();'

# Do snapshot
today=$(date +"%Y_%m_%d")
zfs snapshot zpool-docker@"$today"

# Restore DB to default state
psql -h 'localhost' -p '8812' -U 'admin' -c 'CHECKPOINT RELEASE'
psql -h 'localhost' -p '8812' -U 'admin' -c 'SELECT * FROM checkpoint_status();'
``` 
2. Shut down the db
3. Restore a snapshot and create the `_restore` file (`zfs rollback`)
4. Power on db

At this point we found a mix of suspended and not partitioned tables (partitioned before the restore).

### QuestDB version:

8.2.1

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 24.04.1 LTS (Docker)

### File System, in case of Docker specify Host File System:

ZFS

### Full Name:

Enrico Benedos

### Affiliation:

Deimos

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

[quest_20241204.log](https://github.com/user-attachments/files/18096835/quest_20241204.log)

**Comment by ideoma** [comment]
I quickly checked the log and the only trace of suspended table is:

```
2024-12-04T08:19:47.803563Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=databento_trades~658, error=
java.lang.AssertionError
	at io.questdb.cairo.VarcharTypeDriver.getDataVectorSize(VarcharTypeDriver.java:629)
	at io.questdb.cairo.VarcharTypeDriver.setAppendPosition(VarcharTypeDriver.java:574)
	at io.questdb.cairo.TableWriter.setColumnAppendPosition(TableWriter.java:7655)
	at io.questdb.cairo.TableWriter.setAppendPosition(TableWriter.java:7640)
	at io.questdb.cairo.TableWriter.openLastPartitionAndSetAppendPosition(TableWriter.java:6203)
	at io.questdb.cairo.TableWriter.initLastPartition(TableWriter.java:5419)
	at io.questdb.cairo.TableWriter.configureAppendPosition(TableWriter.java:3808)
	at io.questdb.cairo.TableWriter.<init>(TableWriter.java:434)
	at io.questdb.cairo.pool.WriterPool.createWriter(WriterPool.java:383)
	at io.questdb.cairo.pool.WriterPool.getWriterEntry(WriterPool.java:429)
	at io.questdb.cairo.pool.WriterPool.get(WriterPool.java:135)
	at io.questdb.cairo.CairoEngine.getWriterUnsafe(CairoEngine.java:821)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyWal(ApplyWal2TableJob.java:645)
	at io.questdb.cairo.wal.ApplyWal2TableJob.doRun(ApplyWal2TableJob.java:699)
	at io.questdb.mp.AbstractQueueConsumerJob.run(AbstractQueueConsumerJob.java:50)
	at io.questdb.mp.Worker.run(Worker.java:152)
]
2024-12-04T08:19:47.808830Z I i.q.c.w.s.TableSequencerImpl closed table sequencer [table=TableToken{tableName=databento_trades, dirName=databento_trades~658, tableId=658, isWal=true, isSystem=false}, distressed=false, dropped=true]
```

Which seems to be a dropped table.

What tables do you see as suspended after the restore?

**Comment by enricobenedos** [comment]
That's the only one suspended. 
Then another with a name similar with `deimos_1d` wasn't partitioned after restore. Before the backup it was partitioned.
