### ISSUE TITLE
ARM64/apple silicon support

### ISSUE THREAD

**Issue by bathtimefish** [questdb/questdb#569]
I tried to build and run ARM64 docker image referenced this doc, but I could'nt run it.
https://github.com/questdb/questdb/tree/master/core#switch-docker-desktop-to-linux

My approach was below.

First, I couldn't run the command on the document because repo has no file such as `Dockerfile-linux-arm64`

```
docker buildx build --platform linux/arm64 -t questdb/questdb:4.0.0-linux-arm64 --file Dockerfile-linux-arm64 . --load
```

So I created a new one based on `Dockerfile-linux` which modefied it.

```
diff Dockerfile-linux Dockerfile-linux-arm64

18c18
< RUN tar xvfz questdb-*-rt-linux-amd64.tar.gz
---
> RUN tar xvfz questdb-*-rt-linux-aarch64.tar.gz
24c24
< COPY --from=0 /build/questdb/core/target/questdb-*-rt-linux-amd64 .
---
> COPY --from=0 /build/questdb/core/target/questdb-*-rt-linux-aarch64 .
```

Image build was succeed, So I tried to run it on [Ubuntu 18.04 for Raspberry Pi ARM64](https://wiki.ubuntu.com/ARM/RaspberryPi) and I had an error as bellow.

```
sudo docker run -p 9000:9000 -p 8812:8812 -p 9009:9009 bathtimefish/questdb:5.0.3-linux-arm64
QuestDB server [DEVELOPMENT]
Copyright (C) 2014-2020, all rights reserved.

2020-08-30T11:35:00.568759Z I server-main extracted [path=/root/.questdb/public/573e9313e05d89f4acb5d005476c61bb.woff]
2020-08-30T11:35:02.747060Z I server-main extracted [path=/root/.questdb/public/6437d5f4c14e01aaf4801aef3909151b.woff]
2020-08-30T11:35:02.757650Z I server-main extracted [path=/root/.questdb/public/7dafb1a4bab4938a38b2d68d9c4575a9.woff]
2020-08-30T11:35:02.769892Z I server-main extracted [path=/root/.questdb/public/80b32d346cfff1921b52.worker.js]
2020-08-30T11:35:02.796667Z I server-main extracted [path=/root/.questdb/public/a940d584750708f5435ce2c523498ddb.woff]
2020-08-30T11:35:02.805294Z I server-main extracted [path=/root/.questdb/public/d0b483ce9717b92b4bf815d5d4db597a.woff]
2020-08-30T11:35:02.808302Z I server-main extracted [path=/root/.questdb/public/index.html]
2020-08-30T11:35:02.827243Z I server-main extracted [path=/root/.questdb/public/qdb.css]
2020-08-30T11:35:02.949609Z I server-main extracted [path=/root/.questdb/public/qdb.js]
2020-08-30T11:35:02.952580Z I server-main extracted [path=/root/.questdb/public/assets/console-configuration.json]
2020-08-30T11:35:02.955519Z I server-main extracted [path=/root/.questdb/public/assets/favicon.png]
2020-08-30T11:35:02.997642Z I server-main extracted [path=/root/.questdb/conf/date.formats]
2020-08-30T11:35:03.005191Z I server-main extracted [path=/root/.questdb/conf/mime.types]
2020-08-30T11:35:03.010691Z I server-main extracted [path=/root/.questdb/conf/server.conf]
2020-08-30T11:35:03.891395Z I i.q.c.t.t.InputFormatConfiguration loading [from=/text_loader.json]
Exception in thread "main" 2020-08-30T11:35:04.027201Z I server-main database root [dir=/root/.questdb/db/]
java.lang.UnsatisfiedLinkError: 'int io.questdb.std.Vect.getSupportedInstructionSet()'
	at io.questdb@5.0.3-SNAPSHOT/io.questdb.std.Vect.getSupportedInstructionSet(Native Method)
	at io.questdb@5.0.3-SNAPSHOT/io.questdb.std.Vect.getSupportedInstructionSetName(Vect.java:40)
	at io.questdb@5.0.3-SNAPSHOT/io.questdb.ServerMain.main(ServerMain.java:134)
```

How can I do for that?

**Comment by bluestreak01** [comment]
We no longer support ARM64 due to lack of serious interest for this platform. It would be useful to know what context

**Comment by russelljahn** [comment]
I'm also interested in running the latest docker images on ARM64. I have a 64-bit Raspberry Pi 4B running headless Ubuntu Server. I'm collecting large amounts of streamed sensor data for a startup project. I was impressed with the docker demo, and running QuestDB on the Pi seemed a serious cost-effective contender for the time being.

**Comment by bathtimefish** [comment]
My needs is simular to above. I want to collect some sensor data with RPi3/4 and aggregate the data or filter noise quickly for sending to cloud. I think QuestDB is useful for that because it has various queries to aggegate time series data.
For now, I am tring to use influxdb because it has arm64/armv7 docker image.

**Comment by russelljahn** [comment]
Likewise, I'll likely switch to InfluxDB until/if the QuestDB team sees it valuable to maintain ARM64 support. I'm hopeful, there's a few votes on their internal Slack channel. @bathtimefish I'd suggest voting there if you don't mind.

**Comment by AxelRHD** [comment]
I'm also interrested in an ARM-Version of your fabulous database. :)

**Comment by fuomag9** [comment]
Interested too

**Comment by bluestreak01** [comment]
Guys, to get ARM64 image working again we need to be able to compile C++ binary. The build is already setup and documented here: https://github.com/questdb/questdb/blob/master/core/CMAKE_README.md

We need port for https://github.com/questdb/questdb/blob/master/core/src/main/c/share/rosti.h to support ARM64. Perhaps this can be templated to provide ARM64 implementations of `BSF` and `GroupSse2Impl`. These are the major elements of whats needed to ARM64 support. Everything else should be trivial.

**Comment by Ramblurr** [comment]
> We no longer support ARM64 due to lack of serious interest for this platform. It would be useful to know what context you'd like to use questdb in. 

I found quest db by searching for "embedded timeseries database". Obviously running QuestDB on a microcontroller is out of the question, but running it on small ARM64 SBCs (of which the raspberry pi is just one) makes it a big contender for IOT/Edge computing devices.

**Comment by inviridi** [comment]
I played around with quest and love it on my desktop machine. Quite disappointed, that it does not run on the RPi.. The performance would be awesome on this thing.

**Comment by uski** [comment]
+1 on running QuestDB on a Raspberry Pi !

I am using Raspberry Pi boards as dataloggers, and it is pretty obvious that I need a time series database for that purpose. QuestDB would be perfect due to its low code and memory footprint, if only I could run it there

**Comment by puzpuzpuz** [comment]
@uski QuestDB restored ARM64 support since 6.0, so you should be able to run it on RPi. We have an ARM64 machine in our CI pipeline, so all tests run and pass succesfully on ARM64.

**Comment by jerrinot** [comment]
@uski bear in mind many Raspberry PI distributions run the CPU in the 32bits mode and QuestDB supports 64 bits ARM only. The CPUs of all modern Raspberry boards are perfectly capable to run in 64 bits tho. 

If you are on Raspberry Pi OS (aka Raspbian) then you have to choose the [64 bits build](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit) which was actually released as a GA [relatively recently](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/)

You will also need the "Any (no JVM)" [distribution of QuestDB](https://github.com/questdb/questdb/releases/download/6.2.1/questdb-6.2.1-no-jre-bin.tar.gz) as the Linux distribution assume AMD64.

**Comment by russelljahn** [comment]
Confirmed I was able to build QuestDB 6.3.1 from source on 64-bit Raspbian and run it. I've tested connecting to the web console through my browser via a different computer on my LAN, and things are looking solid! 👍 

Appreciate the QuestDB team getting ARM64 working again! I'm looking forward to using it.

**Comment by jerrinot** [comment]
Excellent news, thanks for reporting back!
