### ISSUE TITLE
Using /tmp for libraries causes failure

### ISSUE THREAD

**Issue by davidgs** [questdb/questdb#570]
**Describe the bug**
Using `/tmp` for libraries causes a failure if the `/tmp` partition is mounted `noexec` 

**To Reproduce**

`mount -o remount,noexec /tmp` 
Attempt to run QuestDB
```
JAVA: /usr/lib/jvm/java-11-openjdk-11.0.8.10-0.el7_8.x86_64/bin/java
QuestDB server 5.0.2
Copyright (C) 2014-2020, all rights reserved.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libquestdb10253599434925275181.so: /tmp/libquestdb10253599434925275181.so: failed to map segment from shared object: Operation not permitted
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at io.questdb@5.0.2/io.questdb.std.Os.loadLib(Os.java:158)
	at io.questdb@5.0.2/io.questdb.std.Os.<clinit>(Os.java:176)
	at io.questdb@5.0.2/io.questdb.ServerMain.main(ServerMain.java:96)
```
**Expected behavior**
it works fine if `/tmp` is not mounted `noexec`, so we need a way to have it run no matter what

**Screenshots**

**Environment (please complete the following information):**
 - OS:CentOs

**Additional context**
Would be better to have the location for unpacked libraries configurable, something like `$QUESTDB_HOME/tmp` would be ideal. `/tmp` is often mounted `noexec` as a security measure.

**Comment by newgeekorder** [comment]
this is a deployment blocker for me

**Comment by eugenels** [comment]
> this is a deployment blocker for me
You can specify your own path for `java.io.tmpdir` system property.
`java -Djava.io.tmpdir=/path/to/tmpdir`

**Comment by bsmth** [comment]
Hi @newgeekorder does the fix suggested by @eugenels work for you? We want to unblock this for you!

**Comment by bsmth** [comment]
I'm going to close this one for now given the suggestion from Eugene above should resolve this. If having `/tmp` mounted as `exec` is acceptable, see the following workaround: https://github.com/vespa-engine/vespa/issues/17844#issuecomment-840681353

If these fixes do not resolve the problem, please feel free to reopen the issue or reply here directly.

Thank you :)

**Comment by jerrinot** [comment]
I am reopening the issue - we should do our best to detect this condition and provide guidance. 
it looks RHEL (=the most popular commercial Linux distribution) has `noexec` in `/tmp` by default.

**Comment by wkbrd** [comment]
It is a security finding to run Enterprise Linux (multiple distros) with the /tmp mount without noexec:

- https://stigviewer.com/stigs/red_hat_enterprise_linux_8/2025-03-26/finding/V-230522
- https://stigviewer.com/stigs/oracle_linux_8/2025-02-20/finding/V-248849

Can the software be improved to support the libraries not being unpacked into /tmp?  For a Java application that performs other activities than just QuestDB, the libraries should be able to be unpacked into a separate location than the location of general temporary files.  An alternate 'working' library directory should suffice.
