### ISSUE TITLE
inner join missing error

### ISSUE THREAD

**Issue by dybxin** [questdb/questdb#604]
**Describe the bug**
java.lang.IllegalArgumentException

**To Reproduce**
1. Go to 'http://localhost:9000/'
2. Click on 'RUN'
3. Run this SQL `select * from temp_orders inner join temp_riders on temp_orders.rider_id = temp_riders.uid
		inner join temp_drivers on temp_orders.driver_id = temp_drivers.uid where temp_orders.uid = 100;`
``` java
java.lang.IllegalArgumentException
	at jdk.internal.misc.Unsafe.invalidInput(Unsafe.java:437)
	at jdk.internal.misc.Unsafe.checkSize(Unsafe.java:466)
	at jdk.internal.misc.Unsafe.allocateMemoryChecks(Unsafe.java:631)
	at jdk.internal.misc.Unsafe.allocateMemory(Unsafe.java:608)
	at sun.misc.Unsafe.allocateMemory(Unsafe.java:462)
	at io.questdb.std.Unsafe.malloc(Unsafe.java:128)
	at io.questdb.std.DirectLongList.<init>(DirectLongList.java:47)
	at io.questdb.cairo.map.FastMap.rehash(FastMap.java:324)
	at io.questdb.cairo.map.FastMap.asNew(FastMap.java:256)
	at io.questdb.cairo.map.FastMap$Key.createValue(FastMap.java:395)
	at io.questdb.griffin.engine.join.HashJoinLightRecordCursorFactory.buildMapOfSlaveRecords(HashJoinLightRecordCursorFactory.java:113)
	at io.questdb.griffin.engine.join.HashJoinLightRecordCursorFactory.getCursor(HashJoinLightRecordCursorFactory.java:91)
	at io.questdb.griffin.engine.join.HashJoinLightRecordCursorFactory.getCursor(HashJoinLightRecordCursorFactory.java:96)
	at io.questdb.griffin.engine.table.SelectedRecordCursorFactory.getCursor(SelectedRecordCursorFactory.java:57)
	at io.questdb.cutlass.pgwire.PGConnectionContext.executeSelect(PGConnectionContext.java:845)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:1422)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:976)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:304)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:79)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:69)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:151)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:82)
	at io.questdb.mp.Worker.run(Worker.java:107)

```

**Expected behavior**
i expected get information that the order_id is 100.

**Screenshots**
temp_orders(`remark: timestamp(start_time)`) & temp_riders & temp_drivers .
![Screenshot from 2020-09-21 15-42-43](https://user-images.githubusercontent.com/14888437/93742783-53e72900-fc21-11ea-858b-fb86d6e56c81.png)
![Screenshot from 2020-09-21 15-42-59](https://user-images.githubusercontent.com/14888437/93742797-56498300-fc21-11ea-8b4f-b0a5f3560fe8.png)
![Screenshot from 2020-09-21 15-43-11](https://user-images.githubusercontent.com/14888437/93742804-59447380-fc21-11ea-84f5-6fcd2fa4b806.png)

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser: [e.g. chrome]
 - Version: [e.g. latest]

**Additional context**
i modify server.conf. 
cairo.sql.map.page.size=67108864
cairo.sql.hash.join.light.value.page.size=67108864

**Comment by bluestreak01** [comment]
This is likely to an out of memory condition. That said there are multiple issues here:

- SQL plan should have been different
- Out of memory error should have been reported

**Comment by dybxin** [comment]
thanks a lot for you quick reply, i have noticed this out of memory, Is it caused by unreasonable parameter settings in server.conf?

**Comment by bluestreak01** [comment]
I'm not sure yet. How much RAM does this instance have?

**Comment by bluestreak01** [comment]
this issue has the same cause as #748

**Comment by bluestreak01** [comment]
Fixed
