### ISSUE TITLE
NullPointerException when select some columns from table with 300 columns.

### ISSUE THREAD

**Issue by dybxin** [questdb/questdb#608]
**Describe the bug**
NullPointerException when select some columns from table with 300  columns.

**To Reproduce**
1. Go to 'http://localhost:9000/'
2. Click on 'RUN'
3. Run this SQL 'select f1, f3, f4, f5, f6, f11, f12, f13 from temps limit 0, 1000;'
```java
2020-09-23T03:34:04.162777Z E server-main unhandled error [job=io.questdb.cutlass.pgwire.PGWireServer$1@53941c2f, ex=
java.lang.NullPointerException
	at io.questdb.cutlass.pgwire.PGConnectionContext.appendRecord(PGConnectionContext.java:605)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor(PGConnectionContext.java:1469)
	at io.questdb.cutlass.pgwire.PGConnectionContext.executeSelect(PGConnectionContext.java:847)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:1422)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:976)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:304)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:79)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:69)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:151)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:82)
	at io.questdb.mp.Worker.run(Worker.java:107)
```

**Expected behavior**
i hope to get the correct result.

**Screenshots**
questdb version:
![Screenshot from 2020-09-23 13-06-48](https://user-images.githubusercontent.com/14888437/93969128-bbc27e80-fd9d-11ea-8bd2-4e3e2f10da01.png)

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser: [e.g. chrome]
 - Version: [e.g. latest]

**Additional context**
the table has 300 columns, from f1 to f300:
 timestamp(f2).
 f141--f300 and f19 and f5  is STRING,
 f25--f140 and f15--f17 and f9 is FLOAT,
 f22 f23  f3 is BYTE, 
 f22 f21 f20 f1  is LONG,
 f18 is SHORT,
 f14 and f6 is INT,
 f13 and f7 is BOOLEAN,
 f12 is SYMBOL,
 f11 is CHAR,
 f10 is DATE,
 f8 is SHORT,  f4 is DOUBLE
 
![Screenshot from 2020-09-23 13-13-06](https://user-images.githubusercontent.com/14888437/93969522-a568f280-fd9e-11ea-8abc-69c4e042e0dd.png)

**Comment by bluestreak01** [comment]
@jaugsburger we are missing appenders for CHAR and LONG256

**Comment by mpsq** [comment]
Fixed on master.
