### ISSUE TITLE
Kafka JDBC connector does not work

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#609]
```
==== 5.0.2
-- Logs from QuestDB
2020-09-23T12:42:00.522898Z I pg-server connected [ip=10.150.49.109, fd=26]
2020-09-23T12:42:00.523586Z I i.q.c.p.PGConnectionContext protocol [major=3, minor=0]
2020-09-23T12:42:00.523595Z I i.q.c.p.PGConnectionContext property [name=user, value=admin]
2020-09-23T12:42:00.523612Z I i.q.c.p.PGConnectionContext property [name=database, value=qdb]
2020-09-23T12:42:00.523617Z I i.q.c.p.PGConnectionContext property [name=client_encoding, value=UTF8]
2020-09-23T12:42:00.523621Z I i.q.c.p.PGConnectionContext property [name=DateStyle, value=ISO]
2020-09-23T12:42:00.523626Z I i.q.c.p.PGConnectionContext property [name=TimeZone, value=Etc/UTC]
2020-09-23T12:42:00.523630Z I i.q.c.p.PGConnectionContext property [name=extra_float_digits, value=2]
2020-09-23T12:42:00.524382Z I i.q.c.p.PGConnectionContext parse [q=SET extra_float_digits = 3]
2020-09-23T12:42:00.524475Z I i.q.c.p.PGConnectionContext executed DDL
2020-09-23T12:42:00.524766Z I i.q.c.p.PGConnectionContext parse [q=SET application_name = 'PostgreSQL JDBC Driver']
2020-09-23T12:42:00.524803Z I i.q.c.p.PGConnectionContext executed DDL
2020-09-23T12:42:00.525304Z I pg-server disconnected [ip=10.150.49.109, fd=26]
2020-09-23T12:42:00.525418Z I i.q.c.p.PGWireServer pushed
2020-09-23T12:42:00.525729Z I i.q.c.p.PGConnectionContext parse [q=BEGIN]
2020-09-23T12:42:00.525771Z I i.q.c.p.PGConnectionContext executed DDL
2020-09-23T12:42:00.525840Z I i.q.c.p.PGConnectionContext parse [q=SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, c.relname AS TABLE_NAME,  CASE n.nspname ~ '^pg_' OR n.nspname = 'information_schema'  WHEN true THEN CASE  WHEN n.nspname = 'pg_catalog' OR n.nspname = 'information_schema' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TABLE'   WHEN 'v' THEN 'SYSTEM VIEW'   WHEN 'i' THEN 'SYSTEM INDEX'   ELSE NULL   END  WHEN n.nspname = 'pg_toast' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TOAST TABLE'   WHEN 'i' THEN 'SYSTEM TOAST INDEX'   ELSE NULL   END  ELSE CASE c.relkind   WHEN 'r' THEN 'TEMPORARY TABLE'   WHEN 'p' THEN 'TEMPORARY TABLE'   WHEN 'i' THEN 'TEMPORARY INDEX'   WHEN 'S' THEN 'TEMPORARY SEQUENCE'   WHEN 'v' THEN 'TEMPORARY VIEW'   ELSE NULL   END  END  WHEN false THEN CASE c.relkind  WHEN 'r' THEN 'TABLE'  WHEN 'p' THEN 'TABLE'  WHEN 'i' THEN 'INDEX'  WHEN 'S' THEN 'SEQUENCE'  WHEN 'v' THEN 'VIEW'  WHEN 'c' THEN 'TYPE'  WHEN 'f' THEN 'FOREIGN TABLE'  WHEN 'm' THEN 'MATERIALIZED VIEW'  ELSE NULL  END  ELSE NULL  END  AS TABLE_TYPE, d.description AS REMARKS,  '' as TYPE_CAT, '' as TYPE_SCHEM, '' as TYPE_NAME, '' AS SELF_REFERENCING_COL_NAME, '' AS REF_GENERATION  FROM pg_catalog.pg_namespace n, pg_catalog.pg_class c  LEFT JOIN pg_catalog.pg_description d ON (c.oid = d.objoid AND d.objsubid = 0)  LEFT JOIN pg_catalog.pg_class dc ON (d.classoid=dc.oid AND dc.relname='pg_class')  LEFT JOIN pg_catalog.pg_namespace dn ON (dn.oid=dc.relnamespace AND dn.nspname='pg_catalog')  WHERE c.relnamespace = n.oid  AND c.relname LIKE E'global_indicator_02' AND (false  OR ( c.relkind IN ('r','p') AND n.nspname !~ '^pg_' AND n.nspname <> 'information_schema' ) )  ORDER BY TABLE_TYPE,TABLE_SCHEM,TABLE_NAME ]
2020-09-23T12:42:00.526429Z I i.q.c.p.PGConnectionContext SQL exception [pos=95, msg=dangling expression]
2020-09-23T12:42:00.527027Z I pg-server disconnected [ip=10.150.49.109, fd=17]
-- Logs from kafka-connected
TRACE:
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
              at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:567)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
              at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
              at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
              at java.util.concurrent.FutureTask.run(FutureTask.java:266)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
              at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Exception chain:
org.postgresql.util.PSQLException: No results were returned by the query.
              at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:89)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
              ... 10 more
Caused by: java.sql.SQLException: Exception chain:
org.postgresql.util.PSQLException: No results were returned by the query.
              at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:86)
              ... 11 more
==== 5.0.3
-- Logs from QuestDB 
2020-09-23T12:55:01.773139Z I pg-server connected [ip=10.150.49.109, fd=27]
2020-09-23T12:55:01.773663Z I i.q.c.p.PGConnectionContext protocol [major=3, minor=0]
2020-09-23T12:55:01.773701Z I i.q.c.p.PGConnectionContext property [name=user, value=admin]
2020-09-23T12:55:01.773741Z I i.q.c.p.PGConnectionContext property [name=database, value=qdb]
2020-09-23T12:55:01.773790Z I i.q.c.p.PGConnectionContext property [name=client_encoding, value=UTF8]
2020-09-23T12:55:01.773828Z I i.q.c.p.PGConnectionContext property [name=DateStyle, value=ISO]
2020-09-23T12:55:01.773860Z I i.q.c.p.PGConnectionContext property [name=TimeZone, value=Etc/UTC]
2020-09-23T12:55:01.773886Z I i.q.c.p.PGConnectionContext property [name=extra_float_digits, value=2]
2020-09-23T12:55:01.776732Z I i.q.c.p.PGConnectionContext parse [q=SET extra_float_digits = 3]
2020-09-23T12:55:01.776907Z I i.q.c.p.PGConnectionContext executed query
2020-09-23T12:55:01.777532Z I i.q.c.p.PGConnectionContext parse [q=SET application_name = 'PostgreSQL JDBC Driver']
2020-09-23T12:55:01.777624Z I i.q.c.p.PGConnectionContext executed query
2020-09-23T12:55:01.778287Z I pg-server disconnected [ip=10.150.49.109, fd=27]
2020-09-23T12:55:01.778392Z I i.q.c.p.PGWireServer pushed
2020-09-23T12:55:01.778727Z I i.q.c.p.PGConnectionContext parse [q=BEGIN]
2020-09-23T12:55:01.778817Z I i.q.c.p.PGConnectionContext executed query
2020-09-23T12:55:01.778877Z I i.q.c.p.PGConnectionContext parse [q=SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, c.relname AS TABLE_NAME,  CASE n.nspname ~ '^pg_' OR n.nspname = 'information_schema'  WHEN true THEN CASE  WHEN n.nspname = 'pg_catalog' OR n.nspname = 'information_schema' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TABLE'   WHEN 'v' THEN 'SYSTEM VIEW'   WHEN 'i' THEN 'SYSTEM INDEX'   ELSE NULL   END  WHEN n.nspname = 'pg_toast' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TOAST TABLE'   WHEN 'i' THEN 'SYSTEM TOAST INDEX'   ELSE NULL   END  ELSE CASE c.relkind   WHEN 'r' THEN 'TEMPORARY TABLE'   WHEN 'p' THEN 'TEMPORARY TABLE'   WHEN 'i' THEN 'TEMPORARY INDEX'   WHEN 'S' THEN 'TEMPORARY SEQUENCE'   WHEN 'v' THEN 'TEMPORARY VIEW'   ELSE NULL   END  END  WHEN false THEN CASE c.relkind  WHEN 'r' THEN 'TABLE'  WHEN 'p' THEN 'TABLE'  WHEN 'i' THEN 'INDEX'  WHEN 'S' THEN 'SEQUENCE'  WHEN 'v' THEN 'VIEW'  WHEN 'c' THEN 'TYPE'  WHEN 'f' THEN 'FOREIGN TABLE'  WHEN 'm' THEN 'MATERIALIZED VIEW'  ELSE NULL  END  ELSE NULL  END  AS TABLE_TYPE, d.description AS REMARKS,  '' as TYPE_CAT, '' as TYPE_SCHEM, '' as TYPE_NAME, '' AS SELF_REFERENCING_COL_NAME, '' AS REF_GENERATION  FROM pg_catalog.pg_namespace n, pg_catalog.pg_class c  LEFT JOIN pg_catalog.pg_description d ON (c.oid = d.objoid AND d.objsubid = 0)  LEFT JOIN pg_catalog.pg_class dc ON (d.classoid=dc.oid AND dc.relname='pg_class')  LEFT JOIN pg_catalog.pg_namespace dn ON (dn.oid=dc.relnamespace AND dn.nspname='pg_catalog')  WHERE c.relnamespace = n.oid  AND c.relname LIKE E'global_indicator_03' AND (false  OR ( c.relkind IN ('r','p') AND n.nspname !~ '^pg_' AND n.nspname <> 'information_schema' ) )  ORDER BY TABLE_TYPE,TABLE_SCHEM,TABLE_NAME ]
2020-09-23T12:55:01.779324Z I i.q.c.p.PGConnectionContext SQL exception [pos=95, msg=dangling expression]
2020-09-23T12:55:01.780219Z I pg-server disconnected [ip=10.150.49.109, fd=26]
-- Logs from kafka-connected
TRACE:
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
              at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:567)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
              at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
              at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
              at java.util.concurrent.FutureTask.run(FutureTask.java:266)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
              at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Exception chain:
org.postgresql.util.PSQLException: Expected command status BEGIN, got SET.
org.postgresql.util.PSQLException: ERROR: dangling expression
  Position: 96
              at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:89)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
              ... 10 more
Caused by: java.sql.SQLException: Exception chain:
org.postgresql.util.PSQLException: Expected command status BEGIN, got SET.
org.postgresql.util.PSQLException: ERROR: dangling expression
  Position: 96
              at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:86)
              ... 11 more
```

**Comment by bluestreak01** [comment]
Fixed in https://github.com/questdb/questdb/pull/706
