### ISSUE TITLE
questdb test build failed on apple silicon

### ISSUE THREAD

**Issue by chenrui333** [questdb/questdb#809]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test build failure</summary>

```
==> Testing questdb
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210203-68849-1wvmmv2.sb ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/questdb.rb --verbose

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

JAVA: /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home/bin/java
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
QuestDB server 5.0.6
Copyright (C) 2014-2021, all rights reserved.

Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/tmp/libquestdb7842751173469620677.dylib: dlopen(/private/tmp/libquestdb7842751173469620677.dylib, 1): no suitable image found.  Did find:
	/private/tmp/libquestdb7842751173469620677.dylib: mach-o, but wrong architecture
	/private/tmp/libquestdb7842751173469620677.dylib: mach-o, but wrong architecture
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at io.questdb@5.0.6/io.questdb.std.Os.loadLib(Os.java:160)
	at io.questdb@5.0.6/io.questdb.std.Os.<clinit>(Os.java:182)
	at io.questdb@5.0.6/io.questdb.ServerMain.<init>(ServerMain.java:73)
	at io.questdb@5.0.6/io.questdb.ServerMain.main(ServerMain.java:238)
==> curl -Is localhost:9000/index.html

==> /opt/homebrew/Cellar/questdb/5.0.6/bin/questdb stop

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

Not running
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1823346905
relates to https://github.com/Homebrew/homebrew-core/pull/70209

**Comment by bluestreak01** [comment]
this is the same issue as #569. We suspended support for ARM64 for now

**Comment by chenrui333** [comment]
Got you, thanks!
