### ISSUE TITLE
questdb 6.0 can not start server to create database   FileNotFoundException

### ISSUE THREAD

**Issue by WLLS253** [questdb/questdb#910]
```
XXX (master)> ./questdb.sh start -d  data

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

JAVA: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
Created QuestDB ROOT directory: data
QuestDB server 6.0.0-SNAPSHOT
Copyright (C) 2014-2021, all rights reserved.

XXXXX~/o/p/d/q/bin (master)> Exception in thread "main" java.io.FileNotFoundException: data/conf/server.conf (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at io.questdb@6.0.0-SNAPSHOT/io.questdb.ServerMain.<init>(ServerMain.java:92)
	at io.questdb@6.0.0-SNAPSHOT/io.questdb.ServerMain.main(ServerMain.java:238)
```

**Comment by ideoma** [comment]
6.0 is not released yet. Are you building from master sources?

**Comment by bluestreak01** [comment]
you can re-build to include the missing UI zip using the following command:
```
mvn clean package --batch-mode --quiet -DskipTests -P use-built-in-nodejs,build-web-console,build-binaries
```
