### ISSUE TITLE
NullPointerException When trying to insert from the console.

### ISSUE THREAD

**Issue by haftrine** [questdb/questdb#97]
Hello,
Please find below the steps

Docker Version: questdb/questdb:4.0.1

Created a table using:
```
CREATE TABLE TS (timestamp TIMESTAMP, field STRING, value DOUBLE) TIMESTAMP(timestamp);
```

Executing the following insert produces the below Exception:
```
INSERT INTO TS values(to_timestamp('2019-12-04T13:20:49', 'yyyy-MM-ddTHH:mm:ss'),'X',123.33);
```

```
2019-12-04T14:11:28.733340Z I i.q.c.h.p.JsonQueryProcessor [63] exec [q='INSERT INTO TS values(to_timestamp('2019-12-04T13:20:49', 'yyyy-MM-ddTHH:mm:ss'),'X',123.33);']
2019-12-04T14:11:28.739085Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@4f5c72ad, ex=
java.lang.NullPointerException
	at io.questdb.cairo.sql.VirtualRecord.getColumnType(VirtualRecord.java:64)
	at io.questdb.griffin.SqlCompiler.assembleRecordToRowCopier(SqlCompiler.java:254)
	at io.questdb.griffin.SqlCompiler.insert(SqlCompiler.java:1166)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:886)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:174)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:137)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:170)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:347)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:136)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:78)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:147)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:82)
	at io.questdb.mp.Worker.run(Worker.java:107)
]
```

**Comment by bluestreak01** [comment]
thanks Armen, I'm able to reproduce, will fix asap
